import {
  ArrowCounterClockwise,
  ArrowRight,
  ArrowsClockwise,
  ArrowsLeftRight,
  Bell,
  BellRinging,
  CalendarBlank,
  Calculator,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  CheckCircle,
  CheckSquare,
  ClockCounterClockwise,
  Code,
  Database,
  DownloadSimple,
  FileArrowDown,
  FileText,
  Funnel,
  GearSix,
  HardDrives,
  Key,
  Link,
  ListChecks,
  LockKey,
  MagnifyingGlass,
  Medal,
  Monitor,
  Package,
  Password,
  Path,
  Play,
  Plus,
  ShieldCheck,
  SlidersHorizontal,
  Stack,
  Tag,
  TrayArrowDown,
  TrayArrowUp,
  UploadSimple,
  Warning,
  WarningCircle,
  X,
  XCircle,
  type Icon,
} from "@phosphor-icons/react";

/* 아이콘은 Phosphor regular 한 굵기로 통일한다. 이름은 화면 코드에서 쓰는 키다. */
export const ICONS = {
  "arrow-counter-clockwise": ArrowCounterClockwise,
  "arrow-right": ArrowRight,
  "arrows-clockwise": ArrowsClockwise,
  "arrows-left-right": ArrowsLeftRight,
  bell: Bell,
  "bell-ringing": BellRinging,
  "calendar-blank": CalendarBlank,
  calculator: Calculator,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "clock-counter-clockwise": ClockCounterClockwise,
  code: Code,
  database: Database,
  "download-simple": DownloadSimple,
  "file-arrow-down": FileArrowDown,
  "file-text": FileText,
  funnel: Funnel,
  "gear-six": GearSix,
  "hard-drives": HardDrives,
  key: Key,
  link: Link,
  "list-checks": ListChecks,
  "lock-key": LockKey,
  "magnifying-glass": MagnifyingGlass,
  medal: Medal,
  monitor: Monitor,
  package: Package,
  password: Password,
  path: Path,
  play: Play,
  plus: Plus,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  stack: Stack,
  tag: Tag,
  "tray-arrow-down": TrayArrowDown,
  "tray-arrow-up": TrayArrowUp,
  "upload-simple": UploadSimple,
  warning: Warning,
  "warning-circle": WarningCircle,
  x: X,
  "x-circle": XCircle,
} satisfies Record<string, Icon>;

export type IconName = keyof typeof ICONS;
