import type {
  Bid,
  Deal,
  DisputeItem,
  Equipment,
  Inspection,
  NoticeItem,
} from "@/projects/b2b/buildbid/lib/types";
import photoExcavator1 from "@/projects/b2b/buildbid/assets/equipment/excavator-1.jpg";
import photoExcavator2 from "@/projects/b2b/buildbid/assets/equipment/excavator-2.jpg";
import photoCraneCrawler from "@/projects/b2b/buildbid/assets/equipment/crane-crawler.jpg";
import photoCraneMobile from "@/projects/b2b/buildbid/assets/equipment/crane-mobile.jpg";
import photoDumpTruck1 from "@/projects/b2b/buildbid/assets/equipment/dumptruck-1.jpg";
import photoDumpTruck2 from "@/projects/b2b/buildbid/assets/equipment/dumptruck-2.jpg";
import photoDumpTruck3 from "@/projects/b2b/buildbid/assets/equipment/dumptruck-3.jpg";
import photoForklift1 from "@/projects/b2b/buildbid/assets/equipment/forklift-1.jpg";
import photoLoader1 from "@/projects/b2b/buildbid/assets/equipment/loader-1.jpg";
import photoRoller1 from "@/projects/b2b/buildbid/assets/equipment/roller-1.jpg";

/* 판매자/바이어/제조사 모두 알파벳 기반 익명 표기(CLAUDE.md 포트폴리오 익명화 규칙).
   개인 판매자는 사람 이름을 쓰되 가상 인물이다. */

export const sellerCompany = {
  name: "D중장비임대",
  tier: "기업 판매자",
  bizNo: "301-86-4XXXX",
  manager: { name: "이도윤", role: "장비 운영팀장", phone: "010-3XXX-8842" },
  region: "경기 화성시",
};

export const buyerCompany = {
  name: "L기계유통",
  tier: "우수바이어",
  bizNo: "214-81-2XXXX",
  manager: { name: "한서윤", role: "매입팀 과장", phone: "010-7XXX-1930" },
  region: "인천 서구",
};

export const equipmentList: Equipment[] = [
  {
    id: "e1",
    code: "BB-1042",
    name: "0.7m³급 굴착기",
    maker: "S중공업",
    model: "SX210W",
    category: "excavator",
    quantity: 1,
    manufacturedYear: 2019,
    usedHours: 8200,
    grade: "B",
    status: "bidding1",
    registeredAt: "2024-07-10",
    region: "경기 화성",
    seller: "C개발",
    spec: "버킷 0.7m³ · 휠타입 · Tier3 엔진",
    photo: photoExcavator1,
    autoPrice: 68_400_000,
    listPrice: 145_000_000,
    factors: [
      { label: "가동시간", impact: -8, note: "동급 연식 평균(6,400시간) 대비 높음" },
      { label: "외관 상태", impact: -3, note: "붐대 하단 경미한 도장 마모" },
      { label: "정비 이력", impact: 2, note: "최근 1년 정기 오일교체 이력 확인" },
    ],
    basis: [
      { label: "동일 모델 최근 거래가", value: "71,200,000원" },
      { label: "연식 감가율", value: "연 6.8%" },
      { label: "가동시간 구간 지수", value: "8,000~9,000시간 구간" },
    ],
    confidence: 84,
  },
  {
    id: "e2",
    code: "BB-1039",
    name: "5톤급 지게차",
    maker: "T산업기계",
    model: "FL-50D",
    category: "forklift",
    quantity: 1,
    manufacturedYear: 2021,
    usedHours: 3100,
    grade: "A",
    status: "quoted",
    registeredAt: "2024-07-20",
    region: "충남 아산",
    seller: "김도현 (개인판매자)",
    spec: "디젤 · 마스트 3단 · 최대 인양 3.2m",
    photo: photoForklift1,
    autoPrice: 21_300_000,
    listPrice: 52_000_000,
    factors: [
      { label: "가동시간", impact: 4, note: "동급 연식 평균 대비 낮음" },
      { label: "타이어 마모", impact: -1, note: "전륜 교체 권장 시점 근접" },
    ],
    basis: [
      { label: "동일 모델 최근 거래가", value: "22,600,000원" },
      { label: "연식 감가율", value: "연 9.2%" },
    ],
    confidence: 79,
  },
  {
    id: "e3",
    code: "BB-1051",
    name: "25톤급 크롤러 크레인",
    maker: "U중공업",
    model: "UC-250R",
    category: "crane",
    quantity: 1,
    manufacturedYear: 2017,
    usedHours: 11400,
    grade: "B",
    status: "inspecting",
    registeredAt: "2024-07-03",
    region: "전남 여수",
    seller: "A건설기계",
    spec: "정격하중 25톤 · 붐 길이 38m · 크롤러 타입",
    photo: photoCraneCrawler,
    autoPrice: 187_000_000,
    listPrice: 410_000_000,
    factors: [
      { label: "가동시간", impact: -11, note: "플랜트 상주 장비, 가동시간 높음" },
      { label: "와이어로프 상태", impact: -4, note: "권상 와이어 교체 임박" },
      { label: "붐 구조", impact: 3, note: "구조 균열 없음, 비파괴 검사 이력 확인" },
    ],
    basis: [
      { label: "동일 모델 최근 거래가", value: "201,000,000원" },
      { label: "연식 감가율", value: "연 7.1%" },
      { label: "가동시간 구간 지수", value: "10,000시간 이상 구간" },
    ],
    confidence: 71,
  },
  {
    id: "e4",
    code: "BB-1028",
    name: "8톤급 덤프트럭",
    maker: "V모터스",
    model: "VD-8500",
    category: "dumpTruck",
    quantity: 1,
    manufacturedYear: 2020,
    usedHours: 62000,
    grade: "B",
    status: "bidding2",
    registeredAt: "2024-06-25",
    region: "경북 포항",
    seller: "D중장비임대",
    spec: "적재중량 8톤 · 6단 수동 · 배출가스 4종",
    photo: photoDumpTruck1,
    autoPrice: 41_200_000,
    listPrice: 98_000_000,
    factors: [
      { label: "주행거리 환산", impact: -6, note: "누적 운행거리 상위 구간" },
      { label: "적재함 상태", impact: -2, note: "바닥판 부분 교체 이력" },
      { label: "정비 이력", impact: 3, note: "엔진/미션 정기 정비 이력 양호" },
    ],
    basis: [
      { label: "동일 모델 최근 거래가", value: "43,800,000원" },
      { label: "연식 감가율", value: "연 8.4%" },
    ],
    confidence: 76,
  },
  {
    id: "e5",
    code: "BB-1015",
    name: "1.6m³급 휠로더",
    maker: "W기계",
    model: "WL-160",
    category: "loader",
    quantity: 1,
    manufacturedYear: 2018,
    usedHours: 9800,
    grade: "B",
    status: "confirmed",
    registeredAt: "2024-06-10",
    region: "충북 청주",
    seller: "E인프라",
    spec: "버킷 1.6m³ · 4륜구동 · 파일럿 조작",
    photo: photoLoader1,
    autoPrice: 76_800_000,
    listPrice: 165_000_000,
    factors: [
      { label: "가동시간", impact: -5, note: "동급 연식 평균 대비 소폭 높음" },
      { label: "타이어 상태", impact: -3, note: "전 타이어 잔여 마모 40% 수준" },
    ],
    basis: [
      { label: "동일 모델 최근 거래가", value: "80,500,000원" },
      { label: "연식 감가율", value: "연 6.9%" },
    ],
    confidence: 88,
  },
  {
    id: "e6",
    code: "BB-1004",
    name: "10톤급 진동롤러",
    maker: "S중공업",
    model: "SR-1000V",
    category: "roller",
    quantity: 1,
    manufacturedYear: 2016,
    usedHours: 7400,
    grade: "C",
    status: "settled",
    registeredAt: "2024-05-15",
    region: "강원 원주",
    seller: "F현장기계",
    spec: "정적 하중 10톤 · 진동 편심 2단 · 드럼폭 2.13m",
    photo: photoRoller1,
    autoPrice: 33_500_000,
    listPrice: 88_000_000,
    factors: [
      { label: "드럼 부식", impact: -6, note: "드럼 표면 경미한 부식 확인" },
      { label: "누유 흔적", impact: -4, note: "유압 실린더 미세 누유" },
    ],
    basis: [{ label: "동일 모델 최근 거래가", value: "35,900,000원" }],
    confidence: 68,
  },
  {
    id: "e7",
    code: "BB-1061",
    name: "0.45m³급 미니 굴착기",
    maker: "T산업기계",
    model: "TX045",
    category: "excavator",
    quantity: 1,
    manufacturedYear: 2022,
    usedHours: 1650,
    grade: "A",
    status: "draft",
    registeredAt: "2024-07-26",
    region: "경남 김해",
    seller: "박서준 (개인판매자)",
    spec: "버킷 0.045m³ · 제로턴 · 캐빈형",
    photo: photoExcavator2,
    autoPrice: 24_100_000,
    listPrice: 58_000_000,
    factors: [{ label: "가동시간", impact: 6, note: "동급 연식 평균 대비 현저히 낮음" }],
    basis: [{ label: "동일 모델 최근 거래가", value: "25,400,000원" }],
    confidence: 81,
  },
  {
    id: "e8",
    code: "BB-1033",
    name: "5톤급 카고 크레인",
    maker: "U중공업",
    model: "UC-050C",
    category: "crane",
    quantity: 1,
    manufacturedYear: 2015,
    usedHours: 41200,
    grade: "D",
    status: "canceled",
    registeredAt: "2024-06-19",
    region: "충남 당진",
    seller: "G토건",
    spec: "정격하중 5톤 · 카고 데크 · 3단 붐",
    photo: photoCraneMobile,
    autoPrice: 29_700_000,
    listPrice: 132_000_000,
    factors: [
      { label: "유압계통", impact: -14, note: "붐 실린더 작동 이상 확인" },
      { label: "구조 부식", impact: -7, note: "하부 프레임 부식 진행" },
    ],
    basis: [{ label: "동일 모델 최근 거래가", value: "34,000,000원" }],
    confidence: 52,
  },
  {
    id: "e9",
    code: "BB-1046",
    name: "15톤급 덤프트럭",
    maker: "V모터스",
    model: "VD-1500",
    category: "dumpTruck",
    quantity: 1,
    manufacturedYear: 2021,
    usedHours: 38000,
    grade: "A",
    status: "bidding1",
    registeredAt: "2024-07-15",
    region: "전북 군산",
    seller: "H건설",
    spec: "적재중량 15톤 · 8단 자동 · 배출가스 5종",
    photo: photoDumpTruck2,
    autoPrice: 89_300_000,
    listPrice: 187_000_000,
    factors: [
      { label: "가동시간", impact: 3, note: "동급 연식 평균 대비 낮음" },
      { label: "정비 이력", impact: 2, note: "제조사 정기점검 이력 완비" },
    ],
    basis: [{ label: "동일 모델 최근 거래가", value: "91,000,000원" }],
    confidence: 85,
  },
  {
    id: "e10",
    code: "BB-1010",
    name: "11톤급 덤프트럭",
    maker: "V모터스",
    model: "VD-1100",
    category: "dumpTruck",
    quantity: 1,
    manufacturedYear: 2019,
    usedHours: 54200,
    grade: "B",
    status: "settled",
    registeredAt: "2024-05-01",
    region: "경기 이천",
    seller: "F현장기계",
    spec: "적재중량 11톤 · 6단 수동 · 배출가스 4종",
    photo: photoDumpTruck3,
    autoPrice: 52_600_000,
    listPrice: 121_000_000,
    factors: [{ label: "가동시간", impact: -4, note: "동급 연식 평균 대비 다소 높음" }],
    basis: [{ label: "동일 모델 최근 거래가", value: "54,100,000원" }],
    confidence: 80,
  },
];

export const bids: Bid[] = [
  // e1 · 굴착기 · 1차 입찰 진행
  { id: "b1", equipmentId: "e1", buyer: "J중고기계", buyerTier: "우수바이어", round: 1, unitPrice: 66_800_000, submittedAt: "2024-07-24 09:12", transportDays: 5, note: "현장 자체 운송 가능", immediatePickup: true },
  { id: "b2", equipmentId: "e1", buyer: "K글로벌기계상사", buyerTier: "공식파트너", round: 1, unitPrice: 69_500_000, submittedAt: "2024-07-24 11:40", transportDays: 10, note: "수출용, 선적 일정 협의 필요", immediatePickup: false },
  { id: "b3", equipmentId: "e1", buyer: "N장비몰", buyerTier: "일반바이어", round: 1, unitPrice: 64_200_000, submittedAt: "2024-07-24 08:03", transportDays: 7, note: "", immediatePickup: false },
  { id: "b4", equipmentId: "e1", buyer: "L기계유통", buyerTier: "우수바이어", round: 1, unitPrice: 70_100_000, submittedAt: "2024-07-24 14:27", transportDays: 3, note: "검수 결과 확인 후 최종가 조정 희망", immediatePickup: true },

  // e9 · 덤프트럭 15톤 · 1차 입찰 진행
  { id: "b5", equipmentId: "e9", buyer: "P기계무역", buyerTier: "공식파트너", round: 1, unitPrice: 87_400_000, submittedAt: "2024-07-25 10:05", transportDays: 4, note: "즉시 인수 가능", immediatePickup: true },
  { id: "b6", equipmentId: "e9", buyer: "Q리퍼비시", buyerTier: "일반바이어", round: 1, unitPrice: 84_900_000, submittedAt: "2024-07-25 16:31", transportDays: 9, note: "", immediatePickup: false },
  { id: "b7", equipmentId: "e9", buyer: "R중장비컴퍼니", buyerTier: "우수바이어", round: 1, unitPrice: 90_200_000, submittedAt: "2024-07-25 09:48", transportDays: 6, note: "타이어 상태 확인 요청", immediatePickup: false },

  // e3 · 크레인 · 검수 중 (1차 입찰은 마감됨)
  { id: "b8", equipmentId: "e3", buyer: "K글로벌기계상사", buyerTier: "공식파트너", round: 1, unitPrice: 179_000_000, submittedAt: "2024-07-17 09:20", transportDays: 14, note: "해상 선적 예정", immediatePickup: false },
  { id: "b9", equipmentId: "e3", buyer: "L기계유통", buyerTier: "우수바이어", round: 1, unitPrice: 184_500_000, submittedAt: "2024-07-17 15:02", transportDays: 5, note: "", immediatePickup: true },
  { id: "b10", equipmentId: "e3", buyer: "R중장비컴퍼니", buyerTier: "우수바이어", round: 1, unitPrice: 176_200_000, submittedAt: "2024-07-18 11:17", transportDays: 8, note: "와이어로프 교체 여부 확인 요청", immediatePickup: false },

  // e4 · 덤프트럭 8톤 · 최종(2차) 입찰 진행
  { id: "b11", equipmentId: "e4", buyer: "N장비몰", buyerTier: "일반바이어", round: 1, unitPrice: 39_600_000, submittedAt: "2024-07-01 09:30", transportDays: 6, note: "", immediatePickup: false },
  { id: "b12", equipmentId: "e4", buyer: "P기계무역", buyerTier: "공식파트너", round: 1, unitPrice: 42_700_000, submittedAt: "2024-07-01 13:52", transportDays: 4, note: "", immediatePickup: true },
  { id: "b13", equipmentId: "e4", buyer: "J중고기계", buyerTier: "우수바이어", round: 1, unitPrice: 40_900_000, submittedAt: "2024-07-02 10:11", transportDays: 5, note: "", immediatePickup: false },
  { id: "b14", equipmentId: "e4", buyer: "N장비몰", buyerTier: "일반바이어", round: 2, unitPrice: 41_800_000, submittedAt: "2024-07-22 09:40", transportDays: 6, note: "검수 리포트 확인, 감가 반영해 소폭 하향", immediatePickup: false },
  { id: "b15", equipmentId: "e4", buyer: "P기계무역", buyerTier: "공식파트너", round: 2, unitPrice: 44_100_000, submittedAt: "2024-07-22 15:18", transportDays: 3, note: "최종가 인상, 즉시 인수 조건", immediatePickup: true },

  // e5 · 휠로더 · 낙찰 확정
  { id: "b16", equipmentId: "e5", buyer: "L기계유통", buyerTier: "우수바이어", round: 1, unitPrice: 74_300_000, submittedAt: "2024-06-13 09:00", transportDays: 5, note: "", immediatePickup: true },
  { id: "b17", equipmentId: "e5", buyer: "K글로벌기계상사", buyerTier: "공식파트너", round: 1, unitPrice: 77_800_000, submittedAt: "2024-06-13 14:22", transportDays: 9, note: "", immediatePickup: false },
  { id: "b18", equipmentId: "e5", buyer: "R중장비컴퍼니", buyerTier: "우수바이어", round: 1, unitPrice: 73_100_000, submittedAt: "2024-06-14 10:45", transportDays: 6, note: "", immediatePickup: false },
  { id: "b19", equipmentId: "e5", buyer: "L기계유통", buyerTier: "우수바이어", round: 2, unitPrice: 79_600_000, submittedAt: "2024-06-21 09:15", transportDays: 4, note: "검수 결과 양호, 최종가 인상 제시", immediatePickup: true, selected: true },
  { id: "b20", equipmentId: "e5", buyer: "K글로벌기계상사", buyerTier: "공식파트너", round: 2, unitPrice: 78_400_000, submittedAt: "2024-06-21 16:03", transportDays: 8, note: "", immediatePickup: false },

  // e6 · 롤러 · 거래 완료
  { id: "b21", equipmentId: "e6", buyer: "Q리퍼비시", buyerTier: "일반바이어", round: 1, unitPrice: 32_400_000, submittedAt: "2024-05-20 09:40", transportDays: 7, note: "", immediatePickup: false },
  { id: "b22", equipmentId: "e6", buyer: "N장비몰", buyerTier: "일반바이어", round: 2, unitPrice: 34_800_000, submittedAt: "2024-05-27 11:00", transportDays: 5, note: "드럼 부식 반영해 최종가 제시", immediatePickup: true, selected: true },

  // e10 · 덤프트럭 11톤 · 거래 완료
  { id: "b23", equipmentId: "e10", buyer: "P기계무역", buyerTier: "공식파트너", round: 1, unitPrice: 50_200_000, submittedAt: "2024-05-03 09:20", transportDays: 4, note: "", immediatePickup: true },
  { id: "b24", equipmentId: "e10", buyer: "L기계유통", buyerTier: "우수바이어", round: 2, unitPrice: 53_400_000, submittedAt: "2024-05-10 13:10", transportDays: 3, note: "즉시 인수 조건으로 최종가 인상", immediatePickup: true, selected: true },
];

export const inspections: Inspection[] = [
  {
    equipmentId: "e3",
    inspector: "정민석 검수원",
    inspectedAt: "2024-07-22 14:00",
    site: "전남 여수 현장 야적장",
    gradeBefore: "B",
    gradeAfter: "B",
    priceBefore: 187_000_000,
    priceAfter: 179_500_000,
    summary: "권상 와이어로프 교체 임박 확인, 붐 구조 비파괴 검사 이상 없음. 신고가 대비 감가 폭 소폭 확대 권고.",
    items: [
      { label: "붐 구조 균열", declared: "이상 없음", observed: "이상 없음", delta: "same" },
      { label: "와이어로프 마모율", declared: "15%", observed: "28%", delta: "worse" },
      { label: "유압 실린더 누유", declared: "없음", observed: "미세 누유 1건", delta: "worse" },
      { label: "엔진 냉각계통", declared: "정상", observed: "정상", delta: "same" },
    ],
  },
  {
    equipmentId: "e4",
    inspector: "한지훈 검수원",
    inspectedAt: "2024-07-21 10:30",
    site: "경북 포항 세아베스틸 인근 부지",
    gradeBefore: "B",
    gradeAfter: "B",
    priceBefore: 41_200_000,
    priceAfter: 40_600_000,
    summary: "적재함 바닥판 교체 이력 확인, 타이어 잔여 마모 양호. 신고 내용과 실측 간 큰 차이 없음.",
    items: [
      { label: "적재함 바닥판", declared: "부분 교체", observed: "부분 교체 확인", delta: "same" },
      { label: "타이어 잔여 마모", declared: "60%", observed: "55%", delta: "worse" },
      { label: "브레이크 계통", declared: "정상", observed: "정상", delta: "same" },
    ],
  },
  {
    equipmentId: "e5",
    inspector: "오세영 검수원",
    inspectedAt: "2024-06-18 11:00",
    site: "충북 청주 공사 현장",
    gradeBefore: "B",
    gradeAfter: "B",
    priceBefore: 76_800_000,
    priceAfter: 78_100_000,
    summary: "타이어 마모 신고 내용보다 양호, 파일럿 조작계통 최근 정비 이력 확인되어 감가 폭 축소.",
    items: [
      { label: "타이어 잔여 마모", declared: "40%", observed: "52%", delta: "better" },
      { label: "파일럿 조작계통", declared: "정상", observed: "최근 정비 확인", delta: "better" },
      { label: "버킷 마모", declared: "보통", observed: "보통", delta: "same" },
    ],
  },
  {
    equipmentId: "e6",
    inspector: "정민석 검수원",
    inspectedAt: "2024-05-23 09:30",
    site: "강원 원주 야적장",
    gradeBefore: "C",
    gradeAfter: "C",
    priceBefore: 33_500_000,
    priceAfter: 33_100_000,
    summary: "드럼 표면 부식 및 실린더 미세 누유 신고 내용과 실측 일치. 등급 변동 없음.",
    items: [
      { label: "드럼 표면 부식", declared: "경미", observed: "경미", delta: "same" },
      { label: "유압 실린더 누유", declared: "미세 누유", observed: "미세 누유", delta: "same" },
    ],
  },
  {
    equipmentId: "e10",
    inspector: "한지훈 검수원",
    inspectedAt: "2024-05-07 13:20",
    site: "경기 이천 물류센터 부지",
    gradeBefore: "B",
    gradeAfter: "B",
    priceBefore: 52_600_000,
    priceAfter: 53_000_000,
    summary: "정비 이력 완비, 가동시간 신고와 실측 일치. 상태 양호로 판단.",
    items: [
      { label: "가동시간 실측", declared: "54,200시간", observed: "54,180시간", delta: "same" },
      { label: "정비 이력", declared: "완비", observed: "완비 확인", delta: "better" },
    ],
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    code: "BB-DL-0512",
    equipmentId: "e5",
    equipmentName: "1.6m³급 휠로더",
    quantity: 1,
    buyer: "L기계유통",
    seller: "E인프라",
    amount: 79_600_000,
    stage: "transport",
    confirmedAt: "2024-06-23",
    expectedAt: "2024-07-31",
    documents: [
      { name: "장비 매매계약서", kind: "계약서", size: "412KB", issuedAt: "2024-06-23" },
      { name: "검수 리포트", kind: "검수", size: "1.1MB", issuedAt: "2024-06-18" },
    ],
    timeline: [
      { label: "낙찰 확정", at: "2024-06-23", done: true },
      { label: "계약서 체결", at: "2024-06-25", done: true },
      { label: "운송 준비", at: "2024-07-27", done: true, note: "인천항 선적 대기" },
      { label: "정산 대기", at: "2024-07-29", done: false },
      { label: "거래 완료", at: "2024-07-31", done: false },
    ],
  },
  {
    id: "d2",
    code: "BB-DL-0348",
    equipmentId: "e6",
    equipmentName: "10톤급 진동롤러",
    quantity: 1,
    buyer: "N장비몰",
    seller: "F현장기계",
    amount: 34_800_000,
    stage: "done",
    confirmedAt: "2024-05-28",
    expectedAt: "2024-06-11",
    documents: [
      { name: "장비 매매계약서", kind: "계약서", size: "398KB", issuedAt: "2024-05-28" },
      { name: "검수 리포트", kind: "검수", size: "980KB", issuedAt: "2024-05-23" },
      { name: "정산 명세서", kind: "정산", size: "220KB", issuedAt: "2024-06-11" },
    ],
    timeline: [
      { label: "낙찰 확정", at: "2024-05-28", done: true },
      { label: "계약서 체결", at: "2024-05-30", done: true },
      { label: "운송 완료", at: "2024-06-06", done: true },
      { label: "정산 완료", at: "2024-06-11", done: true },
      { label: "거래 완료", at: "2024-06-11", done: true },
    ],
  },
  {
    id: "d3",
    code: "BB-DL-0201",
    equipmentId: "e10",
    equipmentName: "11톤급 덤프트럭",
    quantity: 1,
    buyer: "L기계유통",
    seller: "F현장기계",
    amount: 53_400_000,
    stage: "done",
    confirmedAt: "2024-05-10",
    expectedAt: "2024-05-25",
    documents: [
      { name: "장비 매매계약서", kind: "계약서", size: "405KB", issuedAt: "2024-05-10" },
      { name: "검수 리포트", kind: "검수", size: "890KB", issuedAt: "2024-05-07" },
      { name: "정산 명세서", kind: "정산", size: "215KB", issuedAt: "2024-05-25" },
    ],
    timeline: [
      { label: "낙찰 확정", at: "2024-05-10", done: true },
      { label: "계약서 체결", at: "2024-05-12", done: true },
      { label: "운송 완료", at: "2024-05-20", done: true },
      { label: "정산 완료", at: "2024-05-25", done: true },
      { label: "거래 완료", at: "2024-05-25", done: true },
    ],
  },
];

export const notices: NoticeItem[] = [
  { id: "n1", kind: "bid", title: "0.7m³급 굴착기 1차 입찰 신규 참여", detail: "L기계유통 70,100,000원 입찰", at: "10분 전", unread: true },
  { id: "n2", kind: "inspection", title: "25톤급 크롤러 크레인 검수 완료", detail: "검수 후 예상가 179,500,000원으로 조정", at: "1시간 전", unread: true },
  { id: "n3", kind: "bid", title: "15톤급 덤프트럭 1차 입찰 마감 임박", detail: "마감까지 3시간 남음", at: "2시간 전", unread: true },
  { id: "n4", kind: "deal", title: "1.6m³급 휠로더 운송 준비 시작", detail: "인천항 선적 대기 중", at: "어제", unread: false },
  { id: "n5", kind: "notice", title: "8월 정산 주기 안내", detail: "8월 정산은 매주 화/금요일에 진행됩니다", at: "2일 전", unread: false },
  { id: "n6", kind: "deal", title: "10톤급 진동롤러 거래 완료", detail: "정산 명세서가 발급되었습니다", at: "3일 전", unread: false },
];

export const disputes: DisputeItem[] = [
  {
    id: "dp1",
    dealCode: "BB-DL-0512",
    equipmentName: "1.6m³급 휠로더",
    raisedBy: "L기계유통",
    reason: "운송 지연으로 인한 인수 일정 재조정 요청",
    status: "reviewing",
    raisedAt: "2024-07-25",
  },
  {
    id: "dp2",
    dealCode: "BB-DL-0289",
    equipmentName: "3톤급 지게차",
    raisedBy: "Q리퍼비시",
    reason: "검수 리포트와 실물 상태 불일치 이의 제기",
    status: "open",
    raisedAt: "2024-07-27",
  },
  {
    id: "dp3",
    dealCode: "BB-DL-0176",
    equipmentName: "0.5m³급 미니 굴착기",
    raisedBy: "F현장기계",
    reason: "정산 지급 지연 문의",
    status: "resolved",
    raisedAt: "2024-07-16",
  },
];

export const adminStats = {
  pendingApprovals: 3,
  pendingInspectorAssign: 2,
  activeBidding: 4,
  openDisputes: 2,
  membersTotal: 128,
  membersSeller: 74,
  membersBuyer: 54,
};
