import avatarBaekdam from "@/projects/platform/lumi/assets/avatars/baekdam.jpg";
import avatarSoyun from "@/projects/platform/lumi/assets/avatars/soyun.jpg";
import avatarCheongyeon from "@/projects/platform/lumi/assets/avatars/cheongyeon.jpg";
import avatarHaram from "@/projects/platform/lumi/assets/avatars/haram.jpg";
import avatarSeorin from "@/projects/platform/lumi/assets/avatars/seorin.jpg";
import avatarMuyeong from "@/projects/platform/lumi/assets/avatars/muyeong.jpg";
import avatarIseol from "@/projects/platform/lumi/assets/avatars/iseol.jpg";
import avatarGangwol from "@/projects/platform/lumi/assets/avatars/gangwol.jpg";
import avatarDohyeon from "@/projects/platform/lumi/assets/avatars/dohyeon.jpg";
import avatarYeonhwa from "@/projects/platform/lumi/assets/avatars/yeonhwa.jpg";
import avatarTaeo from "@/projects/platform/lumi/assets/avatars/taeo.jpg";
import avatarYuan from "@/projects/platform/lumi/assets/avatars/yuan.jpg";
import themeHeart from "@/projects/platform/lumi/assets/theme-heart-sunset.jpg";
import themeSea from "@/projects/platform/lumi/assets/theme-sea-view.jpg";
import themeLotus from "@/projects/platform/lumi/assets/theme-lotus.jpg";
import themeMug from "@/projects/platform/lumi/assets/mood-morning-mug.jpg";
import type {
  AdminApplicant,
  AdminExpertRow,
  AdminReservation,
  CategoryKey,
  ConcernTheme,
  Consultation,
  EventItem,
  Expert,
  FaqItem,
  Notice,
  OwnedPass,
  PassProduct,
  PassTier,
  Payment,
  Review,
  Settlement,
} from "@/projects/platform/lumi/lib/types";

/** 기준 날짜: 2026년 7월 28일 화요일. 모든 mock 날짜는 이 날을 오늘로 둔다. */
export const TODAY_LABEL = "7월 28일 화요일";

export const CATEGORY_META: Record<
  CategoryKey,
  { label: string; sub: string; blurb: string }
> = {
  saju: { label: "사주", sub: "명리", blurb: "타고난 흐름과 시기를 짚습니다" },
  tarot: { label: "타로", sub: "카드", blurb: "지금 놓인 선택지를 읽습니다" },
  sinjeom: { label: "신점", sub: "신령", blurb: "묻고 답을 받는 방식입니다" },
};

export const PASS_PRODUCTS: PassProduct[] = [
  {
    tier: "lite",
    name: "Lite",
    minutes: 15,
    price: 24000,
    listPrice: 27000,
    perMinute: 1600,
    summary: "질문 한두 개를 빠르게 정리할 때",
    includes: ["상담 15분", "상담 요약 노트", "녹취 보관 30일"],
    bestFor: "오늘 결정해야 하는 단답형 고민",
  },
  {
    tier: "standard",
    name: "Standard",
    minutes: 30,
    price: 44000,
    listPrice: 52000,
    perMinute: 1467,
    summary: "사연을 설명하고 흐름까지 볼 때",
    includes: ["상담 30분", "상담 요약 노트", "녹취 보관 90일", "재상담 5% 적립"],
    bestFor: "연애, 이직처럼 배경 설명이 필요한 고민",
  },
  {
    tier: "premium",
    name: "Premium",
    minutes: 60,
    price: 82000,
    listPrice: 98000,
    perMinute: 1367,
    summary: "한 해 전체 운을 짚고 정리할 때",
    includes: [
      "상담 60분",
      "상담 요약 노트",
      "녹취 보관 180일",
      "월별 흐름표 PDF",
      "재상담 10% 적립",
    ],
    bestFor: "신년운세, 사업 방향, 택일처럼 범위가 넓은 고민",
  },
];

export const PASS_BY_TIER: Record<PassTier, PassProduct> = {
  lite: PASS_PRODUCTS[0],
  standard: PASS_PRODUCTS[1],
  premium: PASS_PRODUCTS[2],
};

export const OWNED_PASSES: OwnedPass[] = [
  { tier: "lite", count: 2, expiresAt: "2026.10.14" },
  { tier: "standard", count: 1, expiresAt: "2026.09.02" },
  { tier: "premium", count: 0, expiresAt: "-" },
];

export const USER = {
  name: "정예린",
  nickname: "예린",
  phone: "010-3847-2210",
  birth: "1994년 3월 12일 (음력)",
  birthTime: "인시 (03:30 ~ 05:30)",
  gender: "여성",
  joinedAt: "2025.11.08",
  grade: "실버",
  gradeNote: "누적 상담 9회",
  point: 3200,
  coupon: 2,
};

const SLOT_DATES = [
  { date: "2026-07-28", label: "오늘 7/28" },
  { date: "2026-07-29", label: "내일 7/29" },
  { date: "2026-07-30", label: "목 7/30" },
  { date: "2026-07-31", label: "금 7/31" },
  { date: "2026-08-01", label: "토 8/1" },
];

function slots(pattern: [string, boolean][][]) {
  return SLOT_DATES.map((d, i) => ({
    date: d.date,
    label: d.label,
    times: (pattern[i] ?? pattern[pattern.length - 1]).map(([time, taken]) => ({ time, taken })),
  }));
}

const EVENING: [string, boolean][] = [
  ["18:00", false],
  ["19:00", true],
  ["20:00", false],
  ["21:00", false],
  ["22:00", false],
];

const DAYTIME: [string, boolean][] = [
  ["10:00", true],
  ["11:00", false],
  ["13:00", false],
  ["14:00", false],
  ["16:00", true],
  ["17:00", false],
];

const FULL_DAY: [string, boolean][] = [
  ["09:00", false],
  ["10:30", false],
  ["12:00", true],
  ["14:00", false],
  ["15:30", false],
  ["17:00", true],
  ["19:00", false],
  ["20:30", false],
];

export const EXPERTS: Expert[] = [
  {
    id: "baekdam",
    name: "백담",
    headline: "재물과 직업의 시기를 연도별로 끊어 봅니다",
    category: "saju",
    alsoHandles: ["sinjeom"],
    avatar: avatarBaekdam,
    rating: 4.92,
    reviewCount: 2841,
    sessionCount: 11420,
    years: 24,
    responseRate: 98,
    repeatRate: 61,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2024.02.11",
    isNew: false,
    specialties: ["재물운", "직장·이직", "사업 방향", "대운 흐름"],
    styleTags: ["단호한 편", "결론 먼저", "숫자로 정리"],
    intro:
      "사주는 성격 감정이 아니라 시기 판단이라고 생각합니다. 지금 움직여도 되는 해인지, 한 해를 더 기다려야 하는지부터 말씀드립니다. 위로가 필요하신 분보다 결정을 내려야 하는 분께 맞습니다.",
    career: [
      "명리 상담 24년, 누적 상담 1만 1천 건",
      "직장인 이직 시기 상담 비중 40%",
      "2024년 LUMI 입점, 2025년 루미 마스터 등급",
    ],
    ratingBreakdown: [
      { stars: 5, count: 2510 },
      { stars: 4, count: 251 },
      { stars: 3, count: 58 },
      { stars: 2, count: 14 },
      { stars: 1, count: 8 },
    ],
    slots: slots([EVENING, FULL_DAY, FULL_DAY, EVENING, DAYTIME]),
    tiers: ["lite", "standard", "premium"],
  },
  {
    id: "soyun",
    name: "소윤",
    headline: "연애 상황을 카드로 하나씩 짚어 드립니다",
    category: "tarot",
    alsoHandles: [],
    avatar: avatarSoyun,
    rating: 4.88,
    reviewCount: 3204,
    sessionCount: 9870,
    years: 11,
    responseRate: 99,
    repeatRate: 58,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2024.05.02",
    isNew: false,
    specialties: ["연애·재회", "썸·고백", "상대 속마음", "결혼 시기"],
    styleTags: ["차분한 편", "질문 정리 도움", "다정한 말투"],
    intro:
      "상황을 먼저 충분히 듣고 카드를 뽑습니다. 상대 마음을 단정하기보다 지금 흐름에서 무엇을 바꿀 수 있는지에 시간을 더 씁니다. 첫 상담이라 무엇을 물어야 할지 모르겠다면 같이 정리해 드립니다.",
    career: [
      "타로 상담 11년, 누적 상담 9천 8백 건",
      "재회·관계 회복 상담 비중 55%",
      "월 재상담률 58%",
    ],
    ratingBreakdown: [
      { stars: 5, count: 2790 },
      { stars: 4, count: 322 },
      { stars: 3, count: 62 },
      { stars: 2, count: 19 },
      { stars: 1, count: 11 },
    ],
    slots: slots([EVENING, EVENING, FULL_DAY, FULL_DAY, FULL_DAY]),
    tiers: ["lite", "standard", "premium"],
  },
  {
    id: "cheongyeon",
    name: "청연",
    headline: "조상신 계통, 묻는 것에만 답을 드립니다",
    category: "sinjeom",
    alsoHandles: [],
    avatar: avatarCheongyeon,
    rating: 4.79,
    reviewCount: 1476,
    sessionCount: 6210,
    years: 17,
    responseRate: 94,
    repeatRate: 47,
    status: "inCall",
    waitMinutes: 12,
    joinedAt: "2024.09.20",
    isNew: false,
    specialties: ["가족·집안", "건강 흐름", "이사·택일", "사업 시기"],
    styleTags: ["직설적", "말이 빠른 편", "군더더기 없음"],
    intro:
      "듣고 싶은 말을 해 드리지는 못합니다. 물으신 것에 보이는 대로 답합니다. 짧게 끊어 여쭤보실수록 정확합니다. 부적이나 굿을 권하지 않습니다.",
    career: [
      "신점 상담 17년, 누적 상담 6천 2백 건",
      "집안·조상 관련 상담 비중 43%",
      "고지 사항: 별도 의식 비용을 요구하지 않습니다",
    ],
    ratingBreakdown: [
      { stars: 5, count: 1152 },
      { stars: 4, count: 214 },
      { stars: 3, count: 74 },
      { stars: 2, count: 22 },
      { stars: 1, count: 14 },
    ],
    slots: slots([DAYTIME, DAYTIME, FULL_DAY, DAYTIME, DAYTIME]),
    tiers: ["standard", "premium"],
  },
  {
    id: "haram",
    name: "하람",
    headline: "궁합과 결혼 시기를 두 사람 사주로 봅니다",
    category: "saju",
    alsoHandles: ["tarot"],
    avatar: avatarHaram,
    rating: 4.85,
    reviewCount: 1932,
    sessionCount: 7340,
    years: 15,
    responseRate: 97,
    repeatRate: 52,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2025.01.14",
    isNew: false,
    specialties: ["궁합", "결혼 시기", "가족 관계", "택일"],
    styleTags: ["설명이 자세함", "근거 위주", "메모 권장"],
    intro:
      "두 분 사주를 같이 놓고 어디서 부딪히는지, 그게 시기 문제인지 성향 문제인지 나눠 설명합니다. 상대 생년월일을 모르면 태어난 해만으로도 가능한 범위까지만 봅니다.",
    career: [
      "명리 상담 15년, 누적 상담 7천 3백 건",
      "궁합·결혼 상담 비중 62%",
      "2025년 상반기 재상담률 상위 5%",
    ],
    ratingBreakdown: [
      { stars: 5, count: 1690 },
      { stars: 4, count: 182 },
      { stars: 3, count: 42 },
      { stars: 2, count: 11 },
      { stars: 1, count: 7 },
    ],
    slots: slots([EVENING, FULL_DAY, EVENING, FULL_DAY, DAYTIME]),
    tiers: ["lite", "standard", "premium"],
  },
  {
    id: "seorin",
    name: "서린",
    headline: "커리어 고민을 카드와 현실 조건으로 같이 봅니다",
    category: "tarot",
    alsoHandles: ["saju"],
    avatar: avatarSeorin,
    rating: 4.9,
    reviewCount: 1108,
    sessionCount: 4180,
    years: 8,
    responseRate: 99,
    repeatRate: 55,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2025.06.03",
    isNew: false,
    specialties: ["이직·퇴사", "시험·합격", "사업 시작", "동료 관계"],
    styleTags: ["현실적", "실행안 제시", "빠른 정리"],
    intro:
      "카드만 보고 답하지 않습니다. 지금 조건에서 실행 가능한 선택지를 두세 개로 좁힌 다음, 그중 어떤 쪽에 흐름이 붙는지를 봅니다. 이력서나 면접 일정이 있으시면 미리 말씀해 주세요.",
    career: [
      "타로 상담 8년, 누적 상담 4천 1백 건",
      "직장·커리어 상담 비중 71%",
      "이전 직군: 인사 담당 6년",
    ],
    ratingBreakdown: [
      { stars: 5, count: 984 },
      { stars: 4, count: 96 },
      { stars: 3, count: 19 },
      { stars: 2, count: 6 },
      { stars: 1, count: 3 },
    ],
    slots: slots([DAYTIME, DAYTIME, DAYTIME, EVENING, EVENING]),
    tiers: ["lite", "standard"],
  },
  {
    id: "muyeong",
    name: "무영",
    headline: "택일과 이사, 개업 날짜를 잡아 드립니다",
    category: "sinjeom",
    alsoHandles: ["saju"],
    avatar: avatarMuyeong,
    rating: 4.72,
    reviewCount: 864,
    sessionCount: 3520,
    years: 21,
    responseRate: 92,
    repeatRate: 44,
    status: "reserveOnly",
    waitMinutes: 0,
    joinedAt: "2025.03.27",
    isNew: false,
    specialties: ["택일", "이사·개업", "조상·제사", "구설 회피"],
    styleTags: ["말수 적음", "핵심만", "날짜 위주"],
    intro:
      "날짜를 잡을 때는 후보를 세 개까지 드립니다. 사정상 조정이 필요하면 어느 날이 차선인지도 같이 말씀드립니다. 즉시 상담은 받지 않고 예약만 받습니다.",
    career: [
      "신점 상담 21년, 누적 상담 3천 5백 건",
      "택일 상담 비중 58%",
      "예약제 운영, 당일 예약 불가",
    ],
    ratingBreakdown: [
      { stars: 5, count: 621 },
      { stars: 4, count: 158 },
      { stars: 3, count: 54 },
      { stars: 2, count: 21 },
      { stars: 1, count: 10 },
    ],
    slots: slots([[], DAYTIME, DAYTIME, DAYTIME, [["10:00", false], ["11:30", false]]]),
    tiers: ["standard", "premium"],
  },
  {
    id: "iseol",
    name: "이설",
    headline: "타로와 상담 심리를 같이 씁니다",
    category: "tarot",
    alsoHandles: [],
    avatar: avatarIseol,
    rating: 4.94,
    reviewCount: 412,
    sessionCount: 980,
    years: 6,
    responseRate: 100,
    repeatRate: 49,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2026.06.19",
    isNew: true,
    specialties: ["자존감·불안", "가족 갈등", "번아웃", "관계 정리"],
    styleTags: ["듣는 시간이 김", "감정 정리", "질문형"],
    intro:
      "결론을 먼저 드리기보다 지금 감정이 어디서 나오는지 같이 찾습니다. 30분 이상 상담을 권해 드립니다. 15분으로는 사연을 다 듣기 어렵습니다.",
    career: [
      "타로 상담 6년, 상담심리 전공",
      "관계·정서 상담 비중 68%",
      "2026년 6월 LUMI 입점",
    ],
    ratingBreakdown: [
      { stars: 5, count: 389 },
      { stars: 4, count: 18 },
      { stars: 3, count: 3 },
      { stars: 2, count: 1 },
      { stars: 1, count: 1 },
    ],
    slots: slots([EVENING, EVENING, EVENING, FULL_DAY, FULL_DAY]),
    tiers: ["standard", "premium"],
  },
  {
    id: "gangwol",
    name: "강월",
    headline: "신년운세와 한 해 흐름을 정리해 드립니다",
    category: "saju",
    alsoHandles: [],
    avatar: avatarGangwol,
    rating: 4.81,
    reviewCount: 2260,
    sessionCount: 8940,
    years: 19,
    responseRate: 96,
    repeatRate: 63,
    status: "inCall",
    waitMinutes: 25,
    joinedAt: "2024.07.08",
    isNew: false,
    specialties: ["신년운세", "월별 흐름", "재물운", "건강"],
    styleTags: ["차분한 편", "표로 정리", "복기 좋음"],
    intro:
      "한 해를 월 단위로 끊어 어느 달에 무엇을 조심해야 하는지 정리해 드립니다. 60분 상담을 하시면 월별 흐름표를 상담 후 발송해 드립니다.",
    career: [
      "명리 상담 19년, 누적 상담 8천 9백 건",
      "신년운세 시즌 누적 3천 건",
      "재상담률 63%로 플랫폼 상위",
    ],
    ratingBreakdown: [
      { stars: 5, count: 1889 },
      { stars: 4, count: 288 },
      { stars: 3, count: 58 },
      { stars: 2, count: 17 },
      { stars: 1, count: 8 },
    ],
    slots: slots([DAYTIME, FULL_DAY, FULL_DAY, FULL_DAY, DAYTIME]),
    tiers: ["standard", "premium"],
  },
  {
    id: "dohyeon",
    name: "도현",
    headline: "작명과 개명, 상호 이름을 봅니다",
    category: "saju",
    alsoHandles: [],
    avatar: avatarDohyeon,
    rating: 4.76,
    reviewCount: 538,
    sessionCount: 2140,
    years: 13,
    responseRate: 95,
    repeatRate: 31,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2025.09.11",
    isNew: false,
    specialties: ["작명·개명", "상호명", "아이 사주", "가족 궁합"],
    styleTags: ["설명이 자세함", "한자 풀이", "자료 발송"],
    intro:
      "이름은 소리와 한자, 사주 보완 세 가지를 같이 봅니다. 후보를 받아 오시면 그중 무엇이 나은지 비교해 드리고, 없으시면 상담 중에 세 개까지 잡아 드립니다.",
    career: [
      "명리·작명 13년, 누적 상담 2천 1백 건",
      "출생아 작명 비중 54%",
      "상담 후 한자 풀이 자료 발송",
    ],
    ratingBreakdown: [
      { stars: 5, count: 421 },
      { stars: 4, count: 82 },
      { stars: 3, count: 24 },
      { stars: 2, count: 7 },
      { stars: 1, count: 4 },
    ],
    slots: slots([DAYTIME, DAYTIME, DAYTIME, DAYTIME, [["10:00", false], ["14:00", false]]]),
    tiers: ["standard", "premium"],
  },
  {
    id: "yeonhwa",
    name: "연화",
    headline: "가족 문제와 오래된 갈등을 봅니다",
    category: "sinjeom",
    alsoHandles: [],
    avatar: avatarYeonhwa,
    rating: 4.68,
    reviewCount: 1024,
    sessionCount: 4620,
    years: 26,
    responseRate: 90,
    repeatRate: 38,
    status: "offline",
    waitMinutes: 0,
    joinedAt: "2024.11.30",
    isNew: false,
    specialties: ["가족 갈등", "자녀 문제", "건강", "조상"],
    styleTags: ["느린 말투", "오래 듣는 편", "직설적"],
    intro:
      "묻는 사람보다 주변 사람 이야기를 더 하시는 경우가 많습니다. 그래도 괜찮습니다. 다 듣고 나서 한 번에 정리해 드립니다. 상담 가능 시간은 오전 10시부터 오후 4시까지입니다.",
    career: [
      "신점 상담 26년, 누적 상담 4천 6백 건",
      "가족·자녀 상담 비중 66%",
      "오전 시간대 운영",
    ],
    ratingBreakdown: [
      { stars: 5, count: 712 },
      { stars: 4, count: 208 },
      { stars: 3, count: 68 },
      { stars: 2, count: 24 },
      { stars: 1, count: 12 },
    ],
    slots: slots([[], DAYTIME, DAYTIME, DAYTIME, []]),
    tiers: ["lite", "standard"],
  },
  {
    id: "taeo",
    name: "태오",
    headline: "짧게 묻고 짧게 답하는 15분 전용 상담",
    category: "tarot",
    alsoHandles: [],
    avatar: avatarTaeo,
    rating: 4.83,
    reviewCount: 296,
    sessionCount: 720,
    years: 5,
    responseRate: 100,
    repeatRate: 41,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2026.07.02",
    isNew: true,
    specialties: ["단답 질문", "선택 비교", "면접·시험", "일상 운"],
    styleTags: ["속도 빠름", "결론 먼저", "군더더기 없음"],
    intro:
      "질문 두세 개를 정해 오시면 15분 안에 정리해 드립니다. 길게 상담하고 싶으신 분께는 맞지 않습니다. 오늘 당장 답이 필요한 분께 권합니다.",
    career: [
      "타로 상담 5년, 누적 상담 720건",
      "15분 상담 비중 84%",
      "2026년 7월 LUMI 입점",
    ],
    ratingBreakdown: [
      { stars: 5, count: 258 },
      { stars: 4, count: 29 },
      { stars: 3, count: 6 },
      { stars: 2, count: 2 },
      { stars: 1, count: 1 },
    ],
    slots: slots([EVENING, EVENING, EVENING, EVENING, EVENING]),
    tiers: ["lite"],
  },
  {
    id: "yuan",
    name: "유안",
    headline: "시험과 합격 시기를 사주로 봅니다",
    category: "saju",
    alsoHandles: ["tarot"],
    avatar: avatarYuan,
    rating: 4.87,
    reviewCount: 742,
    sessionCount: 3080,
    years: 9,
    responseRate: 98,
    repeatRate: 46,
    status: "available",
    waitMinutes: 0,
    joinedAt: "2026.05.21",
    isNew: true,
    specialties: ["시험·합격", "공무원 준비", "학업", "진로"],
    styleTags: ["차분한 편", "근거 위주", "일정 정리"],
    intro:
      "준비 중인 시험 일정과 회차를 알려 주시면 어느 회차에 흐름이 붙는지 봅니다. 무조건 붙는다는 말씀은 드리지 않습니다. 붙기 어려운 해라면 그 이유와 보완할 부분을 말씀드립니다.",
    career: [
      "명리 상담 9년, 누적 상담 3천 건",
      "수험·학업 상담 비중 73%",
      "2026년 5월 LUMI 입점",
    ],
    ratingBreakdown: [
      { stars: 5, count: 662 },
      { stars: 4, count: 62 },
      { stars: 3, count: 12 },
      { stars: 2, count: 4 },
      { stars: 1, count: 2 },
    ],
    slots: slots([EVENING, DAYTIME, DAYTIME, EVENING, DAYTIME]),
    tiers: ["lite", "standard", "premium"],
  },
];

export const EXPERT_BY_ID: Record<string, Expert> = Object.fromEntries(
  EXPERTS.map((e) => [e.id, e]),
);

export function expertById(id: string): Expert {
  return EXPERT_BY_ID[id] ?? EXPERTS[0];
}

export const REVIEWS: Review[] = [
  {
    id: "rv-01",
    expertId: "baekdam",
    author: "김*민",
    rating: 5,
    tier: "standard",
    createdAt: "2026.07.26",
    body: "이직 시기만 물었는데 올해 하반기는 이력서를 넣어도 결과가 늦게 온다고 하시고, 내년 3월 이후를 보라고 하셨어요. 이유까지 연도별로 설명해 주셔서 납득이 됐습니다.",
    tags: ["결론이 명확해요", "시기를 짚어줘요"],
    helpful: 42,
  },
  {
    id: "rv-02",
    expertId: "baekdam",
    author: "이*재",
    rating: 5,
    tier: "premium",
    createdAt: "2026.07.21",
    body: "가게 확장 문제로 60분 상담했습니다. 듣기 좋은 말은 안 하시는 분이라 오히려 믿음이 갔어요. 자금 들어가는 시점을 미루라는 조언대로 하려고 합니다.",
    tags: ["단호해요", "사업 상담 잘봐요"],
    helpful: 31,
  },
  {
    id: "rv-03",
    expertId: "baekdam",
    author: "박*은",
    rating: 4,
    tier: "lite",
    createdAt: "2026.07.18",
    body: "15분이라 질문 두 개만 했는데도 정리가 됐습니다. 다만 말씀이 빠른 편이라 메모 준비하고 들어가시는 걸 추천드려요.",
    tags: ["속도가 빨라요"],
    helpful: 18,
  },
  {
    id: "rv-04",
    expertId: "soyun",
    author: "최*아",
    rating: 5,
    tier: "standard",
    createdAt: "2026.07.27",
    body: "재회 상담이었는데 상대 마음을 단정하지 않고 제가 지금 하고 있는 행동 중에 뭘 멈춰야 하는지 짚어 주셨어요. 울면서 통화했는데 끝나고 마음이 정리됐습니다.",
    tags: ["다정해요", "이야기를 잘 들어줘요"],
    helpful: 67,
  },
  {
    id: "rv-05",
    expertId: "soyun",
    author: "정*현",
    rating: 5,
    tier: "lite",
    createdAt: "2026.07.24",
    body: "썸 타는 중에 고백 타이밍만 물어봤어요. 이번 주는 아니고 상대 일정이 정리되는 다음 주라고 하셨는데 실제로 그때 분위기가 달라졌습니다.",
    tags: ["시기를 짚어줘요", "차분해요"],
    helpful: 54,
  },
  {
    id: "rv-06",
    expertId: "soyun",
    author: "한*림",
    rating: 4,
    tier: "standard",
    createdAt: "2026.07.19",
    body: "카드 해석을 자세히 설명해 주셔서 좋았습니다. 제가 질문을 두서없이 해서 시간이 조금 부족했어요. 다음엔 정리해서 다시 가려고요.",
    tags: ["설명이 자세해요"],
    helpful: 12,
  },
  {
    id: "rv-07",
    expertId: "cheongyeon",
    author: "오*석",
    rating: 5,
    tier: "standard",
    createdAt: "2026.07.25",
    body: "집안 어른 건강 문제로 봤습니다. 묻지도 않은 걸 먼저 말씀하셔서 놀랐어요. 굿이나 부적 얘기는 한마디도 없으셨습니다.",
    tags: ["정확해요", "권유가 없어요"],
    helpful: 88,
  },
  {
    id: "rv-08",
    expertId: "cheongyeon",
    author: "서*빈",
    rating: 3,
    tier: "standard",
    createdAt: "2026.07.20",
    body: "말씀이 워낙 직설적이라 마음의 준비가 필요합니다. 내용 자체는 맞는 부분이 많았는데 위로를 기대하고 갔다면 힘들 수도 있어요.",
    tags: ["직설적이에요"],
    helpful: 45,
  },
  {
    id: "rv-09",
    expertId: "haram",
    author: "윤*진",
    rating: 5,
    tier: "premium",
    createdAt: "2026.07.23",
    body: "결혼 준비 중에 둘이 자꾸 부딪혀서 궁합 봤습니다. 성향 차이가 아니라 올해 둘 다 예민한 시기라는 설명이 제일 도움이 됐어요.",
    tags: ["궁합 잘봐요", "설명이 자세해요"],
    helpful: 39,
  },
  {
    id: "rv-10",
    expertId: "seorin",
    author: "강*우",
    rating: 5,
    tier: "lite",
    createdAt: "2026.07.27",
    body: "퇴사 고민으로 15분 상담했는데 선택지를 세 개로 좁혀 주시고 각각 뭘 확인해야 하는지 알려 주셨어요. 점 본다기보다 상담받은 느낌입니다.",
    tags: ["현실적이에요", "정리를 잘해줘요"],
    helpful: 73,
  },
  {
    id: "rv-11",
    expertId: "gangwol",
    author: "노*경",
    rating: 5,
    tier: "premium",
    createdAt: "2026.07.22",
    body: "신년운세를 여름에 보는 게 늦나 싶었는데 남은 달만 짚어 주셔서 좋았어요. 상담 끝나고 월별 흐름표도 받았습니다.",
    tags: ["자료를 줘요", "차분해요"],
    helpful: 26,
  },
  {
    id: "rv-12",
    expertId: "iseol",
    author: "장*희",
    rating: 5,
    tier: "standard",
    createdAt: "2026.07.26",
    body: "번아웃 때문에 아무한테도 말 못 하던 걸 다 얘기했어요. 카드보다 대화 시간이 길었는데 그게 필요했던 것 같습니다.",
    tags: ["이야기를 잘 들어줘요", "편안해요"],
    helpful: 34,
  },
  {
    id: "rv-13",
    expertId: "muyeong",
    author: "임*수",
    rating: 4,
    tier: "standard",
    createdAt: "2026.07.17",
    body: "개업 날짜 세 개 받았습니다. 말수가 적으셔서 처음엔 당황했는데 필요한 건 다 알려 주셨어요.",
    tags: ["핵심만 말해요"],
    helpful: 15,
  },
  {
    id: "rv-14",
    expertId: "taeo",
    author: "문*지",
    rating: 5,
    tier: "lite",
    createdAt: "2026.07.28",
    body: "면접 두 곳 중에 어디를 갈지만 물었어요. 5분 만에 답 나오고 나머지는 이유 설명이었습니다. 짧게 물어보기 좋아요.",
    tags: ["빨라요", "단답 상담"],
    helpful: 21,
  },
];

export function reviewsOf(expertId: string) {
  return REVIEWS.filter((r) => r.expertId === expertId);
}

export const CONSULTATIONS: Consultation[] = [
  {
    id: "cs-2401",
    expertId: "baekdam",
    tier: "standard",
    status: "upcoming",
    scheduledAt: "2026-07-28T20:00",
    dateLabel: "오늘 7월 28일",
    timeLabel: "오후 8:00",
    usedMinutes: 0,
    topic: "하반기 이직 시기",
    reviewed: false,
    memo: "8월 지원 예정인 회사 두 곳, 연봉 협상 시점",
  },
  {
    id: "cs-2402",
    expertId: "iseol",
    tier: "standard",
    status: "upcoming",
    scheduledAt: "2026-07-31T21:00",
    dateLabel: "금 7월 31일",
    timeLabel: "오후 9:00",
    usedMinutes: 0,
    topic: "가족 갈등 정리",
    reviewed: false,
    memo: "명절 이후 반복되는 문제",
  },
  {
    id: "cs-2398",
    expertId: "soyun",
    tier: "lite",
    status: "done",
    scheduledAt: "2026-07-24T19:00",
    dateLabel: "7월 24일",
    timeLabel: "오후 7:00",
    usedMinutes: 15,
    topic: "재회 가능성",
    reviewed: false,
  },
  {
    id: "cs-2391",
    expertId: "seorin",
    tier: "lite",
    status: "done",
    scheduledAt: "2026-07-16T14:00",
    dateLabel: "7월 16일",
    timeLabel: "오후 2:00",
    usedMinutes: 14,
    topic: "퇴사 후 공백 기간",
    reviewed: true,
  },
  {
    id: "cs-2377",
    expertId: "gangwol",
    tier: "premium",
    status: "done",
    scheduledAt: "2026-06-29T11:00",
    dateLabel: "6월 29일",
    timeLabel: "오전 11:00",
    usedMinutes: 58,
    topic: "하반기 전체 흐름",
    reviewed: true,
  },
  {
    id: "cs-2364",
    expertId: "cheongyeon",
    tier: "standard",
    status: "done",
    scheduledAt: "2026-06-11T13:00",
    dateLabel: "6월 11일",
    timeLabel: "오후 1:00",
    usedMinutes: 30,
    topic: "부모님 건강",
    reviewed: true,
  },
  {
    id: "cs-2352",
    expertId: "haram",
    tier: "standard",
    status: "canceled",
    scheduledAt: "2026-05-30T20:00",
    dateLabel: "5월 30일",
    timeLabel: "오후 8:00",
    usedMinutes: 0,
    topic: "궁합",
    reviewed: false,
    canceledReason: "본인 취소 (상담 2시간 전, 상담권 복구 완료)",
  },
  {
    id: "cs-2341",
    expertId: "muyeong",
    tier: "standard",
    status: "noshow",
    scheduledAt: "2026-05-12T15:00",
    dateLabel: "5월 12일",
    timeLabel: "오후 3:00",
    usedMinutes: 0,
    topic: "이사 택일",
    reviewed: false,
    canceledReason: "미응답 처리 (상담권 50% 복구)",
  },
];

export const PAYMENTS: Payment[] = [
  {
    id: "pay-9821",
    label: "Standard 30분 상담권",
    tier: "standard",
    quantity: 2,
    amount: 88000,
    method: "A페이 간편결제",
    paidAt: "2026.07.20 21:14",
    status: "완료",
  },
  {
    id: "pay-9744",
    label: "Lite 15분 상담권",
    tier: "lite",
    quantity: 3,
    amount: 72000,
    method: "B카드 5*** 4412",
    paidAt: "2026.07.08 12:32",
    status: "완료",
  },
  {
    id: "pay-9612",
    label: "Premium 60분 상담권",
    tier: "premium",
    quantity: 1,
    amount: 82000,
    method: "A페이 간편결제",
    paidAt: "2026.06.27 19:05",
    status: "완료",
  },
  {
    id: "pay-9530",
    label: "Standard 30분 상담권",
    tier: "standard",
    quantity: 1,
    amount: 44000,
    method: "B카드 5*** 4412",
    paidAt: "2026.05.29 18:41",
    status: "환불",
  },
  {
    id: "pay-9488",
    label: "첫 상담 쿠폰 적용",
    tier: "coupon",
    quantity: 1,
    amount: 0,
    method: "웰컴 쿠폰",
    paidAt: "2026.05.12 10:20",
    status: "완료",
  },
];

export const FAVORITE_IDS = ["soyun", "baekdam", "seorin", "iseol"];

export const CONCERN_THEMES: ConcernTheme[] = [
  {
    id: "love",
    label: "연애·재회",
    copy: "마음을 확인하고 싶을 때",
    image: themeHeart,
    count: 128,
  },
  {
    id: "career",
    label: "직장·이직",
    copy: "옮길 때인지 알고 싶을 때",
    image: themeSea,
    count: 94,
  },
  {
    id: "year",
    label: "신년·운세",
    copy: "한 해 흐름을 정리할 때",
    image: themeLotus,
    count: 76,
  },
  {
    id: "daily",
    label: "오늘의 결정",
    copy: "지금 답이 필요할 때",
    image: themeMug,
    count: 61,
  },
];

export const CONSULT_TAGS = [
  "결론이 명확해요",
  "이야기를 잘 들어줘요",
  "시기를 짚어줘요",
  "설명이 자세해요",
  "현실적이에요",
  "다정해요",
  "직설적이에요",
  "속도가 빨라요",
];

export const CAUTIONS = [
  "상담은 안심번호로 연결되며 상담사에게 번호가 노출되지 않습니다.",
  "상담 시작 후 5분 이내 종료 시에만 상담권이 복구됩니다.",
  "예약 시간 10분 전까지 취소하면 상담권이 전액 복구됩니다.",
  "의료, 법률, 투자 자문을 대신하지 않습니다.",
];

export function formatWon(value: number) {
  return value.toLocaleString("ko-KR");
}

/* ---------- 관리자 콘솔 mock ---------- */

export const ADMIN_TODAY = {
  sessions: 428,
  sessionsDelta: 6.2,
  reservations: 214,
  reservationsPending: 37,
  revenue: 18420000,
  revenueDelta: 4.1,
  completionRate: 93.4,
  newMembers: 186,
  newMembersDelta: -2.8,
  payoutDue: 42680000,
  payoutCount: 74,
  liveSessions: 26,
  waiting: 9,
  issues: 3,
};

export const ADMIN_HOURLY = [
  { hour: "09", sessions: 12 },
  { hour: "10", sessions: 21 },
  { hour: "11", sessions: 26 },
  { hour: "12", sessions: 18 },
  { hour: "13", sessions: 24 },
  { hour: "14", sessions: 31 },
  { hour: "15", sessions: 29 },
  { hour: "16", sessions: 27 },
  { hour: "17", sessions: 33 },
  { hour: "18", sessions: 41 },
  { hour: "19", sessions: 52 },
  { hour: "20", sessions: 58 },
  { hour: "21", sessions: 34 },
  { hour: "22", sessions: 22 },
];

export const ADMIN_TIER_MIX = [
  { tier: "lite" as PassTier, share: 46, sessions: 197 },
  { tier: "standard" as PassTier, share: 38, sessions: 163 },
  { tier: "premium" as PassTier, share: 16, sessions: 68 },
];

export const ADMIN_LIVE_FEED = [
  { time: "21:34", text: "청연 상담사 상담 시작 (Standard 30분)", state: "info" as const },
  { time: "21:31", text: "예약 R-20874 노쇼 임박, 미응답 8분 경과", state: "warn" as const },
  { time: "21:28", text: "백담 상담사 상담 종료, 사용 28분", state: "info" as const },
  { time: "21:22", text: "결제 실패 3건 연속 발생, B카드 승인 지연", state: "danger" as const },
  { time: "21:19", text: "신규 상담사 유안 프로필 수정 요청", state: "info" as const },
  { time: "21:07", text: "강월 상담사 대기열 25분 초과", state: "warn" as const },
];

export const ADMIN_RESERVATIONS: AdminReservation[] = [
  {
    id: "R-20881",
    memberName: "정예린",
    memberPhone: "010-3847-2210",
    expertId: "baekdam",
    tier: "standard",
    scheduledAt: "07.28 20:00",
    channel: "예약",
    state: "대기",
    amount: 44000,
    usedMinutes: 0,
    note: "하반기 이직 시기",
  },
  {
    id: "R-20880",
    memberName: "차민석",
    memberPhone: "010-2211-8834",
    expertId: "cheongyeon",
    tier: "standard",
    scheduledAt: "07.28 21:30",
    channel: "즉시",
    state: "진행중",
    amount: 44000,
    usedMinutes: 12,
    note: "집안 건강 문제",
  },
  {
    id: "R-20879",
    memberName: "황지우",
    memberPhone: "010-9042-1176",
    expertId: "soyun",
    tier: "lite",
    scheduledAt: "07.28 21:00",
    channel: "즉시",
    state: "완료",
    amount: 24000,
    usedMinutes: 15,
    note: "고백 시기",
  },
  {
    id: "R-20874",
    memberName: "배소원",
    memberPhone: "010-5518-3390",
    expertId: "gangwol",
    tier: "premium",
    scheduledAt: "07.28 19:00",
    channel: "예약",
    state: "노쇼",
    amount: 82000,
    usedMinutes: 0,
    note: "미응답 8분, 자동 안내 발송",
  },
  {
    id: "R-20871",
    memberName: "고윤재",
    memberPhone: "010-7734-6621",
    expertId: "seorin",
    tier: "lite",
    scheduledAt: "07.28 18:30",
    channel: "즉시",
    state: "완료",
    amount: 24000,
    usedMinutes: 14,
    note: "퇴사 고민",
  },
  {
    id: "R-20866",
    memberName: "신다혜",
    memberPhone: "010-1194-2087",
    expertId: "haram",
    tier: "premium",
    scheduledAt: "07.28 17:00",
    channel: "예약",
    state: "취소",
    amount: 82000,
    usedMinutes: 0,
    note: "상담 3시간 전 본인 취소",
  },
  {
    id: "R-20862",
    memberName: "류태경",
    memberPhone: "010-6605-4418",
    expertId: "iseol",
    tier: "standard",
    scheduledAt: "07.28 16:00",
    channel: "예약",
    state: "완료",
    amount: 44000,
    usedMinutes: 31,
    note: "번아웃 상담",
  },
  {
    id: "R-20858",
    memberName: "오세라",
    memberPhone: "010-3320-7752",
    expertId: "muyeong",
    tier: "standard",
    scheduledAt: "07.29 11:00",
    channel: "예약",
    state: "대기",
    amount: 44000,
    usedMinutes: 0,
    note: "개업 택일",
  },
];

export const ADMIN_APPLICANTS: AdminApplicant[] = [
  {
    id: "AP-114",
    name: "정하윤",
    category: "tarot",
    years: 7,
    appliedAt: "2026.07.26",
    documents: [
      { label: "신분 확인", state: "확인" },
      { label: "상담 이력 증빙", state: "확인" },
      { label: "정산 계좌", state: "미제출" },
    ],
    screeningNote: "관계 상담 위주. 시연 통화에서 진행 속도가 안정적이었습니다.",
    interviewScore: 86,
  },
  {
    id: "AP-113",
    name: "명운",
    category: "sinjeom",
    years: 18,
    appliedAt: "2026.07.25",
    documents: [
      { label: "신분 확인", state: "확인" },
      { label: "상담 이력 증빙", state: "재요청" },
      { label: "정산 계좌", state: "확인" },
    ],
    screeningNote: "이력 증빙 기간이 3년치만 제출되어 재요청했습니다.",
    interviewScore: 74,
  },
  {
    id: "AP-112",
    name: "서온",
    category: "saju",
    years: 12,
    appliedAt: "2026.07.24",
    documents: [
      { label: "신분 확인", state: "확인" },
      { label: "상담 이력 증빙", state: "확인" },
      { label: "정산 계좌", state: "확인" },
    ],
    screeningNote: "재물·사업 상담 비중이 높습니다. 즉시 상담 운영 가능하다고 응답했습니다.",
    interviewScore: 91,
  },
  {
    id: "AP-110",
    name: "율하",
    category: "tarot",
    years: 3,
    appliedAt: "2026.07.22",
    documents: [
      { label: "신분 확인", state: "확인" },
      { label: "상담 이력 증빙", state: "미제출" },
      { label: "정산 계좌", state: "미제출" },
    ],
    screeningNote: "경력 3년으로 입점 기준 5년에 미달합니다.",
    interviewScore: 52,
  },
];

export const ADMIN_EXPERT_ROWS: AdminExpertRow[] = [
  {
    id: "baekdam",
    grade: "루미 마스터",
    state: "활동중",
    monthSessions: 412,
    monthRevenue: 17284000,
    cancelRate: 1.2,
    settlementBank: "B은행",
    settlementAccount: "1002-***-448210",
    feeRate: 22,
  },
  {
    id: "soyun",
    grade: "루미 마스터",
    state: "상담중",
    monthSessions: 388,
    monthRevenue: 14962000,
    cancelRate: 2.1,
    settlementBank: "C은행",
    settlementAccount: "3333-***-901733",
    feeRate: 22,
  },
  {
    id: "cheongyeon",
    grade: "정회원",
    state: "상담중",
    monthSessions: 246,
    monthRevenue: 10824000,
    cancelRate: 3.4,
    settlementBank: "B은행",
    settlementAccount: "1002-***-771904",
    feeRate: 25,
  },
  {
    id: "haram",
    grade: "정회원",
    state: "활동중",
    monthSessions: 271,
    monthRevenue: 12193000,
    cancelRate: 1.8,
    settlementBank: "D은행",
    settlementAccount: "110-***-336742",
    feeRate: 25,
  },
  {
    id: "gangwol",
    grade: "루미 마스터",
    state: "상담중",
    monthSessions: 302,
    monthRevenue: 15644000,
    cancelRate: 2.6,
    settlementBank: "C은행",
    settlementAccount: "3333-***-118206",
    feeRate: 22,
  },
  {
    id: "seorin",
    grade: "정회원",
    state: "활동중",
    monthSessions: 198,
    monthRevenue: 6732000,
    cancelRate: 1.1,
    settlementBank: "B은행",
    settlementAccount: "1002-***-559013",
    feeRate: 25,
  },
  {
    id: "muyeong",
    grade: "정회원",
    state: "휴식",
    monthSessions: 84,
    monthRevenue: 3948000,
    cancelRate: 4.7,
    settlementBank: "D은행",
    settlementAccount: "110-***-224180",
    feeRate: 25,
  },
  {
    id: "iseol",
    grade: "신규",
    state: "활동중",
    monthSessions: 122,
    monthRevenue: 5368000,
    cancelRate: 0.8,
    settlementBank: "C은행",
    settlementAccount: "3333-***-640512",
    feeRate: 28,
  },
  {
    id: "yeonhwa",
    grade: "정회원",
    state: "정지",
    monthSessions: 41,
    monthRevenue: 1804000,
    cancelRate: 9.2,
    settlementBank: "B은행",
    settlementAccount: "1002-***-330877",
    feeRate: 25,
  },
  {
    id: "taeo",
    grade: "신규",
    state: "활동중",
    monthSessions: 96,
    monthRevenue: 2304000,
    cancelRate: 1.4,
    settlementBank: "D은행",
    settlementAccount: "110-***-908341",
    feeRate: 28,
  },
];

export const SETTLEMENTS: Settlement[] = [
  {
    id: "ST-2607-01",
    expertId: "baekdam",
    period: "2026.07.01 ~ 07.15",
    sessions: 206,
    gross: 8642000,
    feeRate: 22,
    fee: 1901240,
    adjust: -48000,
    payout: 6692760,
    state: "지급대기",
    dueAt: "2026.07.31",
  },
  {
    id: "ST-2607-02",
    expertId: "soyun",
    period: "2026.07.01 ~ 07.15",
    sessions: 194,
    gross: 7481000,
    feeRate: 22,
    fee: 1645820,
    adjust: 0,
    payout: 5835180,
    state: "지급대기",
    dueAt: "2026.07.31",
  },
  {
    id: "ST-2607-03",
    expertId: "gangwol",
    period: "2026.07.01 ~ 07.15",
    sessions: 151,
    gross: 7822000,
    feeRate: 22,
    fee: 1720840,
    adjust: -120000,
    payout: 5981160,
    state: "검토중",
    dueAt: "2026.07.31",
  },
  {
    id: "ST-2607-04",
    expertId: "cheongyeon",
    period: "2026.07.01 ~ 07.15",
    sessions: 123,
    gross: 5412000,
    feeRate: 25,
    fee: 1353000,
    adjust: -66000,
    payout: 3993000,
    state: "지급대기",
    dueAt: "2026.07.31",
  },
  {
    id: "ST-2606-11",
    expertId: "haram",
    period: "2026.06.16 ~ 06.30",
    sessions: 138,
    gross: 6096000,
    feeRate: 25,
    fee: 1524000,
    adjust: 0,
    payout: 4572000,
    state: "지급완료",
    dueAt: "2026.07.15",
  },
  {
    id: "ST-2606-12",
    expertId: "seorin",
    period: "2026.06.16 ~ 06.30",
    sessions: 99,
    gross: 3366000,
    feeRate: 25,
    fee: 841500,
    adjust: 12000,
    payout: 2536500,
    state: "지급완료",
    dueAt: "2026.07.15",
  },
  {
    id: "ST-2606-13",
    expertId: "iseol",
    period: "2026.06.16 ~ 06.30",
    sessions: 58,
    gross: 2552000,
    feeRate: 28,
    fee: 714560,
    adjust: 0,
    payout: 1837440,
    state: "지급완료",
    dueAt: "2026.07.15",
  },
];

export const SETTLEMENT_MONTHS = [
  { month: "2026.02", payout: 268400000, sessions: 6420 },
  { month: "2026.03", payout: 291200000, sessions: 6980 },
  { month: "2026.04", payout: 277600000, sessions: 6710 },
  { month: "2026.05", payout: 312800000, sessions: 7540 },
  { month: "2026.06", payout: 329400000, sessions: 7902 },
  { month: "2026.07", payout: 186200000, sessions: 4488 },
];

export const NOTICES: Notice[] = [
  {
    id: "NT-88",
    title: "8월 상담권 가격 조정 안내",
    channel: "앱 공지",
    publishedAt: "2026.07.27",
    state: "게시중",
    views: 12840,
  },
  {
    id: "NT-87",
    title: "심야 상담 운영 시간 확대 (24시까지)",
    channel: "푸시",
    publishedAt: "2026.07.21",
    state: "게시중",
    views: 30412,
  },
  {
    id: "NT-86",
    title: "상담사 정산 주기 변경 (월 2회)",
    channel: "상담사 공지",
    publishedAt: "2026.07.14",
    state: "게시중",
    views: 862,
  },
  {
    id: "NT-85",
    title: "추석 연휴 상담 운영 안내",
    channel: "앱 공지",
    publishedAt: "2026.09.18",
    state: "예약",
    views: 0,
  },
  {
    id: "NT-84",
    title: "6월 시스템 점검 완료 안내",
    channel: "앱 공지",
    publishedAt: "2026.06.30",
    state: "종료",
    views: 9120,
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "EV-31",
    title: "첫 상담 Lite 50% 할인",
    period: "2026.07.01 ~ 08.31",
    discount: "12,000원 할인",
    target: "신규 가입 회원",
    state: "진행중",
    joined: 4218,
    budgetUsed: 68,
  },
  {
    id: "EV-30",
    title: "여름 신년운세 사전 예약",
    period: "2026.07.15 ~ 08.15",
    discount: "Premium 10% 적립",
    target: "전체 회원",
    state: "진행중",
    joined: 1362,
    budgetUsed: 41,
  },
  {
    id: "EV-29",
    title: "신규 상담사 응원 쿠폰",
    period: "2026.08.05 ~ 08.20",
    discount: "5,000원 쿠폰",
    target: "재상담 회원",
    state: "예정",
    joined: 0,
    budgetUsed: 0,
  },
  {
    id: "EV-28",
    title: "장마철 심야 상담 이벤트",
    period: "2026.06.20 ~ 07.10",
    discount: "심야 5% 적립",
    target: "전체 회원",
    state: "종료",
    joined: 2894,
    budgetUsed: 100,
  },
];

export const FAQS: FaqItem[] = [
  {
    id: "FQ-21",
    category: "상담권",
    question: "구매한 상담권의 유효기간은 얼마인가요?",
    answer: "구매일로부터 90일입니다. 이벤트로 지급된 상담권은 지급일 기준 30일입니다.",
    updatedAt: "2026.07.20",
    exposed: true,
  },
  {
    id: "FQ-20",
    category: "예약",
    question: "예약을 변경하거나 취소하고 싶어요.",
    answer:
      "상담 시작 10분 전까지 앱에서 직접 변경, 취소할 수 있고 상담권은 전액 복구됩니다. 이후에는 복구되지 않습니다.",
    updatedAt: "2026.07.18",
    exposed: true,
  },
  {
    id: "FQ-19",
    category: "결제",
    question: "상담이 중간에 끊기면 어떻게 되나요?",
    answer:
      "5분 이내 재연결되면 남은 시간으로 이어서 진행합니다. 재연결이 되지 않으면 사용하지 않은 시간만큼 상담권이 복구됩니다.",
    updatedAt: "2026.07.11",
    exposed: true,
  },
  {
    id: "FQ-18",
    category: "상담사",
    question: "상담사에게 제 번호가 노출되나요?",
    answer: "노출되지 않습니다. 모든 상담은 안심번호로 중계되며 통화 종료 후 번호가 폐기됩니다.",
    updatedAt: "2026.07.02",
    exposed: true,
  },
  {
    id: "FQ-17",
    category: "상담사",
    question: "상담사가 부적이나 굿을 권유했어요.",
    answer:
      "LUMI는 상담 외 판매 권유를 금지합니다. 상담 내역 화면에서 신고하시면 24시간 내 확인 후 조치합니다.",
    updatedAt: "2026.06.28",
    exposed: true,
  },
  {
    id: "FQ-16",
    category: "결제",
    question: "환불은 어떻게 신청하나요?",
    answer: "미사용 상담권은 마이페이지 결제 내역에서 바로 환불 신청할 수 있습니다.",
    updatedAt: "2026.06.15",
    exposed: false,
  },
];

export const POLICY_TIME = [
  { label: "상담 시작 유예", value: "5분", note: "이 시간 안에 연결되면 정상 상담" },
  { label: "무료 취소 가능 시점", value: "10분 전", note: "이후 취소 시 상담권 미복구" },
  { label: "노쇼 판정", value: "미응답 8분", note: "상담권 50% 복구" },
  { label: "심야 운영", value: "24:00까지", note: "2026.07.21 확대 적용" },
];

export const POLICY_FEE = [
  { grade: "루미 마스터", fee: 22, condition: "월 300건 이상, 평점 4.8 이상" },
  { grade: "정회원", fee: 25, condition: "월 100건 이상, 평점 4.5 이상" },
  { grade: "신규", fee: 28, condition: "입점 6개월 미만" },
];
