import type { Category, Occasion, Product, Size } from "@/projects/platform/dressday/lib/types";

/*
 * 사진 표. picsum 고정 id를 한 장씩 600px로 열어 보고 적었다 (2026-09-18).
 *   325  숲 바닥에 맨발로 선 여성, 레이스 밑단 흰 미니 원피스 (허리 아래만 보인다)
 *   656  사막에서 뒤돌아 선 여성, 흰 슬립 미니 원피스
 *   758  갈색 니트 위에 두른 에스닉 패턴 프린지 숄 (클로즈업)
 *   821  지하철 승강장, 흰 루즈핏 니트를 입은 여성의 뒷모습 (흑백 톤)
 *   836  레코드숍에서 기타를 치는 여성, 회색 오버핏 블레이저
 *   628  카메라를 두 손으로 든 여성, 샴브레이 데님 셔츠 + 검정 바지
 *   535  나무 옷걸이가 걸린 행거, 뒤 벽에 달력 숫자 27~31
 * 그 외 상품은 맞는 사진이 없다. 톤 타일로 두고 사진 요청 목록에 올린다.
 */
export const HERO_PHOTO = { id: 535, alt: "달력 아래 나무 옷걸이 행거" };

export const PRODUCTS: Product[] = [
  {
    id: "lace-mini",
    name: "레이스 헴 미니 원피스",
    label: "A아틀리에",
    category: "원피스",
    occasions: ["데이트", "여행"],
    color: "화이트",
    tone: "#f4f1ea",
    toneInk: "dark",
    garment: "dress",
    price: 28900,
    deposit: 50000,
    retail: 189000,
    stock: { XS: 1, S: 2, M: 1, L: 0 },
    today: true,
    isNew: false,
    rank: 1,
    week: 11,
    rentals: 214,
    photo: { id: 325, alt: "레이스 밑단 흰 미니 원피스를 입은 모습" },
  },
  {
    id: "satin-slip",
    name: "새틴 슬립 원피스",
    label: "B스튜디오",
    category: "원피스",
    occasions: ["파티", "여행"],
    color: "아이보리",
    tone: "#efe9dc",
    toneInk: "dark",
    garment: "dress",
    price: 34500,
    deposit: 60000,
    retail: 248000,
    stock: { XS: 0, S: 1, M: 2 },
    today: true,
    isNew: false,
    rank: 4,
    week: 7,
    rentals: 87,
    photo: { id: 656, alt: "흰 슬립 원피스를 입고 사막에 선 뒷모습" },
  },
  {
    id: "fringe-shawl",
    name: "에스닉 패턴 프린지 숄",
    label: "C라벨",
    category: "아우터",
    occasions: ["여행", "데이트"],
    color: "멀티",
    tone: "#7a4a3a",
    toneInk: "light",
    garment: "outer",
    price: 12400,
    deposit: 30000,
    retail: 98000,
    stock: { M: 3 },
    today: true,
    isNew: true,
    rentals: 41,
    photo: { id: 758, alt: "갈색 니트 위에 두른 패턴 프린지 숄" },
  },
  {
    id: "summer-knit",
    name: "루즈핏 서머 니트",
    label: "D니트웍스",
    category: "니트",
    occasions: ["데이트", "여행"],
    color: "화이트",
    tone: "#eeeeea",
    toneInk: "dark",
    garment: "knit",
    price: 16800,
    deposit: 30000,
    retail: 119000,
    stock: { S: 2, M: 3, L: 1 },
    today: true,
    isNew: false,
    rank: 6,
    week: 5,
    rentals: 132,
    photo: { id: 821, alt: "흰 루즈핏 니트를 입은 뒷모습" },
  },
  {
    id: "wool-blazer",
    name: "오버핏 울 블레이저",
    label: "E테일러",
    category: "아우터",
    occasions: ["면접, 오피스"],
    color: "그레이",
    tone: "#8a8a88",
    toneInk: "light",
    garment: "outer",
    price: 31200,
    deposit: 80000,
    retail: 329000,
    stock: { S: 1, M: 0, L: 2 },
    today: true,
    isNew: false,
    rank: 2,
    week: 9,
    rentals: 196,
    photo: { id: 836, alt: "회색 오버핏 블레이저를 입은 모습" },
  },
  {
    id: "chambray-shirt",
    name: "샴브레이 셔츠",
    label: "F데님",
    category: "블라우스, 셔츠",
    occasions: ["데이트", "여행"],
    color: "라이트 블루",
    tone: "#a9bfd6",
    toneInk: "dark",
    garment: "shirt",
    price: 11900,
    deposit: 20000,
    retail: 79000,
    stock: { S: 2, M: 2 },
    today: false,
    isNew: true,
    rentals: 58,
    photo: { id: 628, alt: "샴브레이 데님 셔츠를 입고 카메라를 든 모습" },
  },
  {
    id: "tweed-setup",
    name: "트위드 크롭 재킷 셋업",
    label: "A아틀리에",
    category: "셋업",
    occasions: ["하객", "면접, 오피스"],
    color: "블랙",
    tone: "#2b2a29",
    toneInk: "light",
    garment: "outer",
    price: 46700,
    deposit: 120000,
    retail: 458000,
    stock: { S: 1, M: 1 },
    today: true,
    isNew: false,
    rank: 3,
    week: 8,
    rentals: 173,
  },
  {
    id: "wrap-midi",
    name: "랩 미디 원피스",
    label: "G메종",
    category: "원피스",
    occasions: ["하객"],
    color: "버건디",
    tone: "#6e2433",
    toneInk: "light",
    garment: "dress",
    price: 32400,
    deposit: 60000,
    retail: 268000,
    stock: { S: 2, M: 1, L: 1 },
    today: true,
    isNew: false,
    rank: 5,
    week: 6,
    rentals: 151,
  },
  {
    id: "pleats-skirt",
    name: "새틴 플리츠 미디 스커트",
    label: "B스튜디오",
    category: "스커트",
    occasions: ["하객", "파티"],
    color: "샴페인",
    tone: "#dcc9a6",
    toneInk: "dark",
    garment: "skirt",
    price: 18600,
    deposit: 40000,
    retail: 139000,
    stock: { S: 1, M: 2 },
    today: true,
    isNew: true,
    rentals: 36,
  },
  {
    id: "wide-slacks",
    name: "와이드 울 슬랙스",
    label: "E테일러",
    category: "팬츠",
    occasions: ["면접, 오피스"],
    color: "차콜",
    tone: "#3c3d40",
    toneInk: "light",
    garment: "pants",
    price: 14700,
    deposit: 30000,
    retail: 129000,
    stock: { S: 2, M: 2, L: 1 },
    today: true,
    isNew: false,
    rank: 7,
    week: 4,
    rentals: 118,
  },
  {
    id: "ribbon-blouse",
    name: "리본 타이 블라우스",
    label: "G메종",
    category: "블라우스, 셔츠",
    occasions: ["면접, 오피스", "하객"],
    color: "아이보리",
    tone: "#f1ebdf",
    toneInk: "dark",
    garment: "shirt",
    price: 15300,
    deposit: 30000,
    retail: 118000,
    stock: { XS: 1, S: 2, M: 2 },
    today: true,
    isNew: false,
    rank: 8,
    week: 4,
    rentals: 104,
  },
  {
    id: "single-trench",
    name: "싱글 트렌치 코트",
    label: "H아우터",
    category: "아우터",
    occasions: ["면접, 오피스", "여행"],
    color: "베이지",
    tone: "#c8b08c",
    toneInk: "dark",
    garment: "outer",
    price: 36900,
    deposit: 90000,
    retail: 398000,
    stock: { S: 0, M: 1 },
    today: false,
    isNew: true,
    rentals: 22,
  },
  {
    id: "flower-maxi",
    name: "플라워 프린트 맥시 원피스",
    label: "C라벨",
    category: "원피스",
    occasions: ["여행", "데이트"],
    color: "네이비",
    tone: "#27324a",
    toneInk: "light",
    garment: "dress",
    price: 26300,
    deposit: 50000,
    retail: 198000,
    stock: { S: 1, M: 1, L: 1 },
    today: true,
    isNew: true,
    rentals: 19,
  },
  {
    id: "crop-cardigan",
    name: "크롭 니트 가디건",
    label: "D니트웍스",
    category: "니트",
    occasions: ["데이트"],
    color: "라벤더",
    tone: "#c9c0dc",
    toneInk: "dark",
    garment: "knit",
    price: 13600,
    deposit: 20000,
    retail: 89000,
    stock: { S: 2, M: 1 },
    today: false,
    isNew: false,
    rentals: 67,
  },
  {
    id: "tailored-suit",
    name: "테일러드 셋업 수트",
    label: "E테일러",
    category: "셋업",
    occasions: ["면접, 오피스"],
    color: "네이비",
    tone: "#1f2a44",
    toneInk: "light",
    garment: "outer",
    price: 42800,
    deposit: 120000,
    retail: 489000,
    stock: { S: 1, M: 2, L: 1 },
    today: true,
    isNew: false,
    rank: 9,
    week: 3,
    rentals: 142,
  },
  {
    id: "sequin-dress",
    name: "시퀸 슬리브리스 드레스",
    label: "I파티",
    category: "원피스",
    occasions: ["파티"],
    color: "실버",
    tone: "#b9bbbf",
    toneInk: "dark",
    garment: "dress",
    price: 52900,
    deposit: 150000,
    retail: 520000,
    stock: { S: 1, M: 0 },
    today: false,
    isNew: true,
    rentals: 14,
  },
];

export const CATEGORIES: Category[] = ["원피스", "블라우스, 셔츠", "니트", "아우터", "스커트", "팬츠", "셋업"];
export const OCCASIONS: Occasion[] = ["하객", "면접, 오피스", "데이트", "여행", "파티"];
export const SIZES: Size[] = ["XS", "S", "M", "L", "XL"];

export function getProduct(id: string) {
  return PRODUCTS.find((p) => p.id === id) ?? PRODUCTS[0];
}

export function totalStock(p: Product) {
  return Object.values(p.stock).reduce((a, b) => a + (b ?? 0), 0);
}

export function won(n: number) {
  return `${n.toLocaleString("ko-KR")}원`;
}

export function num(n: number) {
  return n.toLocaleString("ko-KR");
}

export function photoUrl(id: number, w: number, h: number) {
  return `https://picsum.photos/id/${id}/${w}/${h}`;
}
