/* CIVICPIN mock 데이터. spec.md 8절 가명 처리 원칙을 전 항목에 적용했다.
   지자체명 "OO시", 행정동 "△△동", 상점가 "A~D 골목형 상점가", 매장은 유형+위치 조합,
   좌표는 추상화 지도 캔버스(0~100) 위의 가상 값이다. 실제 행정구역과 매핑되지 않는다.

   사진(picsum 고정 id)은 design.md "사진 매핑" 표와 1:1로 맞춰져 있다. id를 바꾸면
   캡션과 어긋나므로 표를 함께 고쳐야 한다. */

import type {
  CorrectionLog,
  DataRecord,
  District,
  Facility,
  Festival,
  Point,
  Report,
  Store,
  StoreCategory,
} from "./types";

/** QR 스캔 지점 — 모든 거리 계산의 기준점 */
export const QR_POINT = {
  code: "QR-△△-12",
  label: "△△동 시장 입구 버스정류장",
  city: "OO시",
  dong: "△△동",
  zone: "ZONE-A1",
  scannedAt: "2026. 06. 12 (금) 15:24",
  coordinates: { x: 46, y: 58 } as Point,
  baseDate: "2026. 06. 01",
};

export const FACILITIES: Facility[] = [
  {
    id: "fc-rest-1",
    type: "쉼터",
    displayName: "△△동 정류장 그늘막쉼터",
    address: "△△동 중앙로 40",
    relativeLocation: "QR 지점 바로 옆, 승차대 안",
    detail: "차양막과 벤치 2석, 안개분사기. 5월부터 9월까지 상시 가동",
    distance: 15,
    walkMinutes: 1,
    coordinates: { x: 47, y: 55 },
    alwaysOpen: true,
    updatedAt: "2026. 06. 01",
  },
  {
    id: "fc-aed-1",
    type: "AED",
    displayName: "△△동 주민센터 AED",
    address: "△△동 중앙로 25",
    relativeLocation: "주민센터 1층 로비 안내데스크 옆",
    detail: "자동심장충격기 1대. 평일 09:00~18:00, 야간에는 당직실 호출",
    distance: 92,
    walkMinutes: 2,
    coordinates: { x: 52, y: 50 },
    alwaysOpen: false,
    updatedAt: "2026. 06. 01",
  },
  {
    id: "fc-wc-1",
    type: "화장실",
    displayName: "A 상점가 공중화장실",
    address: "△△동 시장로 9",
    relativeLocation: "상점가 내 1구역, 시장 입구 아치 왼편",
    detail: "남녀 분리, 기저귀 교환대 있음. 05:00~24:00 개방",
    distance: 74,
    walkMinutes: 1,
    coordinates: { x: 43, y: 63 },
    alwaysOpen: false,
    updatedAt: "2026. 05. 22",
  },
  {
    id: "fc-aed-2",
    type: "AED",
    displayName: "A 상점가 상인회 AED",
    address: "△△동 시장로 41",
    relativeLocation: "상점가 내 2구역, 상인회 사무실 출입구",
    detail: "자동심장충격기 1대. 상인회 운영시간 08:00~20:00",
    distance: 146,
    walkMinutes: 2,
    coordinates: { x: 38, y: 52 },
    alwaysOpen: false,
    updatedAt: "2026. 06. 01",
  },
  {
    id: "fc-wc-2",
    type: "화장실",
    displayName: "1구역 개방화장실",
    address: "△△동 시장로 21",
    relativeLocation: "상점가 내 1구역, 골목 안쪽 상가 1층",
    detail: "개방화장실 협약 점포. 영업시간 내 자유 이용",
    distance: 183,
    walkMinutes: 3,
    coordinates: { x: 35, y: 64 },
    alwaysOpen: false,
    updatedAt: "2026. 05. 22",
  },
  {
    id: "fc-rest-2",
    type: "쉼터",
    displayName: "△△동 그늘막쉼터",
    address: "△△동 중앙로 33",
    relativeLocation: "중앙로 횡단보도 앞 광장",
    detail: "접이식 그늘막과 벤치 3기. 5월부터 9월까지 운영",
    distance: 214,
    walkMinutes: 4,
    coordinates: { x: 56, y: 44 },
    alwaysOpen: true,
    updatedAt: "2026. 04. 17",
  },
  {
    id: "fc-shelter-1",
    type: "대피소",
    displayName: "△△초등학교 지진옥외대피소",
    address: "△△동 중앙로 88",
    relativeLocation: "학교 운동장, 후문으로 진입",
    detail: "수용 인원 약 1,200명. 지진 발생 시 옥외 집결지",
    distance: 384,
    walkMinutes: 6,
    coordinates: { x: 30, y: 38 },
    alwaysOpen: true,
    updatedAt: "2026. 03. 12",
  },
  {
    id: "fc-aed-3",
    type: "AED",
    displayName: "△△동 공영주차장 AED",
    address: "△△동 시장로 72",
    relativeLocation: "주차장 북측 관리동 단층 건물",
    detail: "자동심장충격기 1대. 관리동 상주, 24시간 접근 가능",
    distance: 327,
    walkMinutes: 5,
    coordinates: { x: 64, y: 70 },
    alwaysOpen: true,
    updatedAt: "2026. 06. 01",
  },
  {
    id: "fc-wc-3",
    type: "화장실",
    displayName: "△△동 공영주차장 화장실",
    address: "△△동 시장로 72",
    relativeLocation: "주차장 관리동 옆 독립 건물",
    detail: "남녀 분리, 장애인 화장실 병설. 24시간 개방",
    distance: 341,
    walkMinutes: 5,
    coordinates: { x: 62, y: 73 },
    alwaysOpen: true,
    updatedAt: "2026. 05. 22",
  },
  {
    id: "fc-rest-3",
    type: "쉼터",
    displayName: "△△동 경로당 무더위쉼터",
    address: "△△동 시장로3길 8",
    relativeLocation: "골목 안 경로당 1층",
    detail: "냉방기와 정수기 비치. 6월부터 9월까지 09:00~18:00",
    distance: 437,
    walkMinutes: 7,
    coordinates: { x: 28, y: 72 },
    alwaysOpen: false,
    updatedAt: "2026. 04. 17",
  },
  {
    id: "fc-wc-4",
    type: "화장실",
    displayName: "△△근린공원 화장실",
    address: "△△동 공원로 15",
    relativeLocation: "공원 진입로 우측 단독 건물",
    detail: "남녀 분리. 06:00~22:00 개방",
    distance: 548,
    walkMinutes: 8,
    coordinates: { x: 76, y: 34 },
    alwaysOpen: false,
    updatedAt: "2026. 05. 22",
  },
  {
    id: "fc-aed-4",
    type: "AED",
    displayName: "△△생활체육관 AED",
    address: "△△동 공원로 30",
    relativeLocation: "체육관 1층 매표소 옆 벽면",
    detail: "자동심장충격기 1대. 06:00~22:00 개방",
    distance: 612,
    walkMinutes: 9,
    coordinates: { x: 22, y: 30 },
    alwaysOpen: false,
    updatedAt: "2026. 06. 01",
  },
  {
    id: "fc-shelter-2",
    type: "대피소",
    displayName: "△△동 민방위대피소",
    address: "△△동 중앙로 51",
    relativeLocation: "상가 건물 지하 1층 주차장",
    detail: "수용 인원 약 340명. 민방위 경보 시 개방",
    distance: 726,
    walkMinutes: 11,
    coordinates: { x: 72, y: 20 },
    alwaysOpen: false,
    updatedAt: "2026. 03. 12",
  },
  {
    id: "fc-shelter-3",
    type: "대피소",
    displayName: "△△복지회관 지하대피소",
    address: "△△동 공원로 8",
    relativeLocation: "복지회관 지하 1층",
    detail: "수용 인원 약 520명. 비상 발전기와 급수 설비 구비",
    distance: 1140,
    walkMinutes: 16,
    coordinates: { x: 84, y: 62 },
    alwaysOpen: false,
    updatedAt: "2026. 03. 12",
  },
];

export const DISTRICTS: District[] = [
  {
    id: "d-a",
    name: "A 골목형 상점가",
    zoneCode: "ZONE-A1",
    mainCategories: ["농수산", "음식", "생활"],
    storeCount: 168,
    onnuriCount: 74,
    distance: 0,
    walkMinutes: 0,
    intro:
      "시장 입구 아치에서 중앙로를 지나 공영주차장까지, 네 개 구역이 한 줄로 이어지는 골목 상권이다. 청과와 정육이 모인 1구역에서 시작해 안쪽으로 갈수록 생활 서비스 점포가 늘어난다.",
    polygon: [
      { x: 30, y: 66 },
      { x: 34, y: 48 },
      { x: 52, y: 44 },
      { x: 60, y: 52 },
      { x: 58, y: 70 },
      { x: 40, y: 74 },
    ],
    /* QR 지점(46, 58)과 겹치지 않게 구역 안쪽으로 물린 위치에 클러스터 마커를 둔다 */
    center: { x: 37, y: 67 },
    /* 좁은 골목 양옆으로 점포가 이어지고 조명 줄이 걸린 사진.
       넓은 차도가 보이는 342 는 "골목" 으로 읽히지 않아 교체했다. */
    photo: 195,
    photoAlt: "양옆으로 점포가 이어지고 위로 조명 줄이 걸린 좁은 골목",
    mix: [
      { label: "농수산", ratio: 31 },
      { label: "음식", ratio: 24 },
      { label: "생활", ratio: 18 },
      { label: "카페", ratio: 12 },
      { label: "미용", ratio: 9 },
      { label: "의료", ratio: 6 },
    ],
    course: [
      { label: "시장 입구 아치", note: "1구역 청과, 정육 밀집. 공중화장실과 AED가 여기 있다" },
      { label: "중앙로 먹자골목", note: "2구역 국밥, 반찬. 상인회 사무실과 AED 경유" },
      { label: "뒷길 생활골목", note: "3구역 세탁, 잡화, 카페" },
      { label: "공영주차장", note: "4구역 끝. 24시간 화장실과 AED" },
    ],
    facilityIds: ["fc-wc-1", "fc-aed-2", "fc-rest-1", "fc-aed-3"],
  },
  {
    id: "d-b",
    name: "B 골목형 상점가",
    zoneCode: "ZONE-B2",
    mainCategories: ["음식", "카페", "미용"],
    storeCount: 96,
    onnuriCount: 41,
    distance: 1400,
    walkMinutes: 21,
    intro:
      "하천을 따라 늘어선 저층 상가 골목이다. 노포 식당과 신규 카페가 한 블록 안에 섞여 있어 야간 유동이 많다.",
    polygon: [
      { x: 12, y: 24 },
      { x: 26, y: 16 },
      { x: 36, y: 24 },
      { x: 30, y: 38 },
      { x: 16, y: 38 },
    ],
    center: { x: 24, y: 27 },
    photo: 164,
    photoAlt: "물가를 따라 줄지어 선 저층 상점 건물 골목",
    mix: [
      { label: "음식", ratio: 34 },
      { label: "카페", ratio: 22 },
      { label: "미용", ratio: 16 },
      { label: "생활", ratio: 14 },
      { label: "농수산", ratio: 9 },
      { label: "교육", ratio: 5 },
    ],
    course: [
      { label: "하천 산책로 입구", note: "노포 식당 구간" },
      { label: "중간 사거리", note: "카페, 미용 밀집" },
      { label: "공영자전거 거치대", note: "야시장 진입로" },
    ],
    facilityIds: ["fc-shelter-1", "fc-aed-4"],
  },
  {
    id: "d-c",
    name: "C 골목형 상점가",
    zoneCode: "ZONE-C1",
    mainCategories: ["음식", "생활", "교육"],
    storeCount: 124,
    onnuriCount: 58,
    distance: 2700,
    walkMinutes: 39,
    intro:
      "아파트 단지 상가와 이면도로 점포가 한 상권으로 묶인 구역이다. 학원과 생활 서비스 비중이 높아 낮 시간 이용이 고르게 유지된다.",
    polygon: [
      { x: 64, y: 14 },
      { x: 82, y: 12 },
      { x: 88, y: 26 },
      { x: 78, y: 34 },
      { x: 64, y: 28 },
    ],
    center: { x: 76, y: 22 },
    /* 내용이 맞는 상권 사진이 없어 사진을 쓰지 않는다. 상세 화면은 구역 지도를 히어로로 쓴다. */
    mix: [
      { label: "음식", ratio: 29 },
      { label: "생활", ratio: 21 },
      { label: "교육", ratio: 19 },
      { label: "카페", ratio: 13 },
      { label: "의료", ratio: 11 },
      { label: "미용", ratio: 7 },
    ],
    course: [
      { label: "단지 상가 1동", note: "학원, 의료 구간" },
      { label: "이면도로 골목", note: "분식, 생활 서비스" },
      { label: "근린공원 앞", note: "화장실과 그늘막쉼터 연계" },
    ],
    facilityIds: ["fc-wc-4", "fc-shelter-2"],
  },
  {
    id: "d-d",
    name: "D 골목형 상점가",
    zoneCode: "ZONE-D3",
    mainCategories: ["농수산", "음식", "의료"],
    storeCount: 72,
    onnuriCount: 29,
    distance: 4100,
    walkMinutes: 58,
    intro:
      "닷새마다 서는 오일장 부지를 낀 상권이다. 장이 서지 않는 날에는 상설 점포 중심으로 운영된다.",
    polygon: [
      { x: 70, y: 54 },
      { x: 90, y: 52 },
      { x: 94, y: 68 },
      { x: 80, y: 76 },
      { x: 68, y: 68 },
    ],
    center: { x: 80, y: 64 },
    /* C 상점가와 같은 이유로 사진 없음 */
    mix: [
      { label: "농수산", ratio: 38 },
      { label: "음식", ratio: 26 },
      { label: "의료", ratio: 12 },
      { label: "생활", ratio: 11 },
      { label: "카페", ratio: 8 },
      { label: "미용", ratio: 5 },
    ],
    course: [
      { label: "오일장 부지", note: "장날 노점 구간" },
      { label: "상설 점포 골목", note: "정육, 건어물" },
      { label: "복지회관 앞", note: "지하대피소 연계" },
    ],
    facilityIds: ["fc-shelter-3"],
  },
];

export const STORES: Store[] = [
  {
    id: "st-a-01",
    districtId: "d-a",
    name: "A 시장 입구 청과상회",
    category: "농수산",
    subCategory: "청과",
    onnuriAccepted: true,
    address: "△△동 시장로 12",
    relativeLocation: "상점가 내 1구역, 입구 아치 오른편 첫 점포",
    distance: 45,
    walkMinutes: 1,
    coordinates: { x: 44, y: 61 },
    hours: "07:00~20:00, 둘째 넷째 일요일 휴무",
    photo: 292,
    photoAlt: "도마 위에 놓인 채소와 향신료",
    blurb: "새벽 경매로 들여오는 제철 과일과 나물",
  },
  {
    id: "st-a-02",
    districtId: "d-a",
    name: "A 시장 입구 이발관",
    category: "미용",
    subCategory: "이용원",
    onnuriAccepted: true,
    address: "△△동 시장로 14",
    relativeLocation: "상점가 내 1구역, 청과상회 옆 골목",
    distance: 62,
    walkMinutes: 1,
    coordinates: { x: 42, y: 59 },
    hours: "09:00~19:00, 월요일 휴무",
  },
  {
    id: "st-a-03",
    districtId: "d-a",
    name: "A 상점가 1구역 약국",
    category: "의료",
    subCategory: "약국",
    onnuriAccepted: false,
    address: "△△동 시장로 17",
    relativeLocation: "상점가 내 1구역, 공중화장실 맞은편",
    distance: 78,
    walkMinutes: 2,
    coordinates: { x: 41, y: 63 },
    hours: "09:00~21:00, 공휴일 단축 운영",
  },
  {
    id: "st-a-04",
    districtId: "d-a",
    name: "A 상점가 중앙로 정육점",
    category: "농수산",
    subCategory: "정육",
    onnuriAccepted: true,
    address: "△△동 시장로 28",
    relativeLocation: "상점가 내 2구역, 중앙로 초입",
    distance: 96,
    walkMinutes: 2,
    coordinates: { x: 43, y: 55 },
    hours: "08:00~20:00, 일요일 휴무",
  },
  {
    id: "st-a-05",
    districtId: "d-a",
    name: "A 상점가 골목 반찬가게",
    category: "농수산",
    subCategory: "반찬",
    onnuriAccepted: true,
    address: "△△동 시장로 34",
    relativeLocation: "상점가 내 2구역, 중앙로 중간 골목",
    distance: 112,
    walkMinutes: 2,
    coordinates: { x: 41, y: 52 },
    hours: "08:30~20:00, 연중무휴",
    photo: 488,
    photoAlt: "나무 도마 위에 담긴 나물과 채소 볼",
    blurb: "매일 아침 만드는 밑반찬 스무 가지",
  },
  {
    id: "st-a-06",
    districtId: "d-a",
    name: "A 상점가 중앙로 국밥집",
    category: "음식",
    subCategory: "한식",
    onnuriAccepted: true,
    address: "△△동 시장로 41",
    relativeLocation: "상점가 내 2구역, 상인회 사무실 아래층",
    distance: 128,
    walkMinutes: 2,
    coordinates: { x: 39, y: 53 },
    hours: "06:00~21:00, 첫째 월요일 휴무",
  },
  {
    id: "st-a-07",
    districtId: "d-a",
    name: "A 상점가 2구역 생활잡화점",
    category: "생활",
    subCategory: "생활잡화",
    onnuriAccepted: true,
    address: "△△동 시장로 44",
    relativeLocation: "상점가 내 2구역, 국밥집 맞은편",
    distance: 134,
    walkMinutes: 2,
    coordinates: { x: 38, y: 55 },
    hours: "09:00~21:00, 연중무휴",
  },
  {
    id: "st-a-08",
    districtId: "d-a",
    name: "A 시장 뒷길 분식집",
    category: "음식",
    subCategory: "분식",
    onnuriAccepted: true,
    address: "△△동 시장로3길 5",
    relativeLocation: "상점가 내 3구역, 뒷길 진입로",
    distance: 156,
    walkMinutes: 3,
    coordinates: { x: 37, y: 60 },
    hours: "10:00~20:00, 화요일 휴무",
  },
  {
    id: "st-a-09",
    districtId: "d-a",
    name: "A 상점가 모퉁이 카페",
    category: "카페",
    subCategory: "커피",
    onnuriAccepted: false,
    address: "△△동 시장로3길 11",
    relativeLocation: "상점가 내 3구역, 뒷길 모퉁이",
    distance: 171,
    walkMinutes: 3,
    coordinates: { x: 35, y: 57 },
    hours: "08:00~22:00, 연중무휴",
    photo: 42,
    photoAlt: "원목 테이블 위 커피잔과 창밖 거리",
    blurb: "상점가에서 가장 오래 문을 여는 자리",
  },
  {
    id: "st-a-10",
    districtId: "d-a",
    name: "A 상점가 3구역 세탁소",
    category: "생활",
    subCategory: "세탁",
    onnuriAccepted: true,
    address: "△△동 시장로3길 13",
    relativeLocation: "상점가 내 3구역, 카페 옆",
    distance: 184,
    walkMinutes: 3,
    coordinates: { x: 34, y: 59 },
    hours: "08:00~20:00, 일요일 휴무",
  },
  {
    id: "st-a-11",
    districtId: "d-a",
    name: "A 상점가 뒷길 로스터리",
    category: "카페",
    subCategory: "로스터리",
    onnuriAccepted: false,
    address: "△△동 시장로3길 22",
    relativeLocation: "상점가 내 3구역, 뒷길 끝 단층 건물",
    distance: 203,
    walkMinutes: 3,
    coordinates: { x: 33, y: 62 },
    hours: "10:00~19:00, 월요일 휴무",
    photo: 1060,
    photoAlt: "핸드드립으로 커피를 내리는 장면",
    blurb: "주 2회 직접 볶는 소규모 로스터리",
  },
  {
    id: "st-a-12",
    districtId: "d-a",
    name: "A 상점가 4구역 문구사",
    category: "교육",
    subCategory: "문구",
    onnuriAccepted: true,
    address: "△△동 시장로 68",
    relativeLocation: "상점가 내 4구역, 공영주차장 진입로",
    distance: 246,
    walkMinutes: 4,
    coordinates: { x: 56, y: 66 },
    hours: "09:00~20:00, 일요일 휴무",
  },
];

export const FESTIVALS: Festival[] = [
  {
    id: "fs-01",
    districtId: "d-a",
    name: "A 골목상권 초여름 축제",
    status: "진행중",
    period: "2026. 06. 11 (목) ~ 06. 13 (토)",
    time: "15:00~21:00",
    venue: "A 골목형 상점가 중앙로 일원",
    address: "△△동 시장로 34",
    distance: 0,
    summary: "먹거리 부스 스무 곳과 야외 무대 공연. 상인회가 직접 꾸리는 시장통 잔치",
    photo: 452,
    photoAlt: "무대 조명 아래 손을 든 관객 실루엣",
    programs: [
      { time: "15:00~17:00", title: "먹거리 장터", detail: "중앙로 양쪽에 부스 20곳. 상점가 가맹점이 직접 운영한다" },
      { time: "16:00~18:00", title: "어르신 한마당", detail: "경로당 풍물패 공연과 윷놀이 마당" },
      { time: "18:00~19:30", title: "상인 경품행사", detail: "당일 영수증 지참 시 참여. 온누리상품권 경품" },
      { time: "19:30~21:00", title: "야외 무대 버스킹", detail: "지역 밴드 3팀 순차 공연. 우천 시 아케이드 아래로 이동" },
    ],
    booths: [
      { label: "먹거리 부스", count: "20곳" },
      { label: "체험 부스", count: "6곳" },
      { label: "임시 화장실", count: "3곳" },
      { label: "의무실", count: "1곳" },
    ],
  },
  {
    id: "fs-02",
    districtId: "d-b",
    name: "B 골목상권 밤마실 야시장",
    status: "진행중",
    period: "2026. 06. 05 (금) ~ 06. 21 (일) 매주 금토",
    time: "18:00~23:00",
    venue: "B 골목형 상점가 하천 산책로 구간",
    address: "△△동 하천로 18",
    distance: 1400,
    summary: "해 지면 골목 전체에 등이 들어온다. 노포 식당 열두 곳이 야간 메뉴를 낸다",
    /* 전광판이 늘어선 도심 번화가(274)는 동네 골목 야시장으로 읽히지 않아 교체했다.
       저층 건물 사이 좁은 길에 전구 줄이 걸리고 자전거가 세워진 밤 골목. */
    photo: 351,
    photoAlt: "저층 건물 사이 좁은 길에 전구 줄이 걸린 밤 골목",
    programs: [
      { time: "18:00~23:00", title: "야간 노점 구간", detail: "산책로 300m 구간에 노점 18곳" },
      { time: "19:00~20:00", title: "골목 등 점등식", detail: "매주 금요일 개시. 상인회 인사말과 함께 점등" },
      { time: "20:00~22:00", title: "심야 식당 주간", detail: "노포 식당 12곳 야간 메뉴 운영" },
    ],
    booths: [
      { label: "야간 노점", count: "18곳" },
      { label: "임시 화장실", count: "2곳" },
      { label: "야간 조명탑", count: "6기" },
    ],
  },
  {
    id: "fs-03",
    districtId: "d-c",
    name: "C 골목상권 제철 과일 장터",
    status: "예정",
    period: "2026. 06. 19 (금) ~ 06. 20 (토)",
    time: "10:00~18:00",
    venue: "C 골목형 상점가 단지 상가 앞 광장",
    address: "△△동 단지로 27",
    distance: 2700,
    summary: "갓 딴 제철 과일을 산지값에 내놓는 이틀장. 과일청 담그기는 40명 선착순",
    photo: 674,
    photoAlt: "두 손에 담아 든 포도 송이",
    programs: [
      { time: "10:00~14:00", title: "산지 직거래 장터", detail: "인근 농가 14곳 직접 판매" },
      { time: "13:00~15:00", title: "과일청 담그기 체험", detail: "선착순 40명. 현장 접수만 받는다" },
      { time: "15:00~18:00", title: "상점가 할인 주간", detail: "가맹점 온누리상품권 결제 시 5% 추가 할인" },
    ],
    booths: [
      { label: "직거래 부스", count: "14곳" },
      { label: "체험 부스", count: "3곳" },
      { label: "임시 주차", count: "60면" },
    ],
  },
  {
    id: "fs-04",
    districtId: "d-d",
    name: "D 골목상권 오일장 찻집 거리",
    status: "예정",
    period: "2026. 07. 04 (토) ~ 07. 05 (일)",
    time: "12:00~20:00",
    venue: "D 골목형 상점가 오일장 부지",
    address: "△△동 장터로 5",
    distance: 4100,
    summary: "장이 서지 않는 날 오일장 부지를 찻집 거리로 바꾼다. 상설 점포가 차와 주전부리를 낸다",
    photo: 225,
    photoAlt: "유리 티포트에 우린 차와 곁들인 꽃",
    programs: [
      { time: "12:00~16:00", title: "찻집 거리", detail: "상설 점포 9곳이 야외 테이블을 낸다" },
      { time: "14:00~16:00", title: "시원한 한 잔 나눔", detail: "어르신 대상 무료 냉차 나눔. 경로당 협력" },
      { time: "16:00~20:00", title: "저녁 야시", detail: "오일장 부지 조명 점등과 노점 운영" },
    ],
    booths: [
      { label: "찻집 부스", count: "9곳" },
      { label: "그늘 쉼터", count: "2곳" },
      { label: "임시 화장실", count: "2곳" },
    ],
  },
  {
    id: "fs-05",
    districtId: "d-a",
    name: "A 골목상권 봄 커피 위크",
    status: "종료",
    period: "2026. 04. 11 (토) ~ 04. 19 (일)",
    time: "11:00~20:00",
    venue: "A 골목형 상점가 3구역 뒷길",
    address: "△△동 시장로3길 14",
    distance: 0,
    summary: "뒷길 카페 일곱 곳이 같은 원두로 다른 잔을 냈던 아흐레",
    photo: 431,
    photoAlt: "라떼아트가 올라간 커피와 영수증",
    programs: [
      { time: "11:00~20:00", title: "한 원두 일곱 잔", detail: "참여 카페 7곳이 같은 원두를 각자 방식으로 추출" },
      { time: "14:00~16:00", title: "로스팅 공개", detail: "뒷길 로스터리 현장 로스팅 시연" },
    ],
    booths: [
      { label: "참여 카페", count: "7곳" },
      { label: "체험 부스", count: "2곳" },
    ],
  },
];

/* ── 관리자 콘솔 데이터 ── */

export const ADMIN_SUMMARY = {
  facilities: { total: 1284, added: 26, label: "등록 시설" },
  stores: { total: 460, added: 38, label: "등록 매장" },
  festivals: { total: 17, added: 3, label: "등록 축제" },
  reports: { total: 34, pending: 9, label: "오류 신고" },
  qrPoints: { total: 62, added: 4, label: "QR 지점" },
  baseDate: "2026. 06. 01",
  syncedAt: "2026. 06. 12 09:12",
};

export const REPORT_COUNTS: { status: Report["status"]; count: number }[] = [
  { status: "접수", count: 5 },
  { status: "검토", count: 4 },
  { status: "반영", count: 7 },
  { status: "완료", count: 18 },
];

export const REGISTRATION_TREND = [
  { label: "1월", value: 118 },
  { label: "2월", value: 142 },
  { label: "3월", value: 96 },
  { label: "4월", value: 173 },
  { label: "5월", value: 204 },
  { label: "6월", value: 148, emphasis: true },
];

export const DISTRICT_COVERAGE = [
  { label: "A 골목형 상점가", value: 168, caption: "168곳 / 온누리 74" },
  { label: "C 골목형 상점가", value: 124, caption: "124곳 / 온누리 58" },
  { label: "B 골목형 상점가", value: 96, caption: "96곳 / 온누리 41" },
  { label: "D 골목형 상점가", value: 72, caption: "72곳 / 온누리 29" },
];

export const FACILITY_COVERAGE = [
  { label: "AED", value: 412, caption: "412대 / 검증 398" },
  { label: "화장실", value: 356, caption: "356곳 / 검증 341" },
  { label: "쉼터", value: 318, caption: "318곳 / 검증 296" },
  { label: "대피소", value: 198, caption: "198곳 / 검증 198" },
];

export const RECENT_ACTIVITY: {
  at: string;
  title: string;
  by: string;
  note: string;
  kind: "등록" | "수정" | "반영" | "삭제";
}[] = [
  {
    at: "06. 12 09:04",
    title: "A 상점가 상인회 AED 운영시간 수정",
    by: "운영팀 정하윤",
    note: "08:00~20:00 으로 변경. 상인회 제출 자료 반영",
    kind: "수정",
  },
  {
    at: "06. 11 18:22",
    title: "A 골목상권 초여름 축제 프로그램 4건 등록",
    by: "콘텐츠팀 서지완",
    note: "우천 시 대체 장소 안내 문구 포함",
    kind: "등록",
  },
  {
    at: "06. 11 14:47",
    title: "1구역 개방화장실 상대 위치 정정",
    by: "운영팀 정하윤",
    note: "사용자 신고 RP-2026-031 반영",
    kind: "반영",
  },
  {
    at: "06. 11 11:05",
    title: "B 상점가 매장 12곳 온누리 가맹 갱신",
    by: "데이터팀 남기헌",
    note: "공공데이터포털 10월 배포분 대조",
    kind: "수정",
  },
  {
    at: "06. 10 16:30",
    title: "폐업 매장 3곳 노출 중지",
    by: "데이터팀 남기헌",
    note: "현장 실사 확인. 지도 마커에서 제외",
    kind: "삭제",
  },
];

export const REPORTS: Report[] = [
  {
    id: "RP-2026-042",
    targetType: "Facility",
    targetId: "fc-wc-1",
    targetName: "A 상점가 공중화장실",
    status: "접수",
    kind: "운영시간 불일치",
    reportedAt: "2026. 06. 12 08:41",
    note: "24시간이라고 나오는데 새벽 1시에 잠겨 있었습니다. 실제로는 05시에 여는 것 같아요.",
    reporter: "사용자 8**2",
    channel: "QR 화면",
    history: [{ status: "접수", at: "06. 12 08:41", by: "자동 접수", note: "QR 화면 신고 폼으로 접수" }],
  },
  {
    id: "RP-2026-041",
    targetType: "Store",
    targetId: "st-a-10",
    targetName: "A 상점가 3구역 세탁소",
    status: "접수",
    kind: "폐업 의심",
    reportedAt: "2026. 06. 12 07:55",
    note: "두 달째 셔터가 내려가 있고 임대 안내문이 붙어 있습니다.",
    reporter: "사용자 3**7",
    channel: "매장 상세",
    history: [{ status: "접수", at: "06. 12 07:55", by: "자동 접수", note: "매장 상세 화면에서 접수" }],
  },
  {
    id: "RP-2026-040",
    targetType: "Facility",
    targetId: "fc-aed-3",
    targetName: "△△동 공영주차장 AED",
    status: "검토",
    kind: "위치 오류",
    reportedAt: "2026. 06. 11 19:12",
    note: "관리동이 아니라 주차장 남측 계단 옆 벽면에 있습니다.",
    reporter: "사용자 1**5",
    channel: "QR 화면",
    history: [
      { status: "접수", at: "06. 11 19:12", by: "자동 접수", note: "QR 화면 신고 폼으로 접수" },
      { status: "검토", at: "06. 12 09:30", by: "운영팀 정하윤", note: "현장 실사 요청. 06. 15 방문 예정" },
    ],
  },
  {
    id: "RP-2026-039",
    targetType: "Festival",
    targetId: "fs-01",
    targetName: "A 골목상권 초여름 축제",
    status: "검토",
    kind: "일정 오류",
    reportedAt: "2026. 06. 11 15:03",
    note: "마지막 날 공연이 21시가 아니라 20시에 끝난다고 현장 안내를 받았습니다.",
    reporter: "사용자 6**1",
    channel: "축제 상세",
    history: [
      { status: "접수", at: "06. 11 15:03", by: "자동 접수", note: "축제 상세 화면에서 접수" },
      { status: "검토", at: "06. 11 17:20", by: "콘텐츠팀 서지완", note: "상인회에 최종 일정 확인 요청" },
    ],
  },
  {
    id: "RP-2026-038",
    targetType: "Store",
    targetId: "st-a-09",
    targetName: "A 상점가 모퉁이 카페",
    status: "반영",
    kind: "온누리 가맹 정보 오류",
    reportedAt: "2026. 06. 10 13:28",
    note: "온누리상품권 결제가 된다고 했는데 카드만 받는다고 합니다.",
    reporter: "사용자 4**9",
    channel: "매장 상세",
    history: [
      { status: "접수", at: "06. 10 13:28", by: "자동 접수", note: "매장 상세 화면에서 접수" },
      { status: "검토", at: "06. 10 16:02", by: "데이터팀 남기헌", note: "가맹점 목록 대조. 2026. 04 해지 확인" },
      { status: "반영", at: "06. 11 10:14", by: "데이터팀 남기헌", note: "가맹 배지 해제. 다음 배포에 포함" },
    ],
  },
  {
    id: "RP-2026-035",
    targetType: "Facility",
    targetId: "fc-rest-3",
    targetName: "△△동 경로당 무더위쉼터",
    status: "반영",
    kind: "운영기간 오류",
    reportedAt: "2026. 06. 07 10:44",
    note: "9월까지라고 되어 있는데 10월에도 열려 있습니다.",
    reporter: "사용자 2**3",
    channel: "QR 화면",
    history: [
      { status: "접수", at: "06. 07 10:44", by: "자동 접수", note: "QR 화면 신고 폼으로 접수" },
      { status: "검토", at: "06. 08 09:10", by: "운영팀 정하윤", note: "동 주민센터 확인 요청" },
      { status: "반영", at: "06. 09 14:35", by: "운영팀 정하윤", note: "운영기간 10월 말까지로 수정" },
    ],
  },
  {
    id: "RP-2026-031",
    targetType: "Facility",
    targetId: "fc-wc-2",
    targetName: "1구역 개방화장실",
    status: "완료",
    kind: "위치 오류",
    reportedAt: "2026. 06. 04 17:02",
    note: "골목 안쪽이 아니라 큰길 쪽 상가 1층입니다.",
    reporter: "사용자 7**4",
    channel: "상점가 상세",
    history: [
      { status: "접수", at: "06. 04 17:02", by: "자동 접수", note: "상점가 상세 화면에서 접수" },
      { status: "검토", at: "06. 05 11:20", by: "운영팀 정하윤", note: "현장 실사 배정" },
      { status: "반영", at: "06. 11 14:47", by: "운영팀 정하윤", note: "상대 위치 문구 정정" },
      { status: "완료", at: "06. 11 18:00", by: "운영팀 정하윤", note: "신고자 알림 발송. 지도 반영 확인" },
    ],
  },
  {
    id: "RP-2026-028",
    targetType: "Store",
    targetId: "st-a-05",
    targetName: "A 상점가 골목 반찬가게",
    status: "완료",
    kind: "영업시간 불일치",
    reportedAt: "2026. 05. 31 09:18",
    note: "20시까지라고 되어 있는데 19시에 문을 닫습니다.",
    reporter: "사용자 5**6",
    channel: "매장 상세",
    history: [
      { status: "접수", at: "05. 31 09:18", by: "자동 접수", note: "매장 상세 화면에서 접수" },
      { status: "검토", at: "06. 01 10:40", by: "데이터팀 남기헌", note: "상인회 통해 확인" },
      { status: "반영", at: "06. 02 15:12", by: "데이터팀 남기헌", note: "영업시간 유지. 하절기 기준 안내 문구 추가" },
      { status: "완료", at: "06. 03 09:00", by: "데이터팀 남기헌", note: "신고자 회신 완료" },
    ],
  },
];

export const DATA_RECORDS: DataRecord[] = [
  {
    id: "FC-1284",
    kind: "시설",
    name: "△△동 정류장 그늘막쉼터",
    category: "쉼터",
    zoneCode: "ZONE-A1",
    address: "△△동 중앙로 40",
    relativeLocation: "QR 지점 바로 옆, 승차대 안",
    onnuri: false,
    source: "현장 실사",
    baseDate: "2026. 06. 01",
    verified: true,
  },
  {
    id: "FC-1283",
    kind: "시설",
    name: "△△동 주민센터 AED",
    category: "AED",
    zoneCode: "ZONE-A1",
    address: "△△동 중앙로 25",
    relativeLocation: "주민센터 1층 로비 안내데스크 옆",
    onnuri: false,
    source: "공공데이터포털",
    baseDate: "2026. 06. 01",
    verified: true,
  },
  {
    id: "FC-1281",
    kind: "시설",
    name: "A 상점가 공중화장실",
    category: "화장실",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로 9",
    relativeLocation: "상점가 내 1구역, 시장 입구 아치 왼편",
    onnuri: false,
    source: "공공데이터포털",
    baseDate: "2026. 05. 22",
    verified: true,
  },
  {
    id: "FC-1279",
    kind: "시설",
    name: "△△동 공영주차장 AED",
    category: "AED",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로 72",
    relativeLocation: "주차장 북측 관리동 단층 건물",
    onnuri: false,
    source: "사용자 신고 반영",
    baseDate: "2026. 06. 12",
    verified: false,
  },
  {
    id: "FC-1276",
    kind: "시설",
    name: "△△초등학교 지진옥외대피소",
    category: "대피소",
    zoneCode: "ZONE-B2",
    address: "△△동 중앙로 88",
    relativeLocation: "학교 운동장, 후문으로 진입",
    onnuri: false,
    source: "공공데이터포털",
    baseDate: "2026. 03. 12",
    verified: true,
  },
  {
    id: "ST-0460",
    kind: "매장",
    name: "A 시장 입구 청과상회",
    category: "농수산 / 청과",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로 12",
    relativeLocation: "상점가 내 1구역, 입구 아치 오른편 첫 점포",
    onnuri: true,
    source: "상인회 제출",
    baseDate: "2026. 06. 01",
    verified: true,
  },
  {
    id: "ST-0457",
    kind: "매장",
    name: "A 상점가 중앙로 정육점",
    category: "농수산 / 정육",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로 28",
    relativeLocation: "상점가 내 2구역, 중앙로 초입",
    onnuri: true,
    source: "상인회 제출",
    baseDate: "2026. 06. 01",
    verified: true,
  },
  {
    id: "ST-0455",
    kind: "매장",
    name: "A 상점가 모퉁이 카페",
    category: "카페 / 커피",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로3길 11",
    relativeLocation: "상점가 내 3구역, 뒷길 모퉁이",
    onnuri: false,
    source: "사용자 신고 반영",
    baseDate: "2026. 06. 11",
    verified: true,
  },
  {
    id: "ST-0451",
    kind: "매장",
    name: "A 상점가 3구역 세탁소",
    category: "생활 / 세탁",
    zoneCode: "ZONE-A1",
    address: "△△동 시장로3길 13",
    relativeLocation: "상점가 내 3구역, 카페 옆",
    onnuri: true,
    source: "상인회 제출",
    baseDate: "2026. 05. 08",
    verified: false,
  },
  {
    id: "ST-0448",
    kind: "매장",
    name: "B 상점가 하천길 국수집",
    category: "음식 / 한식",
    zoneCode: "ZONE-B2",
    address: "△△동 하천로 6",
    relativeLocation: "상점가 내 1구역, 산책로 입구",
    onnuri: true,
    source: "공공데이터포털",
    baseDate: "2026. 06. 11",
    verified: true,
  },
  {
    id: "ST-0444",
    kind: "매장",
    name: "C 상점가 단지앞 문구사",
    category: "교육 / 문구",
    zoneCode: "ZONE-C1",
    address: "△△동 단지로 12",
    relativeLocation: "상점가 내 2구역, 단지 상가 1동",
    onnuri: true,
    source: "상인회 제출",
    baseDate: "2026. 05. 26",
    verified: true,
  },
  {
    id: "ST-0439",
    kind: "매장",
    name: "D 상점가 오일장 건어물집",
    category: "농수산 / 건어물",
    zoneCode: "ZONE-D3",
    address: "△△동 장터로 3",
    relativeLocation: "상점가 내 1구역, 오일장 부지 북측",
    onnuri: true,
    source: "현장 실사",
    baseDate: "2026. 04. 24",
    verified: true,
  },
];

export const CORRECTION_LOGS: CorrectionLog[] = [
  {
    id: "CL-0912",
    at: "2026. 06. 12 09:04",
    target: "A 상점가 상인회 AED",
    field: "운영시간",
    before: "09:00~18:00",
    after: "08:00~20:00",
    by: "운영팀 정하윤",
    source: "상인회 제출",
  },
  {
    id: "CL-0911",
    at: "2026. 06. 11 14:47",
    target: "1구역 개방화장실",
    field: "상대 위치",
    before: "골목 안쪽 상가 1층",
    after: "큰길 쪽 상가 1층",
    by: "운영팀 정하윤",
    source: "사용자 신고 반영",
  },
  {
    id: "CL-0908",
    at: "2026. 06. 11 10:14",
    target: "A 상점가 모퉁이 카페",
    field: "온누리 가맹",
    before: "가맹",
    after: "미가맹",
    by: "데이터팀 남기헌",
    source: "공공데이터포털",
  },
  {
    id: "CL-0904",
    at: "2026. 06. 09 14:35",
    target: "△△동 경로당 무더위쉼터",
    field: "운영기간",
    before: "06월 ~ 09월",
    after: "06월 ~ 10월",
    by: "운영팀 정하윤",
    source: "사용자 신고 반영",
  },
  {
    id: "CL-0899",
    at: "2026. 06. 07 11:26",
    target: "△△동 민방위대피소",
    field: "수용 인원",
    before: "280명",
    after: "340명",
    by: "데이터팀 남기헌",
    source: "공공데이터포털",
  },
];

/* 축제 콘텐츠는 대표 사진이 필수라 축제 사진(design.md 사진 매핑 표의 검증된 id)을 그대로
   쓴다. 배너와 추천 카드는 사진 없이 아이콘 타일로 나가는 형식이라 photo 가 없다. */
export const CONTENT_ITEMS: {
  id: string;
  kind: "축제" | "배너" | "추천";
  title: string;
  place: string;
  period: string;
  status: "노출중" | "예약" | "종료";
  slot: string;
  photo?: string;
}[] = [
  {
    id: "CT-118",
    kind: "축제",
    title: "A 골목상권 초여름 축제",
    place: "A 골목형 상점가",
    period: "06. 11 ~ 06. 13",
    status: "노출중",
    slot: "메인 상단 배너 1",
    photo: "https://picsum.photos/id/452/240/160",
  },
  {
    id: "CT-117",
    kind: "배너",
    title: "여름철 무더위쉼터 운영 안내",
    place: "OO시 전역",
    period: "07. 01 ~ 09. 15",
    status: "예약",
    slot: "메인 공지 스트립",
  },
  {
    id: "CT-116",
    kind: "축제",
    title: "B 골목상권 밤마실 야시장",
    place: "B 골목형 상점가",
    period: "06. 05 ~ 06. 21",
    status: "노출중",
    slot: "축제 목록 상단",
    photo: "https://picsum.photos/id/351/240/160",
  },
  {
    id: "CT-114",
    kind: "추천",
    title: "온누리 가맹점 모아보기",
    place: "A 골목형 상점가",
    period: "상시",
    status: "노출중",
    slot: "상점가 상세 추천 카드",
  },
  {
    id: "CT-111",
    kind: "축제",
    title: "C 골목상권 제철 과일 장터",
    place: "C 골목형 상점가",
    period: "06. 19 ~ 06. 20",
    status: "예약",
    slot: "축제 목록 2",
    photo: "https://picsum.photos/id/674/240/160",
  },
  {
    id: "CT-104",
    kind: "축제",
    title: "A 골목상권 봄 커피 위크",
    place: "A 골목형 상점가",
    period: "04. 11 ~ 04. 19",
    status: "종료",
    slot: "지난 축제 아카이브",
    photo: "https://picsum.photos/id/431/240/160",
  },
];

/* ── 조회 헬퍼 ── */

export const CATEGORY_LABEL: Record<StoreCategory, string> = {
  음식: "음식",
  카페: "카페 / 디저트",
  농수산: "농수산 / 청과",
  생활: "생활 서비스",
  미용: "미용 / 이용",
  의료: "의료 / 약국",
  교육: "교육 / 문구",
};

export function facilityById(id: string) {
  return FACILITIES.find((f) => f.id === id);
}

export function storeById(id: string) {
  return STORES.find((s) => s.id === id);
}

export function districtById(id: string) {
  return DISTRICTS.find((d) => d.id === id);
}

export function festivalById(id: string) {
  return FESTIVALS.find((f) => f.id === id);
}

export function storesOf(districtId: string) {
  return STORES.filter((s) => s.districtId === districtId);
}

export function festivalsOf(districtId: string) {
  return FESTIVALS.filter((f) => f.districtId === districtId);
}

/** 길찾기 목적지는 시설과 매장 양쪽에서 온다. 화면에서 쓰는 공통 형태로 좁힌다. */
export function destinationById(id: string) {
  const facility = facilityById(id);
  if (facility) {
    return {
      id: facility.id,
      name: facility.displayName,
      kind: facility.type as string,
      address: facility.address,
      relativeLocation: facility.relativeLocation,
      distance: facility.distance,
      walkMinutes: facility.walkMinutes,
      coordinates: facility.coordinates,
    };
  }
  const store = storeById(id);
  if (store) {
    return {
      id: store.id,
      name: store.name,
      kind: store.subCategory,
      address: store.address,
      relativeLocation: store.relativeLocation,
      distance: store.distance,
      walkMinutes: store.walkMinutes,
      coordinates: store.coordinates,
    };
  }
  return undefined;
}

export function formatDistance(meters: number) {
  return meters >= 1000 ? `${(meters / 1000).toFixed(1)}km` : `${meters}m`;
}
