import type {
  AdminFacilityRow,
  BandStat,
  Child,
  Facility,
  Mission,
  MonthlyStat,
  SeasonMission,
  VisitRecord,
  WelfareBanner,
} from "@/projects/youngin/child/lib/types";

/* ── 사진 대장 ────────────────────────────────────────────────────────────────
 * picsum id 는 전부 손으로 열어보고 확인한 고정 값이다. seed 방식(무작위)은 쓰지 않는다.
 * 캡션을 고칠 때는 반드시 사진을 다시 열어보고 짝이 맞는지 확인할 것.
 *
 *   28   초록 활엽수림 사이 바위 계곡      → 용인어린이상상의숲 (숲 체험)
 *   1043 침엽수림과 화강암 절벽, 강        → 상상의숲 숲길 두 번째 사진, 여름 숲 프로그램 배너
 *   24   나무 탁자에 펼쳐진 두꺼운 책      → 기흥어린이도서관
 *   128  갈대밭 너머 새벽 호수와 산자락    → 죽전 호수공원 유아놀이터
 *   434  맑은 여름 호수와 물가 나무 데크    → 신갈천 물놀이장, 여름 시즌 미션
 *
 * 수지 장난감도서관은 내용이 맞는 사진이 없어 의도적으로 사진을 쓰지 않고
 * 카테고리 글리프 타일(components/ui.tsx 의 FacilityThumb)로 대체한다.
 * 사진 없이 QR 인증만 한 방문 기록도 같은 글리프 타일로 표시된다.
 * ───────────────────────────────────────────────────────────────────────────── */

export const CHILDREN: Child[] = [
  {
    id: "seoa",
    name: "서아",
    months: 79,
    band: "preschool",
    monthsToNextBand: 5,
    nextBand: "school",
    joinedAt: "2024년 3월",
    visitedCount: 4,
    stampCount: 18,
  },
  {
    id: "doyun",
    name: "도윤",
    months: 21,
    band: "infant",
    monthsToNextBand: 3,
    nextBand: "toddler",
    joinedAt: "2025년 8월",
    visitedCount: 3,
    stampCount: 7,
  },
];

export const FACILITIES: Facility[] = [
  {
    id: "sangsang",
    name: "용인어린이상상의숲",
    category: "forest",
    district: "처인구 포곡읍",
    address: "처인구 포곡읍 삼계로 105",
    distanceKm: 3.2,
    hours: "09:30 - 17:30",
    closedNote: "매주 월요일 휴관, 우천 시 숲길 통제",
    phone: "031-324-3180",
    bands: ["toddler", "preschool", "school"],
    ageLabel: "만 2세 이상",
    intro:
      "유아 숲길 400m와 모래 놀이터, 그늘 쉼터가 이어져 있어 걷기 시작한 아이부터 초등 저학년까지 함께 놀 수 있습니다. 숲 해설사가 상주하는 주말에는 계절 프로그램이 열립니다.",
    tags: ["유아 숲길 400m", "그늘 쉼터", "주차 40면", "유모차 진입 가능"],
    openMission: "숲 놀이터 한 바퀴 걷기",
    reward: "숲 도장 2개",
    missionIds: ["m-forest-walk", "m-forest-leaf"],
    photo: 28,
    gallery: [28, 1043],
    visited: true,
  },
  {
    id: "giheung-lib",
    name: "기흥어린이도서관",
    category: "library",
    district: "기흥구 구갈동",
    address: "기흥구 구갈동 강남서로 21",
    distanceKm: 1.4,
    hours: "09:00 - 18:00",
    closedNote: "매월 첫째 월요일 휴관",
    phone: "031-324-4720",
    bands: ["infant", "toddler", "preschool", "school"],
    ageLabel: "연령 제한 없음",
    intro:
      "1층은 헝겊책과 보드북을 두는 아기방, 2층은 그림책과 독서 프로그램실입니다. 대출증은 보호자 신분증만 있으면 현장에서 바로 발급됩니다.",
    tags: ["아기방 운영", "수유실", "독서 프로그램", "1인 5권 대출"],
    openMission: "그림책 한 권 빌리기",
    reward: "책 도장 1개",
    missionIds: ["m-picture-book", "m-book-club"],
    photo: 24,
    gallery: [24],
    visited: true,
  },
  {
    id: "jukjeon-park",
    name: "죽전 호수공원 유아놀이터",
    category: "playground",
    district: "수지구 죽전동",
    address: "수지구 죽전동 포은대로 435",
    distanceKm: 0.8,
    hours: "상시 개방",
    closedNote: "야간 조명 22:00 소등",
    phone: "031-324-5510",
    bands: ["infant", "toddler"],
    ageLabel: "만 0 - 4세",
    intro:
      "호수 산책로 옆에 붙은 영유아 전용 놀이터입니다. 바닥이 전면 탄성 포장이라 이제 막 걷는 아이도 안전하고, 낮은 미끄럼틀과 아기 그네가 있습니다.",
    tags: ["탄성 바닥", "아기 그네", "수유실 200m", "상시 개방"],
    openMission: "놀이터 이용 인증하기",
    reward: "놀이 도장 1개",
    missionIds: ["m-park-swing", "m-sand-play"],
    photo: 128,
    gallery: [128],
    visited: true,
  },
  {
    id: "suji-toy",
    name: "수지 장난감도서관",
    category: "toyLibrary",
    district: "수지구 풍덕천동",
    address: "수지구 풍덕천동 수지로 234",
    distanceKm: 2.6,
    hours: "10:00 - 17:00",
    closedNote: "주말 휴관, 점심시간 12:00 - 13:00 대여 중단",
    phone: "031-324-6640",
    bands: ["infant", "toddler", "preschool"],
    ageLabel: "만 0 - 6세",
    intro:
      "연 3,000원으로 장난감 2점을 2주씩 빌릴 수 있습니다. 반납된 장난감은 전량 소독 후 다시 진열되고, 인기 품목은 앱에서 예약할 수 있습니다.",
    tags: ["연회비 3,000원", "2점 2주 대여", "전량 소독", "예약 가능"],
    openMission: "장난감 대여하고 반납하기",
    reward: "대여 도장 1개",
    missionIds: ["m-toy-return"],
    visited: false,
  },
  {
    id: "singal-water",
    name: "신갈천 물놀이장",
    category: "waterPlay",
    district: "기흥구 신갈동",
    address: "기흥구 신갈동 신갈로 58 하천 둔치",
    distanceKm: 2.1,
    hours: "7 - 8월 10:00 - 17:00",
    closedNote: "수질 검사일과 강우 시 운영 중단",
    phone: "031-324-7150",
    bands: ["toddler", "preschool"],
    ageLabel: "만 2 - 6세",
    intro:
      "하천 둔치에 여름 두 달만 여는 수심 20cm 물놀이장입니다. 보호자 1명당 아동 2명까지 입장할 수 있고, 탈의실과 샤워 시설이 함께 운영됩니다.",
    tags: ["수심 20cm", "여름 한정", "탈의실", "그늘막 20동"],
    openMission: "여름 물놀이 인증하기",
    reward: "여름 도장 2개",
    missionIds: ["m-water-play", "m-summer-photo"],
    photo: 434,
    gallery: [434],
    visited: true,
  },
];

/** 시설 상세는 URL 파라미터가 아니라 onNavigate 로 id 를 받는다. 없는 id 면 첫 시설로 떨어뜨린다. */
export function getFacility(id: string | null | undefined): Facility {
  return FACILITIES.find((item) => item.id === id) ?? FACILITIES[0];
}

export function getMission(id: string): Mission | undefined {
  return MISSIONS.find((item) => item.id === id);
}

export const SEASON_MISSION: SeasonMission = {
  season: "2026 여름",
  title: "여름 나들이 스탬프 5개 모으기",
  detail: "8월 31일까지 서로 다른 시설 5곳에서 인증하면 여름 한정 도장을 받습니다.",
  goal: 5,
  done: 3,
  endsOn: "8월 31일",
  reward: "여름 한정 숲 도장",
  photo: 434,
};

/** 잠금 미션은 "완주"가 아니라 "다음 연령대에 새로 열린다"는 신호로만 쓴다. */
export const MISSIONS: Mission[] = [
  {
    id: "m-forest-walk",
    kind: "visit",
    title: "숲 놀이터 한 바퀴 걷기",
    detail: "상상의숲 유아 숲길 400m 구간을 아이와 함께 걷고 도착점에서 인증합니다.",
    state: "active",
    reward: "숲 도장 2개",
    stamps: 2,
    bands: ["toddler", "preschool", "school"],
    facilityId: "sangsang",
  },
  {
    id: "m-forest-leaf",
    kind: "visit",
    title: "숲에서 나뭇잎 세 장 모으기",
    detail: "떨어진 나뭇잎만 주워 모양을 비교해 봅니다. 살아 있는 가지는 꺾지 않습니다.",
    state: "active",
    reward: "숲 도장 1개",
    stamps: 1,
    bands: ["toddler", "preschool", "school"],
    facilityId: "sangsang",
    progress: { done: 1, goal: 3 },
  },
  {
    id: "m-picture-book",
    kind: "visit",
    title: "그림책 한 권 빌리기",
    detail: "어린이도서관에서 대출 한 건을 완료하면 자동으로 인증됩니다.",
    state: "done",
    reward: "책 도장 1개",
    stamps: 1,
    bands: ["infant", "toddler", "preschool", "school"],
    facilityId: "giheung-lib",
    completedAt: "07.24",
  },
  {
    id: "m-book-club",
    kind: "age",
    title: "도서관 독서 프로그램 4회 참여",
    detail: "취학 준비기 대상 주말 독서 프로그램에 네 번 참여하면 완료됩니다.",
    state: "active",
    reward: "책 도장 4개",
    stamps: 4,
    bands: ["preschool"],
    facilityId: "giheung-lib",
    progress: { done: 2, goal: 4 },
  },
  {
    id: "m-toy-return",
    kind: "visit",
    title: "장난감 대여하고 반납하기",
    detail: "장난감도서관 회원 가입 후 첫 대여와 반납을 마치면 완료됩니다.",
    state: "active",
    reward: "대여 도장 1개",
    stamps: 1,
    bands: ["infant", "toddler", "preschool"],
    facilityId: "suji-toy",
  },
  {
    id: "m-park-swing",
    kind: "visit",
    title: "놀이터 이용 인증하기",
    detail: "죽전 호수공원 유아놀이터 입구 QR로 방문을 인증합니다.",
    state: "done",
    reward: "놀이 도장 1개",
    stamps: 1,
    bands: ["infant", "toddler"],
    facilityId: "jukjeon-park",
    completedAt: "08.01",
  },
  {
    id: "m-water-play",
    kind: "visit",
    title: "여름 물놀이 인증하기",
    detail: "신갈천 물놀이장 입장 후 탈의실 앞 QR로 인증합니다.",
    state: "done",
    reward: "여름 도장 2개",
    stamps: 2,
    bands: ["toddler", "preschool"],
    facilityId: "singal-water",
    completedAt: "08.05",
  },
  {
    id: "m-summer-stamp",
    kind: "season",
    title: "여름 나들이 스탬프 5개 모으기",
    detail: "서로 다른 시설 5곳에서 인증하면 여름 한정 도장을 받습니다.",
    state: "active",
    reward: "여름 한정 숲 도장",
    stamps: 5,
    bands: ["infant", "toddler", "preschool", "school"],
    progress: { done: 3, goal: 5 },
    dueLabel: "8월 31일 마감",
  },
  {
    id: "m-summer-photo",
    kind: "season",
    title: "여름 사진 세 장 남기기",
    detail: "인증할 때 사진을 함께 올리면 나들이 기록에 자동으로 쌓입니다.",
    state: "active",
    reward: "사진 도장 2개",
    stamps: 2,
    bands: ["infant", "toddler", "preschool", "school"],
    progress: { done: 2, goal: 3 },
    dueLabel: "8월 31일 마감",
  },
  {
    id: "m-first-step",
    kind: "age",
    title: "첫 바깥 나들이 인증",
    detail: "걷기 전 아이도 유모차로 방문해 인증할 수 있는 첫 미션입니다.",
    state: "done",
    reward: "첫걸음 도장 1개",
    stamps: 1,
    bands: ["infant"],
    completedAt: "06.14",
  },
  {
    id: "m-sand-play",
    kind: "age",
    title: "모래 놀이터에서 30분 놀기",
    detail: "걷기 시작한 아이가 모래를 만지며 감각을 익히는 유아기 첫 미션입니다.",
    state: "locked",
    unlockBand: "toddler",
    reward: "놀이 도장 2개",
    stamps: 2,
    bands: ["toddler"],
    facilityId: "jukjeon-park",
  },
  {
    id: "m-school-ready",
    kind: "age",
    title: "학교 가는 길 걸어보기",
    detail: "입학 예정 학교까지 걸어가 보고 통학로 안전 지점을 확인합니다.",
    state: "locked",
    unlockBand: "school",
    reward: "입학 준비 도장 3개",
    stamps: 3,
    bands: ["school"],
  },
];

export const BANNERS: WelfareBanner[] = [
  {
    id: "b-parent-pay",
    kind: "현금성 지원",
    title: "부모급여 신청 안내",
    body: "만 0세 월 100만원, 만 1세 월 50만원을 지원합니다. 출생일로부터 60일 안에 신청하면 출생월부터 소급 지급됩니다.",
    cta: "신청 방법 보기",
    bands: ["infant"],
    department: "여성가족과",
    period: "2026.01.01 - 2026.12.31",
    impressions: 12480,
    taps: 1937,
    status: "노출 중",
  },
  {
    id: "b-toy-library",
    kind: "이용 안내",
    title: "장난감도서관 회원 가입 안내",
    body: "용인시에 주소를 둔 만 0 - 6세 가정은 연 3,000원으로 장난감 2점을 2주씩 빌릴 수 있습니다.",
    cta: "가까운 지점 찾기",
    bands: ["infant", "toddler", "preschool"],
    department: "아동청소년과",
    period: "상시",
    impressions: 9260,
    taps: 1104,
    status: "노출 중",
  },
  {
    id: "b-summer-forest",
    kind: "프로그램 모집",
    title: "여름 숲 놀이 프로그램 모집",
    body: "상상의숲 여름학기를 7월 21일부터 8월 22일까지 주 1회 운영합니다. 회차당 20가정을 선착순으로 받습니다.",
    cta: "모집 공고 보기",
    bands: ["toddler", "preschool"],
    photo: 1043,
    department: "공원녹지과",
    period: "2026.07.01 - 2026.08.22",
    impressions: 7815,
    taps: 1642,
    status: "노출 중",
  },
  {
    id: "b-checkup",
    kind: "건강 관리",
    title: "영유아 건강검진 4차 대상 안내",
    body: "생후 18 - 24개월은 4차 검진과 구강검진 대상입니다. 검진 기간이 지나면 비용이 청구됩니다.",
    cta: "검진 기관 찾기",
    bands: ["infant"],
    department: "보건행정과",
    period: "상시",
    impressions: 6390,
    taps: 812,
    status: "노출 중",
  },
  {
    id: "b-school-care",
    kind: "이용 안내",
    title: "초등 입학 전 돌봄 신청 안내",
    body: "2027년 입학 예정 아동은 9월부터 다함께돌봄센터 우선 배정을 신청할 수 있습니다.",
    cta: "신청 일정 보기",
    bands: ["preschool", "school"],
    department: "아동청소년과",
    period: "2026.09.01 - 2026.10.15",
    impressions: 4127,
    taps: 596,
    status: "예약",
  },
  {
    id: "b-water-safe",
    kind: "건강 관리",
    title: "물놀이장 안전 수칙 안내",
    body: "신갈천 물놀이장은 보호자 1명당 아동 2명까지 입장할 수 있습니다. 수영복과 아쿠아슈즈를 준비해 주세요.",
    cta: "안전 수칙 보기",
    bands: ["toddler", "preschool"],
    department: "공원녹지과",
    period: "2026.07.01 - 2026.08.31",
    impressions: 5304,
    taps: 488,
    status: "종료",
  },
];

export const VISITS: Record<string, VisitRecord[]> = {
  seoa: [
    {
      id: "v-s1",
      month: "2026.08",
      date: "08.05 수",
      facilityId: "singal-water",
      facilityName: "신갈천 물놀이장",
      category: "waterPlay",
      note: "물총 놀이 처음 해본 날",
      stamps: 2,
      photo: 434,
    },
    {
      id: "v-s2",
      month: "2026.08",
      date: "08.01 토",
      facilityId: "jukjeon-park",
      facilityName: "죽전 호수공원 유아놀이터",
      category: "playground",
      note: "저녁 산책하고 그네",
      stamps: 1,
      photo: 128,
    },
    {
      id: "v-s3",
      month: "2026.07",
      date: "07.30 목",
      facilityId: "sangsang",
      facilityName: "용인어린이상상의숲",
      category: "forest",
      note: "숲길 완주하고 도토리 주웠어요",
      stamps: 2,
      photo: 28,
    },
    {
      id: "v-s4",
      month: "2026.07",
      date: "07.24 금",
      facilityId: "giheung-lib",
      facilityName: "기흥어린이도서관",
      category: "library",
      note: "그림책 3권 대출",
      stamps: 1,
      photo: 24,
    },
    {
      id: "v-s5",
      month: "2026.07",
      date: "07.18 토",
      facilityId: "jukjeon-park",
      facilityName: "죽전 호수공원 유아놀이터",
      category: "playground",
      note: "해질 때까지 미끄럼틀",
      stamps: 1,
      photo: 128,
    },
    {
      id: "v-s6",
      month: "2026.06",
      date: "06.21 일",
      facilityId: "sangsang",
      facilityName: "용인어린이상상의숲",
      category: "forest",
      note: "숲 해설 프로그램 참여",
      stamps: 2,
      photo: 1043,
    },
    {
      id: "v-s7",
      month: "2026.06",
      date: "06.07 일",
      facilityId: "giheung-lib",
      facilityName: "기흥어린이도서관",
      category: "library",
      note: "독서 프로그램 1회차",
      stamps: 1,
      photo: 24,
    },
  ],
  doyun: [
    {
      id: "v-d1",
      month: "2026.08",
      date: "08.02 일",
      facilityId: "jukjeon-park",
      facilityName: "죽전 호수공원 유아놀이터",
      category: "playground",
      note: "그네 처음 타본 날",
      stamps: 1,
      photo: 128,
    },
    {
      id: "v-d2",
      month: "2026.07",
      date: "07.26 일",
      facilityId: "giheung-lib",
      facilityName: "기흥어린이도서관",
      category: "library",
      note: "아기방에서 헝겊책 읽기",
      stamps: 1,
      photo: 24,
    },
    {
      id: "v-d3",
      month: "2026.07",
      date: "07.12 일",
      facilityId: "suji-toy",
      facilityName: "수지 장난감도서관",
      category: "toyLibrary",
      note: "첫 장난감 대여, 사진은 못 찍었어요",
      stamps: 1,
    },
    {
      id: "v-d4",
      month: "2026.06",
      date: "06.14 일",
      facilityId: "jukjeon-park",
      facilityName: "죽전 호수공원 유아놀이터",
      category: "playground",
      note: "유모차로 호수 한 바퀴",
      stamps: 1,
      photo: 128,
    },
  ],
};

export const MONTHLY_STATS: Record<string, MonthlyStat[]> = {
  seoa: [
    { month: "2026.08", label: "8월", visits: 2, facilities: 2, stamps: 3 },
    { month: "2026.07", label: "7월", visits: 3, facilities: 3, stamps: 4 },
    { month: "2026.06", label: "6월", visits: 2, facilities: 2, stamps: 3 },
  ],
  doyun: [
    { month: "2026.08", label: "8월", visits: 1, facilities: 1, stamps: 1 },
    { month: "2026.07", label: "7월", visits: 2, facilities: 2, stamps: 2 },
    { month: "2026.06", label: "6월", visits: 1, facilities: 1, stamps: 1 },
  ],
};

/* ── 관리자 콘솔 ── */

export const ADMIN_SUMMARY = {
  children: 4182,
  monthlyScans: 9347,
  facilities: 46,
  liveBanners: 4,
  scanDelta: "+12.4%",
  childrenDelta: "+186명",
};

export const BAND_STATS: BandStat[] = [
  { band: "infant", children: 1204, visits: 2118, tapRate: 18.4 },
  { band: "toddler", children: 1376, visits: 3242, tapRate: 14.2 },
  { band: "preschool", children: 968, visits: 2571, tapRate: 11.6 },
  { band: "school", children: 634, visits: 1416, tapRate: 8.9 },
];

/** 월별 QR 인증 건수. 물놀이장이 열리는 7 - 8월에 뚜렷하게 오른다. */
export const MONTHLY_SCANS = [
  { label: "2월", value: 3120 },
  { label: "3월", value: 4285 },
  { label: "4월", value: 5640 },
  { label: "5월", value: 6912 },
  { label: "6월", value: 7108 },
  { label: "7월", value: 8317 },
  { label: "8월", value: 9347, emphasis: true },
];

export const ADMIN_FACILITIES: AdminFacilityRow[] = [
  {
    id: "f-1",
    name: "용인어린이상상의숲",
    category: "forest",
    district: "처인구 포곡읍",
    bands: ["toddler", "preschool", "school"],
    qrScans: 1842,
    lastSyncedAt: "08.07 08:20",
    status: "운영 중",
  },
  {
    id: "f-2",
    name: "기흥어린이도서관",
    category: "library",
    district: "기흥구 구갈동",
    bands: ["infant", "toddler", "preschool", "school"],
    qrScans: 1516,
    lastSyncedAt: "08.07 08:20",
    status: "운영 중",
  },
  {
    id: "f-3",
    name: "죽전 호수공원 유아놀이터",
    category: "playground",
    district: "수지구 죽전동",
    bands: ["infant", "toddler"],
    qrScans: 1274,
    lastSyncedAt: "08.07 08:20",
    status: "운영 중",
  },
  {
    id: "f-4",
    name: "신갈천 물놀이장",
    category: "waterPlay",
    district: "기흥구 신갈동",
    bands: ["toddler", "preschool"],
    qrScans: 1103,
    lastSyncedAt: "08.06 18:40",
    status: "운영 중",
  },
  {
    id: "f-5",
    name: "수지 장난감도서관",
    category: "toyLibrary",
    district: "수지구 풍덕천동",
    bands: ["infant", "toddler", "preschool"],
    qrScans: 869,
    lastSyncedAt: "08.05 09:10",
    status: "점검",
  },
];

export const ADMIN_ACTIVITY = [
  {
    label: "부모급여 배너 노출 연령대 수정",
    at: "08.07 09:12",
    done: true,
    note: "영아기 단독 노출로 변경 (기존 영아기 + 유아기)",
  },
  {
    label: "여름 숲 놀이 프로그램 3차 모집 등록",
    at: "08.06 16:48",
    done: true,
    note: "정원 20가정, 신청 시작 08.10 09:00",
  },
  {
    label: "수지 장난감도서관 QR 재발급",
    at: "08.05 09:10",
    done: true,
    note: "출입구 QR 훼손 신고 접수 후 교체",
  },
  {
    label: "가을 시즌 미션 초안 검토",
    at: "08.11 예정",
    done: false,
    note: "낙엽 줍기, 도서관 가을 특별전 연계 3종",
  },
];
