import type {
  Facility,
  FacilityCategory,
  FacilityKind,
  Floor,
  FloorId,
  Notice,
  Service,
} from "./types";

export const BUILDING = {
  name: "용인시청",
  wing: "본관",
  /** QR sticker location. Everything on the map is routed from here. */
  entryPoint: "1층 정문 출입구",
  entryFloor: 1 as FloorId,
  address: "경기도 용인시 처인구 시청로 25",
  hours: "평일 09:00 ~ 18:00",
  lunch: "점심시간 12:00 ~ 13:00 (창구 교대 운영)",
  closedDays: "토요일, 일요일, 공휴일 휴무",
  tel: "031-324-2114",
  scannedAt: "2026년 8월 7일 금요일 오전 10시 12분",
};

/** Coarse grouping used by the map filter chips and the legend. */
export const FACILITY_CATEGORY: Record<FacilityKind, FacilityCategory> = {
  counter: "counter",
  dept: "dept",
  ticket: "kiosk",
  kiosk: "kiosk",
  info: "info",
  restroom: "amenity",
  restroomAccessible: "amenity",
  nursing: "amenity",
  cafe: "amenity",
  water: "amenity",
  atm: "amenity",
  elevator: "move",
  stairs: "move",
  entrance: "move",
  parking: "move",
};

export const CATEGORY_LABEL: Record<FacilityCategory, string> = {
  counter: "민원 창구",
  dept: "부서 사무실",
  kiosk: "번호표 / 발급기",
  info: "안내데스크",
  amenity: "편의시설",
  move: "이동 / 출입",
};

export const CATEGORY_COLOR: Record<FacilityCategory, string> = {
  counter: "var(--yi-cat-counter)",
  dept: "var(--yi-cat-dept)",
  kiosk: "var(--yi-cat-kiosk)",
  info: "var(--yi-cat-info)",
  amenity: "var(--yi-cat-amenity)",
  move: "var(--yi-cat-move)",
};

export const FLOORS: Floor[] = [
  {
    id: 1,
    label: "1F",
    name: "종합민원동",
    summary: "번호표 발급, 주민 / 가족관계 / 제증명 창구, 무인민원발급기",
    corridor: "중앙 안내홀을 기준으로 왼쪽이 종합민원실, 오른쪽이 무인민원 구역입니다.",
    zones: [
      { id: "west", label: "서편 종합민원실" },
      { id: "center", label: "중앙 안내홀" },
      { id: "east", label: "동편 무인민원 / 편의구역" },
    ],
  },
  {
    id: 2,
    label: "2F",
    name: "여권 / 복지 / 세무",
    summary: "여권민원실, 복지정책과, 세무과, 시민 휴게 카페",
    corridor: "엘리베이터에서 내려 왼쪽이 여권민원실, 오른쪽이 복지 / 세무 구역입니다.",
    zones: [
      { id: "west", label: "서편 여권민원실" },
      { id: "center", label: "중앙 엘리베이터홀" },
      { id: "east", label: "동편 복지 / 세무 구역" },
    ],
  },
  {
    id: 3,
    label: "3F",
    name: "도시 / 건축 / 토지",
    summary: "건축과, 도시계획과, 토지정보과, 지적 열람실",
    corridor: "엘리베이터에서 내려 왼쪽이 도시 / 건축 구역, 오른쪽이 토지 / 열람 구역입니다.",
    zones: [
      { id: "west", label: "서편 도시 / 건축 구역" },
      { id: "center", label: "중앙 엘리베이터홀" },
      { id: "east", label: "동편 토지 / 열람 구역" },
    ],
  },
];

export const FACILITIES: Facility[] = [
  /* ---------------------------- 1F ---------------------------- */
  {
    id: "f1-counter-1",
    floor: 1,
    zone: "west",
    kind: "counter",
    name: "1번 창구",
    sub: "주민등록 / 인감",
    span: 1,
    detail: "주민등록등본, 초본, 인감증명서를 발급합니다. 인감은 본인만 신청할 수 있습니다.",
    route: "정문에서 왼쪽 종합민원실로 들어가 첫 번째 창구",
    distance: "약 18m",
    hours: "09:00 ~ 18:00",
    queue: 3,
    tags: ["주민등록등본", "인감증명"],
  },
  {
    id: "f1-counter-2",
    floor: 1,
    zone: "west",
    kind: "counter",
    name: "2번 창구",
    sub: "가족관계",
    span: 1,
    detail: "가족관계증명서, 기본증명서, 혼인관계증명서를 발급합니다.",
    route: "정문에서 왼쪽 종합민원실로 들어가 두 번째 창구",
    distance: "약 20m",
    hours: "09:00 ~ 18:00",
    queue: 5,
    tags: ["가족관계증명서"],
  },
  {
    id: "f1-counter-3",
    floor: 1,
    zone: "west",
    kind: "counter",
    name: "3번 창구",
    sub: "전입 / 전출 신고",
    span: 1,
    detail: "전입신고와 세대주 변경을 접수합니다. 세대원 전원 신고 시 위임장이 필요합니다.",
    route: "정문에서 왼쪽 종합민원실로 들어가 오른쪽 복도 끝",
    distance: "약 25m",
    hours: "09:00 ~ 18:00",
    queue: 2,
    tags: ["전입신고"],
  },
  {
    id: "f1-counter-4",
    floor: 1,
    zone: "west",
    kind: "counter",
    name: "4번 창구",
    sub: "종합 상담",
    span: 1,
    detail: "어떤 창구로 가야 할지 모를 때 먼저 들르는 창구입니다. 서류 작성도 도와드립니다.",
    route: "종합민원실 입구 바로 왼쪽",
    distance: "약 16m",
    hours: "09:00 ~ 18:00",
    queue: 0,
    tags: ["상담", "서류 작성"],
  },
  {
    id: "f1-ticket",
    floor: 1,
    zone: "west",
    kind: "ticket",
    name: "번호표 발급기",
    sub: "종합민원실 입구",
    span: 4,
    detail:
      "창구 방문 전 반드시 번호표를 먼저 뽑아 주세요. 화면에서 민원 종류를 고르면 해당 창구 번호표가 나옵니다.",
    route: "종합민원실 입구 오른쪽 벽면, 안내데스크 맞은편",
    distance: "약 14m",
    hours: "09:00 ~ 17:50",
    tags: ["대기표", "창구 안내"],
  },
  {
    id: "f1-info",
    floor: 1,
    zone: "center",
    kind: "info",
    name: "종합안내데스크",
    sub: "정문 정면",
    span: 2,
    detail: "청사 위치 안내, 서류 작성 도움, 휠체어 대여를 담당합니다. 수어 통역은 사전 예약제입니다.",
    route: "정문으로 들어와 정면 8m",
    distance: "약 8m",
    hours: "09:00 ~ 18:00",
    tags: ["휠체어 대여", "길 안내"],
  },
  {
    id: "f1-entrance",
    floor: 1,
    zone: "center",
    kind: "entrance",
    name: "정문 출입구",
    sub: "현재 위치",
    span: 2,
    detail: "지금 계신 곳입니다. QR 안내판은 자동문 오른쪽 기둥에 있습니다.",
    route: "현재 위치",
    hours: "08:00 ~ 20:00",
    tags: ["QR 안내판", "자동문"],
  },
  {
    id: "f1-elevator",
    floor: 1,
    zone: "center",
    kind: "elevator",
    name: "엘리베이터",
    sub: "3대 운행",
    span: 2,
    detail: "지하 2층부터 5층까지 운행합니다. 3호기는 들것 이송용 대형 엘리베이터입니다.",
    route: "안내데스크 뒤편 왼쪽",
    distance: "약 12m",
    hours: "08:00 ~ 20:00",
    tags: ["휠체어 이용 가능", "점자 버튼"],
  },
  {
    id: "f1-stairs",
    floor: 1,
    zone: "center",
    kind: "stairs",
    name: "중앙 계단",
    sub: "1F ~ 5F",
    span: 2,
    detail: "각 층 중앙홀로 이어집니다. 계단 양쪽에 손잡이가 있습니다.",
    route: "안내데스크 뒤편 오른쪽",
    distance: "약 12m",
    tags: ["손잡이 설치"],
  },
  {
    id: "f1-kiosk",
    floor: 1,
    zone: "east",
    kind: "kiosk",
    name: "무인민원발급기",
    sub: "2대 설치",
    span: 2,
    detail:
      "주민등록등본, 초본, 가족관계증명서 등 42종을 창구 대기 없이 발급합니다. 지문 인증 또는 신분증으로 본인 확인을 합니다.",
    route: "정문에서 오른쪽 복도로 10m, 카페 맞은편",
    distance: "약 22m",
    hours: "평일 07:00 ~ 22:00, 주말 09:00 ~ 18:00",
    tags: ["24시간 아님", "카드 결제 가능"],
  },
  {
    id: "f1-restroom",
    floor: 1,
    zone: "east",
    kind: "restroom",
    name: "화장실",
    sub: "남 / 여",
    span: 1,
    detail: "동편 복도 끝에 있습니다. 기저귀 교환대는 여자화장실 안쪽에 있습니다.",
    route: "정문에서 오른쪽 복도 끝",
    distance: "약 30m",
    tags: ["기저귀 교환대"],
  },
  {
    id: "f1-restroom-acc",
    floor: 1,
    zone: "east",
    kind: "restroomAccessible",
    name: "장애인 화장실",
    sub: "남녀 공용",
    span: 1,
    detail: "출입문 폭 90cm, 자동문입니다. 내부에 비상 호출 버튼이 있습니다.",
    route: "동편 화장실 바로 왼쪽, 복도에서 바로 진입",
    distance: "약 29m",
    tags: ["자동문", "비상 호출"],
  },
  {
    id: "f1-nursing",
    floor: 1,
    zone: "east",
    kind: "nursing",
    name: "수유실",
    sub: "예약 없이 이용",
    span: 2,
    detail:
      "수유 의자 2석, 기저귀 교환대, 아기 침대, 정수기가 있습니다. 문 앞 표시등이 켜져 있으면 사용 중입니다.",
    route: "동편 복도 중간, 무인민원발급기 옆",
    distance: "약 26m",
    hours: "09:00 ~ 18:00",
    tags: ["아기 침대", "정수기"],
  },
  {
    id: "f1-cafe",
    floor: 1,
    zone: "east",
    kind: "cafe",
    name: "시민 휴게 카페",
    sub: "좌석 24석",
    span: 2,
    detail:
      "대기 시간에 앉아 쉴 수 있는 개방형 카페입니다. 번호표 호출 화면이 카페 안에도 있어 자리에서 순서를 확인할 수 있습니다.",
    route: "정문에서 오른쪽 복도 10m, 무인민원발급기 맞은편",
    distance: "약 20m",
    hours: "08:30 ~ 17:30",
    photoId: 42,
    photoCaption: "창가 공용 테이블이 있는 시민 휴게 카페",
    tags: ["번호표 호출 화면", "충전 콘센트"],
  },
  {
    id: "f1-atm",
    floor: 1,
    zone: "east",
    kind: "atm",
    name: "현금인출기",
    sub: "2대",
    span: 1,
    detail: "수수료 면제 시간은 평일 09:00부터 18:00까지입니다.",
    route: "동편 복도 초입 오른쪽",
    distance: "약 18m",
    tags: ["통장 정리 가능"],
  },
  {
    id: "f1-water",
    floor: 1,
    zone: "east",
    kind: "water",
    name: "정수기",
    sub: "냉 / 온수",
    span: 1,
    detail: "종이컵이 비치되어 있습니다.",
    route: "동편 복도 초입 왼쪽",
    distance: "약 18m",
  },
  {
    id: "f1-parking",
    floor: 1,
    zone: "east",
    kind: "parking",
    name: "지하주차장 연결 통로",
    sub: "B1 ~ B2",
    span: 4,
    detail:
      "민원 방문 시 1시간 무료입니다. 창구에서 주차권을 확인받으세요. 장애인 주차 구역은 B1 엘리베이터 바로 앞입니다.",
    route: "동편 복도 끝에서 왼쪽 계단, 또는 중앙 엘리베이터로 B1",
    distance: "약 34m",
    tags: ["1시간 무료", "장애인 구역 6면"],
  },

  /* ---------------------------- 2F ---------------------------- */
  {
    id: "f2-counter-5",
    floor: 2,
    zone: "west",
    kind: "counter",
    name: "5번 창구",
    sub: "여권 접수",
    span: 1,
    detail: "여권 신규 발급과 재발급을 접수합니다. 사진은 6개월 이내 촬영본만 받습니다.",
    route: "엘리베이터에서 내려 왼쪽 여권민원실 첫 번째 창구",
    distance: "약 15m",
    hours: "09:00 ~ 18:00",
    queue: 7,
    tags: ["여권 발급"],
  },
  {
    id: "f2-counter-6",
    floor: 2,
    zone: "west",
    kind: "counter",
    name: "6번 창구",
    sub: "여권 교부",
    span: 1,
    detail: "발급이 끝난 여권을 찾는 창구입니다. 접수증과 신분증을 준비해 주세요.",
    route: "엘리베이터에서 내려 왼쪽 여권민원실 두 번째 창구",
    distance: "약 17m",
    hours: "09:00 ~ 18:00",
    queue: 1,
    tags: ["여권 수령"],
  },
  {
    id: "f2-photo",
    floor: 2,
    zone: "west",
    kind: "kiosk",
    name: "여권사진 촬영기",
    sub: "규격 자동 보정",
    span: 2,
    detail: "여권 규격에 맞춰 자동 촬영합니다. 4매 5000원, 카드 결제만 가능합니다.",
    route: "여권민원실 입구 오른쪽",
    distance: "약 14m",
    hours: "09:00 ~ 17:30",
    tags: ["카드 전용"],
  },
  {
    id: "f2-ticket",
    floor: 2,
    zone: "west",
    kind: "ticket",
    name: "번호표 발급기",
    sub: "여권민원실 입구",
    span: 4,
    detail: "여권 접수와 교부 번호표가 따로 나옵니다. 교부는 대기가 짧은 편입니다.",
    route: "여권민원실 입구 왼쪽 벽면",
    distance: "약 13m",
    hours: "09:00 ~ 17:50",
  },
  {
    id: "f2-info",
    floor: 2,
    zone: "center",
    kind: "info",
    name: "2층 안내데스크",
    sub: "엘리베이터홀",
    span: 4,
    detail: "여권 서류 작성과 부서 위치를 안내합니다. 서식 작성대가 옆에 있습니다.",
    route: "엘리베이터에서 내려 정면",
    distance: "약 4m",
    hours: "09:00 ~ 18:00",
    tags: ["서식 작성대"],
  },
  {
    id: "f2-elevator",
    floor: 2,
    zone: "center",
    kind: "elevator",
    name: "엘리베이터",
    sub: "3대 운행",
    span: 2,
    detail: "1층 안내데스크 뒤편 엘리베이터와 같은 라인입니다.",
    route: "중앙홀 정면",
    tags: ["휠체어 이용 가능"],
  },
  {
    id: "f2-stairs",
    floor: 2,
    zone: "center",
    kind: "stairs",
    name: "중앙 계단",
    sub: "1F ~ 5F",
    span: 2,
    detail: "1층 중앙홀과 바로 이어집니다.",
    route: "중앙홀 오른쪽",
  },
  {
    id: "f2-welfare",
    floor: 2,
    zone: "east",
    kind: "dept",
    name: "복지정책과",
    sub: "201호",
    span: 2,
    detail: "기초생활보장, 긴급복지지원, 복지 상담을 담당합니다. 상담은 예약 우선입니다.",
    route: "엘리베이터에서 오른쪽 복도 첫 번째 사무실",
    distance: "약 12m",
    hours: "09:00 ~ 18:00",
    tags: ["복지 상담 예약"],
  },
  {
    id: "f2-tax",
    floor: 2,
    zone: "east",
    kind: "dept",
    name: "세무과",
    sub: "203호",
    span: 2,
    detail: "재산세, 자동차세, 지방소득세 부과와 조회를 담당합니다.",
    route: "엘리베이터에서 오른쪽 복도 두 번째 사무실",
    distance: "약 18m",
    hours: "09:00 ~ 18:00",
  },
  {
    id: "f2-counter-7",
    floor: 2,
    zone: "east",
    kind: "counter",
    name: "7번 창구",
    sub: "지방세 납부 / 증명",
    span: 2,
    detail: "지방세 납부확인서, 세목별 과세증명서를 발급합니다.",
    route: "세무과 사무실 앞 복도 창구",
    distance: "약 19m",
    hours: "09:00 ~ 18:00",
    queue: 4,
    tags: ["납부확인서"],
  },
  {
    id: "f2-cafe",
    floor: 2,
    zone: "east",
    kind: "cafe",
    name: "휴게 라운지",
    sub: "좌석 16석",
    span: 2,
    detail: "여권 발급 대기 중 이용할 수 있는 조용한 라운지입니다. 자판기와 충전 콘센트가 있습니다.",
    route: "동편 복도 끝 창가",
    distance: "약 26m",
    hours: "09:00 ~ 18:00",
    tags: ["자판기", "충전 콘센트"],
  },
  {
    id: "f2-restroom",
    floor: 2,
    zone: "east",
    kind: "restroom",
    name: "화장실",
    sub: "남 / 여",
    span: 2,
    detail: "동편 복도 중간에 있습니다.",
    route: "엘리베이터에서 오른쪽 복도 중간",
    distance: "약 20m",
  },
  {
    id: "f2-restroom-acc",
    floor: 2,
    zone: "east",
    kind: "restroomAccessible",
    name: "장애인 화장실",
    sub: "남녀 공용",
    span: 2,
    detail: "자동문이며 내부에 비상 호출 버튼이 있습니다.",
    route: "동편 화장실 바로 옆",
    distance: "약 20m",
    tags: ["자동문", "비상 호출"],
  },

  /* ---------------------------- 3F ---------------------------- */
  {
    id: "f3-arch",
    floor: 3,
    zone: "west",
    kind: "dept",
    name: "건축과",
    sub: "301호",
    span: 2,
    detail: "건축 인허가, 건축물대장, 위반건축물 업무를 담당합니다.",
    route: "엘리베이터에서 내려 왼쪽 첫 번째 사무실",
    distance: "약 10m",
    hours: "09:00 ~ 18:00",
  },
  {
    id: "f3-city",
    floor: 3,
    zone: "west",
    kind: "dept",
    name: "도시계획과",
    sub: "303호",
    span: 2,
    detail: "도시계획 확인, 지구단위계획, 개발행위 허가를 담당합니다.",
    route: "엘리베이터에서 내려 왼쪽 두 번째 사무실",
    distance: "약 16m",
    hours: "09:00 ~ 18:00",
  },
  {
    id: "f3-counter-8",
    floor: 3,
    zone: "west",
    kind: "counter",
    name: "8번 창구",
    sub: "건축 / 도시 상담",
    span: 4,
    detail: "건축물대장 발급과 인허가 사전 상담을 한 자리에서 처리합니다.",
    route: "서편 복도 초입 상담 창구",
    distance: "약 9m",
    hours: "09:00 ~ 18:00",
    queue: 2,
    tags: ["건축물대장", "사전 상담"],
  },
  {
    id: "f3-elevator",
    floor: 3,
    zone: "center",
    kind: "elevator",
    name: "엘리베이터",
    sub: "3대 운행",
    span: 2,
    detail: "1층, 2층과 같은 라인입니다.",
    route: "중앙홀 정면",
    tags: ["휠체어 이용 가능"],
  },
  {
    id: "f3-stairs",
    floor: 3,
    zone: "center",
    kind: "stairs",
    name: "중앙 계단",
    sub: "1F ~ 5F",
    span: 2,
    detail: "각 층 중앙홀로 이어집니다.",
    route: "중앙홀 오른쪽",
  },
  {
    id: "f3-land",
    floor: 3,
    zone: "east",
    kind: "dept",
    name: "토지정보과",
    sub: "305호",
    span: 2,
    detail: "토지대장, 지적도, 경계 측량 접수를 담당합니다.",
    route: "엘리베이터에서 오른쪽 첫 번째 사무실",
    distance: "약 12m",
    hours: "09:00 ~ 18:00",
  },
  {
    id: "f3-reading",
    floor: 3,
    zone: "east",
    kind: "dept",
    name: "지적 열람실",
    sub: "306호",
    span: 2,
    detail: "지적도와 도시계획도를 직접 열람할 수 있습니다. 복사는 창구에 신청합니다.",
    route: "토지정보과 맞은편",
    distance: "약 13m",
    hours: "09:00 ~ 17:30",
    tags: ["직접 열람"],
  },
  {
    id: "f3-meeting",
    floor: 3,
    zone: "east",
    kind: "dept",
    name: "시민 회의실",
    sub: "307호",
    span: 2,
    detail: "주민 설명회와 사전 상담이 열리는 공간입니다. 일정은 안내데스크에서 확인하세요.",
    route: "동편 복도 끝",
    distance: "약 24m",
  },
  {
    id: "f3-restroom",
    floor: 3,
    zone: "east",
    kind: "restroom",
    name: "화장실",
    sub: "남 / 여",
    span: 2,
    detail: "동편 복도 중간에 있습니다.",
    route: "엘리베이터에서 오른쪽 복도 중간",
    distance: "약 18m",
  },
];

export const SERVICES: Service[] = [
  {
    id: "resident-copy",
    name: "주민등록등본 발급",
    short: "주민등록등본",
    category: "주민 / 등록",
    icon: "resident",
    desc: "세대 구성원과 주소 이력이 표시되는 증명서입니다. 은행 제출용은 주민등록번호 뒷자리 표시 여부를 미리 확인하세요.",
    facilityId: "f1-counter-1",
    place: "1층 종합민원실 1번 창구",
    floor: 1,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true, note: "주민등록증, 운전면허증, 여권 중 1종" },
      { label: "위임장", required: false, note: "대리 신청 시에만 필요" },
      { label: "대리인 신분증", required: false, note: "대리 신청 시에만 필요" },
    ],
    steps: [
      { title: "번호표 발급", desc: "종합민원실 입구 발급기에서 주민등록 항목을 선택합니다." },
      { title: "대기", desc: "카페와 대기석 화면에서 호출 순서를 확인할 수 있습니다." },
      { title: "창구 방문", desc: "1번 창구에서 신분증을 제시하고 필요 통수를 말씀하세요." },
      { title: "수수료 납부", desc: "카드와 현금 모두 가능하며 계좌이체는 되지 않습니다." },
      { title: "서류 수령", desc: "발급 내용을 그 자리에서 확인한 뒤 창구를 떠나세요." },
    ],
    duration: "약 5분",
    fee: "400원",
    feeNote: "무인민원발급기 이용 시 200원",
    kiosk: {
      available: true,
      note: "1층 동편 무인민원발급기에서 창구 대기 없이 발급됩니다.",
    },
    related: ["resident-abstract", "family-cert", "move-in"],
    rating: { avg: 4.7, count: 1284 },
    popular: true,
    keywords: ["등본", "주민등록", "세대"],
  },
  {
    id: "resident-abstract",
    name: "주민등록초본 발급",
    short: "주민등록초본",
    category: "주민 / 등록",
    icon: "resident",
    desc: "본인의 주소 변동 이력만 표시되는 증명서입니다. 병역 사항과 과거 주소 표시 여부를 선택할 수 있습니다.",
    facilityId: "f1-counter-1",
    place: "1층 종합민원실 1번 창구",
    floor: 1,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "위임장", required: false, note: "직계가족 외 대리 신청 시 필요" },
    ],
    steps: [
      { title: "번호표 발급", desc: "주민등록 항목을 선택합니다." },
      { title: "대기", desc: "평균 대기 시간은 오전이 짧습니다." },
      { title: "창구 방문", desc: "표시할 항목을 창구 직원에게 알려 주세요." },
      { title: "서류 수령", desc: "수수료 납부 후 바로 받습니다." },
    ],
    duration: "약 5분",
    fee: "400원",
    feeNote: "무인민원발급기 이용 시 200원",
    kiosk: { available: true, note: "무인민원발급기에서 항목 선택까지 가능합니다." },
    related: ["resident-copy", "move-in"],
    rating: { avg: 4.6, count: 742 },
    popular: true,
    keywords: ["초본", "주소 이력"],
  },
  {
    id: "family-cert",
    name: "가족관계증명서 발급",
    short: "가족관계증명서",
    category: "가족관계",
    icon: "family",
    desc: "본인 기준 부모, 배우자, 자녀가 표시됩니다. 일반증명서와 상세증명서 중 제출처 요구 사항을 확인하고 선택하세요.",
    facilityId: "f1-counter-2",
    place: "1층 종합민원실 2번 창구",
    floor: 1,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "가족관계 확인 서류", required: false, note: "제3자 신청 시 이해관계 소명 자료" },
    ],
    steps: [
      { title: "번호표 발급", desc: "가족관계 항목을 선택합니다." },
      { title: "대기", desc: "오전 11시 전후로 대기가 가장 깁니다." },
      { title: "창구 방문", desc: "일반증명서인지 상세증명서인지 알려 주세요." },
      { title: "서류 수령", desc: "발급 후 이름과 생년월일을 확인하세요." },
    ],
    duration: "약 7분",
    fee: "1000원",
    feeNote: "무인민원발급기 이용 시 500원",
    kiosk: { available: true, note: "일반증명서만 발급되며 상세증명서는 창구에서 신청합니다." },
    related: ["resident-copy", "seal-cert"],
    rating: { avg: 4.5, count: 968 },
    popular: true,
    keywords: ["가족관계", "혼인관계", "기본증명서"],
  },
  {
    id: "passport",
    name: "여권 발급 신청",
    short: "여권 발급",
    category: "여권",
    icon: "passport",
    desc: "신규 발급과 기간 만료 재발급을 접수합니다. 접수 후 실제 수령까지 근무일 기준 7일에서 10일이 걸립니다.",
    facilityId: "f2-counter-5",
    place: "2층 여권민원실 5번 창구",
    floor: 2,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "여권용 사진 1매", required: true, note: "6개월 이내 촬영, 흰 배경" },
      { label: "본인 신분증", required: true },
      { label: "기존 여권", required: false, note: "재발급 시 반드시 지참" },
      { label: "법정대리인 동의서", required: false, note: "18세 미만 신청 시" },
    ],
    steps: [
      { title: "번호표 발급", desc: "여권민원실 입구에서 접수 번호표를 뽑습니다." },
      { title: "신청서 작성", desc: "안내데스크 옆 서식 작성대에서 작성합니다." },
      { title: "창구 접수", desc: "5번 창구에서 사진과 서류를 확인받습니다." },
      { title: "수수료 납부", desc: "여권 종류에 따라 금액이 다릅니다." },
      { title: "수령", desc: "문자 안내를 받은 뒤 6번 창구에서 찾습니다." },
    ],
    duration: "접수 약 15분, 수령까지 7일에서 10일",
    fee: "53000원",
    feeNote: "10년 복수여권 58면 기준",
    kiosk: { available: false, note: "본인 확인과 사진 검수가 필요해 창구 접수만 가능합니다." },
    related: ["family-cert", "resident-copy"],
    rating: { avg: 4.4, count: 613 },
    popular: true,
    keywords: ["여권", "패스포트", "해외"],
  },
  {
    id: "seal-cert",
    name: "인감증명서 발급",
    short: "인감증명서",
    category: "주민 / 등록",
    icon: "seal",
    desc: "부동산 거래와 금융 계약에 쓰이는 증명서입니다. 용도에 따라 서식이 달라 창구에서 용도를 정확히 말씀해 주세요.",
    facilityId: "f1-counter-1",
    place: "1층 종합민원실 1번 창구",
    floor: 1,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "인감 도장", required: false, note: "신규 등록 또는 변경 시" },
      { label: "위임장", required: false, note: "대리 발급 시 본인 자필 서명 필요" },
    ],
    steps: [
      { title: "번호표 발급", desc: "인감 항목을 선택합니다." },
      { title: "대기", desc: "본인 확인 절차가 있어 다른 증명서보다 조금 더 걸립니다." },
      { title: "창구 방문", desc: "부동산 매도용인지 일반용인지 알려 주세요." },
      { title: "본인 확인", desc: "신분증 대조와 서명을 진행합니다." },
      { title: "서류 수령", desc: "매도용은 매수자 정보가 포함되어 발급됩니다." },
    ],
    duration: "약 10분",
    fee: "600원",
    kiosk: { available: false, note: "본인 확인 절차가 필요해 창구에서만 발급됩니다." },
    related: ["resident-copy", "family-cert"],
    rating: { avg: 4.3, count: 405 },
    popular: true,
    keywords: ["인감", "매도용", "도장"],
  },
  {
    id: "move-in",
    name: "전입신고",
    short: "전입신고",
    category: "주민 / 등록",
    icon: "resident",
    desc: "이사한 날부터 14일 이내에 신고해야 합니다. 기한을 넘기면 과태료가 부과될 수 있습니다.",
    facilityId: "f1-counter-3",
    place: "1층 종합민원실 3번 창구",
    floor: 1,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "신고인 신분증", required: true },
      { label: "세대주 도장 또는 서명", required: false, note: "기존 세대에 들어가는 경우" },
      { label: "임대차계약서", required: false, note: "확정일자를 함께 받을 때" },
    ],
    steps: [
      { title: "번호표 발급", desc: "전입 항목을 선택합니다." },
      { title: "신고서 작성", desc: "창구 옆 작성대에서 새 주소를 기재합니다." },
      { title: "창구 방문", desc: "3번 창구에서 세대 구성 방식을 정합니다." },
      { title: "확정일자 신청", desc: "임대차계약서를 함께 내면 같은 자리에서 처리됩니다." },
      { title: "처리 완료", desc: "우편물 이전 서비스 신청 여부를 확인합니다." },
    ],
    duration: "약 12분",
    fee: "무료",
    feeNote: "확정일자 부여는 600원",
    kiosk: { available: false, note: "세대 구성 확인이 필요해 창구에서만 접수합니다." },
    related: ["resident-copy", "resident-abstract"],
    rating: { avg: 4.6, count: 522 },
    popular: false,
    keywords: ["전입", "이사", "확정일자"],
  },
  {
    id: "tax-payment",
    name: "지방세 납부확인서 발급",
    short: "지방세 납부확인서",
    category: "세무",
    icon: "tax",
    desc: "재산세, 자동차세 등 지방세 납부 내역을 증명합니다. 대출과 입찰 서류로 자주 쓰입니다.",
    facilityId: "f2-counter-7",
    place: "2층 세무과 7번 창구",
    floor: 2,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "사업자등록증", required: false, note: "법인 또는 사업자 명의 발급 시" },
    ],
    steps: [
      { title: "번호표 발급", desc: "2층 여권민원실 입구 발급기에서 세무 항목을 선택합니다." },
      { title: "창구 방문", desc: "7번 창구에서 필요한 과세 연도를 알려 주세요." },
      { title: "서류 수령", desc: "연도별로 나누어 발급받을 수 있습니다." },
    ],
    duration: "약 6분",
    fee: "무료",
    kiosk: { available: true, note: "무인민원발급기에서도 발급되며 수수료가 없습니다." },
    related: ["building-cert", "land-cert"],
    rating: { avg: 4.5, count: 288 },
    popular: false,
    keywords: ["지방세", "납부확인서", "세금"],
  },
  {
    id: "building-cert",
    name: "건축물대장 발급",
    short: "건축물대장",
    category: "건축 / 토지",
    icon: "land",
    desc: "건물의 면적, 구조, 용도가 기재된 공적 장부입니다. 총괄표제부와 전유부 중 필요한 종류를 확인하세요.",
    facilityId: "f3-counter-8",
    place: "3층 건축과 8번 창구",
    floor: 3,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "건물 주소", required: true, note: "지번 또는 도로명 주소" },
    ],
    steps: [
      { title: "창구 방문", desc: "8번 창구는 번호표 없이 바로 접수합니다." },
      { title: "종류 선택", desc: "총괄표제부, 표제부, 전유부 중에서 고릅니다." },
      { title: "서류 수령", desc: "발급 후 면적과 용도를 확인하세요." },
    ],
    duration: "약 8분",
    fee: "500원",
    feeNote: "전유부는 1건당 300원",
    kiosk: { available: true, note: "1층 무인민원발급기에서도 발급됩니다." },
    related: ["land-cert", "tax-payment"],
    rating: { avg: 4.2, count: 197 },
    popular: false,
    keywords: ["건축물대장", "건물", "면적"],
  },
  {
    id: "land-cert",
    name: "토지대장 발급",
    short: "토지대장",
    category: "건축 / 토지",
    icon: "land",
    desc: "토지의 지목, 면적, 소유자 변동이 기재된 장부입니다. 지적도는 별도로 신청해야 합니다.",
    facilityId: "f3-land",
    place: "3층 토지정보과 305호",
    floor: 3,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "토지 지번", required: true },
    ],
    steps: [
      { title: "사무실 방문", desc: "305호 접수 창구에서 신청서를 작성합니다." },
      { title: "열람 또는 발급 선택", desc: "열람만 필요하면 306호 열람실을 이용하세요." },
      { title: "서류 수령", desc: "지적도가 함께 필요하면 같은 자리에서 신청합니다." },
    ],
    duration: "약 10분",
    fee: "500원",
    feeNote: "지적도 등본은 1건당 700원",
    kiosk: { available: true, note: "1층 무인민원발급기에서 토지대장만 발급됩니다." },
    related: ["building-cert", "tax-payment"],
    rating: { avg: 4.1, count: 154 },
    popular: false,
    keywords: ["토지대장", "지적도", "지번"],
  },
  {
    id: "car-tax",
    name: "자동차 등록원부 발급",
    short: "자동차 등록원부",
    category: "세무",
    icon: "car",
    desc: "차량 소유 이력과 저당 설정 여부를 확인하는 서류입니다. 중고 거래 시 갑부와 을부를 함께 확인하세요.",
    facilityId: "f2-counter-7",
    place: "2층 세무과 7번 창구",
    floor: 2,
    hours: "평일 09:00 ~ 18:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "차량번호", required: true },
    ],
    steps: [
      { title: "번호표 발급", desc: "2층 발급기에서 세무 항목을 선택합니다." },
      { title: "창구 방문", desc: "갑부와 을부 중 필요한 것을 말씀하세요." },
      { title: "서류 수령", desc: "저당 설정 여부는 을부에 표시됩니다." },
    ],
    duration: "약 6분",
    fee: "300원",
    kiosk: { available: true, note: "무인민원발급기에서 갑부만 발급됩니다." },
    related: ["tax-payment", "resident-copy"],
    rating: { avg: 4.3, count: 231 },
    popular: false,
    keywords: ["자동차", "등록원부", "저당"],
  },
  {
    id: "welfare-consult",
    name: "복지 상담 신청",
    short: "복지 상담",
    category: "복지",
    icon: "welfare",
    desc: "기초생활보장, 긴급복지, 돌봄 서비스를 한 자리에서 상담합니다. 예약자 우선이며 현장 접수도 가능합니다.",
    facilityId: "f2-welfare",
    place: "2층 복지정책과 201호",
    floor: 2,
    hours: "평일 09:00 ~ 17:00",
    closed: "토요일, 일요일, 공휴일 휴무",
    docs: [
      { label: "본인 신분증", required: true },
      { label: "소득 증빙 자료", required: false, note: "급여명세서, 건강보험 납부확인서 등" },
      { label: "가족관계증명서", required: false, note: "부양가족 관련 상담 시" },
    ],
    steps: [
      { title: "사무실 방문", desc: "201호 접수대에서 상담 신청서를 작성합니다." },
      { title: "대기", desc: "예약자 상담이 먼저 진행됩니다." },
      { title: "상담", desc: "담당 주무관과 20분에서 30분 상담합니다." },
      { title: "후속 안내", desc: "필요한 신청 서류와 접수 일정을 안내받습니다." },
    ],
    duration: "약 30분",
    fee: "무료",
    kiosk: { available: false, note: "상담 업무라 무인 처리 대상이 아닙니다." },
    related: ["family-cert", "resident-copy"],
    rating: { avg: 4.8, count: 176 },
    popular: false,
    keywords: ["복지", "상담", "긴급지원"],
  },
];

export const NOTICES: Notice[] = [
  {
    id: "n1",
    tone: "warning",
    title: "8월 15일 광복절 휴무",
    body: "8월 15일 토요일은 공휴일로 전 창구가 운영하지 않습니다. 무인민원발급기는 09:00부터 18:00까지 이용할 수 있습니다.",
  },
  {
    id: "n2",
    tone: "info",
    title: "여권민원실 점심시간 교대 운영",
    body: "12:00부터 13:00까지 5번 창구만 운영합니다. 대기 시간이 평소보다 길어질 수 있습니다.",
  },
];

/** Dashboard-style numbers shown on the lobby screen. */
export const LIVE_STATUS = {
  waitingTotal: 22,
  busiestCounter: "2번 창구",
  busiestWait: "약 18분",
  quietCounter: "4번 창구",
  quietWait: "대기 없음",
  kioskFree: 2,
  kioskTotal: 2,
  parkingFree: 47,
  parkingTotal: 180,
};

export function facilityById(id: string): Facility | undefined {
  return FACILITIES.find((f) => f.id === id);
}

export function serviceById(id: string): Service | undefined {
  return SERVICES.find((s) => s.id === id);
}

export function facilitiesOnFloor(floor: FloorId): Facility[] {
  return FACILITIES.filter((f) => f.floor === floor);
}

export function floorById(id: FloorId): Floor {
  return FLOORS.find((f) => f.id === id) ?? FLOORS[0];
}

export function servicesAtFacility(facilityId: string): Service[] {
  return SERVICES.filter((s) => s.facilityId === facilityId);
}

export function searchServices(query: string): Service[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return SERVICES.filter((s) =>
    [s.name, s.short, s.category, s.place, ...s.keywords].some((v) =>
      v.toLowerCase().includes(q)
    )
  );
}
