import type {
  BasicCorrection,
  HslBand,
  Recipe,
  ToneCurves,
} from "@/projects/camera/colorrecipe/lib/types";

function picsum(seed: string, w: number, h: number) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export function flatBasic(overrides: Partial<BasicCorrection> = {}): BasicCorrection {
  return {
    brightness: 0,
    contrast: 0,
    exposure: 0,
    saturation: 0,
    vibrance: 0,
    temperature: 0,
    tint: 0,
    highlights: 0,
    shadows: 0,
    whites: 0,
    blacks: 0,
    ...overrides,
  };
}

const HSL_BAND_META: { id: string; label: string; swatch: string }[] = [
  { id: "red", label: "빨강", swatch: "#F2555F" },
  { id: "orange", label: "주황", swatch: "#F2934A" },
  { id: "yellow", label: "노랑", swatch: "#E8D24D" },
  { id: "green", label: "초록", swatch: "#5FC271" },
  { id: "aqua", label: "아쿠아", swatch: "#4DD8D0" },
  { id: "blue", label: "파랑", swatch: "#4E9BF2" },
  { id: "purple", label: "보라", swatch: "#9169E8" },
  { id: "magenta", label: "마젠타", swatch: "#E866B8" },
];

export function flatHsl(overrides: Record<string, Partial<Omit<HslBand, "id" | "label" | "swatch">>> = {}): HslBand[] {
  return HSL_BAND_META.map((meta) => ({
    ...meta,
    hue: 0,
    saturation: 0,
    luminance: 0,
    ...overrides[meta.id],
  }));
}

export function flatCurves(
  overrides: Partial<Record<keyof ToneCurves, ToneCurves["rgb"]>> = {},
): ToneCurves {
  const identity = [
    { x: 0, y: 0 },
    { x: 50, y: 50 },
    { x: 100, y: 100 },
  ];
  return {
    rgb: overrides.rgb ?? identity,
    r: overrides.r ?? identity,
    g: overrides.g ?? identity,
    b: overrides.b ?? identity,
  };
}

export const recipes: Recipe[] = [
  {
    id: "clean-daily",
    name: "클린 데일리",
    tagline: "손대지 않은 듯 자연스럽게",
    description:
      "채도와 대비를 절제해 원본에 가까운 톤을 유지하면서 하이라이트만 살짝 눌러줍니다. 매일 찍는 일상 기록에 무난하게 어울리는 기본 레시피입니다.",
    category: "데일리",
    tags: ["자연광", "일상", "무보정 느낌"],
    source: "official",
    favorite: true,
    usageCount: 482,
    lastUsedAt: "2023.10.29 08:12",
    lutIntensity: 62,
    heroSeed: "colorrecipe-cafe-morning-flatlay",
    sampleSeeds: ["colorrecipe-portrait-window-light", "colorrecipe-flower-field-pastel"],
    palette: ["#E4DED2", "#B9AE98", "#7C7264", "#3C3833", "#F2EEE4"],
    colorGrade: {
      filter: "saturate(1.02) contrast(1.02) brightness(1.01)",
      grain: 0.05,
      vignette: 0.04,
    },
    basic: flatBasic({ contrast: 6, highlights: -8, whites: 4 }),
    hsl: flatHsl(),
    curves: flatCurves(),
    optical: {
      bloomEnabled: false,
      bloomIntensity: 0,
      bloomThreshold: 70,
      grainEnabled: true,
      grainSize: 20,
      grainIntensity: 12,
      vignetteEnabled: true,
      vignetteIntensity: 10,
      vignetteFeather: 60,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 15,
      fade: 0,
      noise: 0,
      chromaticAberration: 0,
    },
  },
  {
    id: "cinema-teal-orange",
    name: "시네마 틸앤오렌지",
    tagline: "스크린 속 한 장면처럼",
    description:
      "쉐도우는 틸로 하이라이트는 오렌지로 갈라지는 클래식 시네마틱 스플릿톤. 해질녘 도심과 자동차 라이트 트레일을 극적으로 담아냅니다.",
    category: "시네마틱",
    tags: ["틸앤오렌지", "도심 야경", "고대비"],
    source: "official",
    favorite: true,
    usageCount: 356,
    lastUsedAt: "2023.10.28 19:47",
    lutIntensity: 78,
    heroSeed: "colorrecipe-city-dusk-avenue",
    sampleSeeds: ["colorrecipe-neon-alley-night", "colorrecipe-old-town-brick-street"],
    palette: ["#E0793C", "#1F5C63", "#F2B36B", "#12262B", "#8C4A2A"],
    colorGrade: {
      filter: "saturate(1.14) contrast(1.16) brightness(0.98)",
      overlayGradient:
        "linear-gradient(200deg, rgba(18,60,66,0.34), rgba(230,146,74,0.26) 100%)",
      overlayBlend: "soft-light",
      grain: 0.24,
      vignette: 0.22,
    },
    basic: flatBasic({
      contrast: 22,
      exposure: -4,
      saturation: 8,
      shadows: -12,
      blacks: -8,
    }),
    hsl: flatHsl({
      orange: { hue: 4, saturation: 12, luminance: 6 },
      aqua: { hue: -6, saturation: 18, luminance: -8 },
      blue: { hue: -4, saturation: 10, luminance: -10 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: 6 },
        { x: 50, y: 46 },
        { x: 100, y: 96 },
      ],
    }),
    optical: {
      bloomEnabled: true,
      bloomIntensity: 32,
      bloomThreshold: 62,
      grainEnabled: true,
      grainSize: 32,
      grainIntensity: 28,
      vignetteEnabled: true,
      vignetteIntensity: 34,
      vignetteFeather: 48,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 20,
      fade: 8,
      noise: 4,
      chromaticAberration: 12,
    },
  },
  {
    id: "soft-portrait",
    name: "소프트 포트레이트",
    tagline: "크리미한 피부 톤의 정석",
    description:
      "낮은 대비와 따뜻한 하이라이트로 인물의 피부 톤을 부드럽게 표현합니다. 역광 창가 인물컷에서 특히 자연스러운 결과를 냅니다.",
    category: "인물",
    tags: ["역광 인물", "크리미 톤", "저대비"],
    source: "official",
    favorite: false,
    usageCount: 271,
    lastUsedAt: "2023.10.27 15:03",
    lutIntensity: 55,
    heroSeed: "colorrecipe-portrait-window-light",
    sampleSeeds: ["colorrecipe-cafe-morning-flatlay", "colorrecipe-flower-field-pastel"],
    palette: ["#E9C9B4", "#D6A98D", "#B98671", "#F4E6D8", "#6B4A3A"],
    colorGrade: {
      filter: "saturate(0.9) contrast(0.9) brightness(1.06) sepia(0.06)",
      overlayGradient:
        "linear-gradient(160deg, rgba(217,168,143,0.24), rgba(217,168,143,0) 62%)",
      overlayBlend: "soft-light",
      grain: 0.1,
      vignette: 0.06,
    },
    basic: flatBasic({
      contrast: -10,
      exposure: 6,
      temperature: 10,
      highlights: -6,
      shadows: 10,
      vibrance: 8,
    }),
    hsl: flatHsl({
      red: { hue: -4, saturation: -8, luminance: 6 },
      orange: { hue: -2, saturation: -6, luminance: 8 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: 8 },
        { x: 50, y: 52 },
        { x: 100, y: 96 },
      ],
    }),
    optical: {
      bloomEnabled: true,
      bloomIntensity: 18,
      bloomThreshold: 55,
      grainEnabled: true,
      grainSize: 14,
      grainIntensity: 8,
      vignetteEnabled: true,
      vignetteIntensity: 12,
      vignetteFeather: 70,
      softFocusEnabled: true,
      softFocusBlur: 22,
      softFocusGlow: 30,
      sharpen: 5,
      fade: 6,
      noise: 0,
      chromaticAberration: 0,
    },
  },
  {
    id: "mono-contrast",
    name: "모노 콘트라스트",
    tagline: "빛과 그림자만 남기다",
    description:
      "높은 대비의 하이컨트라스트 흑백 룩입니다. 굵은 그레인이 거리 다큐멘터리 사진의 질감을 극적으로 강조합니다.",
    category: "모노",
    tags: ["흑백", "하이콘트라스트", "다큐"],
    source: "official",
    favorite: false,
    usageCount: 198,
    lastUsedAt: "2023.10.24 14:02",
    lutIntensity: 90,
    heroSeed: "colorrecipe-street-portrait-mono",
    sampleSeeds: ["colorrecipe-neon-alley-night", "colorrecipe-old-town-brick-street"],
    palette: ["#F5F5F0", "#B8B8B0", "#7A7A72", "#3A3A36", "#121210"],
    colorGrade: {
      filter: "grayscale(1) contrast(1.3) brightness(1.02)",
      grain: 0.4,
      vignette: 0.26,
    },
    basic: flatBasic({ contrast: 30, saturation: -100, blacks: -16, whites: 10 }),
    hsl: flatHsl(),
    curves: flatCurves({
      rgb: [
        { x: 0, y: -8 },
        { x: 50, y: 48 },
        { x: 100, y: 104 },
      ],
    }),
    optical: {
      bloomEnabled: false,
      bloomIntensity: 0,
      bloomThreshold: 70,
      grainEnabled: true,
      grainSize: 46,
      grainIntensity: 46,
      vignetteEnabled: true,
      vignetteIntensity: 30,
      vignetteFeather: 50,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 34,
      fade: 0,
      noise: 6,
      chromaticAberration: 0,
    },
  },
  {
    id: "vintage-paper",
    name: "빈티지 페이퍼",
    tagline: "바랜 인화지의 온기",
    description:
      "채도를 낮추고 화이트를 들어 올려 오래된 인화지 같은 색바램을 표현합니다. 유럽풍 골목이나 오브젝트 스냅에 잘 어울립니다.",
    category: "빈티지",
    tags: ["색바램", "페이드", "따뜻한 그레인"],
    source: "official",
    favorite: false,
    usageCount: 143,
    lastUsedAt: "2023.10.20 11:35",
    lutIntensity: 68,
    heroSeed: "colorrecipe-old-town-brick-street",
    sampleSeeds: ["colorrecipe-cafe-morning-flatlay", "colorrecipe-mountain-pine-forest"],
    palette: ["#D8C7A8", "#B79A72", "#8A6B4B", "#F2E6CE", "#4A3B2C"],
    colorGrade: {
      filter: "saturate(0.78) contrast(0.88) brightness(1.05) sepia(0.18)",
      overlayGradient:
        "linear-gradient(160deg, rgba(200,168,120,0.28), rgba(200,168,120,0) 60%)",
      overlayBlend: "soft-light",
      grain: 0.3,
      vignette: 0.18,
    },
    basic: flatBasic({
      contrast: -12,
      saturation: -18,
      temperature: 14,
      whites: -10,
      blacks: 14,
    }),
    hsl: flatHsl({
      yellow: { hue: 2, saturation: -10, luminance: 8 },
      green: { hue: -4, saturation: -14, luminance: 4 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: 14 },
        { x: 50, y: 50 },
        { x: 100, y: 90 },
      ],
    }),
    optical: {
      bloomEnabled: false,
      bloomIntensity: 0,
      bloomThreshold: 70,
      grainEnabled: true,
      grainSize: 40,
      grainIntensity: 30,
      vignetteEnabled: true,
      vignetteIntensity: 20,
      vignetteFeather: 55,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 8,
      fade: 26,
      noise: 8,
      chromaticAberration: 0,
    },
  },
  {
    id: "neon-night",
    name: "네온 나잇",
    tagline: "도시의 불빛을 머금다",
    description:
      "쿨 블루와 마젠타를 강조해 네온 간판이 있는 야간 골목의 분위기를 극적으로 살립니다. 채도와 대비를 함께 올려 선명한 도시 야경을 만듭니다.",
    category: "시네마틱",
    tags: ["네온", "야간", "블루 마젠타"],
    source: "official",
    favorite: true,
    usageCount: 227,
    lastUsedAt: "2023.10.26 21:18",
    lutIntensity: 74,
    heroSeed: "colorrecipe-neon-alley-night",
    sampleSeeds: ["colorrecipe-city-dusk-avenue", "colorrecipe-street-portrait-mono"],
    palette: ["#3E5CE8", "#E85CC7", "#1A1F3A", "#8C6BE8", "#0D0E1A"],
    colorGrade: {
      filter: "saturate(1.2) contrast(1.15) brightness(0.96) hue-rotate(-4deg)",
      overlayGradient:
        "linear-gradient(200deg, rgba(62,92,232,0.3), rgba(232,92,199,0.24) 100%)",
      overlayBlend: "screen",
      grain: 0.2,
      vignette: 0.28,
    },
    basic: flatBasic({ contrast: 18, exposure: -6, saturation: 14, shadows: -18 }),
    hsl: flatHsl({
      blue: { hue: -6, saturation: 20, luminance: 4 },
      purple: { hue: 4, saturation: 16, luminance: 6 },
      magenta: { hue: -4, saturation: 18, luminance: 8 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: 4 },
        { x: 50, y: 44 },
        { x: 100, y: 98 },
      ],
    }),
    optical: {
      bloomEnabled: true,
      bloomIntensity: 46,
      bloomThreshold: 48,
      grainEnabled: true,
      grainSize: 24,
      grainIntensity: 18,
      vignetteEnabled: true,
      vignetteIntensity: 38,
      vignetteFeather: 42,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 12,
      fade: 0,
      noise: 2,
      chromaticAberration: 22,
    },
  },
  {
    id: "pastel-dream",
    name: "파스텔 드림",
    tagline: "낮은 채도의 부드러운 공기",
    description:
      "전반적인 채도를 낮추고 화이트를 부드럽게 밀어 올려 뿌연 파스텔 톤을 만듭니다. 들꽃밭처럼 연한 색이 많은 장면에 어울립니다.",
    category: "인물",
    tags: ["파스텔", "로우 채도", "헤이즈"],
    source: "user",
    favorite: true,
    usageCount: 89,
    lastUsedAt: "2023.10.29 10:44",
    lutIntensity: 48,
    heroSeed: "colorrecipe-flower-field-pastel",
    sampleSeeds: ["colorrecipe-portrait-window-light", "colorrecipe-cafe-morning-flatlay"],
    palette: ["#F2D9DE", "#D9C7E8", "#C9E0DC", "#F5EDE4", "#8C7B8A"],
    colorGrade: {
      filter: "saturate(0.72) contrast(0.86) brightness(1.08)",
      overlayGradient:
        "linear-gradient(160deg, rgba(242,217,222,0.3), rgba(217,199,232,0.2) 100%)",
      overlayBlend: "soft-light",
      grain: 0.06,
      vignette: 0.02,
    },
    basic: flatBasic({
      contrast: -16,
      exposure: 8,
      saturation: -22,
      whites: 12,
      blacks: 8,
    }),
    hsl: flatHsl({
      red: { hue: 2, saturation: -16, luminance: 10 },
      purple: { hue: -2, saturation: -12, luminance: 8 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: 16 },
        { x: 50, y: 54 },
        { x: 100, y: 92 },
      ],
    }),
    optical: {
      bloomEnabled: true,
      bloomIntensity: 24,
      bloomThreshold: 60,
      grainEnabled: false,
      grainSize: 10,
      grainIntensity: 0,
      vignetteEnabled: false,
      vignetteIntensity: 0,
      vignetteFeather: 60,
      softFocusEnabled: true,
      softFocusBlur: 16,
      softFocusGlow: 22,
      sharpen: 0,
      fade: 14,
      noise: 0,
      chromaticAberration: 0,
    },
  },
  {
    id: "deep-forest",
    name: "딥 포레스트",
    tagline: "짙은 초록의 무게감",
    description:
      "초록과 틸 계열을 깊게 눌러주고 대비를 강하게 살려 침엽수 산림처럼 무거운 풍경에 극적인 밀도를 더합니다.",
    category: "풍경",
    tags: ["숲", "딥그린", "무드"],
    source: "user",
    favorite: false,
    usageCount: 64,
    lastUsedAt: "2023.10.18 07:52",
    lutIntensity: 70,
    heroSeed: "colorrecipe-mountain-pine-forest",
    sampleSeeds: ["colorrecipe-old-town-brick-street", "colorrecipe-street-portrait-mono"],
    palette: ["#2F4A3A", "#1B2E24", "#6B8C74", "#0F1A14", "#A8B89C"],
    colorGrade: {
      filter: "saturate(1.08) contrast(1.12) brightness(0.94) hue-rotate(6deg)",
      overlayGradient:
        "linear-gradient(180deg, rgba(15,26,20,0.32), rgba(15,26,20,0) 55%)",
      overlayBlend: "multiply",
      grain: 0.22,
      vignette: 0.24,
    },
    basic: flatBasic({
      contrast: 16,
      exposure: -8,
      saturation: 6,
      shadows: -16,
      blacks: -10,
    }),
    hsl: flatHsl({
      green: { hue: -8, saturation: 10, luminance: -10 },
      aqua: { hue: -4, saturation: 8, luminance: -6 },
    }),
    curves: flatCurves({
      rgb: [
        { x: 0, y: -4 },
        { x: 50, y: 42 },
        { x: 100, y: 94 },
      ],
    }),
    optical: {
      bloomEnabled: false,
      bloomIntensity: 0,
      bloomThreshold: 70,
      grainEnabled: true,
      grainSize: 30,
      grainIntensity: 22,
      vignetteEnabled: true,
      vignetteIntensity: 32,
      vignetteFeather: 46,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 22,
      fade: 0,
      noise: 4,
      chromaticAberration: 0,
    },
  },
];

export function getRecipe(id: string) {
  return recipes.find((r) => r.id === id);
}

export function recipesByCategory(category: string) {
  return recipes.filter((r) => r.category === category);
}

export const categories: Recipe["category"][] = [
  "데일리",
  "인물",
  "풍경",
  "시네마틱",
  "빈티지",
  "모노",
];

export function recipeThumb(seed: string, size = 400) {
  return picsum(seed, size, size);
}

export function blankRecipe(): Recipe {
  return {
    id: `user-${Date.now()}`,
    name: "",
    tagline: "",
    description: "",
    category: "데일리",
    tags: [],
    source: "user",
    favorite: false,
    usageCount: 0,
    lastUsedAt: "",
    lutIntensity: 80,
    heroSeed: "colorrecipe-cafe-morning-flatlay",
    sampleSeeds: [],
    palette: ["#8B93A1", "#565C66", "#F2F4F6", "#262A31", "#4DE8FF"],
    colorGrade: { filter: "none", grain: 0, vignette: 0 },
    basic: flatBasic(),
    hsl: flatHsl(),
    curves: flatCurves(),
    optical: {
      bloomEnabled: false,
      bloomIntensity: 0,
      bloomThreshold: 60,
      grainEnabled: false,
      grainSize: 20,
      grainIntensity: 0,
      vignetteEnabled: false,
      vignetteIntensity: 0,
      vignetteFeather: 60,
      softFocusEnabled: false,
      softFocusBlur: 0,
      softFocusGlow: 0,
      sharpen: 0,
      fade: 0,
      noise: 0,
      chromaticAberration: 0,
    },
  };
}
