import type {
  Badge,
  Library,
  Mission,
  MonthStat,
  ReadLog,
  RecommendedBook,
  Reward,
  Stamp,
  TimelineEntry,
} from "./types";

/*
 * 사진은 전부 picsum 고정 id. 아래 표의 설명은 실제 사진을 눈으로 확인하고 적은 것이므로
 * id를 바꿀 때는 반드시 다시 확인한다. design.md의 "사진 매핑" 절과 1:1로 대응한다.
 *
 *   618  유리 격자 돔 천장의 대형 공공건물 아트리움
 *   192  큰 통창 앞에 앉은 사람들 실루엣, 흑백
 *   625  흰 벽의 밝은 방에 놓인 원목 테이블과 흰 의자 네 개
 *   208  어두운 실내에서 초록 나무가 보이는 격자 창
 *   946  노란 벽돌 건물의 초록 현관문과 창가 화분
 *    42  창가에 긴 원목 테이블이 놓인 밝은 실내
 *   635  원목 작업대 위에 늘어놓은 머그와 도자기
 *   513  밝은 창가에서 마주 앉아 이야기하는 두 사람
 *  1073  펼쳐진 책들이 벽면을 가득 채운 모습
 *    24  따뜻한 톤으로 펼쳐진 두꺼운 책 클로즈업
 *   832  어두운 실내에서 책을 읽는 여성
 *   998  끈으로 묶인 낡은 책 묶음과 만년필, 오래된 사진
 *   882  붉은 타일 바닥 카페에서 커피를 두고 잡지를 읽는 사람
 *   365  침대 위에 펼쳐진 책과 찻잔, 마른 꽃
 *   464  원목 테이블 위에 펼쳐진 사진집과 카메라
 *    20  책상 위 노트와 컬러 도표가 실린 잡지, 색연필
 *   504  원목 테이블에서 스마트폰을 든 손
 */
export function photo(id: number, w: number, h: number) {
  return `https://picsum.photos/id/${id}/${w}/${h}`;
}

export const USER = {
  name: "이윤재",
  nickname: "윤재",
  joinedAt: "2025년 11월 3일",
  joinedShort: "2025.11.03",
  homeDistrict: "기흥구",
  level: "은잎 독서가",
  levelStep: 3,
  levelTotal: 5,
  nextLevel: "금잎 독서가",
  nextLevelNeed: 4,
  cardNo: "YI-2025-004182",
  totalVisits: 27,
  totalReads: 31,
  totalStamps: 58,
};

export const THIS_MONTH = {
  label: "2026년 8월",
  short: "8월",
  today: "8월 7일 금요일",
  visitedLibraries: 4,
  visitedGoal: 8,
  reads: 6,
  readsGoal: 10,
  badges: 2,
  daysLeft: 24,
  rankPercent: 12,
};

export const LIBRARIES: Library[] = [
  {
    id: "central",
    name: "용인중앙도서관",
    short: "중앙",
    district: "처인구",
    address: "경기 용인시 처인구 중부대로 1199",
    tel: "031-324-4800",
    distanceKm: 8.4,
    photoId: 618,
    photoAlt: "유리 격자 돔 천장 아래 밝은 아트리움",
    map: { x: 62, y: 58 },
    hours: {
      weekday: "09:00 - 22:00",
      weekend: "09:00 - 18:00",
      closed: "매월 둘째, 넷째 월요일",
    },
    facilities: [
      "종합자료실",
      "어린이자료실",
      "디지털자료실",
      "스터디룸",
      "문화프로그램실",
      "장애인 편의시설",
      "수유실",
    ],
    qrSpot: "1층 중앙 로비 안내데스크 옆 기둥",
    programs: [
      {
        id: "p-central-1",
        title: "여름 밤의 인문학 강좌",
        period: "8월 12일 - 9월 16일 매주 수요일",
        target: "성인",
        slots: "정원 40명 중 12명 남음",
        status: "모집중",
      },
      {
        id: "p-central-2",
        title: "어린이 그림책 놀이터",
        period: "8월 매주 토요일 10:30",
        target: "6세 - 9세",
        slots: "정원 20명 마감",
        status: "대기접수",
      },
      {
        id: "p-central-3",
        title: "시니어 큰글자책 낭독 모임",
        period: "8월 11일 - 10월 6일 매주 화요일",
        target: "65세 이상",
        slots: "정원 15명 중 9명 남음",
        status: "모집중",
      },
    ],
    visited: true,
    visitCount: 9,
    lastVisitedAt: "8월 2일",
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "guteun",
    name: "구갈희망누리도서관",
    short: "구갈",
    district: "기흥구",
    address: "경기 용인시 기흥구 구갈로 63",
    tel: "031-324-8720",
    distanceKm: 1.2,
    photoId: 192,
    photoAlt: "큰 통창 앞에 앉아 책을 보는 사람들",
    map: { x: 38, y: 44 },
    hours: {
      weekday: "09:00 - 20:00",
      weekend: "09:00 - 17:00",
      closed: "매주 월요일",
    },
    facilities: ["종합자료실", "어린이자료실", "노트북존", "장애인 편의시설"],
    qrSpot: "출입구 자동문 안쪽 게시판",
    programs: [
      {
        id: "p-guteun-1",
        title: "동네책방과 함께 읽기",
        period: "8월 9일 - 8월 30일 매주 일요일",
        target: "청소년 / 성인",
        slots: "정원 18명 중 5명 남음",
        status: "모집중",
      },
      {
        id: "p-guteun-2",
        title: "다문화가정 한글 그림책 교실",
        period: "8월 13일 - 9월 24일 매주 목요일",
        target: "초등 저학년 및 보호자",
        slots: "정원 12명 중 7명 남음",
        status: "모집중",
      },
    ],
    visited: true,
    visitCount: 6,
    lastVisitedAt: "8월 6일",
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "giheung",
    name: "기흥도서관",
    short: "기흥",
    district: "기흥구",
    address: "경기 용인시 기흥구 신정로 65",
    tel: "031-324-8300",
    distanceKm: 3.6,
    photoId: 625,
    photoAlt: "흰 벽의 밝은 방에 놓인 원목 테이블과 의자",
    map: { x: 30, y: 62 },
    hours: {
      weekday: "09:00 - 22:00",
      weekend: "09:00 - 18:00",
      closed: "매월 첫째, 셋째 월요일",
    },
    facilities: ["종합자료실", "어린이자료실", "스터디룸", "디지털자료실", "수유실"],
    qrSpot: "2층 종합자료실 입구 벽면",
    programs: [
      {
        id: "p-giheung-1",
        title: "주말 가족 독서 토론",
        period: "8월 16일, 8월 30일 14:00",
        target: "초등 3학년 이상 가족",
        slots: "정원 10가족 중 3가족 남음",
        status: "모집중",
      },
    ],
    visited: true,
    visitCount: 5,
    lastVisitedAt: "7월 28일",
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "suji",
    name: "수지도서관",
    short: "수지",
    district: "수지구",
    address: "경기 용인시 수지구 풍덕천로 88",
    tel: "031-324-8600",
    distanceKm: 9.7,
    photoId: 208,
    photoAlt: "초록 나무가 보이는 격자 창가 열람 공간",
    map: { x: 22, y: 24 },
    hours: {
      weekday: "09:00 - 22:00",
      weekend: "09:00 - 18:00",
      closed: "매월 둘째, 넷째 월요일",
    },
    facilities: ["종합자료실", "어린이자료실", "북카페", "야외독서마당", "장애인 편의시설"],
    qrSpot: "1층 야외독서마당 출입구 옆",
    programs: [
      {
        id: "p-suji-1",
        title: "숲속 낭독회",
        period: "8월 22일 17:00 야외독서마당",
        target: "전 연령",
        slots: "현장 참여 자유",
        status: "모집중",
      },
      {
        id: "p-suji-2",
        title: "청소년 진로 독서 워크숍",
        period: "8월 18일 - 8월 25일",
        target: "중학생",
        slots: "정원 16명 마감",
        status: "마감",
      },
    ],
    visited: true,
    visitCount: 4,
    lastVisitedAt: "7월 19일",
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "cheoin",
    name: "처인도서관",
    short: "처인",
    district: "처인구",
    address: "경기 용인시 처인구 금학로 265",
    tel: "031-324-4930",
    distanceKm: 11.3,
    photoId: 946,
    photoAlt: "노란 벽돌 건물의 초록 현관문과 창가 화분",
    map: { x: 74, y: 74 },
    hours: {
      weekday: "09:00 - 18:00",
      weekend: "09:00 - 17:00",
      closed: "매주 월요일",
    },
    facilities: ["종합자료실", "어린이자료실", "장애인 편의시설"],
    qrSpot: "현관 출입문 오른쪽 벽면",
    programs: [
      {
        id: "p-cheoin-1",
        title: "농한기 어르신 큰글자책 사랑방",
        period: "8월 10일 - 11월 30일 매주 월요일 제외",
        target: "65세 이상",
        slots: "상시 운영",
        status: "모집중",
      },
    ],
    visited: false,
    visitCount: 0,
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: true,
  },
  {
    id: "heungdeok",
    name: "흥덕도서관",
    short: "흥덕",
    district: "기흥구",
    address: "경기 용인시 기흥구 흥덕중앙로 120",
    tel: "031-324-8930",
    distanceKm: 4.9,
    photoId: 42,
    photoAlt: "창가에 긴 원목 테이블이 놓인 밝은 열람실",
    map: { x: 44, y: 34 },
    hours: {
      weekday: "09:00 - 22:00",
      weekend: "09:00 - 18:00",
      closed: "매월 둘째, 넷째 월요일",
    },
    facilities: ["종합자료실", "북카페", "노트북존", "스터디룸", "디지털자료실"],
    qrSpot: "3층 북카페 카운터 옆",
    programs: [
      {
        id: "p-heungdeok-1",
        title: "직장인 새벽 독서클럽",
        period: "8월 11일 - 9월 29일 매주 화요일 07:30",
        target: "성인",
        slots: "정원 14명 중 2명 남음",
        status: "모집중",
      },
    ],
    visited: false,
    visitCount: 0,
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "jukjeon",
    name: "죽전도서관",
    short: "죽전",
    district: "수지구",
    address: "경기 용인시 수지구 포은대로 435",
    tel: "031-324-8500",
    distanceKm: 7.1,
    photoId: 635,
    photoAlt: "원목 작업대 위에 늘어놓은 머그와 도자기",
    map: { x: 34, y: 12 },
    hours: {
      weekday: "09:00 - 20:00",
      weekend: "09:00 - 18:00",
      closed: "매주 월요일",
    },
    facilities: ["종합자료실", "문화프로그램실", "어린이자료실", "수유실"],
    qrSpot: "1층 문화프로그램실 복도 안내판",
    programs: [
      {
        id: "p-jukjeon-1",
        title: "책과 도예, 한 권 한 그릇",
        period: "8월 15일 - 9월 19일 격주 토요일",
        target: "성인",
        slots: "정원 12명 중 4명 남음",
        status: "모집중",
      },
    ],
    visited: false,
    visitCount: 0,
    opensAt: "09:00",
    isOpenNow: true,
    newBranch: false,
  },
  {
    id: "dongbaek",
    name: "동백도서관",
    short: "동백",
    district: "기흥구",
    address: "경기 용인시 기흥구 동백중앙로 191",
    tel: "031-324-8880",
    distanceKm: 6.3,
    photoId: 513,
    photoAlt: "밝은 창가에서 마주 앉아 이야기하는 두 사람",
    map: { x: 56, y: 26 },
    hours: {
      weekday: "09:00 - 20:00",
      weekend: "09:00 - 17:00",
      closed: "매주 월요일",
    },
    facilities: ["종합자료실", "어린이자료실", "북카페", "장애인 편의시설", "노트북존"],
    qrSpot: "2층 독서모임실 앞 게시판",
    programs: [
      {
        id: "p-dongbaek-1",
        title: "우리 동네 첫 독서모임",
        period: "8월 14일 - 10월 9일 매주 금요일 19:00",
        target: "성인 초심자",
        slots: "정원 10명 중 6명 남음",
        status: "모집중",
      },
    ],
    visited: false,
    visitCount: 0,
    opensAt: "09:00",
    isOpenNow: false,
    newBranch: true,
  },
];

export function getLibrary(id?: string) {
  return LIBRARIES.find((l) => l.id === id) ?? LIBRARIES[1];
}

export const MISSIONS: Mission[] = [
  {
    id: "m-recommend",
    kind: "recommend",
    label: "이달의 추천도서",
    title: "8월의 책, 여름을 건너는 문장",
    summary: "추천도서 3권 중 1권을 완독하고 인증하기",
    description:
      "용인시 도서관 사서 12명이 8월 주제로 고른 세 권입니다. 전 지점에 각각 4권 이상 배가되어 있고, 대출 중이면 예약 신청으로 순번을 잡을 수 있습니다.",
    period: "8월 1일 - 8월 31일",
    daysLeft: 24,
    progress: 1,
    goal: 1,
    unit: "권",
    reward: "완독 스탬프 2개, 추천도서 배지",
    photoId: 24,
    photoAlt: "따뜻한 조명 아래 펼쳐진 두꺼운 책",
    steps: [
      "추천도서 3권 중 읽고 싶은 책을 고릅니다",
      "가까운 지점에서 대출하거나 열람실에서 읽습니다",
      "다 읽으면 책 사진과 제목으로 완독 인증합니다",
    ],
    joined: 1842,
    books: ["b-1", "b-2", "b-3"],
  },
  {
    id: "m-theme",
    kind: "theme",
    label: "테마 미션",
    title: "밤에 읽는 한 권",
    summary: "저녁 7시 이후 완독 인증 2회 달성하기",
    description:
      "야간 개관 지점을 활용해 퇴근 후, 하교 후 독서 습관을 만드는 미션입니다. 저녁 7시부터 자정 사이에 올린 완독 인증만 집계됩니다.",
    period: "8월 1일 - 8월 31일",
    daysLeft: 24,
    progress: 1,
    goal: 2,
    unit: "회",
    reward: "테마 스탬프 1개, 야간 독서 배지",
    photoId: 832,
    photoAlt: "어두운 실내에서 조용히 책을 읽는 사람",
    steps: [
      "야간 개관 지점 4곳 중 한 곳을 확인합니다",
      "저녁 7시 이후 완독 인증을 올립니다",
      "두 번째 인증까지 마치면 자동으로 달성됩니다",
    ],
    joined: 967,
  },
  {
    id: "m-branch",
    kind: "branch",
    label: "신규 지점 방문",
    title: "아직 안 가 본 지점 두 곳",
    summary: "방문 기록이 없는 지점 2곳에서 QR 인증하기",
    description:
      "소규모 분관과 신설 지점을 한 번씩 돌아보는 순회 미션입니다. 처인도서관과 동백도서관은 개관한 지 얼마 되지 않아 방문 스탬프가 2배로 적립됩니다.",
    period: "8월 1일 - 8월 31일",
    daysLeft: 24,
    progress: 0,
    goal: 2,
    unit: "곳",
    reward: "방문 스탬프 4개, 지점 순회 배지",
    steps: [
      "도서관 안내에서 미방문 지점을 확인합니다",
      "지점에 도착해 입구 QR을 스캔합니다",
      "두 곳을 모두 방문하면 달성됩니다",
    ],
    joined: 613,
    priority: "정보취약계층 우선",
  },
  {
    id: "m-event",
    kind: "event",
    label: "특별 이벤트",
    title: "용인 독서주간 스탬프 랠리",
    summary: "행사 기간 중 서로 다른 구에서 각 1회 인증하기",
    description:
      "제12회 용인 독서주간 연계 이벤트입니다. 처인구, 기흥구, 수지구 지점에서 각각 한 번씩 인증하면 완주로 처리되고 기념 굿즈 교환권을 드립니다.",
    period: "8월 24일 - 8월 30일",
    daysLeft: 17,
    progress: 0,
    goal: 3,
    unit: "개 구",
    reward: "독서주간 한정 배지, 기념 굿즈 교환권",
    steps: [
      "행사 기간이 시작되면 미션이 열립니다",
      "구별로 한 곳씩 골라 방문 인증합니다",
      "세 구를 모두 채우면 교환권이 발급됩니다",
    ],
    joined: 228,
  },
];

export function getMission(id?: string) {
  return MISSIONS.find((m) => m.id === id) ?? MISSIONS[0];
}

export const RECOMMENDED_BOOKS: RecommendedBook[] = [
  {
    id: "b-1",
    title: "물의 기억",
    author: "정한아름",
    publisher: "창비",
    category: "문학",
    pages: 312,
    blurb: "저수지가 있던 자리에 신도시가 들어선 뒤, 남겨진 사람들의 여름을 따라가는 장편소설.",
    holdings: 14,
    available: 6,
  },
  {
    id: "b-2",
    title: "도시는 어떻게 기억하는가",
    author: "서동해",
    publisher: "돌베개",
    category: "인문",
    pages: 268,
    blurb: "도서관, 목욕탕, 시장처럼 사라지고 남는 공간을 통해 도시의 기억을 읽는 도시인문 에세이.",
    holdings: 11,
    available: 3,
  },
  {
    id: "b-3",
    title: "여름의 온도를 재는 법",
    author: "민하윤",
    publisher: "사이언스북스",
    category: "과학",
    pages: 244,
    blurb: "폭염과 열섬 현상을 기후 데이터로 풀어낸 대중 과학서. 중학생도 읽을 수 있는 문장.",
    holdings: 9,
    available: 5,
  },
];

export const READ_LOGS: ReadLog[] = [
  {
    id: "r-1",
    title: "물의 기억",
    author: "정한아름",
    publisher: "창비",
    category: "문학",
    finishedAt: "8월 6일",
    photoId: 998,
    photoAlt: "끈으로 묶인 낡은 책 묶음과 만년필",
    note: "저수지 이야기가 우리 동네 얘기 같아서 한참 덮어 두고 다시 읽었다.",
    libraryId: "guteun",
    missionId: "m-recommend",
  },
  {
    id: "r-2",
    title: "밤의 도서관",
    author: "알베르토 망겔",
    publisher: "세종서적",
    category: "인문",
    finishedAt: "8월 4일",
    photoId: 882,
    photoAlt: "붉은 타일 바닥 카페에서 커피를 두고 읽는 사람",
    note: "책이 있는 방을 이렇게 오래 들여다본 사람이 또 있을까 싶었다.",
    libraryId: "guteun",
    missionId: "m-theme",
  },
  {
    id: "r-3",
    title: "우리가 빛의 속도로 갈 수 없다면",
    author: "김초엽",
    publisher: "허블",
    category: "문학",
    finishedAt: "7월 30일",
    photoId: 365,
    photoAlt: "침대 위에 펼쳐진 책과 찻잔, 마른 꽃",
    note: "표제작보다 마지막 단편이 오래 남았다.",
    libraryId: "central",
  },
  {
    id: "r-4",
    title: "사진의 언어",
    author: "고형욱",
    publisher: "안그라픽스",
    category: "예술",
    finishedAt: "7월 24일",
    photoId: 464,
    photoAlt: "원목 테이블 위에 펼쳐진 사진집과 카메라",
    libraryId: "giheung",
  },
  {
    id: "r-5",
    title: "도시는 어떻게 기억하는가",
    author: "서동해",
    publisher: "돌베개",
    category: "인문",
    finishedAt: "7월 17일",
    photoId: 20,
    photoAlt: "책상 위 노트와 컬러 도표가 실린 잡지, 색연필",
    note: "목욕탕 챕터를 읽고 처인구 옛 사진을 한참 찾아봤다.",
    libraryId: "suji",
  },
];

export const STAMPS: Stamp[] = LIBRARIES.map((library) => ({
  id: `s-${library.id}`,
  kind: "visit" as const,
  label: library.short,
  caption: library.name,
  date: library.lastVisitedAt ? `2026.${library.lastVisitedAt.replace("월 ", ".").replace("일", "")}` : "",
  earned: library.visited,
}));

export const BADGES: Badge[] = [
  {
    id: "bd-1",
    name: "첫 도장",
    description: "첫 방문 인증을 마쳤습니다",
    tier: "bronze",
    icon: "solar:verified-check-bold",
    earned: true,
    earnedAt: "2025년 11월 3일",
  },
  {
    id: "bd-2",
    name: "완독 10권",
    description: "완독 인증 10권을 넘겼습니다",
    tier: "silver",
    icon: "solar:book-bookmark-bold",
    earned: true,
    earnedAt: "2026년 3월 21일",
  },
  {
    id: "bd-3",
    name: "세 구 순회",
    description: "처인구, 기흥구, 수지구를 모두 방문했습니다",
    tier: "silver",
    icon: "solar:map-point-wave-bold",
    earned: true,
    earnedAt: "2026년 6월 9일",
  },
  {
    id: "bd-4",
    name: "야간 독서",
    description: "저녁 7시 이후 완독 인증 2회",
    tier: "bronze",
    icon: "solar:moon-stars-bold",
    earned: true,
    earnedAt: "2026년 8월 4일",
  },
  {
    id: "bd-5",
    name: "추천도서 완독",
    description: "이달의 추천도서를 완독했습니다",
    tier: "gold",
    icon: "solar:medal-ribbon-star-bold",
    earned: true,
    earnedAt: "2026년 8월 6일",
  },
  {
    id: "bd-6",
    name: "지점 순회",
    description: "전 지점 8곳을 모두 방문하면 받습니다",
    tier: "gold",
    icon: "solar:route-bold",
    earned: false,
    progress: { current: 4, goal: 8 },
  },
  {
    id: "bd-7",
    name: "백 권의 여름",
    description: "누적 완독 100권을 달성하면 받습니다",
    tier: "gold",
    icon: "solar:cup-star-bold",
    earned: false,
    progress: { current: 31, goal: 100 },
  },
  {
    id: "bd-8",
    name: "함께 읽기",
    description: "가족 또는 친구와 독서기록을 연결하면 받습니다",
    tier: "bronze",
    icon: "solar:users-group-rounded-bold",
    earned: false,
    progress: { current: 1, goal: 2 },
  },
];

export const REWARDS: Reward[] = [
  {
    id: "rw-1",
    name: "도서관 굿즈 교환권",
    detail: "용인시 도서관 로고 북마크와 에코백 중 택 1",
    condition: "스탬프 50개 달성",
    status: "사용가능",
    date: "8월 6일 발급",
  },
  {
    id: "rw-2",
    name: "문화프로그램 우선 신청권",
    detail: "죽전도서관 도예 프로그램 등 인기 강좌 선접수",
    condition: "지점 4곳 방문",
    status: "사용가능",
    date: "7월 28일 발급",
  },
  {
    id: "rw-3",
    name: "독서주간 기념 배지 세트",
    detail: "제12회 용인 독서주간 한정 금속 배지 3종",
    condition: "독서주간 스탬프 랠리 완주",
    status: "진행중",
    progress: { current: 0, goal: 3 },
  },
  {
    id: "rw-4",
    name: "대출 권수 확대 (5권에서 7권)",
    detail: "3개월간 1인 대출 한도 상향",
    condition: "완독 인증 10권 달성",
    status: "사용완료",
    date: "3월 22일 사용",
  },
  {
    id: "rw-5",
    name: "지역서점 도서교환권 5천원",
    detail: "용인시 등록 지역서점 27곳에서 사용",
    condition: "완독 인증 20권 달성",
    status: "사용완료",
    date: "5월 14일 사용",
  },
];

export const TIMELINE: TimelineEntry[] = [
  {
    id: "t-1",
    kind: "read",
    date: "8월 6일",
    title: "물의 기억 완독",
    detail: "구갈희망누리도서관에서 읽음 | 추천도서 미션 달성",
    photoId: 998,
    photoAlt: "끈으로 묶인 낡은 책 묶음과 만년필",
  },
  {
    id: "t-2",
    kind: "badge",
    date: "8월 6일",
    title: "추천도서 완독 배지 획득",
    detail: "8월의 책 미션을 완주했습니다",
  },
  {
    id: "t-3",
    kind: "visit",
    date: "8월 6일",
    title: "구갈희망누리도서관 방문",
    detail: "올해 6번째 방문 | 방문 스탬프 1개",
  },
  {
    id: "t-4",
    kind: "read",
    date: "8월 4일",
    title: "밤의 도서관 완독",
    detail: "밤 9시 24분 인증 | 테마 미션 1회 인정",
    photoId: 882,
    photoAlt: "붉은 타일 바닥 카페에서 커피를 두고 읽는 사람",
  },
  {
    id: "t-5",
    kind: "visit",
    date: "8월 2일",
    title: "용인중앙도서관 방문",
    detail: "올해 9번째 방문 | 방문 스탬프 1개",
  },
  {
    id: "t-6",
    kind: "reward",
    date: "7월 28일",
    title: "문화프로그램 우선 신청권 발급",
    detail: "지점 4곳 방문 조건을 채웠습니다",
  },
  {
    id: "t-7",
    kind: "read",
    date: "7월 30일",
    title: "우리가 빛의 속도로 갈 수 없다면 완독",
    detail: "용인중앙도서관에서 읽음",
    photoId: 365,
    photoAlt: "침대 위에 펼쳐진 책과 찻잔, 마른 꽃",
  },
];

export const MONTH_STATS: MonthStat[] = [
  { month: "3월", visits: 3, reads: 4, missionRate: 67 },
  { month: "4월", visits: 2, reads: 3, missionRate: 50 },
  { month: "5월", visits: 5, reads: 6, missionRate: 100 },
  { month: "6월", visits: 4, reads: 5, missionRate: 75 },
  { month: "7월", visits: 5, reads: 7, missionRate: 100 },
  { month: "8월", visits: 4, reads: 6, missionRate: 50 },
];

export const FAMILY = [
  { id: "f-1", name: "이서준", relation: "아들", reads: 12, initial: "서" },
  { id: "f-2", name: "한지우", relation: "친구", reads: 24, initial: "지" },
];

/** 도서 검색, 대출, 예약은 새로 만들지 않고 기존 시스템으로 넘긴다. */
export const OUTLINKS = [
  {
    id: "search",
    title: "소장자료 검색",
    detail: "용인시 도서관 통합 검색으로 이동",
    icon: "solar:magnifer-linear",
  },
  {
    id: "loan",
    title: "내 대출 현황",
    detail: "대출 중인 도서와 반납일 확인",
    icon: "solar:clipboard-list-linear",
  },
  {
    id: "reserve",
    title: "예약 및 상호대차",
    detail: "대출 중인 책 예약, 다른 지점에서 받기",
    icon: "solar:transfer-horizontal-linear",
  },
];

export const NOTICES = [
  {
    id: "n-1",
    title: "8월 미션이 새로 열렸습니다",
    detail: "이달의 추천도서 3권과 테마 미션을 확인해 보세요",
    date: "8월 1일",
  },
  {
    id: "n-2",
    title: "처인도서관 QR 설치 위치 변경",
    detail: "현관 자동문 왼쪽에서 오른쪽 벽면으로 옮겼습니다",
    date: "7월 29일",
  },
];
