import type {
  AdminComplex,
  AdminMember,
  AdminPost,
  ChatThread,
  Complex,
  LockerSlot,
  MyVerification,
  NoticeItem,
  Product,
  Report,
  Resident,
  Review,
} from "@/projects/community/enclave/lib/types";

/* 전부 다운로드 후 육안 확인한 id만 쓴다. design.md "사진 매핑" 표 참고. */
export function picsumId(id: number, w: number, h: number) {
  return `https://picsum.photos/id/${id}/${w}/${h}`;
}

export function resolveResident(id: string): Resident {
  if (id === "me") return ME;
  return RESIDENTS.find((r) => r.id === id) ?? RESIDENTS[0];
}

export const MY_COMPLEX: Complex = {
  id: "cx1",
  name: "그린포레 3단지",
  address: "서울 은평구 갈현동 512",
  householdCount: 1840,
  verifiedResidentCount: 1206,
  lockerCount: 18,
};

export const COMPLEX_SEARCH_RESULTS: Complex[] = [
  MY_COMPLEX,
  { id: "cx2", name: "행복마을 5단지", address: "서울 은평구 대조동 88", householdCount: 960, verifiedResidentCount: 704, lockerCount: 10 },
  { id: "cx3", name: "리버뷰 오피스텔", address: "서울 은평구 응암동 210", householdCount: 320, verifiedResidentCount: 198, lockerCount: 4 },
];

export const ME: Resident = {
  id: "me",
  nickname: "3단지산책러",
  dong: "104동",
  ho: "1502호",
  complexId: "cx1",
  reputationScore: 78,
  dealCount: 19,
  reviewCount: 17,
  verifiedAt: "2025.03.06",
};

export const RESIDENTS: Resident[] = [
  { id: "r1", nickname: "베란다정원사", dong: "102동", ho: "804호", complexId: "cx1", reputationScore: 92, dealCount: 41, reviewCount: 38, verifiedAt: "2025.03.02" },
  { id: "r2", nickname: "주말등산화", dong: "108동", ho: "1201호", complexId: "cx1", reputationScore: 65, dealCount: 14, reviewCount: 12, verifiedAt: "2025.03.11" },
  { id: "r3", nickname: "이사정리중", dong: "105동", ho: "603호", complexId: "cx1", reputationScore: 84, dealCount: 27, reviewCount: 25, verifiedAt: "2025.03.19" },
  { id: "r4", nickname: "재택3년차", dong: "110동", ho: "1904호", complexId: "cx1", reputationScore: 58, dealCount: 6, reviewCount: 4, verifiedAt: "2025.04.02" },
  { id: "r5", nickname: "책방집사", dong: "103동", ho: "702호", complexId: "cx1", reputationScore: 71, dealCount: 22, reviewCount: 20, verifiedAt: "2025.04.15" },
  { id: "r6", nickname: "육아템정리", dong: "107동", ho: "1108호", complexId: "cx1", reputationScore: 88, dealCount: 33, reviewCount: 30, verifiedAt: "2025.04.28" },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    title: "맥북 에어 M1 13인치 골드",
    price: 780000,
    category: "전자기기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 2,
    sellerId: "r1",
    postedAt: "2025.03.08",
    likeCount: 21,
    viewCount: 284,
    chatCount: 5,
    description: "24년 초 구매, 배터리 사이클 180회. 박스, 충전기 모두 있습니다. 단지 내 무인택배함으로 비대면 픽업 가능합니다.",
    tags: ["박스있음", "네고가능"],
    lockerAvailable: true,
  },
  {
    id: "p2",
    title: "아이패드 프로 11 128G 실버",
    price: 620000,
    category: "전자기기",
    condition: "거의새것",
    status: "판매중",
    photoId: 6,
    sellerId: "r3",
    postedAt: "2025.03.14",
    likeCount: 28,
    viewCount: 356,
    chatCount: 7,
    description: "애플펜슬 2세대 함께 드립니다. 액정 필름 부착 상태로 사용해서 흠집 없습니다.",
    tags: ["펜슬포함", "실측사진"],
    lockerAvailable: true,
  },
  {
    id: "p3",
    title: "맥북 프로 14 M2 스페이스그레이",
    price: 1650000,
    category: "전자기기",
    condition: "사용감있음",
    status: "예약중",
    photoId: 48,
    sellerId: "r2",
    postedAt: "2025.03.21",
    likeCount: 39,
    viewCount: 512,
    chatCount: 10,
    description: "회사 지급으로 개인 기기 처분합니다. 사용감 적고 애플케어플러스 25년 12월까지 남아있습니다.",
    tags: ["애플케어", "정품박스"],
    lockerAvailable: false,
  },
  {
    id: "p4",
    title: "출퇴근용 미니벨로 자전거",
    price: 95000,
    category: "스포츠/레저",
    condition: "사용감있음",
    status: "판매중",
    photoId: 76,
    sellerId: "r4",
    postedAt: "2025.03.27",
    likeCount: 13,
    viewCount: 176,
    chatCount: 3,
    description: "출퇴근용으로 6개월 탔습니다. 타이어 최근 교체했고 지하 주차장 픽업도 가능합니다.",
    tags: ["직거래", "타이어교체"],
    lockerAvailable: false,
  },
  {
    id: "p5",
    title: "필름카메라 야시카 T4",
    price: 340000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 91,
    sellerId: "r5",
    postedAt: "2025.04.03",
    likeCount: 47,
    viewCount: 601,
    chatCount: 12,
    description: "필름 두 롤 테스트 촬영만 했습니다. 렌즈 클리어하고 셔터 정상 작동합니다.",
    tags: ["필름테스트완료", "인기매물"],
    lockerAvailable: true,
  },
  {
    id: "p6",
    title: "듀얼센스 컨트롤러 화이트",
    price: 42000,
    category: "취미/악기",
    condition: "거의새것",
    status: "판매중",
    photoId: 96,
    sellerId: "r6",
    postedAt: "2025.04.09",
    likeCount: 8,
    viewCount: 96,
    chatCount: 2,
    description: "PS5 처분하면서 컨트롤러만 남았습니다. 스틱 드리프트 없고 정상 작동합니다.",
    tags: ["정상작동확인"],
    lockerAvailable: true,
  },
  {
    id: "p7",
    title: "통기타 (입문용, 케이스포함)",
    price: 75000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 145,
    sellerId: "r1",
    postedAt: "2025.04.16",
    likeCount: 10,
    viewCount: 132,
    chatCount: 4,
    description: "6개월 배우다 그만뒀습니다. 넥 상태 좋고 튜너 함께 드립니다.",
    tags: ["케이스포함", "튜너포함"],
    lockerAvailable: true,
  },
  {
    id: "p8",
    title: "아이폰 13 미니 128G 스타라이트",
    price: 480000,
    category: "전자기기",
    condition: "사용감있음",
    status: "거래완료",
    photoId: 160,
    sellerId: "r3",
    postedAt: "2025.04.24",
    likeCount: 24,
    viewCount: 298,
    chatCount: 9,
    description: "배터리 성능 89%. 액정 무흠집이고 케이스 씌워 사용했습니다.",
    tags: ["배터리성능89"],
    lockerAvailable: true,
  },
  {
    id: "p9",
    title: "여성 구두 235 (라운드토)",
    price: 28000,
    category: "패션/잡화",
    condition: "거의새것",
    status: "판매중",
    photoId: 21,
    sellerId: "r4",
    postedAt: "2025.05.02",
    likeCount: 5,
    viewCount: 74,
    chatCount: 1,
    description: "두 번 착용 후 사이즈가 안 맞아 판매합니다. 박스 있습니다.",
    tags: ["착용2회"],
    lockerAvailable: true,
  },
  {
    id: "p10",
    title: "무선 헤드폰 (거의 새것)",
    price: 110000,
    category: "전자기기",
    condition: "거의새것",
    status: "판매중",
    photoId: 26,
    sellerId: "r5",
    postedAt: "2025.05.11",
    likeCount: 17,
    viewCount: 189,
    chatCount: 5,
    description: "선물 받았는데 이미 쓰는 게 있어서 판매합니다. 파우치, 케이블 모두 있습니다.",
    tags: ["미개봉급", "파우치포함"],
    lockerAvailable: true,
  },
  {
    id: "p11",
    title: "유리 티팟 세트 (스트레이너 포함)",
    price: 18000,
    category: "생활가전",
    condition: "거의새것",
    status: "판매중",
    photoId: 225,
    sellerId: "r6",
    postedAt: "2025.05.19",
    likeCount: 3,
    viewCount: 52,
    chatCount: 1,
    description: "선물받고 한 번 사용했습니다. 700ml 용량, 스트레이너 포함입니다.",
    tags: ["한번사용"],
    lockerAvailable: true,
  },
  {
    id: "p12",
    title: "홈오피스 책상+체어 세트",
    price: 150000,
    category: "가구/인테리어",
    condition: "사용감있음",
    status: "판매중",
    photoId: 445,
    sellerId: "r2",
    postedAt: "2025.05.27",
    likeCount: 11,
    viewCount: 143,
    chatCount: 3,
    description: "재택근무 종료로 함께 처분합니다. 책상 120x60, 의자는 메쉬형입니다. 지하주차장 직접 픽업만 가능합니다.",
    tags: ["직접픽업", "세트할인"],
    lockerAvailable: false,
  },
  {
    id: "p13",
    title: "스터디 데스크 셋업 일체",
    price: 65000,
    category: "가구/인테리어",
    condition: "사용감있음",
    status: "거래완료",
    photoId: 20,
    sellerId: "me",
    postedAt: "2025.06.04",
    likeCount: 7,
    viewCount: 88,
    chatCount: 2,
    description: "책, 스탠드, 소품까지 한 번에 정리하며 판매 완료했습니다.",
    tags: ["일괄판매"],
    lockerAvailable: false,
  },
  {
    id: "p14",
    title: "레트로 카메라 컬렉션 (3대)",
    price: 260000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 91,
    sellerId: "me",
    postedAt: "2025.06.12",
    likeCount: 15,
    viewCount: 178,
    chatCount: 4,
    description: "정리하면서 안 쓰는 필름카메라 세 대를 세트로 내놓습니다. 개별 판매는 어렵습니다.",
    tags: ["세트판매만"],
    lockerAvailable: true,
  },
];

export const CHAT_THREADS: ChatThread[] = [
  {
    id: "c1",
    productId: "p1",
    counterpartId: "r1",
    dealStatus: "거래중",
    unreadCount: 2,
    lastMessage: "네 좋습니다, 그럼 무인택배함에 넣어둘게요",
    lastMessageAt: "2025.03.10 18:42",
    messages: [
      { id: "m1", type: "text", from: "them", text: "안녕하세요, 맥북 아직 판매하시나요?", at: "18:20" },
      { id: "m2", type: "text", from: "me", text: "네 가능합니다! 무인택배함 픽업으로 하실까요?", at: "18:24" },
      { id: "m3", type: "priceOffer", from: "them", offerPrice: 750000, at: "18:29" },
      { id: "m4", type: "text", from: "me", text: "네 그 가격에 드릴게요", at: "18:33" },
      { id: "m5", type: "lockerShare", from: "me", lockerLabel: "A동 1층 3번함", at: "18:38" },
      { id: "m6", type: "text", from: "them", text: "네 좋습니다, 그럼 무인택배함에 넣어둘게요", at: "18:42" },
    ],
  },
  {
    id: "c2",
    productId: "p3",
    counterpartId: "r2",
    dealStatus: "예약중",
    unreadCount: 0,
    lastMessage: "내일 저녁 7시에 지하주차장에서 뵐게요",
    lastMessageAt: "2025.03.23 21:05",
    messages: [
      { id: "m1", type: "text", from: "me", text: "맥북 프로 아직 있나요? 애플케어 남은 기간이 정확히 언제까지인가요", at: "20:40" },
      { id: "m2", type: "text", from: "them", text: "네 있습니다, 25년 12월까지예요. 영수증도 보여드릴 수 있어요", at: "20:52" },
      { id: "m3", type: "system", from: "them", text: "예약중 상태로 변경되었습니다", at: "20:58" },
      { id: "m4", type: "text", from: "them", text: "내일 저녁 7시에 지하주차장에서 뵐게요", at: "21:05" },
    ],
  },
  {
    id: "c3",
    productId: "p5",
    counterpartId: "r5",
    dealStatus: "거래중",
    unreadCount: 1,
    lastMessage: "셔터 소리 영상 찍어서 보내드릴게요",
    lastMessageAt: "2025.04.05 09:12",
    messages: [
      { id: "m1", type: "text", from: "them", text: "필름카메라 셔터 소리 영상 있으신가요?", at: "08:55" },
      { id: "m2", type: "text", from: "me", text: "네 찍어서 보내드릴게요 잠시만요", at: "09:01" },
      { id: "m3", type: "image", from: "me", at: "09:04" },
      { id: "m4", type: "text", from: "them", text: "오 상태 좋네요! 무인택배함으로 받을 수 있을까요?", at: "09:09" },
      { id: "m5", type: "text", from: "me", text: "셔터 소리 영상 찍어서 보내드릴게요", at: "09:12" },
    ],
  },
  {
    id: "c4",
    productId: "p8",
    counterpartId: "r3",
    dealStatus: "거래완료",
    unreadCount: 0,
    lastMessage: "후기 남겨주셔서 감사합니다!",
    lastMessageAt: "2025.04.26 19:30",
    messages: [
      { id: "m1", type: "text", from: "them", text: "무인택배함에서 무사히 잘 받았습니다, 감사합니다", at: "19:20" },
      { id: "m2", type: "system", from: "them", text: "거래완료로 변경되었습니다", at: "19:22" },
      { id: "m3", type: "text", from: "me", text: "후기 남겨주셔서 감사합니다!", at: "19:30" },
    ],
  },
  {
    id: "c5",
    productId: "p10",
    counterpartId: "r5",
    dealStatus: "거래중",
    unreadCount: 0,
    lastMessage: "네고는 조금 어려울 것 같아요, 죄송합니다",
    lastMessageAt: "2025.05.13 12:18",
    messages: [
      { id: "m1", type: "text", from: "them", text: "혹시 가격 조금 조정 가능할까요?", at: "12:10" },
      { id: "m2", type: "priceOffer", from: "them", offerPrice: 95000, at: "12:12" },
      { id: "m3", type: "text", from: "me", text: "네고는 조금 어려울 것 같아요, 죄송합니다", at: "12:18" },
    ],
  },
];

export const MY_LOCKERS: LockerSlot[] = [
  { id: "lk1", label: "A동 1층 3번함", size: "중형", status: "픽업대기", productId: "p1", pin: "7204", storedAt: "2025.03.10 19:00", expiresAt: "2025.03.12 19:00" },
  { id: "lk2", label: "B동 1층 7번함", size: "소형", status: "픽업완료", productId: "p8", pin: "4491", storedAt: "2025.04.24 20:10", expiresAt: "2025.04.26 20:10" },
  { id: "lk3", label: "A동 1층 1번함", size: "대형", status: "회수예정", productId: "p12", pin: "5830", storedAt: "2025.05.28 11:20", expiresAt: "2025.05.29 11:20" },
];

export const MY_REVIEWS: Review[] = [
  { id: "rv1", reviewerNickname: "베란다정원사", keyword: "시간 약속을 잘 지켜요", createdAt: "2025.04.27" },
  { id: "rv2", reviewerNickname: "이사정리중", keyword: "친절하고 매너가 좋아요", createdAt: "2025.05.14" },
  { id: "rv3", reviewerNickname: "책방집사", keyword: "응답이 빨라요", createdAt: "2025.06.05" },
];

export const MY_VERIFICATION: MyVerification = {
  emailVerified: true,
  phoneVerified: true,
  complexId: "cx1",
  dong: "104동",
  ho: "1502호",
  verifiedAt: "2025.03.06",
  verifyStatus: "완료",
  interests: ["전자기기", "취미/악기", "가구/인테리어"],
  dealWindow: "평일 저녁 7시 ~ 10시",
};

/* ── 관리자 ── */

export const ADMIN_MEMBERS: AdminMember[] = [
  { id: "a1", nickname: "베란다정원사", dong: "102동", ho: "804호", complexName: "그린포레 3단지", joinedAt: "2025.03.02", emailVerified: true, complexVerified: true, reputationScore: 92, dealCount: 41, reportCount: 0, status: "정상" },
  { id: "a2", nickname: "주말등산화", dong: "108동", ho: "1201호", complexName: "그린포레 3단지", joinedAt: "2025.03.11", emailVerified: true, complexVerified: true, reputationScore: 65, dealCount: 14, reportCount: 1, status: "정상" },
  { id: "a3", nickname: "이사정리중", dong: "105동", ho: "603호", complexName: "그린포레 3단지", joinedAt: "2025.03.19", emailVerified: true, complexVerified: true, reputationScore: 84, dealCount: 27, reportCount: 0, status: "정상" },
  { id: "a4", nickname: "재택3년차", dong: "110동", ho: "1904호", complexName: "그린포레 3단지", joinedAt: "2025.04.02", emailVerified: true, complexVerified: false, reputationScore: 58, dealCount: 6, reportCount: 2, status: "주의" },
  { id: "a5", nickname: "책방집사", dong: "103동", ho: "702호", complexName: "그린포레 3단지", joinedAt: "2025.04.15", emailVerified: true, complexVerified: true, reputationScore: 71, dealCount: 22, reportCount: 0, status: "정상" },
  { id: "a6", nickname: "육아템정리", dong: "107동", ho: "1108호", complexName: "그린포레 3단지", joinedAt: "2025.04.28", emailVerified: true, complexVerified: true, reputationScore: 88, dealCount: 33, reportCount: 1, status: "정상" },
  { id: "a7", nickname: "급처가격흥정", dong: "109동", ho: "301호", complexName: "행복마을 5단지", joinedAt: "2025.05.06", emailVerified: true, complexVerified: false, reputationScore: 14, dealCount: 2, reportCount: 4, status: "정지" },
  { id: "a8", nickname: "새벽3시연락", dong: "204동", ho: "1102호", complexName: "행복마을 5단지", joinedAt: "2025.05.14", emailVerified: true, complexVerified: true, reputationScore: 22, dealCount: 3, reportCount: 3, status: "정지" },
  { id: "a9", nickname: "3단지산책러", dong: "104동", ho: "1502호", complexName: "그린포레 3단지", joinedAt: "2025.03.06", emailVerified: true, complexVerified: true, reputationScore: 78, dealCount: 19, reportCount: 0, status: "정상" },
  { id: "a10", nickname: "오피스텔302", dong: "-", ho: "302호", complexName: "리버뷰 오피스텔", joinedAt: "2025.05.24", emailVerified: true, complexVerified: true, reputationScore: 61, dealCount: 4, reportCount: 0, status: "정상" },
  { id: "a11", nickname: "공방하는사람", dong: "201동", ho: "905호", complexName: "행복마을 5단지", joinedAt: "2025.06.02", emailVerified: true, complexVerified: true, reputationScore: 55, dealCount: 2, reportCount: 1, status: "주의" },
  { id: "a12", nickname: "신규입주민9", dong: "112동", ho: "1601호", complexName: "그린포레 3단지", joinedAt: "2025.06.11", emailVerified: false, complexVerified: false, reputationScore: 50, dealCount: 0, reportCount: 0, status: "정상" },
];

export const REPORTS: Report[] = [
  {
    id: "rp1",
    type: "사기의심",
    targetType: "회원",
    targetLabel: "급처가격흥정",
    reporterNickname: "이사정리중",
    reportedNickname: "급처가격흥정",
    status: "완료",
    createdAt: "2025.05.10",
    memo: "선입금 요구 후 연락 두절 신고. 동일 수법 3건 확인되어 영구정지 처리.",
    penalty: "영구정지",
  },
  {
    id: "rp2",
    type: "허위매물",
    targetType: "게시글",
    targetLabel: "아이폰 15 프로 미개봉 (삭제됨)",
    reporterNickname: "책방집사",
    reportedNickname: "새벽3시연락",
    status: "완료",
    createdAt: "2025.05.18",
    memo: "타 사이트 도용 사진 확인, 게시글 삭제 및 경고 처리.",
    penalty: "경고",
  },
  {
    id: "rp3",
    type: "욕설/비매너",
    targetType: "채팅",
    targetLabel: "채팅방 #c-4402",
    reporterNickname: "육아템정리",
    reportedNickname: "새벽3시연락",
    status: "완료",
    createdAt: "2025.05.25",
    memo: "채팅 내 반복 욕설 확인, 7일 정지 처리.",
    penalty: "7일 정지",
  },
  {
    id: "rp4",
    type: "무인택배함오남용",
    targetType: "회원",
    targetLabel: "재택3년차",
    reporterNickname: "베란다정원사",
    reportedNickname: "재택3년차",
    status: "처리중",
    createdAt: "2025.06.03",
  },
  {
    id: "rp5",
    type: "개인정보노출",
    targetType: "채팅",
    targetLabel: "채팅방 #c-4471",
    reporterNickname: "주말등산화",
    reportedNickname: "공방하는사람",
    status: "대기",
    createdAt: "2025.06.09",
  },
  {
    id: "rp6",
    type: "허위매물",
    targetType: "게시글",
    targetLabel: "듀얼센스 컨트롤러 화이트",
    reporterNickname: "공방하는사람",
    reportedNickname: "육아템정리",
    status: "대기",
    createdAt: "2025.06.12",
  },
  {
    id: "rp7",
    type: "사기의심",
    targetType: "회원",
    targetLabel: "공방하는사람",
    reporterNickname: "오피스텔302",
    reportedNickname: "공방하는사람",
    status: "대기",
    createdAt: "2025.06.13",
  },
];

export const ADMIN_POSTS: AdminPost[] = [
  { id: "ap1", title: "맥북 에어 M1 13인치 골드", photoId: 2, sellerNickname: "베란다정원사", complexName: "그린포레 3단지", price: 780000, status: "판매중", reportCount: 0, postedAt: "2025.03.08" },
  { id: "ap2", title: "아이패드 프로 11 128G 실버", photoId: 6, sellerNickname: "이사정리중", complexName: "그린포레 3단지", price: 620000, status: "판매중", reportCount: 0, postedAt: "2025.03.14" },
  { id: "ap3", title: "맥북 프로 14 M2 스페이스그레이", photoId: 48, sellerNickname: "주말등산화", complexName: "그린포레 3단지", price: 1650000, status: "예약중", reportCount: 0, postedAt: "2025.03.21" },
  { id: "ap4", title: "듀얼센스 컨트롤러 화이트", photoId: 96, sellerNickname: "육아템정리", complexName: "그린포레 3단지", price: 42000, status: "신고접수", reportCount: 1, postedAt: "2025.04.09" },
  { id: "ap5", title: "아이폰 15 프로 미개봉 (도용사진)", photoId: 160, sellerNickname: "새벽3시연락", complexName: "행복마을 5단지", price: 890000, status: "숨김처리", reportCount: 3, postedAt: "2025.05.15" },
  { id: "ap6", title: "필름카메라 야시카 T4", photoId: 91, sellerNickname: "책방집사", complexName: "그린포레 3단지", price: 340000, status: "판매중", reportCount: 0, postedAt: "2025.04.03" },
  { id: "ap7", title: "무선 헤드폰 (거의 새것)", photoId: 26, sellerNickname: "책방집사", complexName: "그린포레 3단지", price: 110000, status: "판매중", reportCount: 0, postedAt: "2025.05.11" },
  { id: "ap8", title: "선입금 유도 의심 게시글", photoId: 76, sellerNickname: "급처가격흥정", complexName: "행복마을 5단지", price: 250000, status: "숨김처리", reportCount: 4, postedAt: "2025.05.08" },
  { id: "ap9", title: "홈오피스 책상+체어 세트", photoId: 445, sellerNickname: "주말등산화", complexName: "그린포레 3단지", price: 150000, status: "판매중", reportCount: 0, postedAt: "2025.05.27" },
  { id: "ap10", title: "여성 구두 235 (라운드토)", photoId: 21, sellerNickname: "재택3년차", complexName: "그린포레 3단지", price: 28000, status: "판매중", reportCount: 0, postedAt: "2025.05.02" },
];

export const ADMIN_COMPLEXES: AdminComplex[] = [
  { id: "cx1", name: "그린포레 3단지", address: "서울 은평구 갈현동 512", householdCount: 1840, residentCount: 1206, verifyStatus: "승인완료", requestedAt: "2025.02.20", lockerCount: 18 },
  { id: "cx2", name: "행복마을 5단지", address: "서울 은평구 대조동 88", householdCount: 960, residentCount: 704, verifyStatus: "승인완료", requestedAt: "2025.02.24", lockerCount: 10 },
  { id: "cx3", name: "리버뷰 오피스텔", address: "서울 은평구 응암동 210", householdCount: 320, residentCount: 198, verifyStatus: "승인완료", requestedAt: "2025.03.15", lockerCount: 4 },
  { id: "cx4", name: "센트럴포레 1차", address: "서울 서대문구 홍제동 44", householdCount: 1120, residentCount: 62, verifyStatus: "승인대기", requestedAt: "2025.06.05", lockerCount: 12 },
  { id: "cx5", name: "미래도 7단지", address: "경기 고양시 화정동 990", householdCount: 2100, residentCount: 0, verifyStatus: "승인대기", requestedAt: "2025.06.10", lockerCount: 0 },
  { id: "cx6", name: "한빛타운 2단지", address: "서울 은평구 녹번동 77", householdCount: 540, residentCount: 12, verifyStatus: "반려", requestedAt: "2025.05.29", lockerCount: 6 },
];

export const NOTICES: NoticeItem[] = [
  { id: "n1", title: "여름철 무인택배함 보관기간 단축 안내", body: "2025년 6월부터 고온기 보관기간을 48시간에서 36시간으로 조정합니다.", publishedAt: "2025.06.02", pinned: true },
  { id: "n2", title: "단지 인증 승인 기준 안내", body: "관리사무소 확인서 또는 관리비 고지서 업로드 시 승인 처리 기준을 정리했습니다.", publishedAt: "2025.05.12", pinned: true },
  { id: "n3", title: "이웃평판 산정 방식 안내", body: "거래 완료율과 응답 속도를 반영해 이웃평판 점수 체감도를 높였습니다.", publishedAt: "2025.04.08", pinned: false },
  { id: "n4", title: "서비스 오픈 안내", body: "그린포레 3단지, 행복마을 5단지, 리버뷰 오피스텔에서 먼저 서비스를 시작합니다.", publishedAt: "2025.03.01", pinned: false },
];

export const DASHBOARD_MEMBER_TREND = [
  { label: "3월", value: 820 },
  { label: "4월", value: 1360 },
  { label: "5월", value: 1890 },
  { label: "6월", value: 2108, emphasis: true },
];

export const DASHBOARD_DEAL_TREND = [
  { label: "3월", value: 96 },
  { label: "4월", value: 182 },
  { label: "5월", value: 264 },
  { label: "6월", value: 341, emphasis: true },
];

export const DASHBOARD_CATEGORY_SHARE = [
  { label: "전자기기", value: 168, caption: "168건" },
  { label: "취미/악기", value: 94, caption: "94건" },
  { label: "가구/인테리어", value: 61, caption: "61건" },
  { label: "생활가전", value: 38, caption: "38건" },
  { label: "패션/잡화", value: 22, caption: "22건" },
];
