import type {
  AdminMember,
  AdminPost,
  ChatThread,
  MyVerification,
  NoticeItem,
  Product,
  PushLog,
  Report,
  Seller,
  WaypointSpot,
} from "@/projects/community/waypoint/lib/types";

/* 전부 다운로드 후 육안 확인한 id만 쓴다. design.md "사진 매핑" 표 참고. */
export function picsumId(id: number, w: number, h: number) {
  return `https://picsum.photos/id/${id}/${w}/${h}`;
}

export const ME: Seller = {
  id: "me",
  nickname: "합정역도보7분",
  avatarInitial: "합",
  homeDong: "서울 마포구 합정동",
  workDong: "서울 강남구 역삼동",
  trustScore: 87,
  dealCount: 24,
  reviewCount: 21,
  onTimeRate: 96,
  responseRate: 92,
  dualVerified: true,
};

export const SELLERS: Seller[] = [
  {
    id: "s1",
    nickname: "판교출근러",
    avatarInitial: "판",
    homeDong: "서울 마포구 망원동",
    workDong: "경기 성남시 판교동",
    trustScore: 94,
    dealCount: 58,
    reviewCount: 51,
    onTimeRate: 98,
    responseRate: 97,
    dualVerified: true,
  },
  {
    id: "s2",
    nickname: "새벽기차",
    avatarInitial: "새",
    homeDong: "서울 은평구 연신내동",
    workDong: "서울 중구 을지로동",
    trustScore: 76,
    dealCount: 12,
    reviewCount: 10,
    onTimeRate: 88,
    responseRate: 80,
    dualVerified: true,
  },
  {
    id: "s3",
    nickname: "이차선라이더",
    avatarInitial: "이",
    homeDong: "서울 광진구 자양동",
    workDong: "서울 강남구 삼성동",
    trustScore: 91,
    dealCount: 33,
    reviewCount: 30,
    onTimeRate: 95,
    responseRate: 90,
    dualVerified: true,
  },
  {
    id: "s4",
    nickname: "우주정거장",
    avatarInitial: "우",
    homeDong: "서울 동작구 사당동",
    workDong: "서울 서초구 서초동",
    trustScore: 68,
    dealCount: 7,
    reviewCount: 5,
    onTimeRate: 78,
    responseRate: 70,
    dualVerified: false,
  },
  {
    id: "s5",
    nickname: "2호선정주민",
    avatarInitial: "2",
    homeDong: "서울 성동구 성수동",
    workDong: "서울 중구 명동",
    trustScore: 85,
    dealCount: 19,
    reviewCount: 17,
    onTimeRate: 93,
    responseRate: 89,
    dualVerified: true,
  },
  {
    id: "s6",
    nickname: "야근각",
    avatarInitial: "야",
    homeDong: "서울 노원구 상계동",
    workDong: "서울 종로구 종로동",
    trustScore: 72,
    dealCount: 9,
    reviewCount: 8,
    onTimeRate: 84,
    responseRate: 75,
    dualVerified: true,
  },
];

export const WAYPOINT_SPOTS: WaypointSpot[] = [
  {
    id: "w1",
    name: "합정역 3번 출구",
    type: "지하철역",
    address: "서울 마포구 합정동 지하철역 3번 출구 앞",
    distanceM: 180,
    safetyScore: 92,
    crowdLevel: "보통",
    hours: "24시간",
    favorite: true,
  },
  {
    id: "w2",
    name: "카페 드림 합정점",
    type: "카페",
    address: "서울 마포구 합정동 396-12",
    distanceM: 240,
    safetyScore: 88,
    crowdLevel: "여유",
    hours: "07:00 ~ 22:00",
    favorite: true,
    photoId: 42,
  },
  {
    id: "w3",
    name: "GS25 역삼큰길점",
    type: "편의점",
    address: "서울 강남구 역삼동 719-3",
    distanceM: 90,
    safetyScore: 95,
    crowdLevel: "여유",
    hours: "24시간",
    favorite: false,
  },
  {
    id: "w4",
    name: "테라스 카페 역삼",
    type: "카페",
    address: "서울 강남구 역삼동 828-11",
    distanceM: 310,
    safetyScore: 84,
    crowdLevel: "혼잡",
    hours: "08:00 ~ 21:00",
    favorite: false,
    photoId: 163,
  },
  {
    id: "w5",
    name: "스터디카페 잠실나루",
    type: "스터디카페",
    address: "서울 송파구 잠실동 40-2",
    distanceM: 150,
    safetyScore: 90,
    crowdLevel: "보통",
    hours: "24시간",
    favorite: true,
  },
  {
    id: "w6",
    name: "성수역 상점가 입구",
    type: "지하철역",
    address: "서울 성동구 성수동 685-70",
    distanceM: 420,
    safetyScore: 79,
    crowdLevel: "혼잡",
    hours: "24시간",
    favorite: false,
    photoId: 195,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    title: "맥북 에어 M1 13인치 골드",
    price: 780000,
    category: "전자기기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 1,
    sellerId: "s1",
    postedAt: "2026.01.14",
    distanceM: 320,
    nearestStation: "판교역",
    etaMin: 6,
    waypointSpotId: "w2",
    likeCount: 24,
    viewCount: 312,
    chatCount: 5,
    description: "24년 초 구매, 배터리 사이클 180회. 박스, 충전기 모두 있습니다. 판교역 웨이스팟에서 직거래 선호합니다.",
    tags: ["직거래선호", "박스있음", "네고가능"],
  },
  {
    id: "p2",
    title: "아이패드 프로 11 128G 실버",
    price: 620000,
    category: "전자기기",
    condition: "거의새것",
    status: "판매중",
    photoId: 6,
    sellerId: "s3",
    postedAt: "2026.01.20",
    distanceM: 540,
    nearestStation: "삼성역",
    etaMin: 9,
    likeCount: 31,
    viewCount: 401,
    chatCount: 8,
    description: "애플펜슬 2세대 함께 드립니다. 액정 필름 부착 상태로 사용해서 흠집 없습니다.",
    tags: ["펜슬포함", "실측사진"],
  },
  {
    id: "p3",
    title: "맥북 프로 14 M2 스페이스그레이",
    price: 1650000,
    category: "전자기기",
    condition: "사용감있음",
    status: "예약중",
    photoId: 48,
    sellerId: "s2",
    postedAt: "2025.12.28",
    distanceM: 210,
    nearestStation: "을지로3가역",
    etaMin: 4,
    waypointSpotId: "w2",
    likeCount: 42,
    viewCount: 588,
    chatCount: 11,
    description: "회사 지급으로 개인 기기 처분합니다. 사용감 적고 애플케어플러스 26년 6월까지 남아있습니다.",
    tags: ["애플케어", "정품박스"],
  },
  {
    id: "p4",
    title: "미니벨로 자전거 (접이식)",
    price: 95000,
    category: "스포츠/레저",
    condition: "사용감있음",
    status: "판매중",
    photoId: 76,
    sellerId: "s4",
    postedAt: "2025.11.09",
    distanceM: 450,
    nearestStation: "사당역",
    etaMin: 8,
    likeCount: 15,
    viewCount: 203,
    chatCount: 3,
    description: "출퇴근용으로 6개월 탔습니다. 타이어 작년에 교체했고 접이식이라 지하철 반입 편합니다.",
    tags: ["접이식", "타이어교체"],
  },
  {
    id: "p5",
    title: "필름카메라 야시카 T4",
    price: 340000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 91,
    sellerId: "s5",
    postedAt: "2026.02.03",
    distanceM: 380,
    nearestStation: "성수역",
    etaMin: 7,
    waypointSpotId: "w6",
    likeCount: 58,
    viewCount: 674,
    chatCount: 14,
    description: "필름 두 롤 테스트 촬영만 했습니다. 렌즈 클리어하고 셔터 정상 작동합니다.",
    tags: ["필름테스트완료", "인기매물"],
  },
  {
    id: "p6",
    title: "듀얼센스 컨트롤러 화이트",
    price: 42000,
    category: "취미/악기",
    condition: "거의새것",
    status: "판매중",
    photoId: 96,
    sellerId: "s6",
    postedAt: "2026.01.05",
    distanceM: 610,
    nearestStation: "종로3가역",
    etaMin: 11,
    likeCount: 9,
    viewCount: 128,
    chatCount: 2,
    description: "PS5 처분하면서 컨트롤러만 남았습니다. 스틱 드리프트 없고 정상 작동합니다.",
    tags: ["정상작동확인"],
  },
  {
    id: "p7",
    title: "통기타 (입문용, 케이스포함)",
    price: 75000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 145,
    sellerId: "s1",
    postedAt: "2025.10.22",
    distanceM: 290,
    nearestStation: "판교역",
    etaMin: 5,
    likeCount: 11,
    viewCount: 154,
    chatCount: 4,
    description: "6개월 배우다 그만뒀습니다. 넥 상태 좋고 튜너 함께 드립니다.",
    tags: ["케이스포함", "튜너포함"],
  },
  {
    id: "p8",
    title: "아이폰 13 미니 128G 스타라이트",
    price: 480000,
    category: "전자기기",
    condition: "사용감있음",
    status: "거래완료",
    photoId: 160,
    sellerId: "s3",
    postedAt: "2025.11.30",
    distanceM: 500,
    nearestStation: "삼성역",
    etaMin: 9,
    likeCount: 27,
    viewCount: 340,
    chatCount: 9,
    description: "배터리 성능 89%. 액정 무흠집이고 케이스 씌워 사용했습니다.",
    tags: ["배터리성능89"],
  },
  {
    id: "p9",
    title: "여성 구두 235 (라운드토)",
    price: 28000,
    category: "패션/잡화",
    condition: "거의새것",
    status: "판매중",
    photoId: 21,
    sellerId: "s4",
    postedAt: "2026.01.28",
    distanceM: 260,
    nearestStation: "사당역",
    etaMin: 5,
    likeCount: 6,
    viewCount: 88,
    chatCount: 1,
    description: "두 번 착용 후 사이즈가 안 맞아 판매합니다. 박스 있습니다.",
    tags: ["착용2회"],
  },
  {
    id: "p10",
    title: "무선 헤드폰 (거의 새것)",
    price: 110000,
    category: "전자기기",
    condition: "거의새것",
    status: "판매중",
    photoId: 26,
    sellerId: "s5",
    postedAt: "2026.02.10",
    distanceM: 330,
    nearestStation: "성수역",
    etaMin: 6,
    waypointSpotId: "w6",
    likeCount: 19,
    viewCount: 221,
    chatCount: 5,
    description: "선물 받았는데 이미 쓰는 게 있어서 판매합니다. 파우치, 케이블 모두 있습니다.",
    tags: ["미개봉급", "파우치포함"],
  },
  {
    id: "p11",
    title: "유리 티팟 세트 (스트레이너 포함)",
    price: 18000,
    category: "생활가전",
    condition: "거의새것",
    status: "판매중",
    photoId: 225,
    sellerId: "s6",
    postedAt: "2025.12.15",
    distanceM: 470,
    nearestStation: "종로3가역",
    etaMin: 10,
    likeCount: 4,
    viewCount: 61,
    chatCount: 1,
    description: "선물받고 한 번 사용했습니다. 700ml 용량, 스트레이너 포함입니다.",
    tags: ["한번사용"],
  },
  {
    id: "p13",
    title: "레트로 카메라 컬렉션 (3대)",
    price: 260000,
    category: "취미/악기",
    condition: "사용감있음",
    status: "판매중",
    photoId: 355,
    sellerId: "me",
    postedAt: "2026.02.08",
    distanceM: 0,
    nearestStation: "합정역",
    etaMin: 2,
    likeCount: 17,
    viewCount: 205,
    chatCount: 4,
    description: "정리하면서 안 쓰는 필름카메라 세 대를 세트로 내놓습니다. 개별 판매는 어렵습니다.",
    tags: ["세트판매만"],
  },
  {
    id: "p14",
    title: "스터디 데스크 셋업 일체",
    price: 65000,
    category: "가구/인테리어",
    condition: "사용감있음",
    status: "거래완료",
    photoId: 20,
    sellerId: "me",
    postedAt: "2025.11.11",
    distanceM: 0,
    nearestStation: "합정역",
    etaMin: 2,
    likeCount: 8,
    viewCount: 96,
    chatCount: 2,
    description: "책, 스탠드, 소품까지 한 번에 정리하며 판매 완료했습니다.",
    tags: ["일괄판매"],
  },
  {
    id: "p12",
    title: "홈오피스 책상+체어 세트",
    price: 150000,
    category: "가구/인테리어",
    condition: "사용감있음",
    status: "판매중",
    photoId: 445,
    sellerId: "s2",
    postedAt: "2025.10.06",
    distanceM: 180,
    nearestStation: "을지로3가역",
    etaMin: 3,
    likeCount: 13,
    viewCount: 176,
    chatCount: 3,
    description: "재택근무 종료로 함께 처분합니다. 책상 120x60, 의자는 메쉬형입니다. 직접 픽업만 가능합니다.",
    tags: ["직접픽업", "세트할인"],
  },
];

export const CHAT_THREADS: ChatThread[] = [
  {
    id: "c1",
    productId: "p1",
    counterpartId: "s1",
    dealStatus: "거래중",
    unreadCount: 2,
    lastMessage: "네 좋습니다. 그럼 판교역 웨이스팟에서 뵐게요",
    lastMessageAt: "2026.02.12 18:42",
    messages: [
      { id: "m1", type: "text", from: "them", text: "안녕하세요, 맥북 아직 판매하시나요?", at: "18:20" },
      { id: "m2", type: "text", from: "me", text: "네 가능합니다! 퇴근길에 보실 수 있으세요?", at: "18:24" },
      { id: "m3", type: "text", from: "them", text: "좋아요, 저 판교역 쪽으로 퇴근해서 그 근처면 편할 것 같아요", at: "18:31" },
      {
        id: "m4",
        type: "waypointShare",
        from: "me",
        waypointSpotId: "w2",
        at: "18:36",
      },
      { id: "m5", type: "text", from: "me", text: "여기 카페 드림 어떠세요? 항상 웨이스팟으로 쓰는 곳이라 안전해요", at: "18:37" },
      { id: "m6", type: "text", from: "them", text: "네 좋습니다. 그럼 판교역 웨이스팟에서 뵐게요", at: "18:42" },
    ],
  },
  {
    id: "c2",
    productId: "p3",
    counterpartId: "s2",
    dealStatus: "예약중",
    unreadCount: 0,
    lastMessage: "내일 저녁 7시에 뵐게요, 감사합니다",
    lastMessageAt: "2026.02.10 21:05",
    messages: [
      { id: "m1", type: "text", from: "me", text: "맥북 프로 아직 있나요? 애플케어 남은 기간이 정확히 언제까지인가요", at: "20:40" },
      { id: "m2", type: "text", from: "them", text: "네 있습니다, 26년 6월까지예요. 영수증도 보여드릴 수 있어요", at: "20:52" },
      { id: "m3", type: "system", from: "them", text: "예약중 상태로 변경되었습니다", at: "20:58" },
      { id: "m4", type: "text", from: "them", text: "내일 저녁 7시에 뵐게요, 감사합니다", at: "21:05" },
    ],
  },
  {
    id: "c3",
    productId: "p5",
    counterpartId: "s5",
    dealStatus: "거래중",
    unreadCount: 1,
    lastMessage: "성수역 웨이스팟 사진 보내드릴게요",
    lastMessageAt: "2026.02.13 09:12",
    messages: [
      { id: "m1", type: "text", from: "them", text: "필름카메라 셔터 소리 영상 있으신가요?", at: "08:55" },
      { id: "m2", type: "text", from: "me", text: "네 찍어서 보내드릴게요 잠시만요", at: "09:01" },
      { id: "m3", type: "image", from: "me", at: "09:04" },
      { id: "m4", type: "text", from: "them", text: "오 상태 좋네요! 오늘 저녁 가능하세요?", at: "09:09" },
      { id: "m5", type: "text", from: "them", text: "성수역 웨이스팟 사진 보내드릴게요", at: "09:12" },
    ],
  },
  {
    id: "c4",
    productId: "p8",
    counterpartId: "s3",
    dealStatus: "거래완료",
    unreadCount: 0,
    lastMessage: "후기 남겨주셔서 감사합니다!",
    lastMessageAt: "2025.12.02 19:30",
    messages: [
      { id: "m1", type: "text", from: "them", text: "무사히 잘 받았습니다, 감사합니다", at: "19:20" },
      { id: "m2", type: "system", from: "them", text: "거래완료로 변경되었습니다", at: "19:22" },
      { id: "m3", type: "text", from: "me", text: "후기 남겨주셔서 감사합니다!", at: "19:30" },
    ],
  },
  {
    id: "c5",
    productId: "p10",
    counterpartId: "s5",
    dealStatus: "거래중",
    unreadCount: 0,
    lastMessage: "네고는 조금 어려울 것 같아요, 죄송합니다",
    lastMessageAt: "2026.02.11 12:18",
    messages: [
      { id: "m1", type: "text", from: "them", text: "혹시 가격 조금 조정 가능할까요?", at: "12:10" },
      { id: "m2", type: "text", from: "me", text: "네고는 조금 어려울 것 같아요, 죄송합니다", at: "12:18" },
    ],
  },
];

export const MY_VERIFICATION: MyVerification = {
  phoneVerified: true,
  homeVerified: true,
  homeAddress: "서울 마포구 합정동",
  homeVerifiedAt: "2025.10.03",
  workVerified: true,
  workAddress: "서울 강남구 역삼동",
  workVerifiedAt: "2025.10.03",
  loginDevices: [
    { device: "iPhone 16 Pro", location: "서울 마포구", at: "2026.02.13 08:12", current: true },
    { device: "iPhone 16 Pro", location: "서울 강남구", at: "2026.02.12 18:02", current: false },
    { device: "Galaxy Tab S9", location: "서울 마포구", at: "2026.01.29 21:40", current: false },
  ],
  blockedUsers: [
    { id: "b1", nickname: "급처가격흥정", blockedAt: "2025.11.18" },
    { id: "b2", nickname: "새벽3시연락", blockedAt: "2026.01.02" },
  ],
};

/* ── 관리자 ── */

export const ADMIN_MEMBERS: AdminMember[] = [
  { id: "a1", nickname: "판교출근러", joinedAt: "2025.10.02", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 94, dealCount: 58, reportCount: 0, status: "정상" },
  { id: "a2", nickname: "새벽기차", joinedAt: "2025.10.09", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 76, dealCount: 12, reportCount: 1, status: "정상" },
  { id: "a3", nickname: "이차선라이더", joinedAt: "2025.10.15", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 91, dealCount: 33, reportCount: 0, status: "정상" },
  { id: "a4", nickname: "우주정거장", joinedAt: "2025.11.02", phoneVerified: true, homeVerified: true, workVerified: false, trustScore: 68, dealCount: 7, reportCount: 2, status: "주의" },
  { id: "a5", nickname: "2호선정주민", joinedAt: "2025.11.20", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 85, dealCount: 19, reportCount: 0, status: "정상" },
  { id: "a6", nickname: "야근각", joinedAt: "2025.12.04", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 72, dealCount: 9, reportCount: 1, status: "정상" },
  { id: "a7", nickname: "급처가격흥정", joinedAt: "2025.12.19", phoneVerified: true, homeVerified: false, workVerified: false, trustScore: 31, dealCount: 2, reportCount: 4, status: "정지" },
  { id: "a8", nickname: "새벽3시연락", joinedAt: "2026.01.06", phoneVerified: true, homeVerified: true, workVerified: false, trustScore: 44, dealCount: 3, reportCount: 3, status: "정지" },
  { id: "a9", nickname: "합정역도보7분", joinedAt: "2025.10.03", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 87, dealCount: 24, reportCount: 0, status: "정상" },
  { id: "a10", nickname: "잠실나루러너", joinedAt: "2026.01.24", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 63, dealCount: 4, reportCount: 0, status: "정상" },
  { id: "a11", nickname: "성수동공방", joinedAt: "2026.02.02", phoneVerified: true, homeVerified: true, workVerified: true, trustScore: 58, dealCount: 2, reportCount: 1, status: "주의" },
  { id: "a12", nickname: "종로퇴근9시", joinedAt: "2026.02.11", phoneVerified: false, homeVerified: true, workVerified: false, trustScore: 20, dealCount: 0, reportCount: 0, status: "정상" },
];

export const REPORTS: Report[] = [
  {
    id: "r1",
    type: "사기의심",
    targetType: "회원",
    targetLabel: "급처가격흥정",
    reporterNickname: "이차선라이더",
    reportedNickname: "급처가격흥정",
    status: "완료",
    createdAt: "2025.12.20",
    memo: "선입금 요구 후 연락 두절 신고. 계좌 확인 결과 동일 수법 3건 확인되어 영구정지 처리.",
    penalty: "영구정지",
  },
  {
    id: "r2",
    type: "허위매물",
    targetType: "상품",
    targetLabel: "아이폰 15 프로 미개봉 (삭제됨)",
    reporterNickname: "2호선정주민",
    reportedNickname: "새벽3시연락",
    status: "완료",
    createdAt: "2026.01.08",
    memo: "타 사이트 도용 사진 확인, 게시글 삭제 및 경고 처리.",
    penalty: "경고",
  },
  {
    id: "r3",
    type: "욕설/비매너",
    targetType: "채팅",
    targetLabel: "채팅방 #c-9910",
    reporterNickname: "야근각",
    reportedNickname: "새벽3시연락",
    status: "완료",
    createdAt: "2026.01.15",
    memo: "채팅 내 반복 욕설 확인, 7일 정지 처리.",
    penalty: "7일 정지",
  },
  {
    id: "r4",
    type: "개인정보노출",
    targetType: "채팅",
    targetLabel: "채팅방 #c-10042",
    reporterNickname: "판교출근러",
    reportedNickname: "우주정거장",
    status: "처리중",
    createdAt: "2026.02.09",
  },
  {
    id: "r5",
    type: "웨이스팟오남용",
    targetType: "회원",
    targetLabel: "우주정거장",
    reporterNickname: "새벽기차",
    reportedNickname: "우주정거장",
    status: "대기",
    createdAt: "2026.02.12",
  },
  {
    id: "r6",
    type: "허위매물",
    targetType: "상품",
    targetLabel: "듀얼센스 컨트롤러 화이트",
    reporterNickname: "성수동공방",
    reportedNickname: "야근각",
    status: "대기",
    createdAt: "2026.02.13",
  },
  {
    id: "r7",
    type: "사기의심",
    targetType: "회원",
    targetLabel: "성수동공방",
    reporterNickname: "잠실나루러너",
    reportedNickname: "성수동공방",
    status: "대기",
    createdAt: "2026.02.13",
  },
  {
    id: "r8",
    type: "욕설/비매너",
    targetType: "채팅",
    targetLabel: "채팅방 #c-10101",
    reporterNickname: "이차선라이더",
    reportedNickname: "급처가격흥정",
    status: "완료",
    createdAt: "2025.11.25",
    memo: "일회성 언쟁으로 확인, 양측 안내 후 조치없음.",
    penalty: "조치없음",
  },
];

export const ADMIN_POSTS: AdminPost[] = [
  { id: "ap1", title: "맥북 에어 M1 13인치 골드", photoId: 1, sellerNickname: "판교출근러", price: 780000, status: "판매중", reportCount: 0, postedAt: "2026.01.14" },
  { id: "ap2", title: "아이패드 프로 11 128G 실버", photoId: 6, sellerNickname: "이차선라이더", price: 620000, status: "판매중", reportCount: 0, postedAt: "2026.01.20" },
  { id: "ap3", title: "맥북 프로 14 M2 스페이스그레이", photoId: 48, sellerNickname: "새벽기차", price: 1650000, status: "예약중", reportCount: 0, postedAt: "2025.12.28" },
  { id: "ap4", title: "듀얼센스 컨트롤러 화이트", photoId: 96, sellerNickname: "야근각", price: 42000, status: "신고접수", reportCount: 1, postedAt: "2026.01.05" },
  { id: "ap5", title: "아이폰 15 프로 미개봉 (도용사진)", photoId: 160, sellerNickname: "새벽3시연락", price: 890000, status: "숨김처리", reportCount: 3, postedAt: "2026.01.07" },
  { id: "ap6", title: "필름카메라 야시카 T4", photoId: 91, sellerNickname: "2호선정주민", price: 340000, status: "판매중", reportCount: 0, postedAt: "2026.02.03" },
  { id: "ap7", title: "무선 헤드폰 (거의 새것)", photoId: 26, sellerNickname: "2호선정주민", price: 110000, status: "판매중", reportCount: 0, postedAt: "2026.02.10" },
  { id: "ap8", title: "선입금 유도 의심 게시글", photoId: 60, sellerNickname: "급처가격흥정", price: 250000, status: "숨김처리", reportCount: 4, postedAt: "2025.12.19" },
  { id: "ap9", title: "홈오피스 책상+체어 세트", photoId: 445, sellerNickname: "새벽기차", price: 150000, status: "판매중", reportCount: 0, postedAt: "2025.10.06" },
  { id: "ap10", title: "여성 구두 235 (라운드토)", photoId: 21, sellerNickname: "우주정거장", price: 28000, status: "판매중", reportCount: 0, postedAt: "2026.01.28" },
];

export const NOTICES: NoticeItem[] = [
  { id: "n1", title: "설 연휴 고객센터 운영시간 안내", body: "2026년 2월 16일부터 2월 18일까지 고객센터 운영이 축소됩니다. 신고 접수는 평소와 동일하게 처리됩니다.", publishedAt: "2026.02.10", pinned: true },
  { id: "n2", title: "웨이스팟 안전도 산정 기준 개편 안내", body: "2월부터 시간대별 유동인구 데이터를 반영해 웨이스팟 안전도 점수 산정 방식을 개선했습니다.", publishedAt: "2026.02.01", pinned: true },
  { id: "n3", title: "듀얼 인증(집+회사) 안내 강화", body: "가입 시 듀얼 GPS 인증 완료율을 높이기 위해 온보딩 안내 문구를 개선했습니다.", publishedAt: "2026.01.12", pinned: false },
  { id: "n4", title: "2025년 4분기 신뢰지수 개편 안내", body: "시간 약속 준수율과 응답률 반영 비중을 조정해 신뢰지수 체감도를 높였습니다.", publishedAt: "2025.11.03", pinned: false },
];

export const PUSH_LOGS: PushLog[] = [
  { id: "pl1", title: "판교역 근처 새 매물이 3건 올라왔어요", segment: "판교역 반경 1km 이용자", sentAt: "2026.02.12 08:00", openRate: 41 },
  { id: "pl2", title: "내 동선 홈, 지금 확인해보세요", segment: "듀얼 인증 완료 전체", sentAt: "2026.02.05 18:30", openRate: 33 },
  { id: "pl3", title: "웨이스팟에서 안전하게 거래하는 방법", segment: "가입 7일 이내 신규회원", sentAt: "2026.01.20 10:00", openRate: 52 },
  { id: "pl4", title: "연말 정산, 안 쓰는 물건 정리해보세요", segment: "전체 회원", sentAt: "2025.12.28 09:00", openRate: 28 },
];

export const DASHBOARD_MEMBER_TREND = [
  { label: "10월", value: 2140 },
  { label: "11월", value: 2960 },
  { label: "12월", value: 3820 },
  { label: "1월", value: 5140 },
  { label: "2월", value: 6380, emphasis: true },
];

export const DASHBOARD_DEAL_TREND = [
  { label: "10월", value: 410 },
  { label: "11월", value: 588 },
  { label: "12월", value: 702 },
  { label: "1월", value: 934 },
  { label: "2월", value: 1120, emphasis: true },
];

export const DASHBOARD_CATEGORY_SHARE = [
  { label: "전자기기", value: 412, caption: "412건" },
  { label: "가구/인테리어", value: 188, caption: "188건" },
  { label: "취미/악기", value: 151, caption: "151건" },
  { label: "패션/잡화", value: 96, caption: "96건" },
  { label: "생활가전", value: 74, caption: "74건" },
];
