import type {
  AdminMember,
  AdminReport,
  AppNotification,
  BoardPost,
  CertRequest,
  ChatRoom,
  CollabRequest,
  Company,
  EventItem,
  FeedPost,
  Mentor,
  ProgramItem,
  Question,
} from "./types";

import coverA from "@/projects/community/linkon/assets/company-a.jpg";
import coverB from "@/projects/community/linkon/assets/company-b.jpg";
import coverC from "@/projects/community/linkon/assets/company-c.jpg";
import coverD from "@/projects/community/linkon/assets/company-d.jpg";
import coverE from "@/projects/community/linkon/assets/company-e.jpg";
import coverF from "@/projects/community/linkon/assets/company-f.jpg";
import coverG from "@/projects/community/linkon/assets/company-g.jpg";
import coverH from "@/projects/community/linkon/assets/company-h.jpg";
import coverI from "@/projects/community/linkon/assets/company-i.jpg";
import coverJ from "@/projects/community/linkon/assets/company-j.jpg";
import coverK from "@/projects/community/linkon/assets/company-k.jpg";
import coverL from "@/projects/community/linkon/assets/company-l.jpg";
import eventNetworking from "@/projects/community/linkon/assets/event-networking.jpg";
import eventDemoday from "@/projects/community/linkon/assets/event-demoday.jpg";
import eventSeminar from "@/projects/community/linkon/assets/event-seminar.jpg";
import eventEducation from "@/projects/community/linkon/assets/event-education.jpg";
import eventReview from "@/projects/community/linkon/assets/event-review.jpg";
import feedRecycled from "@/projects/community/linkon/assets/feed-recycled.jpg";
import feedNetworking from "@/projects/community/linkon/assets/feed-networking.jpg";
import feedPopup from "@/projects/community/linkon/assets/feed-popup.jpg";
import chatSite from "@/projects/community/linkon/assets/chat-site.jpg";

// 모든 기관명·기업명·인물·연락처·사업자번호는 실존 대상과 무관한 목업 데이터다.
//
// 사진은 `assets/`에 내려받아 정적으로 임포트한다. 전부 직접 열어 내용을 확인한 뒤
// 화면 문구에 맞게 짝지은 것이므로, 문구를 바꿀 때 사진도 함께 확인할 것.
//   company-a 설비 부품 분해도 · company-b 흙 위 폐플라스틱 · company-c 스마트폰
//   company-d 관절형 기구 · company-e 도로 위 차량 · company-f 손질 중인 채소
//   company-g 펼친 책 · company-h 공구가 걸린 작업장 · company-i 수확이 끝난 밭
//   company-j 카메라를 든 사람 · company-k 벤치에 앉은 두 사람 · company-l 제품 촬영
//   event-networking 공용 테이블이 있는 카페 · event-demoday 강당 좌석
//   event-seminar 데스크 셋업 · event-education 노트와 교재 · event-review 창가에 모인 사람들
//   feed-recycled 담장에 걸린 유리병 · feed-networking 카페 내부 · feed-popup 조명이 걸린 골목
//   chat-site 작업장 현장 사진

export const CHAT_SITE_PHOTO = chatSite.src;

export const TODAY = "2026-07-27";

export const INSTITUTIONS = [
  "나인창업지원재단",
  "한강테크브리지",
  "미래산업진흥원 창업지원단",
  "세움창업허브",
  "서해권 창업보육센터",
];

export const PROGRAMS = [
  "2026 초기창업패키지",
  "2026 예비창업패키지",
  "입주기업 3기",
  "글로벌 스케일업 트랙",
  "딥테크 챌린지 2026",
];

export const CURRENT_USER = {
  name: "정하윤",
  role: "사업개발 리드",
  email: "hayoon.jung@a-tech.kr",
  companyId: "co-a",
  interests: ["제조 AI", "스마트팩토리", "데이터 인프라", "친환경 소재"],
};

export const COMPANIES: Company[] = [
  {
    id: "co-a",
    name: "A테크",
    enName: "A Tech",
    mark: "DL",
    tone: "accent",
    logo: { shape: "grid", color: "#2F5D62" },
    cover: coverA.src,
    industry: "AI·데이터",
    oneLiner: "설비 진동 데이터로 고장을 7일 먼저 잡아내는 예지보전 솔루션",
    description:
      "A테크는 중소 제조 현장의 노후 설비에 저비용 진동·전류 센서를 부착하고, 자체 학습한 이상탐지 모델로 고장 시점을 예측합니다. 별도 PLC 개조 없이 2주 안에 설치가 끝나며, 현재 금형·사출 라인 34곳에서 운영 중입니다.",
    services: ["설비 예지보전 SaaS", "센서 키트 임대", "생산라인 데이터 컨설팅"],
    keywords: ["제조 AI", "스마트팩토리", "예지보전", "IoT 센서"],
    region: "경기 안산",
    employees: 14,
    foundedYear: 2023,
    stage: "프리A",
    invested: true,
    investment: "투자 유치 12억원 (2026.03)",
    collabStatus: "협업 가능",
    ceo: "서지훈",
    manager: {
      name: "정하윤",
      role: "사업개발 리드",
      email: "hayoon.jung@a-tech.kr",
      phone: "010-4728-1163",
    },
    institution: "나인창업지원재단",
    program: "2026 초기창업패키지",
    verifiedAt: "2026-03-11",
    tech: [
      { label: "이상탐지 모델", detail: "비지도 학습 기반, 라벨 없는 설비도 14일 학습 후 적용" },
      { label: "엣지 게이트웨이", detail: "공장 내부망만으로 동작, 외부 반출 없이 온프레미스 추론" },
      { label: "설비 데이터 표준화", detail: "8개 제조사 PLC 프로토콜 어댑터 내장" },
    ],
    projects: [
      {
        title: "사출 라인 예지보전 실증",
        period: "2025.09 - 2026.02",
        partner: "H로보틱스",
        result: "계획외 정지 시간 41% 감소",
      },
      {
        title: "금형 공장 에너지 사용 분석",
        period: "2026.03 - 2026.06",
        partner: "E모빌리티",
        result: "야간 피크 전력 18% 절감",
      },
    ],
    openCollabs: [
      {
        title: "설비 데이터 라벨링 자동화 공동 연구",
        need: "비전 검사 데이터 보유 기업",
        deadline: "2026-08-20",
        applicants: 4,
      },
    ],
    joinedAt: "2026-03-11",
  },
  {
    id: "co-b",
    name: "B소재",
    enName: "B Materials",
    mark: "NT",
    tone: "neutral",
    logo: { shape: "leaf", color: "#3E6B47" },
    cover: coverB.src,
    industry: "친환경·에너지",
    oneLiner: "폐어망을 산업용 재생 원료로 되돌리는 해양 폐기물 리사이클링",
    description:
      "B소재는 남해안 어촌계에서 수거한 폐어망을 세척·분리해 나일론 재생 펠릿으로 가공합니다. 재생 펠릿은 아웃도어 원단과 자동차 내장재로 공급되며, 수거부터 출하까지 전 과정을 이력 데이터로 관리합니다.",
    services: ["재생 나일론 펠릿 공급", "폐어망 수거 네트워크 운영", "탄소 저감 리포트"],
    keywords: ["친환경 소재", "순환경제", "ESG", "소재 공급"],
    region: "부산 사하",
    employees: 21,
    foundedYear: 2022,
    stage: "시리즈A",
    invested: true,
    investment: "투자 유치 38억원 (2026.01)",
    collabStatus: "협업 가능",
    ceo: "문세라",
    manager: {
      name: "배준호",
      role: "파트너십 매니저",
      email: "junho.bae@b-materials.kr",
      phone: "010-2214-8890",
    },
    institution: "서해권 창업보육센터",
    program: "글로벌 스케일업 트랙",
    verifiedAt: "2025-11-04",
    tech: [
      { label: "저온 세척 공정", detail: "염분·부착생물 제거 시 용수 사용량 기존 대비 절반" },
      { label: "이력 추적 시스템", detail: "수거 어촌계, 중량, 재생률을 배치 단위로 기록" },
    ],
    projects: [
      {
        title: "아웃도어 브랜드 재생 원단 공동 개발",
        period: "2025.05 - 2026.01",
        partner: "I커머스",
        result: "재생 원사 12톤 납품",
      },
    ],
    openCollabs: [
      {
        title: "재생 펠릿 적용 사출 제품 공동 기획",
        need: "사출 금형 보유 제조사",
        deadline: "2026-09-05",
        applicants: 7,
      },
      {
        title: "탄소 저감 데이터 검증 파트너",
        need: "환경 데이터 분석 역량",
        deadline: "2026-08-14",
        applicants: 2,
      },
    ],
    joinedAt: "2025-11-04",
  },
  {
    id: "co-c",
    name: "C페이",
    enName: "C Pay",
    mark: "FP",
    tone: "ink",
    logo: { shape: "arc", color: "#33518A" },
    cover: coverC.src,
    industry: "핀테크",
    oneLiner: "여러 배달·예약 플랫폼 정산을 한 화면에서 맞춰주는 자영업 정산 도구",
    description:
      "C페이은 배달 플랫폼, 예약 앱, 카드 매입 데이터를 한 번에 모아 실제 입금액과 예상 정산액의 차이를 자동으로 찾아냅니다. 누락 건은 이의제기 서식까지 만들어 주며 현재 가맹점 2,140곳이 사용합니다.",
    services: ["정산 대사 자동화", "세무 대리인 연동 리포트", "매출 예측"],
    keywords: ["소상공인", "정산", "회계 자동화", "데이터 연동"],
    region: "서울 성동",
    employees: 9,
    foundedYear: 2024,
    stage: "시드",
    invested: true,
    investment: "투자 유치 5억원 (2025.12)",
    collabStatus: "협업 진행중",
    ceo: "임도경",
    manager: {
      name: "임도경",
      role: "대표",
      email: "dk.lim@c-pay.kr",
      phone: "010-3390-5521",
    },
    institution: "나인창업지원재단",
    program: "입주기업 3기",
    verifiedAt: "2026-01-19",
    tech: [
      { label: "정산 대사 엔진", detail: "플랫폼별 수수료 규칙 47종을 룰셋으로 관리" },
      { label: "이의제기 자동 서식", detail: "누락 건 근거 자료를 PDF로 자동 생성" },
    ],
    projects: [
      {
        title: "프랜차이즈 본부 정산 파일럿",
        period: "2026.02 - 2026.06",
        partner: "F푸드",
        result: "가맹점당 월 3.2시간 절감",
      },
    ],
    openCollabs: [],
    joinedAt: "2026-01-19",
  },
  {
    id: "co-d",
    name: "D메디",
    enName: "D Medi",
    mark: "MD",
    tone: "neutral",
    logo: { shape: "cross", color: "#7A4459" },
    cover: coverD.src,
    industry: "헬스케어",
    oneLiner: "무릎 인공관절 수술 후 재활을 집에서 이어가는 원격 운동 코칭",
    description:
      "D메디은 정형외과 퇴원 환자가 집에서 재활 운동을 이어갈 수 있도록 동작 인식 카메라와 물리치료사 원격 피드백을 결합했습니다. 협력 병원 11곳에서 퇴원 프로그램으로 사용 중입니다.",
    services: ["원격 재활 코칭", "동작 정확도 분석", "병원용 경과 리포트"],
    keywords: ["디지털 치료", "재활", "동작 인식", "병원 연계"],
    region: "서울 송파",
    employees: 17,
    foundedYear: 2023,
    stage: "프리A",
    invested: true,
    investment: "투자 유치 15억원 (2025.10)",
    collabStatus: "협업 가능",
    ceo: "한가온",
    manager: {
      name: "노유진",
      role: "임상협력 팀장",
      email: "yujin.noh@d-medi.kr",
      phone: "010-8871-4402",
    },
    institution: "한강테크브리지",
    program: "딥테크 챌린지 2026",
    verifiedAt: "2025-09-22",
    tech: [
      { label: "관절 각도 추정", detail: "일반 웹캠으로 무릎 굴곡 각도 오차 3.4도 이내" },
      { label: "재활 순응도 스코어", detail: "수행 횟수와 자세 품질을 함께 반영" },
    ],
    projects: [
      {
        title: "인공관절 퇴원 프로그램 실증",
        period: "2025.06 - 2026.03",
        partner: "K케어",
        result: "8주 순응도 62% → 84%",
      },
    ],
    openCollabs: [
      {
        title: "고령자 대상 사용성 개선 공동 연구",
        need: "시니어 대상 서비스 운영 경험",
        deadline: "2026-08-29",
        applicants: 3,
      },
    ],
    joinedAt: "2025-09-22",
  },
  {
    id: "co-e",
    name: "E모빌리티",
    enName: "E Mobility",
    mark: "GW",
    tone: "accent",
    logo: { shape: "bolt", color: "#47525E" },
    cover: coverE.src,
    industry: "모빌리티",
    oneLiner: "아파트 지하주차장 전기차 충전 부하를 시간대로 나눠주는 제어 소프트웨어",
    description:
      "E모빌리티는 수전 용량을 늘리지 않고도 충전기를 늘릴 수 있도록 세대별 사용 패턴에 맞춰 충전 순서를 배분합니다. 관리사무소용 요금 정산 화면과 입주민 앱을 함께 제공합니다.",
    services: ["충전 부하 분산 제어", "관리사무소 정산", "충전 이용 분석"],
    keywords: ["전기차", "에너지 관리", "공동주택", "부하 분산"],
    region: "경기 성남",
    employees: 12,
    foundedYear: 2023,
    stage: "시리즈A",
    invested: true,
    investment: "투자 유치 27억원 (2026.05)",
    collabStatus: "협업 가능",
    ceo: "오재원",
    manager: {
      name: "신아름",
      role: "사업개발 매니저",
      email: "areum.shin@e-mobility.kr",
      phone: "010-5527-3318",
    },
    institution: "미래산업진흥원 창업지원단",
    program: "글로벌 스케일업 트랙",
    verifiedAt: "2025-08-13",
    tech: [
      { label: "부하 배분 알고리즘", detail: "수전 용량 초과 없이 동시 충전 대수 2.6배 확대" },
      { label: "요금 정산 모듈", detail: "세대별 사용량을 관리비 청구서 형식으로 출력" },
    ],
    projects: [
      {
        title: "1,200세대 단지 실증",
        period: "2025.11 - 2026.04",
        partner: "A테크",
        result: "피크 전력 초과 경보 0건",
      },
    ],
    openCollabs: [
      {
        title: "충전 데이터 기반 배터리 진단 협업",
        need: "배터리 상태 진단 기술",
        deadline: "2026-09-12",
        applicants: 5,
      },
    ],
    joinedAt: "2025-08-13",
  },
  {
    id: "co-f",
    name: "F푸드",
    enName: "F Food",
    mark: "TF",
    tone: "neutral",
    logo: { shape: "wave", color: "#6A7A3A" },
    cover: coverF.src,
    industry: "푸드테크",
    oneLiner: "단체급식 식수 예측으로 잔반과 결품을 동시에 줄이는 발주 도우미",
    description:
      "F푸드은 학교와 기업 구내식당의 과거 식수, 메뉴 선호, 일정 데이터를 학습해 다음 주 식수를 예측하고 발주 수량을 제안합니다. 영양사 확정 한 번으로 거래처 발주서까지 전송됩니다.",
    services: ["식수 예측", "발주 자동화", "잔반 리포트"],
    keywords: ["급식", "수요예측", "푸드 로스", "발주"],
    region: "대전 유성",
    employees: 8,
    foundedYear: 2024,
    stage: "시드",
    invested: false,
    collabStatus: "협업 가능",
    ceo: "곽민서",
    manager: {
      name: "곽민서",
      role: "대표",
      email: "minseo.kwak@f-food.kr",
      phone: "010-7742-9016",
    },
    institution: "세움창업허브",
    program: "2026 초기창업패키지",
    verifiedAt: "2026-04-02",
    tech: [
      { label: "식수 예측 모델", detail: "학사일정·날씨·메뉴 선호 반영, 평균 오차 4.7%" },
      { label: "발주 연동", detail: "식자재 유통사 3곳 EDI 규격 지원" },
    ],
    projects: [
      {
        title: "고교 급식실 잔반 저감 시범",
        period: "2026.03 - 2026.07",
        partner: "G에듀",
        result: "잔반량 주당 96kg 감소",
      },
    ],
    openCollabs: [
      {
        title: "식자재 유통사 연동 파트너 모집",
        need: "지역 식자재 유통 네트워크",
        deadline: "2026-08-31",
        applicants: 6,
      },
    ],
    joinedAt: "2026-04-02",
  },
  {
    id: "co-g",
    name: "G에듀",
    enName: "G Edu",
    mark: "CB",
    tone: "ink",
    logo: { shape: "stack", color: "#8A6A21" },
    cover: coverG.src,
    industry: "에듀테크",
    oneLiner: "직업계고 실습 수업을 위한 산업 현장형 과제 콘텐츠 플랫폼",
    description:
      "G에듀는 제조·물류 기업의 실제 업무 과제를 교사가 수업에서 쓸 수 있는 실습 모듈로 재구성합니다. 학생 결과물은 참여 기업이 직접 피드백하며, 채용 연계 트랙으로 이어집니다.",
    services: ["실습 콘텐츠 제작", "기업 연계 과제 운영", "교사 연수"],
    keywords: ["직업교육", "산학협력", "실습 콘텐츠", "채용 연계"],
    region: "인천 연수",
    employees: 11,
    foundedYear: 2022,
    stage: "프리A",
    invested: false,
    collabStatus: "협업 진행중",
    ceo: "유선재",
    manager: {
      name: "고은비",
      role: "콘텐츠 총괄",
      email: "eunbi.ko@g-edu.kr",
      phone: "010-6608-2277",
    },
    institution: "한강테크브리지",
    program: "입주기업 3기",
    verifiedAt: "2025-06-30",
    tech: [
      { label: "과제 모듈화 프레임", detail: "기업 과제를 4차시 실습 단위로 분해하는 템플릿" },
      { label: "평가 루브릭", detail: "기업 피드백과 교과 성취기준을 함께 채점" },
    ],
    projects: [
      {
        title: "물류 자동화 실습 과정 개발",
        period: "2025.08 - 2026.02",
        partner: "H로보틱스",
        result: "27개교 도입, 수료생 612명",
      },
    ],
    openCollabs: [],
    joinedAt: "2025-06-30",
  },
  {
    id: "co-h",
    name: "H로보틱스",
    enName: "H Robotics",
    mark: "OB",
    tone: "neutral",
    logo: { shape: "notch", color: "#A2543A" },
    cover: coverH.src,
    industry: "제조·하드웨어",
    oneLiner: "좁은 통로형 창고에 그대로 들어가는 모듈형 소형 물류 로봇",
    description:
      "H로보틱스은 기존 랙 구조를 바꾸지 않고 투입할 수 있는 폭 62cm 이송 로봇을 만듭니다. 적재 모듈을 교체해 파렛트, 박스, 행거 이송에 모두 대응하며 중소 물류센터를 주 고객으로 합니다.",
    services: ["소형 이송 로봇 공급", "창고 동선 설계", "로봇 운영 관제"],
    keywords: ["물류 자동화", "로보틱스", "하드웨어", "창고"],
    region: "경기 화성",
    employees: 26,
    foundedYear: 2021,
    stage: "시리즈B",
    invested: true,
    investment: "투자 유치 90억원 (2026.02)",
    collabStatus: "모집 마감",
    ceo: "천상우",
    manager: {
      name: "박도현",
      role: "전략기획 팀장",
      email: "dohyun.park@h-robotics.kr",
      phone: "010-2298-7714",
    },
    institution: "미래산업진흥원 창업지원단",
    program: "딥테크 챌린지 2026",
    verifiedAt: "2025-04-17",
    tech: [
      { label: "협소 통로 주행", detail: "폭 700mm 통로에서 회전 반경 없이 측면 이동" },
      { label: "모듈 교체 구조", detail: "적재부 교체 3분, 공구 없이 체결" },
    ],
    projects: [
      {
        title: "중형 물류센터 자동화 도입",
        period: "2025.03 - 2026.01",
        partner: "I커머스",
        result: "피킹 동선 하루 6.4km 단축",
      },
    ],
    openCollabs: [],
    joinedAt: "2025-04-17",
  },
  {
    id: "co-i",
    name: "I커머스",
    enName: "I Commerce",
    mark: "SS",
    tone: "accent",
    logo: { shape: "orbit", color: "#6A7A3A" },
    cover: coverI.src,
    industry: "커머스",
    oneLiner: "산지 농가가 직접 여는 주 1회 정기 판매 커머스",
    description:
      "I커머스은 농가가 수확 일정에 맞춰 판매 회차를 열고 소비자가 미리 예약하는 방식으로 재고 부담 없이 직거래를 만듭니다. 포장·배송 대행과 정산까지 한 번에 처리합니다.",
    services: ["농가 정기 판매 운영", "합포장 물류 대행", "판매 데이터 리포트"],
    keywords: ["D2C", "농산물", "정기배송", "산지직송"],
    region: "전북 완주",
    employees: 15,
    foundedYear: 2022,
    stage: "시리즈A",
    invested: true,
    investment: "투자 유치 22억원 (2025.09)",
    collabStatus: "협업 가능",
    ceo: "여지수",
    manager: {
      name: "최연우",
      role: "제휴 담당",
      email: "yeonwoo.choi@i-commerce.kr",
      phone: "010-4416-3320",
    },
    institution: "서해권 창업보육센터",
    program: "2026 초기창업패키지",
    verifiedAt: "2025-12-08",
    tech: [
      { label: "회차형 판매 엔진", detail: "예약 수량에 맞춰 수확·포장 물량을 자동 확정" },
      { label: "합포장 라우팅", detail: "인접 농가 주문을 묶어 배송비 27% 절감" },
    ],
    projects: [
      {
        title: "재생 포장재 전환 프로젝트",
        period: "2026.01 - 2026.05",
        partner: "B소재",
        result: "플라스틱 포장재 사용량 34% 감축",
      },
    ],
    openCollabs: [
      {
        title: "지역 축제 연계 팝업 판매 공동 운영",
        need: "오프라인 리테일 운영 경험",
        deadline: "2026-08-18",
        applicants: 8,
      },
    ],
    joinedAt: "2025-12-08",
  },
  {
    id: "co-j",
    name: "J스튜디오",
    enName: "J Studio",
    mark: "FS",
    tone: "ink",
    logo: { shape: "ring", color: "#47525E" },
    cover: coverJ.src,
    industry: "콘텐츠",
    oneLiner: "매장 촬영 영상을 브랜드 톤에 맞춘 숏폼으로 자동 편집",
    description:
      "J스튜디오은 자영업자와 소규모 브랜드가 찍은 원본 영상을 업종별 편집 규칙에 맞춰 숏폼으로 만들어 줍니다. 자막 톤, 컷 길이, 배경음까지 브랜드 프리셋으로 저장해 재사용합니다.",
    services: ["숏폼 자동 편집", "브랜드 프리셋 관리", "성과 분석"],
    keywords: ["숏폼", "브랜드 마케팅", "영상 자동화", "소상공인"],
    region: "서울 마포",
    employees: 7,
    foundedYear: 2024,
    stage: "예비창업",
    invested: false,
    collabStatus: "협업 가능",
    ceo: "봉태리",
    manager: {
      name: "봉태리",
      role: "대표",
      email: "taeri.bong@j-studio.kr",
      phone: "010-9932-1148",
    },
    institution: "세움창업허브",
    program: "2026 예비창업패키지",
    verifiedAt: "2026-06-24",
    tech: [
      { label: "컷 자동 선별", detail: "흔들림·무음 구간을 제거하고 하이라이트 우선 배치" },
      { label: "브랜드 프리셋", detail: "자막 서체, 컬러, 배경음을 계정 단위로 고정" },
    ],
    projects: [
      {
        title: "지역 상권 숏폼 제작 지원",
        period: "2026.04 - 2026.07",
        partner: "I커머스",
        result: "참여 매장 88곳, 영상 1,320편",
      },
    ],
    openCollabs: [
      {
        title: "브랜드 촬영 협업 파트너",
        need: "제품 촬영 스튜디오 보유",
        deadline: "2026-08-09",
        applicants: 1,
      },
    ],
    joinedAt: "2026-06-24",
  },
  {
    id: "co-k",
    name: "K케어",
    enName: "K Care",
    mark: "CL",
    tone: "neutral",
    logo: { shape: "chevron", color: "#7A4459" },
    cover: coverK.src,
    industry: "헬스케어",
    oneLiner: "요양기관과 보호자를 잇는 일상 기록 공유 서비스",
    description:
      "K케어는 요양보호사가 남긴 식사, 복약, 활동 기록을 보호자가 앱에서 바로 확인하도록 정리합니다. 기록은 장기요양 급여 서류 양식으로도 출력됩니다.",
    services: ["돌봄 기록 앱", "보호자 알림", "급여 서류 자동 작성"],
    keywords: ["시니어케어", "요양", "보호자 소통", "돌봄 기록"],
    region: "대구 수성",
    employees: 10,
    foundedYear: 2023,
    stage: "시드",
    invested: false,
    collabStatus: "협업 가능",
    ceo: "진세희",
    manager: {
      name: "진세희",
      role: "대표",
      email: "sehee.jin@k-care.kr",
      phone: "010-3327-6604",
    },
    institution: "나인창업지원재단",
    program: "입주기업 3기",
    verifiedAt: "2026-05-15",
    tech: [
      { label: "음성 기록 입력", detail: "요양보호사가 말로 남긴 기록을 항목별로 분류" },
      { label: "서류 자동 생성", detail: "급여제공기록지 양식 3종 자동 출력" },
    ],
    projects: [
      {
        title: "주야간보호센터 기록 표준화",
        period: "2026.02 - 2026.06",
        partner: "D메디",
        result: "기록 작성 시간 하루 52분 단축",
      },
    ],
    openCollabs: [
      {
        title: "시니어 건강 데이터 연계 협업",
        need: "웨어러블 또는 활동량 데이터",
        deadline: "2026-09-01",
        applicants: 2,
      },
    ],
    joinedAt: "2026-05-15",
  },
  {
    id: "co-l",
    name: "L팩토리",
    enName: "L Factory",
    mark: "LF",
    tone: "accent",
    logo: { shape: "prism", color: "#A2543A" },
    cover: coverL.src,
    industry: "제조·하드웨어",
    oneLiner: "소량 다품종 니트 생산을 24시간 안에 처리하는 디지털 편직 공장",
    description:
      "L팩토리은 디자이너 브랜드의 소량 주문을 자동 편직기로 받아 하루 안에 샘플과 초도 물량을 생산합니다. 도안 파일만 올리면 편직 코드로 변환됩니다.",
    services: ["소량 니트 생산", "도안 자동 변환", "샘플 24시간 제작"],
    keywords: ["패션 제조", "소량생산", "자동화", "니트"],
    region: "서울 중구",
    employees: 13,
    foundedYear: 2021,
    stage: "프리A",
    invested: true,
    investment: "투자 유치 9억원 (2025.07)",
    collabStatus: "협업 진행중",
    ceo: "명하람",
    manager: {
      name: "석지원",
      role: "생산기획 리드",
      email: "jiwon.seok@l-factory.kr",
      phone: "010-8802-5573",
    },
    institution: "한강테크브리지",
    program: "글로벌 스케일업 트랙",
    verifiedAt: "2025-07-21",
    tech: [
      { label: "도안 변환 엔진", detail: "일러스트 파일을 편직기 코드로 자동 변환" },
      { label: "잔사 관리", detail: "실 재고를 색상·수량 단위로 실시간 추적" },
    ],
    projects: [
      {
        title: "재생 원사 니트 라인 개발",
        period: "2026.01 - 2026.06",
        partner: "B소재",
        result: "재생 원사 제품 4종 출시",
      },
    ],
    openCollabs: [],
    joinedAt: "2025-07-21",
  },
];

export function companyById(id: string) {
  return COMPANIES.find((c) => c.id === id);
}

export const MY_COMPANY = companyById(CURRENT_USER.companyId)!;

export const FEED_POSTS: FeedPost[] = [
  {
    id: "f1",
    companyId: "co-b",
    author: "배준호",
    category: "협업 모집",
    content:
      "재생 나일론 펠릿을 사출 제품에 적용해 볼 파트너사를 찾습니다. 저희가 원료와 물성 데이터를 제공하고, 금형과 사출 라인을 가진 기업과 공동으로 시제품을 만들려고 합니다. 첫 목표는 아웃도어 브랜드 납품용 소형 부속입니다.",
    tags: ["재생소재", "사출", "공동개발"],
    image: feedRecycled.src,
    attachment: { name: "재생펠릿_물성요약.pdf", size: "1.4MB" },
    likes: 42,
    saves: 18,
    createdAt: "2026-07-26T09:20:00",
    recruiting: { role: "사출 금형 보유 제조사", deadline: "2026-09-05", positions: 2 },
    comments: [
      {
        id: "f1c1",
        companyId: "co-h",
        author: "박도현",
        content: "물성 데이터시트 먼저 받아볼 수 있을까요. 내부 검토 후 회신드리겠습니다.",
        createdAt: "2026-07-26T11:02:00",
      },
      {
        id: "f1c2",
        companyId: "co-l",
        author: "석지원",
        content: "저희는 사출은 아니지만 원사 쪽으로 이미 협업 중입니다. 물성 이슈 공유 가능해요.",
        createdAt: "2026-07-26T14:41:00",
      },
    ],
  },
  {
    id: "f2",
    companyId: "co-c",
    author: "임도경",
    category: "투자 이야기",
    content:
      "시드 라운드를 마무리하면서 정리한 내용 공유합니다. 심사역이 가장 오래 붙잡은 건 매출 지표가 아니라 이탈 가맹점의 이탈 사유였습니다. 우리 쪽에서 먼저 이탈 코호트를 뜯어 정리해 간 게 결과적으로 가장 큰 도움이 됐습니다.",
    tags: ["시드투자", "IR", "지표"],
    likes: 96,
    saves: 61,
    createdAt: "2026-07-25T17:45:00",
    comments: [
      {
        id: "f2c1",
        companyId: "co-f",
        author: "곽민서",
        content: "이탈 코호트 정리 양식이 있다면 참고하고 싶습니다. 저희도 다음 달 IR입니다.",
        createdAt: "2026-07-25T19:12:00",
      },
    ],
  },
  {
    id: "f3",
    companyId: "co-d",
    author: "노유진",
    category: "정부지원사업",
    content:
      "의료기기 실증 지원사업 신청서를 쓰면서 병원 IRB 일정을 과소평가했다가 한 번 반려됐습니다. 신청 전에 협력 병원 IRB 정기 심의일부터 확인하시길 권합니다. 저희는 심의일 기준으로 일정을 거꾸로 짜서 다시 제출했습니다.",
    tags: ["실증지원", "IRB", "신청팁"],
    likes: 74,
    saves: 55,
    createdAt: "2026-07-24T13:08:00",
    comments: [],
  },
  {
    id: "f4",
    companyId: "co-e",
    author: "신아름",
    category: "행사 후기",
    content:
      "어제 열린 입주기업 네트워킹 데이 후기입니다. 산업별 테이블 배치 덕분에 에너지 분야만 6개 팀을 한 자리에서 만났습니다. 다음 회차에는 실증 부지를 가진 기업과 소프트웨어 기업을 섞어 배치하면 더 좋겠다는 의견을 운영팀에 전달했습니다.",
    tags: ["네트워킹데이", "행사후기"],
    image: feedNetworking.src,
    attachment: { name: "네트워킹데이_참여기업_정리.pdf", size: "820KB" },
    likes: 58,
    saves: 12,
    createdAt: "2026-07-23T10:30:00",
    comments: [
      {
        id: "f4c1",
        companyId: "co-a",
        author: "정하윤",
        content: "저희도 그 테이블에서 실증 협의 하나 시작됐습니다. 배치 방식 계속 유지되면 좋겠어요.",
        createdAt: "2026-07-23T12:20:00",
      },
    ],
  },
  {
    id: "f5",
    companyId: "co-g",
    author: "고은비",
    category: "창업 후기",
    content:
      "교육 콘텐츠는 학교 회계 일정에 매출이 묶입니다. 3월과 9월에 몰리고 그사이는 비어 있습니다. 저희는 방학 기간에 교사 연수 상품을 붙여 비수기를 메웠고, 올해는 연수 매출이 전체의 31%가 됐습니다.",
    tags: ["에듀테크", "매출구조", "운영"],
    likes: 63,
    saves: 40,
    createdAt: "2026-07-22T16:15:00",
    comments: [],
  },
  {
    id: "f6",
    companyId: "co-i",
    author: "최연우",
    category: "협업 모집",
    content:
      "가을 지역 축제 기간에 팝업 매장을 함께 운영할 기업을 찾습니다. 저희가 산지 농가 20곳의 상품과 물류를 맡고, 오프라인 공간 운영과 고객 응대 경험이 있는 팀과 매출을 나누는 구조를 생각하고 있습니다.",
    tags: ["팝업", "오프라인", "지역상생"],
    image: feedPopup.src,
    likes: 37,
    saves: 22,
    createdAt: "2026-07-21T11:05:00",
    recruiting: { role: "오프라인 리테일 운영사", deadline: "2026-08-18", positions: 1 },
    comments: [
      {
        id: "f6c1",
        companyId: "co-j",
        author: "봉태리",
        content: "현장 숏폼 촬영은 저희가 붙을 수 있습니다. 채팅으로 상세 논의 요청드립니다.",
        createdAt: "2026-07-21T13:44:00",
      },
    ],
  },
  {
    id: "f7",
    companyId: "co-h",
    author: "박도현",
    category: "투자 이야기",
    content:
      "하드웨어는 시리즈B에서 실사 항목이 완전히 바뀝니다. 이번에는 재무보다 공급망 이중화와 부품 단종 대응 계획을 훨씬 깊게 봤습니다. 핵심 부품별 대체 벤더 확보 현황표를 미리 만들어 두시길 권합니다.",
    tags: ["시리즈B", "하드웨어", "공급망"],
    likes: 118,
    saves: 87,
    createdAt: "2026-07-20T09:50:00",
    comments: [],
  },
  {
    id: "f8",
    companyId: "co-k",
    author: "진세희",
    category: "정부지원사업",
    content:
      "돌봄 분야는 기관 도입 결정 기간이 길어서 지원사업 성과지표를 계약 건수로 잡으면 위험합니다. 저희는 지표를 시범 운영 기관 수와 기록 건수로 바꿔 제출했고, 중간 점검에서 훨씬 설명이 쉬웠습니다.",
    tags: ["성과지표", "돌봄", "중간점검"],
    likes: 45,
    saves: 33,
    createdAt: "2026-07-19T15:25:00",
    comments: [],
  },
];

export const BOARD_POSTS: BoardPost[] = [
  {
    id: "b1",
    category: "공지사항",
    title: "2026년 하반기 입주기업 정기 간담회 일정 안내",
    summary: "8월 20일 오후 2시, 나인창업지원재단 3층 대회의실에서 진행합니다.",
    content: [
      "2026년 하반기 입주기업 정기 간담회를 아래와 같이 진행합니다. 입주기업 대표 또는 담당자 1인 이상 참석을 부탁드립니다.",
      "일시: 2026년 8월 20일 (목) 14:00 - 16:30 / 장소: 나인창업지원재단 3층 대회의실",
      "안건은 하반기 지원 프로그램 개편, 공용 공간 운영 규칙 변경, 기업 간 협업 지원금 신설 세 가지입니다. 사전 질문은 8월 13일까지 플랫폼 문의 게시판으로 접수해 주시면 당일 답변드립니다.",
    ],
    author: "운영지원팀",
    authorOrg: "나인창업지원재단",
    official: true,
    createdAt: "2026-07-27T09:00:00",
    views: 1284,
    bookmarks: 96,
    tags: ["간담회", "입주기업"],
    attachments: [
      { name: "2026_하반기_간담회_안건.pdf", size: "412KB" },
      { name: "참석_회신서.hwp", size: "68KB" },
    ],
    comments: [
      {
        author: "C페이 임도경",
        content: "협업 지원금 신설 관련해 지급 기준 자료를 사전에 공유해 주실 수 있을까요.",
        createdAt: "2026-07-27T10:22:00",
      },
    ],
    pinned: true,
  },
  {
    id: "b2",
    category: "지원사업",
    title: "2026년 창업도약패키지 하반기 추가 모집 공고",
    summary: "업력 3년 초과 7년 이내 기업 대상, 최대 3억원 사업화 자금 지원.",
    content: [
      "창업도약패키지 하반기 추가 모집을 공고합니다. 업력 3년 초과 7년 이내 기업이 대상이며, 사업화 자금은 최대 3억원까지 지원합니다.",
      "접수 기간: 2026년 8월 3일 09:00 - 8월 24일 18:00 / 접수 방식: 온라인 접수",
      "제출 서류는 사업계획서, 대표자 이력, 최근 3개년 재무제표입니다. 플랫폼 회원사는 첨부된 체크리스트를 활용해 누락 서류를 먼저 확인해 주세요.",
    ],
    author: "사업지원팀",
    authorOrg: "미래산업진흥원 창업지원단",
    official: true,
    createdAt: "2026-07-24T11:30:00",
    deadline: "2026-08-24",
    views: 2467,
    bookmarks: 341,
    tags: ["창업도약패키지", "사업화자금", "모집공고"],
    attachments: [
      { name: "창업도약패키지_공고문.pdf", size: "1.2MB" },
      { name: "사업계획서_양식.docx", size: "184KB" },
      { name: "제출서류_체크리스트.xlsx", size: "42KB" },
    ],
    comments: [
      {
        author: "F푸드 곽민서",
        content: "업력 산정 기준일이 접수 마감일인지 공고일인지 확인 부탁드립니다.",
        createdAt: "2026-07-24T14:05:00",
      },
      {
        author: "사업지원팀",
        content: "공고일 기준입니다. 사업자등록증상 개업일로 산정합니다.",
        createdAt: "2026-07-24T15:10:00",
      },
    ],
  },
  {
    id: "b3",
    category: "투자 정보",
    title: "하반기 시드 투자 심사 흐름과 자료 준비 정리",
    summary: "최근 6개월 회원사 투자 유치 사례에서 반복된 요청 자료를 모았습니다.",
    content: [
      "최근 6개월간 플랫폼 회원사 11곳의 투자 유치 과정을 인터뷰해 공통으로 요청받은 자료를 정리했습니다.",
      "가장 많이 요청된 자료는 코호트별 잔존율, 고객 획득 비용 추이, 핵심 인력 이탈 이력 세 가지였습니다. 반대로 시장 규모 추정 자료는 대부분 참고 수준으로만 다뤄졌습니다.",
      "첨부한 자료 템플릿은 회원사가 제공한 실제 IR 자료를 기업명 제거 후 재구성한 것입니다.",
    ],
    author: "투자지원 데스크",
    authorOrg: "한강테크브리지",
    official: true,
    createdAt: "2026-07-21T13:40:00",
    views: 1876,
    bookmarks: 288,
    tags: ["시드투자", "IR자료", "심사"],
    attachments: [{ name: "IR_자료_템플릿_v3.pptx", size: "3.4MB" }],
    comments: [],
  },
  {
    id: "b4",
    category: "교육 프로그램",
    title: "기술기업을 위한 특허 명세서 작성 실무 교육 (8월 3주차)",
    summary: "변리사와 함께 청구항 작성부터 선행기술 검색까지 실습으로 진행합니다.",
    content: [
      "기술 기반 창업기업을 대상으로 특허 명세서 작성 실무 교육을 진행합니다. 이론 강의 후 참가 기업의 실제 기술을 대상으로 청구항 초안을 작성하는 실습이 이어집니다.",
      "일정: 8월 18일, 8월 20일 각 14:00 - 18:00 (2회차 필수 참석) / 정원: 16개사",
      "참가 기업은 사전에 기술 개요 1장을 제출해야 하며, 제출 자료는 담당 변리사만 열람합니다.",
    ],
    author: "교육운영팀",
    authorOrg: "나인창업지원재단",
    official: true,
    createdAt: "2026-07-18T10:15:00",
    deadline: "2026-08-11",
    views: 942,
    bookmarks: 154,
    tags: ["특허", "교육", "실습"],
    attachments: [{ name: "교육_커리큘럼.pdf", size: "620KB" }],
    comments: [
      {
        author: "A테크 정하윤",
        content: "2회차 중 1회만 참석해도 수료 인정되는지 궁금합니다.",
        createdAt: "2026-07-18T16:48:00",
      },
    ],
  },
  {
    id: "b5",
    category: "창업 자료실",
    title: "기업 간 공동개발 계약서 표준 양식 배포",
    summary: "지식재산 귀속과 성과물 사용 범위 조항을 중심으로 정리한 양식입니다.",
    content: [
      "회원사 간 공동개발이 늘면서 계약 단계에서 반복되는 분쟁 지점을 반영한 표준 양식을 배포합니다.",
      "핵심은 두 가지입니다. 공동개발 결과물의 지식재산 귀속을 기여도 비율이 아니라 사전 합의된 지분으로 명시하는 것, 그리고 각 사가 기존에 보유한 기술의 범위를 계약서 별첨에 구체적으로 적어 두는 것입니다.",
      "법률 검토는 자문 변호사가 진행했으며, 실제 계약 시에는 개별 사안에 맞춘 검토가 필요합니다.",
    ],
    author: "법무지원 데스크",
    authorOrg: "미래산업진흥원 창업지원단",
    official: true,
    createdAt: "2026-07-15T09:20:00",
    views: 1531,
    bookmarks: 402,
    tags: ["계약서", "공동개발", "지식재산"],
    attachments: [
      { name: "공동개발계약서_표준양식.docx", size: "96KB" },
      { name: "조항별_해설.pdf", size: "780KB" },
    ],
    comments: [],
  },
  {
    id: "b6",
    category: "지원사업",
    title: "지역 실증 테스트베드 참여 기업 상시 모집",
    summary: "산업단지 내 실증 부지와 계측 장비를 무상으로 제공합니다.",
    content: [
      "지역 산업단지 내 실증 부지와 계측 장비를 활용할 기업을 상시 모집합니다. 사용료는 없으며 실증 데이터는 기업이 보유합니다.",
      "제공 항목은 실증 공간 82제곱미터, 전력 3상 380V, 환경 계측 장비 6종입니다. 실증 기간은 최대 6개월이며 연장 심의가 가능합니다.",
      "신청은 상시이며, 매월 첫째 주에 심의합니다.",
    ],
    author: "실증지원팀",
    authorOrg: "세움창업허브",
    official: true,
    createdAt: "2026-07-11T14:00:00",
    views: 1103,
    bookmarks: 176,
    tags: ["실증", "테스트베드", "상시모집"],
    attachments: [{ name: "실증부지_안내.pdf", size: "1.1MB" }],
    comments: [],
  },
  {
    id: "b7",
    category: "투자 정보",
    title: "8월 IR 데모데이 참가 기업 모집 (정원 8개사)",
    summary: "벤처캐피털 12곳 심사역이 참석하며, 사전 코칭 2회가 포함됩니다.",
    content: [
      "8월 IR 데모데이에 참가할 기업 8개사를 모집합니다. 참가 확정 기업에는 발표 자료 코칭 2회가 제공됩니다.",
      "행사일: 2026년 8월 28일 (금) 13:00 - 18:00 / 장소: 한강테크브리지 이벤트홀",
      "신청 시 3분 분량 소개 영상과 IR 자료를 함께 제출해 주세요. 선정 결과는 8월 12일에 개별 안내합니다.",
    ],
    author: "투자지원 데스크",
    authorOrg: "한강테크브리지",
    official: true,
    createdAt: "2026-07-08T11:10:00",
    deadline: "2026-08-05",
    views: 2210,
    bookmarks: 367,
    tags: ["데모데이", "IR", "모집"],
    attachments: [{ name: "데모데이_참가신청서.hwp", size: "74KB" }],
    comments: [],
  },
  {
    id: "b8",
    category: "교육 프로그램",
    title: "초기기업 세무 실무: 인건비 처리와 연구인력개발비 세액공제",
    summary: "세무사와 함께 실제 사례 기준으로 계정 처리 방법을 다룹니다.",
    content: [
      "초기 기업이 가장 많이 실수하는 인건비 처리와 연구인력개발비 세액공제 요건을 다룹니다.",
      "일정: 8월 6일 (목) 15:00 - 18:00 / 방식: 온라인 실시간",
      "참여 기업은 사전 질문을 접수할 수 있으며, 강의 후반 1시간은 질의응답으로 운영합니다.",
    ],
    author: "교육운영팀",
    authorOrg: "나인창업지원재단",
    official: true,
    createdAt: "2026-07-04T10:40:00",
    views: 866,
    bookmarks: 121,
    tags: ["세무", "세액공제", "온라인"],
    attachments: [],
    comments: [],
  },
  {
    id: "b9",
    category: "창업 자료실",
    title: "회원사 공동 구매 가능한 클라우드·툴 할인 목록 (7월 갱신)",
    summary: "인프라 크레딧과 협업 도구 할인 조건을 한 번에 정리했습니다.",
    content: [
      "회원사가 사용할 수 있는 인프라 크레딧과 협업 도구 할인 조건을 7월 기준으로 갱신했습니다.",
      "신청은 운영기관을 통해 일괄 접수하며, 크레딧 소진 시 조기 마감될 수 있습니다.",
      "지난 분기 대비 조건이 바뀐 항목은 첨부 파일에 표시해 두었습니다.",
    ],
    author: "운영지원팀",
    authorOrg: "나인창업지원재단",
    official: true,
    createdAt: "2026-07-01T09:30:00",
    views: 1744,
    bookmarks: 259,
    tags: ["할인", "인프라", "운영"],
    attachments: [{ name: "회원사_혜택_목록_2607.xlsx", size: "58KB" }],
    comments: [],
  },
  {
    id: "b10",
    category: "공지사항",
    title: "플랫폼 기업 인증 심사 처리 기간 안내 (평균 1.8영업일)",
    summary: "서류 보완 요청 사유 상위 3가지를 함께 안내합니다.",
    content: [
      "기업 인증 심사는 접수 후 평균 1.8영업일 안에 처리되고 있습니다. 보완 요청이 발생하면 처리 기간이 늘어납니다.",
      "보완 요청 사유는 선정 증빙 서류의 사업 연도 불일치, 사업자등록증 발급일 6개월 초과, 담당자 재직 확인 불가 순으로 많았습니다.",
      "서류는 스캔본 기준 해상도 200dpi 이상, 파일당 10MB 이내로 업로드해 주세요.",
    ],
    author: "인증심사팀",
    authorOrg: "나인창업지원재단",
    official: true,
    createdAt: "2026-06-27T16:00:00",
    views: 1392,
    bookmarks: 88,
    tags: ["기업인증", "심사", "서류"],
    attachments: [],
    comments: [],
  },
];

export const MENTORS: Mentor[] = [
  {
    id: "m1",
    name: "하윤정",
    role: "파트너",
    org: "A벤처스",
    fields: ["투자"],
    career: ["A벤처스 파트너", "초기기업 투자 심사 11년", "누적 검토 기업 1,400곳"],
    answerCount: 218,
    satisfaction: 4.8,
    tone: "accent",
    mark: "하",
  },
  {
    id: "m2",
    name: "권도영",
    role: "변호사",
    org: "B법률사무소",
    fields: ["법률"],
    career: ["스타트업 자문 9년", "투자계약·주주간계약 자문 300건", "창업지원기관 자문 변호사"],
    answerCount: 164,
    satisfaction: 4.9,
    tone: "ink",
    mark: "권",
  },
  {
    id: "m3",
    name: "선우빈",
    role: "변리사",
    org: "C특허사무소",
    fields: ["특허"],
    career: ["기계·전자 분야 출원 800건", "기술보증 심사 자문", "직무발명 제도 설계 지원"],
    answerCount: 132,
    satisfaction: 4.7,
    tone: "neutral",
    mark: "선",
  },
  {
    id: "m4",
    name: "채로운",
    role: "그로스 리드",
    org: "D그로스랩",
    fields: ["마케팅"],
    career: ["커머스 그로스 8년", "초기 브랜드 30곳 성장 자문", "퍼포먼스 예산 운영 120억원"],
    answerCount: 97,
    satisfaction: 4.6,
    tone: "accent",
    mark: "채",
  },
  {
    id: "m5",
    name: "남기웅",
    role: "세무사",
    org: "E세무회계",
    fields: ["세무"],
    career: ["스타트업 전담 세무 12년", "연구인력개발비 세액공제 자문 240건"],
    answerCount: 143,
    satisfaction: 4.8,
    tone: "neutral",
    mark: "남",
  },
  {
    id: "m6",
    name: "표현서",
    role: "사업총괄",
    org: "미래산업진흥원 창업지원단",
    fields: ["정부지원사업"],
    career: ["정부 지원사업 기획 14년", "평가위원 활동 6년", "사업계획서 컨설팅 500건"],
    answerCount: 205,
    satisfaction: 4.7,
    tone: "ink",
    mark: "표",
  },
];

export function mentorById(id: string) {
  return MENTORS.find((m) => m.id === id);
}

export const QUESTIONS: Question[] = [
  {
    id: "q1",
    category: "투자",
    title: "프리A 라운드에서 기존 시드 투자자의 후속 투자 비중은 어느 정도가 적정한가요?",
    content:
      "시드 라운드에서 5억원을 받았고 지금 프리A를 준비 중입니다. 기존 투자자가 후속으로 참여하겠다고 하는데, 신규 투자자 유치 관점에서 기존 투자자 비중이 너무 높으면 오히려 부정적으로 보일 수 있다는 이야기를 들었습니다. 실제로 그런가요?",
    askerCompanyId: "co-a",
    askerLabel: "A테크",
    createdAt: "2026-07-25T14:20:00",
    views: 412,
    likes: 27,
    attachments: [],
    answers: [
      {
        id: "q1a1",
        mentorId: "m1",
        content:
          "부정적으로 보이는 경우는 기존 투자자가 라운드를 사실상 혼자 채울 때입니다. 신규 리드가 없으면 밸류를 검증할 주체가 없다는 뜻이 되기 때문입니다. 반대로 기존 투자자가 30% 안팎으로 따라 들어오는 건 강한 긍정 신호로 읽힙니다. 지금 단계에서는 신규 리드를 먼저 확정하고, 기존 투자자 참여 비중은 그 뒤에 조정하는 순서를 권합니다.",
        createdAt: "2026-07-25T18:05:00",
        likes: 34,
        accepted: true,
        followUps: [
          {
            author: "A테크 정하윤",
            content: "신규 리드 확정 전에 기존 투자자와 비중을 미리 합의해 두는 건 어떨까요?",
            createdAt: "2026-07-25T19:30:00",
          },
          {
            author: "하윤정 멘토",
            content:
              "상한만 합의하고 하한은 열어 두세요. 리드가 정해지면 라운드 규모 자체가 바뀌는 경우가 많습니다.",
            createdAt: "2026-07-25T20:12:00",
          },
        ],
      },
    ],
  },
  {
    id: "q2",
    category: "법률",
    title: "공동개발 결과물의 특허를 공동 출원하면 나중에 단독 사업화가 막히나요?",
    content:
      "다른 회원사와 공동개발을 논의 중인데 결과물 특허를 공동 명의로 출원하자는 제안을 받았습니다. 공동 명의일 경우 저희가 단독으로 제품화하거나 제3자에게 라이선스를 줄 때 제약이 생기는지 궁금합니다.",
    askerCompanyId: "co-b",
    askerLabel: "B소재",
    createdAt: "2026-07-23T10:10:00",
    views: 538,
    likes: 41,
    attachments: [{ name: "공동개발_제안서_요약.pdf", size: "240KB" }],
    answers: [
      {
        id: "q2a1",
        mentorId: "m2",
        content:
          "공동 특허권자는 자기 실시는 자유롭지만, 제3자에게 라이선스를 주거나 지분을 양도할 때는 다른 공유자의 동의가 필요합니다. 즉 직접 제품화는 가능하고 라이선스 사업은 막힙니다. 라이선스를 사업 모델로 보고 있다면 공동 출원 대신 단독 출원 후 실시권을 부여하는 구조를 협의하시는 편이 낫습니다.",
        createdAt: "2026-07-23T13:40:00",
        likes: 52,
        accepted: true,
        followUps: [],
      },
      {
        id: "q2a2",
        mentorId: "m3",
        content:
          "덧붙이면 계약서에 지분 비율만 적고 실시·처분 조건을 빼놓는 경우가 많습니다. 출원 전에 별도 합의서로 라이선스 동의 절차를 명시해 두시면 이후 협상이 훨씬 단순해집니다.",
        createdAt: "2026-07-23T16:22:00",
        likes: 29,
        accepted: false,
        followUps: [],
      },
    ],
  },
  {
    id: "q3",
    category: "특허",
    title: "이미 논문으로 공개한 알고리즘도 특허 출원이 가능한가요?",
    content:
      "작년 학회에서 핵심 알고리즘 일부를 논문으로 발표했습니다. 지금 와서 특허 출원이 가능한지, 가능하다면 어떤 절차가 필요한지 알고 싶습니다.",
    askerCompanyId: "co-d",
    askerLabel: "D메디",
    createdAt: "2026-07-20T09:35:00",
    views: 367,
    likes: 22,
    attachments: [],
    answers: [
      {
        id: "q3a1",
        mentorId: "m3",
        content:
          "본인이 공개한 경우 공지예외 주장 제도를 쓸 수 있습니다. 공개일로부터 12개월 이내에 출원하면서 취지를 밝히고 증명 서류를 제출하면 됩니다. 다만 이 제도는 국내 기준이고 해외 출원 시에는 국가별로 인정 범위가 달라 유럽처럼 인정하지 않는 곳도 있습니다. 해외 진출 계획이 있다면 남은 기간 안에 국제 출원 전략을 먼저 정리하세요.",
        createdAt: "2026-07-20T11:50:00",
        likes: 31,
        accepted: true,
        followUps: [],
      },
    ],
  },
  {
    id: "q4",
    category: "마케팅",
    title: "B2B 제품인데 초기 고객 확보를 콘텐츠로 하는 게 의미가 있을까요?",
    content:
      "제조 현장에 파는 솔루션이라 고객이 검색으로 유입되는 경우가 거의 없습니다. 그런데도 블로그나 뉴스레터 같은 콘텐츠에 시간을 쓰는 게 맞는지 판단이 서지 않습니다.",
    askerCompanyId: "co-a",
    askerLabel: "A테크",
    createdAt: "2026-07-17T15:05:00",
    views: 604,
    likes: 48,
    attachments: [],
    answers: [
      {
        id: "q4a1",
        mentorId: "m4",
        content:
          "유입 채널로 기대하면 실패합니다. B2B 콘텐츠는 영업 사이클 중간에서 신뢰를 확인시키는 자료로 쓰일 때 효과가 납니다. 미팅 후 담당자가 사내 결재를 올릴 때 첨부할 수 있는 도입 사례와 비용 산정 자료부터 만드세요. 검색 유입용 글은 그다음입니다.",
        createdAt: "2026-07-17T17:30:00",
        likes: 57,
        accepted: true,
        followUps: [
          {
            author: "A테크 정하윤",
            content: "도입 사례를 고객사 이름 없이 써도 설득력이 있을까요?",
            createdAt: "2026-07-17T18:15:00",
          },
        ],
      },
    ],
  },
  {
    id: "q5",
    category: "세무",
    title: "연구인력개발비 세액공제를 받으려면 연구소 설립이 꼭 필요한가요?",
    content:
      "개발 인력 6명이 전부 제품 개발에 투입되어 있습니다. 기업부설연구소 설립 없이도 세액공제를 받을 수 있는지, 설립한다면 어떤 요건을 맞춰야 하는지 궁금합니다.",
    askerCompanyId: "co-f",
    askerLabel: "F푸드",
    createdAt: "2026-07-14T11:25:00",
    views: 489,
    likes: 35,
    attachments: [],
    answers: [
      {
        id: "q5a1",
        mentorId: "m5",
        content:
          "연구소 없이도 공제 자체는 가능하지만, 인정 범위와 사후 검증 난이도가 크게 달라집니다. 연구소나 연구개발전담부서를 인정받으면 인건비 귀속을 다투는 일이 거의 없어집니다. 6명 규모면 전담부서 요건은 어렵지 않으니 우선 전담부서부터 신고하시고, 연구 일지와 과제별 근무시간 기록을 지금부터 남기세요.",
        createdAt: "2026-07-14T14:10:00",
        likes: 40,
        accepted: true,
        followUps: [],
      },
    ],
  },
  {
    id: "q6",
    category: "정부지원사업",
    title: "지원사업 중간 점검에서 목표 미달일 때 어떻게 소명하는 게 좋을까요?",
    content:
      "상반기 목표로 잡은 계약 건수의 절반 정도만 달성했습니다. 다음 달 중간 점검이 있는데 어떤 방식으로 설명해야 사업 중단 없이 넘어갈 수 있을지 조언 부탁드립니다.",
    askerCompanyId: "co-k",
    askerLabel: "K케어",
    createdAt: "2026-07-10T16:40:00",
    views: 721,
    likes: 63,
    attachments: [],
    answers: [
      {
        id: "q6a1",
        mentorId: "m6",
        content:
          "평가위원이 보는 건 달성률 자체보다 원인 분석의 구체성과 남은 기간 계획의 현실성입니다. 미달 원인을 외부 환경으로만 돌리면 가장 나쁘고, 초기 가정 중 무엇이 틀렸는지 데이터로 짚은 뒤 지표를 재설정하는 안을 함께 가져오면 대부분 통과합니다. 지표 변경은 사전 협의가 필요하니 점검 2주 전에 담당자에게 먼저 문의하세요.",
        createdAt: "2026-07-10T19:05:00",
        likes: 71,
        accepted: true,
        followUps: [],
      },
    ],
  },
];

export const CHAT_ROOMS: ChatRoom[] = [
  {
    id: "r1",
    companyId: "co-b",
    unread: 2,
    lastAt: "2026-07-27T10:42:00",
    messages: [
      {
        id: "r1m1",
        from: "them",
        kind: "text",
        text: "안녕하세요, B소재 배준호입니다. 피드에 남겨주신 댓글 보고 연락드립니다.",
        createdAt: "2026-07-26T15:10:00",
      },
      {
        id: "r1m2",
        from: "me",
        kind: "text",
        text: "안녕하세요. 재생 펠릿 물성 데이터가 저희 이상탐지 모델 학습에 쓸 수 있는 형태인지 먼저 확인하고 싶습니다.",
        createdAt: "2026-07-26T15:24:00",
      },
      {
        id: "r1m3",
        from: "them",
        kind: "file",
        text: "배치별 물성 측정값입니다. 최근 6개월치 전량 포함되어 있습니다.",
        fileName: "재생펠릿_물성데이터_2601-2606.xlsx",
        fileSize: "1.8MB",
        createdAt: "2026-07-26T15:38:00",
      },
      {
        id: "r1m4",
        from: "me",
        kind: "companyCard",
        companyId: "co-a",
        text: "저희 기업 소개 카드도 함께 보내드립니다.",
        createdAt: "2026-07-26T16:02:00",
      },
      {
        id: "r1m5",
        from: "them",
        kind: "proposal",
        proposal: {
          title: "재생 펠릿 품질 이상탐지 공동 실증",
          budget: "6,000만원 (공동 부담)",
          period: "2026.09 - 2027.02",
        },
        text: "논의 내용 정리해 제안서로 만들었습니다. 검토 후 의견 주세요.",
        createdAt: "2026-07-27T09:55:00",
      },
      {
        id: "r1m6",
        from: "them",
        kind: "text",
        text: "실증 부지는 저희 부산 공장에서 진행 가능합니다. 다음 주 화요일 오후에 통화 가능하실까요?",
        createdAt: "2026-07-27T10:42:00",
      },
    ],
  },
  {
    id: "r2",
    companyId: "co-e",
    unread: 0,
    lastAt: "2026-07-26T18:20:00",
    messages: [
      {
        id: "r2m1",
        from: "me",
        kind: "text",
        text: "지난 단지 실증 데이터 정리본 공유드립니다. 피크 구간 예측 정확도가 개선됐습니다.",
        createdAt: "2026-07-26T17:40:00",
      },
      {
        id: "r2m2",
        from: "me",
        kind: "file",
        fileName: "실증_피크예측_리포트_0726.pdf",
        fileSize: "2.4MB",
        createdAt: "2026-07-26T17:41:00",
      },
      {
        id: "r2m3",
        from: "them",
        kind: "text",
        text: "확인했습니다. 다음 단지 적용 전에 관리사무소 설명 자료도 같이 만들면 좋겠습니다.",
        createdAt: "2026-07-26T18:20:00",
      },
    ],
  },
  {
    id: "r3",
    companyId: "co-h",
    unread: 1,
    lastAt: "2026-07-25T14:05:00",
    messages: [
      {
        id: "r3m1",
        from: "them",
        kind: "namecard",
        fileName: "H로보틱스_박도현_명함.pdf",
        fileSize: "320KB",
        text: "지난 간담회에서 인사드렸던 H로보틱스 박도현입니다.",
        createdAt: "2026-07-25T13:50:00",
      },
      {
        id: "r3m2",
        from: "them",
        kind: "text",
        text: "사출 라인 예지보전 실증 결과 자료를 사내 공유하려는데 인용 가능한 범위를 확인하고 싶습니다.",
        createdAt: "2026-07-25T14:05:00",
      },
    ],
  },
  {
    id: "r4",
    companyId: "co-f",
    unread: 0,
    lastAt: "2026-07-22T11:15:00",
    messages: [
      {
        id: "r4m1",
        from: "them",
        kind: "text",
        text: "수요예측 모델 재학습 주기를 어떻게 잡으셨는지 여쭤봐도 될까요?",
        createdAt: "2026-07-22T10:50:00",
      },
      {
        id: "r4m2",
        from: "me",
        kind: "text",
        text: "저희는 설비 단위로 2주에 한 번 돌리고, 공정 변경이 있으면 즉시 재학습합니다.",
        createdAt: "2026-07-22T11:15:00",
      },
    ],
  },
  {
    id: "r5",
    companyId: "co-d",
    unread: 0,
    lastAt: "2026-07-19T16:30:00",
    messages: [
      {
        id: "r5m1",
        from: "them",
        kind: "text",
        text: "다음 달 데모데이 같이 준비하는 팀 있으신가요? 리허설 상대가 필요합니다.",
        createdAt: "2026-07-19T16:10:00",
      },
      {
        id: "r5m2",
        from: "me",
        kind: "text",
        text: "저희도 참가 신청했습니다. 8월 둘째 주에 서로 발표 봐드리는 걸로 하시죠.",
        createdAt: "2026-07-19T16:30:00",
      },
    ],
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "e1",
    title: "8월 입주기업 네트워킹 데이",
    type: "네트워킹",
    host: "나인창업지원재단",
    date: "2026-08-07",
    time: "18:30 - 21:00",
    place: "나인창업지원재단 1층 라운지",
    capacity: 60,
    applied: 47,
    status: "모집중",
    image: eventNetworking.src,
    myStatus: "신청완료",
  },
  {
    id: "e2",
    title: "8월 IR 데모데이",
    type: "IR",
    host: "한강테크브리지",
    date: "2026-08-28",
    time: "13:00 - 18:00",
    place: "한강테크브리지 이벤트홀",
    capacity: 8,
    applied: 23,
    status: "모집중",
    image: eventDemoday.src,
    myStatus: "신청완료",
  },
  {
    id: "e3",
    title: "제조 AI 실증 사례 세미나",
    type: "세미나",
    host: "미래산업진흥원 창업지원단",
    date: "2026-08-13",
    time: "14:00 - 17:00",
    place: "온라인 실시간",
    capacity: 120,
    applied: 118,
    status: "모집중",
    image: eventSeminar.src,
  },
  {
    id: "e4",
    title: "특허 명세서 작성 실무 교육",
    type: "교육",
    host: "나인창업지원재단",
    date: "2026-08-18",
    time: "14:00 - 18:00",
    place: "나인창업지원재단 2층 교육실",
    capacity: 16,
    applied: 16,
    status: "모집마감",
    image: eventEducation.src,
  },
  {
    id: "e5",
    title: "상반기 성과공유회",
    type: "네트워킹",
    host: "나인창업지원재단",
    date: "2026-06-26",
    time: "15:00 - 18:00",
    place: "나인창업지원재단 3층 대회의실",
    capacity: 80,
    applied: 74,
    status: "진행완료",
    image: eventReview.src,
    applicantsAttended: 68,
  },
];

export const PROGRAMS_LIST: ProgramItem[] = [
  {
    id: "p1",
    title: "하반기 스케일업 멘토링 (8주 과정)",
    period: "2026.08.10 - 2026.10.02",
    target: "프리A 이상 입주기업",
    applied: 19,
    capacity: 12,
    status: "모집중",
  },
  {
    id: "p2",
    title: "해외 진출 준비 과정",
    period: "2026.09.01 - 2026.11.28",
    target: "수출 계획 보유 기업",
    applied: 8,
    capacity: 15,
    status: "모집중",
  },
  {
    id: "p3",
    title: "기업 간 공동개발 지원 트랙",
    period: "2026.07.01 - 2026.12.31",
    target: "협업 계약 체결 기업",
    applied: 11,
    capacity: 10,
    status: "운영중",
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    kind: "collab",
    title: "B소재가 협업 제안서를 보냈습니다",
    body: "재생 펠릿 품질 이상탐지 공동 실증 제안이 도착했습니다.",
    createdAt: "2026-07-27T09:55:00",
    read: false,
  },
  {
    id: "n2",
    kind: "chat",
    title: "B소재 배준호님의 새 메시지",
    body: "실증 부지는 저희 부산 공장에서 진행 가능합니다.",
    createdAt: "2026-07-27T10:42:00",
    read: false,
  },
  {
    id: "n3",
    kind: "notice",
    title: "하반기 입주기업 정기 간담회 안내",
    body: "8월 20일 14시, 3층 대회의실에서 진행됩니다.",
    createdAt: "2026-07-27T09:00:00",
    read: false,
  },
  {
    id: "n4",
    kind: "answer",
    title: "하윤정 멘토가 질문에 답변했습니다",
    body: "프리A 라운드에서 기존 시드 투자자의 후속 투자 비중은",
    createdAt: "2026-07-25T18:05:00",
    read: true,
  },
  {
    id: "n5",
    kind: "notice",
    title: "8월 IR 데모데이 참가 신청이 접수되었습니다",
    body: "선정 결과는 8월 12일에 개별 안내됩니다.",
    createdAt: "2026-07-24T11:20:00",
    read: true,
  },
];

export const ADMIN_MEMBERS: AdminMember[] = [
  {
    id: "am1",
    companyId: "co-a",
    company: "A테크",
    contact: "정하윤",
    email: "hayoon.jung@a-tech.kr",
    role: "기업 담당자",
    industry: "AI·데이터",
    joinedAt: "2026-03-11",
    status: "활성",
    lastActive: "2026-07-27",
  },
  {
    id: "am2",
    companyId: "co-b",
    company: "B소재",
    contact: "배준호",
    email: "junho.bae@b-materials.kr",
    role: "기업 담당자",
    industry: "친환경·에너지",
    joinedAt: "2025-11-04",
    status: "활성",
    lastActive: "2026-07-27",
  },
  {
    id: "am3",
    company: "M커머스",
    contact: "허수아",
    email: "sua.heo@m-commerce.kr",
    role: "기업 대표",
    industry: "커머스",
    joinedAt: "2026-07-26",
    status: "승인대기",
    lastActive: "2026-07-26",
  },
  {
    id: "am4",
    company: "N소재",
    contact: "장한별",
    email: "hanbyul.jang@n-materials.kr",
    role: "기업 담당자",
    industry: "제조·하드웨어",
    joinedAt: "2026-07-25",
    status: "승인대기",
    lastActive: "2026-07-25",
  },
  {
    id: "am5",
    companyId: "co-d",
    company: "D메디",
    contact: "노유진",
    email: "yujin.noh@d-medi.kr",
    role: "기업 담당자",
    industry: "헬스케어",
    joinedAt: "2025-09-22",
    status: "활성",
    lastActive: "2026-07-26",
  },
  {
    id: "am6",
    company: "P푸드",
    contact: "우태경",
    email: "taekyung.woo@p-food.kr",
    role: "기업 대표",
    industry: "푸드테크",
    joinedAt: "2026-07-24",
    status: "반려",
    lastActive: "2026-07-24",
  },
  {
    id: "am7",
    companyId: "co-h",
    company: "H로보틱스",
    contact: "박도현",
    email: "dohyun.park@h-robotics.kr",
    role: "기업 담당자",
    industry: "제조·하드웨어",
    joinedAt: "2025-04-17",
    status: "활성",
    lastActive: "2026-07-25",
  },
  {
    id: "am8",
    company: "나인창업지원재단",
    contact: "심유라",
    email: "yura.shim@nine-foundation.or.kr",
    role: "기관 운영자",
    industry: "기관",
    joinedAt: "2025-01-06",
    status: "활성",
    lastActive: "2026-07-27",
  },
  {
    id: "am9",
    companyId: "co-j",
    company: "J스튜디오",
    contact: "봉태리",
    email: "taeri.bong@j-studio.kr",
    role: "기업 대표",
    industry: "콘텐츠",
    joinedAt: "2026-06-24",
    status: "활성",
    lastActive: "2026-07-22",
  },
  {
    id: "am10",
    company: "R미디어",
    contact: "제민아",
    email: "mina.je@r-media.kr",
    role: "기업 대표",
    industry: "콘텐츠",
    joinedAt: "2025-10-02",
    status: "비활성",
    lastActive: "2026-04-18",
  },
  {
    id: "am11",
    companyId: "co-i",
    company: "I커머스",
    contact: "최연우",
    email: "yeonwoo.choi@i-commerce.kr",
    role: "기업 담당자",
    industry: "커머스",
    joinedAt: "2025-12-08",
    status: "활성",
    lastActive: "2026-07-26",
  },
  {
    id: "am12",
    companyId: "co-k",
    company: "K케어",
    contact: "진세희",
    email: "sehee.jin@k-care.kr",
    role: "기업 대표",
    industry: "헬스케어",
    joinedAt: "2026-05-15",
    status: "활성",
    lastActive: "2026-07-24",
  },
];

export const CERT_REQUESTS: CertRequest[] = [
  {
    id: "cr1",
    company: "M커머스",
    bizNumber: "417-86-01923",
    ceo: "허수아",
    institution: "나인창업지원재단",
    program: "2026 초기창업패키지",
    type: "지원사업",
    submittedAt: "2026-07-26T14:20:00",
    manager: {
      name: "허수아",
      role: "대표",
      phone: "010-6621-4407",
      email: "sua.heo@m-commerce.kr",
    },
    documents: [
      { name: "사업자등록증.pdf", size: "620KB", kind: "사업자등록증" },
      { name: "협약체결_확인서.pdf", size: "1.1MB", kind: "선정 증빙" },
    ],
    status: "심사대기",
  },
  {
    id: "cr2",
    company: "N소재",
    bizNumber: "205-81-77410",
    ceo: "장한별",
    institution: "한강테크브리지",
    program: "입주기업 3기",
    type: "입주기업",
    submittedAt: "2026-07-25T09:45:00",
    manager: {
      name: "장한별",
      role: "경영지원 팀장",
      phone: "010-3348-9925",
      email: "hanbyul.jang@n-materials.kr",
    },
    documents: [
      { name: "사업자등록증.pdf", size: "540KB", kind: "사업자등록증" },
      { name: "입주계약서.pdf", size: "2.2MB", kind: "선정 증빙" },
      { name: "재직증명서.pdf", size: "180KB", kind: "기타" },
    ],
    status: "심사대기",
  },
  {
    id: "cr3",
    company: "O랩스",
    bizNumber: "128-87-33096",
    ceo: "구재이",
    institution: "세움창업허브",
    program: "2026 예비창업패키지",
    type: "지원사업",
    submittedAt: "2026-07-24T16:10:00",
    manager: {
      name: "구재이",
      role: "대표",
      phone: "010-7714-2208",
      email: "jaei.koo@o-labs.kr",
    },
    documents: [{ name: "선정통보_메일_캡처.png", size: "310KB", kind: "선정 증빙" }],
    status: "보완요청",
  },
  {
    id: "cr4",
    company: "P푸드",
    bizNumber: "621-88-45012",
    ceo: "우태경",
    institution: "미래산업진흥원 창업지원단",
    program: "딥테크 챌린지 2026",
    type: "지원사업",
    submittedAt: "2026-07-24T11:02:00",
    manager: {
      name: "우태경",
      role: "대표",
      phone: "010-2287-6640",
      email: "taekyung.woo@p-food.kr",
    },
    documents: [
      { name: "사업자등록증.pdf", size: "580KB", kind: "사업자등록증" },
      { name: "2024_선정확인서.pdf", size: "900KB", kind: "선정 증빙" },
    ],
    status: "반려",
  },
  {
    id: "cr5",
    company: "Q에너지",
    bizNumber: "310-86-20874",
    ceo: "탁유하",
    institution: "서해권 창업보육센터",
    program: "글로벌 스케일업 트랙",
    type: "입주기업",
    submittedAt: "2026-07-23T13:35:00",
    manager: {
      name: "탁유하",
      role: "대표",
      phone: "010-5590-1172",
      email: "yuha.tak@q-energy.kr",
    },
    documents: [
      { name: "사업자등록증.pdf", size: "610KB", kind: "사업자등록증" },
      { name: "입주확인서.pdf", size: "740KB", kind: "선정 증빙" },
    ],
    status: "승인",
  },
];

export const ADMIN_REPORTS: AdminReport[] = [
  {
    id: "rp1",
    target: "홍보성 댓글 반복 등록",
    targetType: "댓글",
    reporter: "F푸드 곽민서",
    reason: "동일 서비스 홍보 문구를 여러 게시글에 반복 등록",
    createdAt: "2026-07-26T17:30:00",
    status: "처리대기",
  },
  {
    id: "rp2",
    target: "협업 모집 글 내 외부 계약 유도",
    targetType: "게시글",
    reporter: "D메디 노유진",
    reason: "플랫폼 외부 결제를 유도하는 내용 포함",
    createdAt: "2026-07-25T10:12:00",
    status: "처리대기",
  },
  {
    id: "rp3",
    target: "반복적인 대량 메시지 발송",
    targetType: "채팅",
    reporter: "I커머스 최연우",
    reason: "다수 기업에 동일 제안 메시지를 반복 발송",
    createdAt: "2026-07-22T14:48:00",
    status: "처리완료",
  },
];

export const COLLAB_REQUESTS: CollabRequest[] = [
  {
    id: "cq1",
    from: "B소재",
    to: "A테크",
    topic: "재생 펠릿 품질 이상탐지 공동 실증",
    createdAt: "2026-07-27",
    status: "논의중",
  },
  {
    id: "cq2",
    from: "J스튜디오",
    to: "I커머스",
    topic: "지역 축제 팝업 숏폼 제작",
    createdAt: "2026-07-24",
    status: "제안",
  },
  {
    id: "cq3",
    from: "E모빌리티",
    to: "A테크",
    topic: "단지 전력 데이터 이상 감지 연동",
    createdAt: "2026-07-18",
    status: "성사",
  },
  {
    id: "cq4",
    from: "G에듀",
    to: "H로보틱스",
    topic: "물류 자동화 실습 과정 2기 개발",
    createdAt: "2026-07-11",
    status: "성사",
  },
  {
    id: "cq5",
    from: "F푸드",
    to: "I커머스",
    topic: "산지 식자재 직거래 연동",
    createdAt: "2026-07-02",
    status: "종료",
  },
];

export const ADMIN_STATS = {
  totalMembers: 486,
  memberDelta: 23,
  pendingCerts: 5,
  newThisMonth: 34,
  posts: 1268,
  comments: 3947,
  programApplications: 61,
  collabMatches: 84,
  dau: 213,
  mau: 428,
  networkParticipation: 71.4,
  weeklyActive: [168, 182, 176, 195, 204, 198, 213],
  industrySignups: [
    { industry: "AI·데이터", count: 94 },
    { industry: "헬스케어", count: 71 },
    { industry: "커머스", count: 63 },
    { industry: "제조·하드웨어", count: 58 },
    { industry: "친환경·에너지", count: 52 },
    { industry: "핀테크", count: 44 },
    { industry: "푸드테크", count: 39 },
    { industry: "기타", count: 65 },
  ],
  topCompanies: [
    { name: "B소재", collabs: 12, views: 3184 },
    { name: "H로보틱스", collabs: 9, views: 2871 },
    { name: "A테크", collabs: 8, views: 2450 },
    { name: "I커머스", collabs: 7, views: 2216 },
    { name: "E모빌리티", collabs: 6, views: 1980 },
  ],
};

export function formatRelativeTime(iso: string) {
  const date = new Date(iso);
  const now = new Date("2026-07-27T12:00:00");
  const diffMin = Math.floor((now.getTime() - date.getTime()) / 60000);
  if (diffMin < 1) return "방금 전";
  if (diffMin < 60) return `${diffMin}분 전`;
  const diffHour = Math.floor(diffMin / 60);
  if (diffHour < 24) return `${diffHour}시간 전`;
  const diffDay = Math.floor(diffHour / 24);
  if (diffDay < 7) return `${diffDay}일 전`;
  return `${date.getMonth() + 1}월 ${date.getDate()}일`;
}

export function formatDate(iso: string) {
  const date = new Date(iso);
  return `${date.getFullYear()}.${String(date.getMonth() + 1).padStart(2, "0")}.${String(
    date.getDate(),
  ).padStart(2, "0")}`;
}

export function formatTime(iso: string) {
  const date = new Date(iso);
  const hour = date.getHours();
  const minute = String(date.getMinutes()).padStart(2, "0");
  const meridiem = hour < 12 ? "오전" : "오후";
  const display = hour % 12 === 0 ? 12 : hour % 12;
  return `${meridiem} ${display}:${minute}`;
}

export function daysUntil(dateStr: string) {
  const target = new Date(`${dateStr}T00:00:00`);
  const now = new Date("2026-07-27T00:00:00");
  return Math.round((target.getTime() - now.getTime()) / 86400000);
}
