import type {
  ActivityItem,
  CommunityPost,
  FaqItem,
  MyReview,
  NoticeItem,
  Review,
  Vendor,
  VerificationRequest,
} from "@/projects/community/wedit/lib/types";

/* 전부 다운로드 후 육안 확인한 Pexels 사진 id만 쓴다. design.md "사진 매핑" 표 참고. */
export function pexelsPhoto(id: number, w: number, h: number) {
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}&h=${h}&fit=crop`;
}

export const CATEGORY_LABEL: Record<string, string> = {
  studio: "스튜디오",
  dress: "드레스",
  makeup: "메이크업",
  prep: "예식 준비",
};

export const ME = {
  name: "김서연",
  email: "seoyeon.kim@example.com",
  verifiedVendorCount: 2,
  writtenReviewCount: 3,
  bookmarkCount: 5,
};

export const VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "루메르 스튜디오",
    category: "studio",
    region: "서울 강남",
    photoId: 17057198,
    ratingAvg: 4.8,
    ratingBreakdown: { kindness: 4.7, priceSatisfaction: 4.5, resultSatisfaction: 4.9, afterCare: 4.8 },
    reviewCount: 214,
    avgPaidPrice: 1350000,
    packageItems: [
      { label: "원판 데이터 전체 제공", included: true },
      { label: "액자 1개 포함", included: true },
      { label: "헬퍼 스냅 1인 동행", included: true },
      { label: "야외 로케이션 촬영", included: false },
      { label: "당일 보정본 30컷", included: true },
    ],
    optionItems: [
      { label: "앨범 30페이지 업그레이드", price: 250000 },
      { label: "액자 추가 (1개)", price: 90000 },
      { label: "원본 파일 전체 다운로드", price: 150000 },
    ],
    verifiedCount: 128,
    tags: ["클래식 톤", "실장 직찍", "당일 확인"],
    summary: "채광 좋은 아치형 스튜디오, 클래식하고 정제된 보정 톤으로 꾸준히 상위권.",
    address: "서울 강남구 논현로 128길 14",
    rankChange: "up",
  },
  {
    id: "v2",
    name: "브리즈 필름 스튜디오",
    category: "studio",
    region: "서울 성수",
    photoId: 19604454,
    ratingAvg: 4.7,
    ratingBreakdown: { kindness: 4.8, priceSatisfaction: 4.6, resultSatisfaction: 4.6, afterCare: 4.5 },
    reviewCount: 156,
    avgPaidPrice: 980000,
    packageItems: [
      { label: "필름 룩 보정", included: true },
      { label: "야외 자연광 촬영", included: true },
      { label: "헬퍼 스냅 1인 동행", included: false },
      { label: "당일 보정본 30컷", included: true },
    ],
    optionItems: [
      { label: "필름 카메라 추가 촬영", price: 180000 },
      { label: "앨범 20페이지", price: 220000 },
    ],
    verifiedCount: 94,
    tags: ["자연광", "필름 톤", "가성비"],
    summary: "숲속 보케를 살린 드리미한 자연광 컨셉, 야외 로케이션 전문.",
    address: "서울 성동구 성수이로 20길 9",
    rankChange: "up",
  },
  {
    id: "v3",
    name: "블랑 드 블랑 드레스",
    category: "dress",
    region: "서울 청담",
    photoId: 5729135,
    ratingAvg: 4.9,
    ratingBreakdown: { kindness: 4.9, priceSatisfaction: 4.4, resultSatisfaction: 5.0, afterCare: 4.8 },
    reviewCount: 189,
    avgPaidPrice: 1600000,
    packageItems: [
      { label: "가봉 2회 포함", included: true },
      { label: "리허설 드레스 1벌", included: true },
      { label: "본식 드레스 1벌", included: true },
      { label: "당일 헬퍼 동행", included: true },
      { label: "글러브 대여", included: false },
    ],
    optionItems: [
      { label: "디자이너 라인 드레스 변경", price: 400000 },
      { label: "티아라 대여", price: 80000 },
      { label: "당일 픽업 서비스", price: 60000 },
    ],
    verifiedCount: 102,
    tags: ["디자이너 라인", "핏 보정 꼼꼼", "청담 본점"],
    summary: "핑크빛 플로럴 무드의 쇼룸, 가봉 꼼꼼하기로 인증 리뷰 최다.",
    address: "서울 강남구 도산대로 45길 8",
    rankChange: "same",
  },
  {
    id: "v4",
    name: "아뜰리에 로젯",
    category: "dress",
    region: "서울 논현",
    photoId: 8459382,
    ratingAvg: 4.6,
    ratingBreakdown: { kindness: 4.6, priceSatisfaction: 4.7, resultSatisfaction: 4.5, afterCare: 4.4 },
    reviewCount: 121,
    avgPaidPrice: 1120000,
    packageItems: [
      { label: "가봉 1회 포함", included: true },
      { label: "리허설 드레스 1벌", included: true },
      { label: "본식 드레스 1벌", included: true },
      { label: "당일 헬퍼 동행", included: false },
    ],
    optionItems: [
      { label: "가봉 추가 (1회)", price: 50000 },
      { label: "부케 매칭 컨설팅", price: 70000 },
    ],
    verifiedCount: 68,
    tags: ["가든 무드", "합리적 가격", "소규모 아틀리에"],
    summary: "정원 느낌의 아담한 아틀리에, 합리적인 가격대의 가든 웨딩 무드 라인업.",
    address: "서울 강남구 논현로 51길 22",
    rankChange: "down",
  },
  {
    id: "v5",
    name: "글로우 헤어메이크업",
    category: "makeup",
    region: "서울 신사",
    photoId: 19936764,
    ratingAvg: 4.9,
    ratingBreakdown: { kindness: 4.9, priceSatisfaction: 4.6, resultSatisfaction: 4.9, afterCare: 4.9 },
    reviewCount: 241,
    avgPaidPrice: 450000,
    packageItems: [
      { label: "원장 직접 시술", included: true },
      { label: "리허설 메이크업 1회", included: true },
      { label: "실장급 헬퍼 동행", included: true },
      { label: "속눈썹 포함", included: true },
    ],
    optionItems: [
      { label: "업스타일 변경 (당일)", price: 50000 },
      { label: "신부 어머니 메이크업", price: 180000 },
      { label: "폐백 메이크업", price: 120000 },
    ],
    verifiedCount: 176,
    tags: ["원장 직찍", "지속력 좋음", "웜톤 전문"],
    summary: "골든아워 웜톤 스타일링으로 유명, 원장 직접 시술 고정 예약 다수.",
    address: "서울 강남구 압구정로 10길 17",
    rankChange: "up",
  },
  {
    id: "v6",
    name: "실크로드 뷰티 스튜디오",
    category: "makeup",
    region: "서울 압구정",
    photoId: 5693815,
    ratingAvg: 4.5,
    ratingBreakdown: { kindness: 4.5, priceSatisfaction: 4.8, resultSatisfaction: 4.4, afterCare: 4.3 },
    reviewCount: 97,
    avgPaidPrice: 380000,
    packageItems: [
      { label: "원장 직접 시술", included: false },
      { label: "리허설 메이크업 1회", included: true },
      { label: "실장급 헬퍼 동행", included: true },
      { label: "속눈썹 포함", included: false },
    ],
    optionItems: [
      { label: "속눈썹 연장", price: 30000 },
      { label: "업스타일 변경 (당일)", price: 40000 },
    ],
    verifiedCount: 51,
    tags: ["가성비", "실장 시술", "예약 여유"],
    summary: "합리적인 가격대의 실장 라인업, 예약 여유가 있어 급한 일정에도 대응.",
    address: "서울 강남구 압구정로 34길 5",
    rankChange: "same",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    vendorId: "v1",
    authorInitial: "민",
    authorLabel: "민지****",
    ratingBreakdown: { kindness: 5, priceSatisfaction: 4, resultSatisfaction: 5, afterCare: 5 },
    ratingAvg: 4.8,
    paidPrice: 1320000,
    packageSummary: "원판 전체 + 액자 1개 + 앨범 업그레이드",
    content:
      "실장님이 포즈 하나하나 잡아주셔서 사진이 훨씬 자연스럽게 나왔어요. 보정도 과하지 않고 딱 저희 톤 그대로라 만족했습니다. 예약할 때 견적서에 없던 추가 비용도 없었어요.",
    photos: [{ photoId: 17057198 }, { photoId: 19816898 }],
    createdAt: "2025.10.19",
    helpfulCount: 42,
  },
  {
    id: "r2",
    vendorId: "v1",
    authorInitial: "하",
    authorLabel: "하늘****",
    ratingBreakdown: { kindness: 4, priceSatisfaction: 4, resultSatisfaction: 5, afterCare: 4 },
    ratingAvg: 4.3,
    paidPrice: 1450000,
    packageSummary: "원판 전체 + 액자 1개 + 원본 다운로드",
    content:
      "결과물은 정말 만족스러웠는데 예약 조율 과정에서 답변이 조금 늦어서 마음 졸였어요. 그래도 실제 촬영 날은 문제없이 진행됐습니다.",
    photos: [{ photoId: 17057198 }],
    createdAt: "2025.09.29",
    helpfulCount: 18,
  },
  {
    id: "r3",
    vendorId: "v3",
    authorInitial: "지",
    authorLabel: "지은****",
    ratingBreakdown: { kindness: 5, priceSatisfaction: 4, resultSatisfaction: 5, afterCare: 5 },
    ratingAvg: 4.8,
    paidPrice: 1580000,
    packageSummary: "가봉 2회 + 본식 드레스 + 리허설 드레스",
    content:
      "가봉을 두 번이나 꼼꼼히 봐주셔서 당일 핏이 완벽했어요. 계약서에 적힌 항목 그대로 진행됐고 추가 결제 요구가 전혀 없어서 믿고 계약했던 보람이 있었습니다.",
    photos: [{ photoId: 5729135 }, { photoId: 10074759 }],
    createdAt: "2025.10.02",
    helpfulCount: 65,
  },
  {
    id: "r4",
    vendorId: "v4",
    authorInitial: "수",
    authorLabel: "수민****",
    ratingBreakdown: { kindness: 4, priceSatisfaction: 5, resultSatisfaction: 4, afterCare: 4 },
    ratingAvg: 4.3,
    paidPrice: 1080000,
    packageSummary: "가봉 1회 + 본식 드레스 + 리허설 드레스",
    content:
      "가격 대비 만족도가 높았어요. 다른 곳보다 저렴한데 드레스 상태도 깨끗했습니다. 다만 인기 있는 라인은 예약이 빨리 차니 서두르는 걸 추천해요.",
    photos: [{ photoId: 8459382 }],
    createdAt: "2025.09.05",
    helpfulCount: 27,
  },
  {
    id: "r5",
    vendorId: "v5",
    authorInitial: "예",
    authorLabel: "예은****",
    ratingBreakdown: { kindness: 5, priceSatisfaction: 4, resultSatisfaction: 5, afterCare: 5 },
    ratingAvg: 4.8,
    paidPrice: 470000,
    packageSummary: "원장 시술 + 리허설 메이크업 + 헬퍼 동행",
    content:
      "원장님이 직접 해주셔서 그런지 지속력이 정말 좋았어요. 리허설 때 상담한 스타일을 본식날 완벽하게 재현해주셨습니다. 헬퍼분도 세심하게 봐주셔서 하루 종일 편했어요.",
    photos: [{ photoId: 19936764 }],
    createdAt: "2025.10.22",
    helpfulCount: 58,
  },
  {
    id: "r6",
    vendorId: "v6",
    authorInitial: "나",
    authorLabel: "나연****",
    ratingBreakdown: { kindness: 4, priceSatisfaction: 5, resultSatisfaction: 4, afterCare: 4 },
    ratingAvg: 4.3,
    paidPrice: 360000,
    packageSummary: "실장 시술 + 리허설 메이크업",
    content:
      "가격이 저렴한 편인데 실장님 실력도 좋으셨어요. 다만 원장 시술이 아니라서 그 부분은 미리 확인하고 예약하시는 걸 추천합니다.",
    photos: [{ photoId: 5693815 }],
    createdAt: "2025.09.13",
    helpfulCount: 12,
  },
  {
    id: "r7",
    vendorId: "v2",
    authorInitial: "채",
    authorLabel: "채원****",
    ratingBreakdown: { kindness: 5, priceSatisfaction: 5, resultSatisfaction: 4, afterCare: 4 },
    ratingAvg: 4.5,
    paidPrice: 950000,
    packageSummary: "필름 룩 보정 + 야외 로케이션",
    content:
      "자연광 활용이 진짜 예쁜 스튜디오예요. 야외 촬영 위주로 진행했는데 날씨 걱정했던 것과 달리 실내 세트도 대안으로 준비돼 있어서 안심했습니다.",
    photos: [{ photoId: 19604454 }],
    createdAt: "2025.10.10",
    helpfulCount: 33,
  },
];

export const VERIFICATIONS: VerificationRequest[] = [
  {
    id: "vr1",
    vendorName: "글로우 헤어메이크업",
    category: "makeup",
    docType: "receipt",
    amount: 470000,
    contractDate: "2025.10.21",
    status: "approved",
    submittedAt: "2025.10.22",
  },
  {
    id: "vr2",
    vendorName: "루메르 스튜디오",
    category: "studio",
    docType: "contract",
    amount: 1320000,
    contractDate: "2025.10.16",
    status: "approved",
    submittedAt: "2025.10.18",
  },
  {
    id: "vr3",
    vendorName: "예그리나 스튜디오",
    category: "studio",
    docType: "contract",
    amount: 1180000,
    contractDate: "2025.10.29",
    status: "reviewing",
    submittedAt: "2025.10.30",
  },
  {
    id: "vr4",
    vendorName: "미유 드레스",
    category: "dress",
    docType: "receipt",
    amount: 990000,
    contractDate: "2025.10.31",
    status: "received",
    submittedAt: "2025.11.01",
  },
  {
    id: "vr5",
    vendorName: "포엠 스튜디오",
    category: "studio",
    docType: "contract",
    amount: 890000,
    contractDate: "2025.09.10",
    status: "rejected",
    rejectReason: "계약서 이미지의 결제 금액란이 흐릿해 정확한 확인이 어렵습니다. 선명한 사진으로 재업로드해 주세요.",
    submittedAt: "2025.09.11",
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "p1",
    category: "studio",
    title: "본식 스냅 헬퍼 유무 꼭 확인하세요",
    content:
      "저는 헬퍼 스냅이 포함인 줄 알고 계약했는데 옵션이었더라구요. 계약서 항목 하나하나 꼼꼼히 확인하시고, 인증 리뷰에서 계약 구성 먼저 비교해보세요.",
    authorInitial: "정",
    authorLabel: "정하윤",
    photoId: 19816898,
    aiAnswer:
      "본식 스냅 헬퍼는 업체마다 기본 포함 여부가 다릅니다. 계약 전 견적서의 '패키지 구성' 항목에서 헬퍼 동행 여부를 명확히 표기해 달라고 요청하시고, 구두 안내만 받았다면 문자나 이메일로 다시 확인받아 두는 걸 권장드려요.",
    answerCount: 6,
    likeCount: 34,
    commentCount: 6,
    createdAt: "2025.10.23",
    comments: [
      {
        id: "c1",
        authorInitial: "박",
        authorLabel: "박은서",
        content: "저도 이 부분 놓쳐서 당일에 추가 결제했어요 ㅠㅠ 미리 알았으면 좋았을 텐데.",
        likeCount: 8,
        createdAt: "2025.10.23",
      },
      {
        id: "c2",
        authorInitial: "이",
        authorLabel: "이수아",
        content: "계약서 사진 인증 올리면서 저장해두니까 나중에 확인하기 편하더라구요.",
        likeCount: 5,
        createdAt: "2025.10.24",
      },
    ],
  },
  {
    id: "p2",
    category: "dress",
    title: "가봉 2회 vs 1회, 체감 차이가 클까요?",
    content:
      "예산 맞추다 보니 가봉 1회인 곳도 고민 중인데 실제로 핏 차이가 많이 나는지 경험 있으신 분 계신가요?",
    authorInitial: "최",
    authorLabel: "최다인",
    answerCount: 4,
    likeCount: 21,
    commentCount: 4,
    createdAt: "2025.10.20",
    aiAnswer:
      "가봉 횟수는 체형 변화가 있는 경우(다이어트, 붓기 등) 특히 중요합니다. 1회 가봉이라면 본식 2~3주 전으로 최대한 늦게 예약하는 것이 핏 오차를 줄이는 방법이에요. 추가 가봉이 유료 옵션인지도 미리 확인해두시면 좋습니다.",
    comments: [
      {
        id: "c3",
        authorInitial: "정",
        authorLabel: "정하윤",
        content: "저는 1회였는데 본식 3주 전에 잡아서 큰 문제 없었어요.",
        likeCount: 6,
        createdAt: "2025.10.20",
      },
    ],
  },
  {
    id: "p3",
    category: "makeup",
    title: "원장 직접 시술이랑 실장 시술, 가격 차이만큼 다른가요",
    content:
      "리허설 메이크업 받아보고 결정하려는데 원장님이랑 실장님 라인 차이가 궁금해요.",
    authorInitial: "한",
    authorLabel: "한소율",
    answerCount: 5,
    likeCount: 29,
    commentCount: 3,
    createdAt: "2025.10.25",
    comments: [
      {
        id: "c4",
        authorInitial: "김",
        authorLabel: "김나영",
        content: "저는 실장 라인이었는데 만족스러웠어요! 스타일마다 다른 것 같아요.",
        likeCount: 9,
        createdAt: "2025.10.25",
      },
    ],
  },
  {
    id: "p4",
    category: "prep",
    title: "부케 셀프 디자인 해보신 분 계신가요",
    content:
      "업체 옵션가가 생각보다 비싸서 직접 만들어볼까 고민 중이에요. 생화 부케 셀프로 하신 분 있으면 팁 공유해주세요!",
    authorInitial: "윤",
    authorLabel: "윤채린",
    photoId: 10074759,
    answerCount: 3,
    likeCount: 41,
    commentCount: 5,
    createdAt: "2025.10.12",
    comments: [
      {
        id: "c5",
        authorInitial: "장",
        authorLabel: "장미래",
        content: "꽃시장에서 재료 사서 전날 미리 만들어두면 생각보다 오래가요!",
        likeCount: 14,
        createdAt: "2025.10.13",
      },
    ],
  },
  {
    id: "p5",
    category: "prep",
    title: "골든아워 야외 촬영, 진짜 다르더라구요",
    content:
      "해질 무렵 역광으로 찍은 컷이 스튜디오 컷보다 훨씬 분위기 있었어요. 촬영 시간대를 오후 4~5시로 잡을 수 있는지 미리 업체에 물어보세요.",
    authorInitial: "오",
    authorLabel: "오지아",
    photoId: 16910979,
    answerCount: 2,
    likeCount: 19,
    commentCount: 2,
    createdAt: "2025.09.28",
    comments: [],
  },
  {
    id: "p6",
    category: "prep",
    title: "축가 연주자 섭외, 어디서 알아보셨나요",
    content:
      "피아노 축가 연주자 섭외하려는데 커뮤니티에서 추천받은 곳 있으면 공유 부탁드려요.",
    authorInitial: "서",
    authorLabel: "서하은",
    photoId: 11199302,
    answerCount: 1,
    likeCount: 8,
    commentCount: 1,
    createdAt: "2025.10.06",
    comments: [
      {
        id: "c6",
        authorInitial: "문",
        authorLabel: "문가온",
        content: "저는 지인 소개로 구했는데 커뮤니티 후기도 많이 도움 될 것 같아요!",
        likeCount: 3,
        createdAt: "2025.10.07",
      },
    ],
  },
];

export const FAQS: FaqItem[] = [
  {
    id: "f1",
    question: "인증 리뷰는 어떻게 작성하나요?",
    answer:
      "영수증 또는 계약서를 업로드해 인증을 신청하고, 검수팀 승인이 완료되면 마이페이지 > 내 인증 관리에서 해당 업체에 리뷰를 작성할 수 있습니다. 승인 전에는 리뷰 작성 버튼이 비활성화됩니다.",
  },
  {
    id: "f2",
    question: "인증이 반려되면 어떻게 하나요?",
    answer:
      "반려 사유는 마이페이지 > 내 인증 관리에서 확인할 수 있습니다. 사유를 확인한 뒤 동일한 신청 건에서 서류를 다시 업로드해 재인증을 신청할 수 있어요.",
  },
  {
    id: "f3",
    question: "실결제가는 어떻게 공개되나요?",
    answer:
      "인증된 영수증/계약서에서 확인된 실제 결제 금액이 리뷰와 함께 공개됩니다. 개인 식별 정보(이름, 연락처, 서명 등)는 자동으로 마스킹 처리되어 결제 금액과 계약 구성만 노출됩니다.",
  },
  {
    id: "f4",
    question: "업체 비교는 몇 개까지 가능한가요?",
    answer: "탐색 화면에서 최대 3개 업체까지 선택해 실결제가, 패키지 구성, 옵션 가격을 한눈에 비교할 수 있습니다.",
  },
  {
    id: "f5",
    question: "AI 자동 답변은 얼마나 정확한가요?",
    answer:
      "커뮤니티의 AI 자동 답변은 축적된 인증 리뷰와 일반적인 스드메 준비 정보를 바탕으로 생성되는 참고용 답변입니다. 실제 계약 조건은 반드시 업체와 직접 확인해 주세요.",
  },
];

export const NOTICES: NoticeItem[] = [
  {
    id: "n1",
    title: "여름 성수기 검수 소요 시간 안내",
    date: "2025.10.21",
    body: "7~8월 인증 신청 폭증으로 검수 소요 시간이 평균 2~3일로 늘어났습니다. 예식 일정이 임박한 경우 고객센터로 문의해 주세요.",
  },
  {
    id: "n2",
    title: "업체 비교함 저장 기능 오픈",
    date: "2025.10.06",
    body: "탐색 화면에서 비교한 업체 조합을 저장하고 마이페이지에서 다시 불러올 수 있는 기능이 추가되었습니다.",
  },
  {
    id: "n3",
    title: "개인정보 마스킹 처리 강화 안내",
    date: "2025.09.20",
    body: "영수증/계약서 업로드 시 이름, 연락처, 서명 영역의 마스킹 처리가 한층 강화되었습니다.",
  },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a1", type: "post", label: "게시글 작성", targetTitle: "부케 셀프 디자인 해보신 분 계신가요", createdAt: "2025.10.12" },
  { id: "a2", type: "comment", label: "댓글 작성", targetTitle: "본식 스냅 헬퍼 유무 꼭 확인하세요", createdAt: "2025.10.23" },
  { id: "a3", type: "like", label: "좋아요", targetTitle: "골든아워 야외 촬영, 진짜 다르더라구요", createdAt: "2025.09.29" },
  { id: "a4", type: "comment", label: "댓글 작성", targetTitle: "가봉 2회 vs 1회, 체감 차이가 클까요?", createdAt: "2025.10.20" },
  { id: "a5", type: "like", label: "좋아요", targetTitle: "축가 연주자 섭외, 어디서 알아보셨나요", createdAt: "2025.10.06" },
];

export const MY_REVIEWS: MyReview[] = [
  {
    id: "mr1",
    vendorName: "글로우 헤어메이크업",
    category: "makeup",
    ratingAvg: 4.8,
    content: "원장님이 직접 해주셔서 지속력이 정말 좋았어요. 리허설 스타일을 그대로 재현해주셨습니다.",
    status: "published",
    createdAt: "2025.10.23",
  },
  {
    id: "mr2",
    vendorName: "루메르 스튜디오",
    category: "studio",
    ratingAvg: 4.5,
    content: "촬영 당일 스케줄이 여유로워서 편안하게 진행했어요. 보정 톤이 자연스러웠습니다.",
    status: "published",
    createdAt: "2025.10.19",
  },
  {
    id: "mr3",
    vendorName: "예그리나 스튜디오",
    category: "studio",
    ratingAvg: 0,
    content: "",
    status: "draft",
    createdAt: "2025.10.31",
  },
];
