import type {
  ActivityLogEntry,
  ApiKeyEntry,
  ChannelIntegration,
  Customer,
  ContentItem,
  DataSource,
  KpiPoint,
  PromptTemplate,
  TeamUser,
  Workflow,
} from "@/projects/monitoring/marketflow/lib/types";

/** 목업 기준 시각. spec.md의 제작 기간(2025.03~2025.09) 안의 날짜로 고정한다. */
export const TODAY = "2025-09-08";
export const TODAY_LABEL = "2025. 09. 08 (월) 09:32 KST";

/* ── 고객사 (CRM) ──
   전부 알파벳 기반 익명화. 사람 이름/연락처는 실제처럼 보이지만 가상이다. */
export const customers: Customer[] = [
  {
    id: "cu1",
    name: "A테크",
    industry: "이커머스 / 가전",
    tier: "엔터프라이즈",
    status: "active",
    contractStart: "2025-03-04",
    contractEnd: "2026-03-03",
    monthlyQuota: 60,
    usedThisMonth: 47,
    manager: { name: "오지훈", email: "jihoon.oh@a-tech.example", phone: "010-2841-7723" },
    brandTone: "신뢰감 있는 정보 전달, 전문 용어는 쉬운 말로 풀어 설명. 이모지 사용 자제.",
    channels: ["네이버 블로그", "인스타그램", "유튜브"],
    notes: [
      { id: "n1", at: "2025-09-02", author: "박서연", content: "9월 추석 프로모션 콘텐츠 물량을 평소 대비 40% 늘리기로 협의. 카드뉴스 비중 확대 요청." },
      { id: "n2", at: "2025-08-11", author: "김도현", content: "블로그 톤앤매너에 대해 '너무 딱딱하다'는 피드백. 프롬프트 템플릿 수정 완료 후 재발송." },
    ],
    createdAt: "2025-03-04",
  },
  {
    id: "cu2",
    name: "B소재",
    industry: "제조 / 산업재",
    tier: "프로",
    status: "active",
    contractStart: "2025-03-18",
    contractEnd: "2026-03-17",
    monthlyQuota: 24,
    usedThisMonth: 19,
    manager: { name: "한승우", email: "sw.han@b-material.example", phone: "010-3312-5590" },
    brandTone: "B2B 담당자 대상. 수치와 근거를 반드시 포함, 과장 표현 금지.",
    channels: ["네이버 블로그", "카카오채널"],
    notes: [
      { id: "n3", at: "2025-08-20", author: "박서연", content: "산업재 특성상 승인 리드타임이 길어 예약 발행 기본값을 +3일로 조정." },
    ],
    createdAt: "2025-03-18",
  },
  {
    id: "cu3",
    name: "C페이",
    industry: "핀테크",
    tier: "엔터프라이즈",
    status: "active",
    contractStart: "2025-03-25",
    contractEnd: "2026-03-24",
    monthlyQuota: 48,
    usedThisMonth: 48,
    manager: { name: "윤소미", email: "somi.yoon@c-pay.example", phone: "010-9021-4468" },
    brandTone: "규제 산업 특성상 모든 수치 표현에 출처 명시 필수. 확정되지 않은 혜택 언급 금지.",
    channels: ["네이버 블로그", "인스타그램", "페이스북"],
    notes: [
      { id: "n4", at: "2025-09-05", author: "이하은", content: "이번 달 쿼터 소진 완료. 추가 생성 요청 시 다음 달로 이월 안내함." },
      { id: "n5", at: "2025-07-14", author: "박서연", content: "금융 규제 검수 프로세스 추가 요청 반영 완료." },
    ],
    createdAt: "2025-03-25",
  },
  {
    id: "cu4",
    name: "D리빙",
    industry: "리빙 / 인테리어",
    tier: "스타터",
    status: "trial",
    contractStart: "2025-08-18",
    contractEnd: "2025-09-17",
    monthlyQuota: 10,
    usedThisMonth: 6,
    manager: { name: "장미래", email: "mirae.jang@d-living.example", phone: "010-4471-8802" },
    brandTone: "따뜻하고 감성적인 어투. 계절감 있는 표현 선호.",
    channels: ["인스타그램"],
    notes: [
      { id: "n6", at: "2025-08-19", author: "정유진", content: "무료 체험 킥오프 콜 완료. 정식 전환은 9월 17일 이전 결정 예정." },
    ],
    createdAt: "2025-08-18",
  },
  {
    id: "cu5",
    name: "E뷰티",
    industry: "뷰티 / 코스메틱",
    tier: "프로",
    status: "active",
    contractStart: "2025-04-02",
    contractEnd: "2026-04-01",
    monthlyQuota: 32,
    usedThisMonth: 21,
    manager: { name: "서다인", email: "dain.seo@e-beauty.example", phone: "010-6650-2214" },
    brandTone: "트렌디하고 발랄한 어투. Z세대 유행어는 팀 검수 후에만 사용.",
    channels: ["인스타그램", "유튜브"],
    notes: [
      { id: "n7", at: "2025-08-29", author: "이하은", content: "숏폼 아바타 영상 반응이 좋아 9월부터 주 3회로 확대 요청." },
    ],
    createdAt: "2025-04-02",
  },
  {
    id: "cu6",
    name: "F푸드",
    industry: "F&B 프랜차이즈",
    tier: "프로",
    status: "active",
    contractStart: "2025-04-15",
    contractEnd: "2026-04-14",
    monthlyQuota: 28,
    usedThisMonth: 24,
    manager: { name: "임재현", email: "jaehyun.lim@f-food.example", phone: "010-7789-3301" },
    brandTone: "친근하고 유쾌한 어투. 가맹점 관점의 실용 정보 포함.",
    channels: ["네이버 블로그", "인스타그램", "카카오채널"],
    notes: [
      { id: "n8", at: "2025-07-30", author: "김도현", content: "신메뉴 출시 일정과 콘텐츠 캘린더 동기화 완료." },
    ],
    createdAt: "2025-04-15",
  },
  {
    id: "cu7",
    name: "G모빌리티",
    industry: "모빌리티",
    tier: "스타터",
    status: "paused",
    contractStart: "2025-05-09",
    contractEnd: "2026-05-08",
    monthlyQuota: 12,
    usedThisMonth: 0,
    manager: { name: "노현서", email: "hyunseo.no@g-mobility.example", phone: "010-1123-9987" },
    brandTone: "간결하고 담백한 어투. 안전 관련 문구는 법무 검수 후 사용.",
    channels: ["네이버 블로그"],
    notes: [
      { id: "n9", at: "2025-08-25", author: "강태우", content: "내부 예산 재검토로 9월 콘텐츠 생성 일시 중지 요청. 10월 재개 예정." },
    ],
    createdAt: "2025-05-09",
  },
  {
    id: "cu8",
    name: "H헬스",
    industry: "헬스케어",
    tier: "엔터프라이즈",
    status: "active",
    contractStart: "2025-05-20",
    contractEnd: "2026-05-19",
    monthlyQuota: 40,
    usedThisMonth: 33,
    manager: { name: "권나윤", email: "nayoon.kwon@h-health.example", phone: "010-5567-2298" },
    brandTone: "의학 정보는 반드시 검수 후 발행. 단정적 효능 표현 금지.",
    channels: ["네이버 블로그", "유튜브"],
    notes: [
      { id: "n10", at: "2025-06-30", author: "박서연", content: "의료광고법 검토 프로세스를 승인 워크플로우에 추가 반영." },
    ],
    createdAt: "2025-05-20",
  },
  {
    id: "cu9",
    name: "J에듀",
    industry: "에듀테크",
    tier: "스타터",
    status: "churned",
    contractStart: "2025-03-10",
    contractEnd: "2025-08-09",
    monthlyQuota: 10,
    usedThisMonth: 0,
    manager: { name: "배은수", email: "eunsu.bae@j-edu.example", phone: "010-8834-5512" },
    brandTone: "친절한 선생님 어투.",
    channels: ["카카오채널"],
    notes: [
      { id: "n11", at: "2025-08-09", author: "강태우", content: "자체 마케팅팀 구성으로 계약 종료. 데이터 백업본 전달 완료." },
    ],
    createdAt: "2025-03-10",
  },
  {
    id: "cu10",
    name: "K펫",
    industry: "펫케어",
    tier: "프로",
    status: "trial",
    contractStart: "2025-08-27",
    contractEnd: "2025-09-26",
    monthlyQuota: 16,
    usedThisMonth: 9,
    manager: { name: "홍재민", email: "jaemin.hong@k-pet.example", phone: "010-2298-6671" },
    brandTone: "다정하고 따뜻한 어투. 반려동물 의인화 표현 적극 사용.",
    channels: ["인스타그램", "카카오채널"],
    notes: [
      { id: "n12", at: "2025-08-28", author: "정유진", content: "체험 기간 중 카드뉴스 성과 리포트 매주 공유하기로 함." },
    ],
    createdAt: "2025-08-27",
  },
];

const IMG = {
  desk: 0,
  air: 2,
  notebook: 8,
  phone: 9,
  closed: 48,
  flatlay1: 180,
  wood: 370,
  imac: 668,
  monitor: 60,
  flatlay2: 532,
};

/* ── 콘텐츠 ── */
export const contentItems: ContentItem[] = [
  {
    id: "ct1",
    title: "추석 연휴 배송 지연 안내와 스마트 주문 팁",
    type: "blog",
    customerId: "cu1",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["추석배송", "이커머스", "주문팁"],
    thumbnail: IMG.desk,
    assignee: "이하은",
    publishedAt: "2025-09-01T09:00:00",
    createdAt: "2025-08-28",
    excerpt: "추석 연휴 배송 일정과 미리 주문해야 하는 품목을 안내하는 정보성 블로그.",
    body: [
      "추석 연휴를 앞두고 배송 일정에 변화가 생깁니다. A테크는 9월 5일까지 주문 건에 한해 연휴 전 도착을 보장합니다.",
      "연휴 기간 중 접수된 주문은 순차 발송되며, 냉장, 냉동 제품은 별도 안내에 따라 처리됩니다.",
      "미리 주문 시 참고할 수 있는 인기 선물세트 TOP 5를 함께 소개합니다.",
    ],
    aiScore: 92,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-08-28T10:20:00", author: "AI 자동 생성", summary: "주제/키워드 기반 초안 생성" },
      { id: "v2", label: "v2 수정", at: "2025-08-29T14:05:00", author: "이하은", summary: "배송 마감일 수치 보정, 문단 순서 조정" },
      { id: "v3", label: "v3 승인본", at: "2025-08-30T11:40:00", author: "박서연", summary: "최종 승인, 발행 일정 확정" },
    ],
    comments: [
      { id: "cm1", author: "박서연", at: "2025-08-30T11:40:00", action: "approve", text: "수치 확인 완료. 예정대로 발행 진행해주세요." },
    ],
  },
  {
    id: "ct2",
    title: "가을맞이 신제품 라인업 카드뉴스",
    type: "cardnews",
    customerId: "cu1",
    status: "scheduled",
    channels: ["인스타그램"],
    keywords: ["신제품", "가을시즌", "가전"],
    thumbnail: IMG.flatlay1,
    assignee: "이하은",
    scheduledAt: "2025-09-12T11:00:00",
    createdAt: "2025-09-03",
    excerpt: "가을 신제품 3종을 소개하는 8장 카드뉴스.",
    body: [
      "1장: 가을, 집안 공기를 바꿀 시간",
      "2장: 초경량 무선 공기청정기 소개",
      "3장: 저소음 모드로 밤에도 편안하게",
    ],
    aiScore: 88,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-09-03T09:12:00", author: "AI 자동 생성", summary: "8장 구성 초안" },
      { id: "v2", label: "v2 승인본", at: "2025-09-04T16:30:00", author: "박서연", summary: "카피 톤 조정 후 승인" },
    ],
    comments: [
      { id: "cm2", author: "박서연", at: "2025-09-04T16:30:00", action: "approve", text: "5장 카피가 임팩트 있네요. 이대로 예약 진행." },
    ],
  },
  {
    id: "ct3",
    title: "AI가 정리한 이번 주 이커머스 트렌드 3가지",
    type: "blog",
    customerId: "cu1",
    status: "pending",
    channels: ["네이버 블로그"],
    keywords: ["이커머스트렌드", "주간리포트"],
    thumbnail: IMG.notebook,
    assignee: "이하은",
    createdAt: "2025-09-06",
    excerpt: "RSS로 수집한 업계 뉴스를 기반으로 정리한 주간 트렌드 블로그.",
    body: [
      "이번 주 이커머스 업계에서는 라이브 커머스 재편, 당일배송 경쟁 심화, 리퍼브 시장 성장이 주요 이슈로 떠올랐습니다.",
      "각 트렌드가 A테크에 미치는 영향을 짧게 짚어봅니다.",
    ],
    aiScore: 85,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-09-06T08:40:00", author: "AI 자동 생성", summary: "수집 뉴스 3건 요약 반영" },
    ],
    comments: [],
  },
  {
    id: "ct4",
    title: "무선 이어폰 오픈형 vs 커널형 비교 숏폼",
    type: "short",
    customerId: "cu1",
    status: "draft",
    channels: ["유튜브"],
    keywords: ["이어폰비교", "숏폼"],
    assignee: "최민준",
    createdAt: "2025-09-07",
    excerpt: "15초 분량 비교 숏폼 대본 초안.",
    body: ["오픈형과 커널형, 뭐가 다를까요?", "착용감은 오픈형이, 저음은 커널형이 우세합니다.", "지금 A테크 앱에서 직접 비교해보세요."],
    aiScore: 79,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-07T15:02:00", author: "AI 자동 생성", summary: "대본 초안 생성, 아바타 영상 미생성" }],
    comments: [],
  },
  {
    id: "ct5",
    title: "산업용 복합소재 내구성 테스트 리포트",
    type: "blog",
    customerId: "cu2",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["복합소재", "내구성테스트"],
    thumbnail: IMG.closed,
    assignee: "김도현",
    publishedAt: "2025-08-25T10:00:00",
    createdAt: "2025-08-18",
    excerpt: "자체 테스트 결과를 근거로 한 신뢰형 정보 블로그.",
    body: [
      "B소재의 신규 복합소재는 자체 인장강도 테스트에서 기존 대비 18% 향상된 수치를 기록했습니다.",
      "테스트 조건과 측정 방식을 투명하게 공개합니다.",
    ],
    aiScore: 90,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-08-18T09:00:00", author: "AI 자동 생성", summary: "테스트 데이터 반영 초안" },
      { id: "v2", label: "v2 승인본", at: "2025-08-20T13:20:00", author: "한승우", summary: "수치 근거 각주 추가 후 승인" },
    ],
    comments: [{ id: "cm3", author: "한승우", at: "2025-08-20T13:20:00", action: "approve", text: "수치 출처 명확해서 좋습니다. 승인합니다." }],
  },
  {
    id: "ct6",
    title: "친환경 소재 인증 획득 소식",
    type: "blog",
    customerId: "cu2",
    status: "rejected",
    channels: ["네이버 블로그"],
    keywords: ["친환경인증", "ESG"],
    assignee: "김도현",
    createdAt: "2025-09-01",
    excerpt: "인증 획득 소식을 전하는 보도자료형 블로그.",
    body: ["B소재가 국제 친환경 소재 인증을 획득했습니다.", "이번 인증은 원료 채취부터 생산까지 전 과정을 평가합니다."],
    aiScore: 74,
    rejectReason: "인증 기관명과 인증 번호가 실제 문서와 불일치합니다. 근거 자료 재확인 후 재요청 바랍니다.",
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-01T11:10:00", author: "AI 자동 생성", summary: "보도자료 톤 초안" }],
    comments: [
      { id: "cm4", author: "한승우", at: "2025-09-02T09:50:00", action: "reject", text: "인증 번호가 실제 서류와 달라 반려합니다. 확인 후 재생성 요청드립니다." },
    ],
  },
  {
    id: "ct7",
    title: "산업 현장 안전관리 체크리스트 카드뉴스",
    type: "cardnews",
    customerId: "cu2",
    status: "scheduled",
    channels: ["카카오채널"],
    keywords: ["안전관리", "산업현장"],
    thumbnail: IMG.flatlay2,
    assignee: "최민준",
    scheduledAt: "2025-09-15T09:00:00",
    createdAt: "2025-09-04",
    excerpt: "현장 안전 점검 항목 6가지를 정리한 카드뉴스.",
    body: ["1장: 오늘도 안전한 현장을 위해", "2장: 보호구 착용 여부 확인", "3장: 비상 대피 경로 숙지"],
    aiScore: 87,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-09-04T10:00:00", author: "한승우", summary: "법무팀 검수 반영 후 승인" }],
    comments: [{ id: "cm5", author: "한승우", at: "2025-09-04T10:00:00", action: "approve", text: "안전 문구 법무 검토 완료, 예약 진행해주세요." }],
  },
  {
    id: "ct8",
    title: "간편송금 신규 기능 소개 블로그",
    type: "blog",
    customerId: "cu3",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["간편송금", "핀테크"],
    thumbnail: IMG.phone,
    assignee: "정유진",
    publishedAt: "2025-09-02T09:30:00",
    createdAt: "2025-08-27",
    excerpt: "신규 송금 기능을 소개하는 규제 검수 완료 블로그.",
    body: ["C페이가 그룹 송금 기능을 새롭게 선보입니다.", "모든 수치와 한도는 2025년 9월 기준 공시 자료를 따릅니다."],
    aiScore: 94,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-08-27T09:00:00", author: "AI 자동 생성", summary: "기능 소개 초안" },
      { id: "v2", label: "v2 규제검수", at: "2025-08-29T17:00:00", author: "윤소미", summary: "한도 문구 규정 확인 후 수정" },
      { id: "v3", label: "v3 승인본", at: "2025-08-31T10:15:00", author: "박서연", summary: "최종 승인" },
    ],
    comments: [{ id: "cm6", author: "박서연", at: "2025-08-31T10:15:00", action: "approve", text: "규제 검수 문구 확인했습니다. 승인합니다." }],
  },
  {
    id: "ct9",
    title: "연말정산 미리 준비하는 절세 카드뉴스",
    type: "cardnews",
    customerId: "cu3",
    status: "pending",
    channels: ["인스타그램", "페이스북"],
    keywords: ["연말정산", "절세"],
    thumbnail: IMG.monitor,
    assignee: "정유진",
    createdAt: "2025-09-07",
    excerpt: "9월부터 미리 준비하는 절세 팁 카드뉴스 6장.",
    body: ["1장: 연말정산, 9월부터 준비하세요", "2장: 놓치기 쉬운 공제 항목 3가지"],
    aiScore: 81,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-07T13:00:00", author: "AI 자동 생성", summary: "절세 항목 카피 초안" }],
    comments: [],
  },
  {
    id: "ct10",
    title: "리빙 인테리어 가을 컬러 트렌드",
    type: "cardnews",
    customerId: "cu4",
    status: "draft",
    channels: ["인스타그램"],
    keywords: ["인테리어트렌드", "가을컬러"],
    thumbnail: IMG.wood,
    assignee: "이하은",
    createdAt: "2025-09-05",
    excerpt: "가을 시즌 인테리어 컬러 트렌드를 소개하는 카드뉴스 초안.",
    body: ["1장: 올가을, 집을 물들일 컬러는?", "2장: 테라코타와 세이지그린의 조합"],
    aiScore: 83,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-05T11:20:00", author: "AI 자동 생성", summary: "컬러 트렌드 초안" }],
    comments: [],
  },
  {
    id: "ct11",
    title: "홈오피스 구축 가이드 블로그",
    type: "blog",
    customerId: "cu4",
    status: "scheduled",
    channels: ["인스타그램"],
    keywords: ["홈오피스", "인테리어"],
    thumbnail: IMG.monitor,
    assignee: "이하은",
    scheduledAt: "2025-09-10T10:00:00",
    createdAt: "2025-08-30",
    excerpt: "재택근무자를 위한 홈오피스 구축 가이드.",
    body: ["재택근무가 늘면서 홈오피스 인테리어에 대한 관심도 커지고 있습니다.", "공간 활용 팁 5가지를 소개합니다."],
    aiScore: 86,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-08-31T09:40:00", author: "장미래", summary: "체험 고객 첫 콘텐츠, 승인 완료" }],
    comments: [{ id: "cm7", author: "장미래", at: "2025-08-31T09:40:00", action: "approve", text: "톤앤매너 마음에 듭니다. 예약 진행해주세요." }],
  },
  {
    id: "ct12",
    title: "여름 클렌징 루틴 숏폼",
    type: "short",
    customerId: "cu5",
    status: "published",
    channels: ["인스타그램", "유튜브"],
    keywords: ["클렌징", "스킨케어"],
    thumbnail: IMG.flatlay2,
    assignee: "최민준",
    publishedAt: "2025-08-20T18:00:00",
    createdAt: "2025-08-14",
    excerpt: "AI 아바타가 소개하는 15초 클렌징 루틴.",
    body: ["끈적임 없이 산뜻하게, 이중 클렌징 루틴", "1단계: 오일 클렌저로 메이크업 녹이기", "2단계: 폼 클렌저로 마무리"],
    aiScore: 91,
    versions: [
      { id: "v1", label: "v1 대본", at: "2025-08-14T10:00:00", author: "AI 자동 생성", summary: "대본 초안" },
      { id: "v2", label: "v2 아바타 영상", at: "2025-08-16T15:30:00", author: "AI 자동 생성", summary: "아바타 영상 생성 완료" },
      { id: "v3", label: "v3 승인본", at: "2025-08-18T11:00:00", author: "서다인", summary: "발음 보정 후 승인" },
    ],
    comments: [{ id: "cm8", author: "서다인", at: "2025-08-18T11:00:00", action: "approve", text: "아바타 발음 자연스럽네요. 발행 진행해주세요." }],
  },
  {
    id: "ct13",
    title: "9월 신상 립 컬러 3종 카드뉴스",
    type: "cardnews",
    customerId: "cu5",
    status: "scheduled",
    channels: ["인스타그램"],
    keywords: ["신상립", "메이크업"],
    thumbnail: IMG.flatlay1,
    assignee: "최민준",
    scheduledAt: "2025-09-11T12:00:00",
    createdAt: "2025-09-02",
    excerpt: "신상 립 컬러 3종을 소개하는 6장 카드뉴스.",
    body: ["1장: 이번 가을, 입술 끝에 물든 계절", "2장: 로즈 브라운 - 데일리용", "3장: 딥 레드 - 포인트용"],
    aiScore: 89,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-09-03T14:00:00", author: "서다인", summary: "컬러 코드 확인 후 승인" }],
    comments: [{ id: "cm9", author: "서다인", at: "2025-09-03T14:00:00", action: "approve", text: "컬러 코드 정확합니다. 예약 진행해주세요." }],
  },
  {
    id: "ct14",
    title: "성분 인증 마크 안내 블로그",
    type: "blog",
    customerId: "cu5",
    status: "pending",
    channels: ["인스타그램"],
    keywords: ["성분인증", "클린뷰티"],
    thumbnail: IMG.desk,
    assignee: "최민준",
    createdAt: "2025-09-06",
    excerpt: "제품에 표기된 성분 인증 마크의 의미를 설명하는 블로그.",
    body: ["EWG 그린등급이 무엇인지, 왜 중요한지 쉽게 풀어 설명합니다."],
    aiScore: 82,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-06T16:00:00", author: "AI 자동 생성", summary: "성분 정보 초안" }],
    comments: [],
  },
  {
    id: "ct15",
    title: "가을 신메뉴 출시 카드뉴스",
    type: "cardnews",
    customerId: "cu6",
    status: "published",
    channels: ["네이버 블로그", "인스타그램"],
    keywords: ["신메뉴", "가을시즌"],
    thumbnail: IMG.flatlay1,
    assignee: "김도현",
    publishedAt: "2025-08-28T11:00:00",
    createdAt: "2025-08-20",
    excerpt: "가을 신메뉴 2종을 소개하는 5장 카드뉴스.",
    body: ["1장: 가을에만 만나는 특별한 맛", "2장: 밤 크림 라떼 출시", "3장: 단호박 스콘 출시"],
    aiScore: 90,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-08-22T10:00:00", author: "임재현", summary: "메뉴명 확정 후 승인" }],
    comments: [{ id: "cm10", author: "임재현", at: "2025-08-22T10:00:00", action: "approve", text: "메뉴명, 가격 모두 정확합니다." }],
  },
  {
    id: "ct16",
    title: "가맹점주를 위한 재고관리 팁 블로그",
    type: "blog",
    customerId: "cu6",
    status: "scheduled",
    channels: ["카카오채널"],
    keywords: ["가맹점", "재고관리"],
    thumbnail: IMG.notebook,
    assignee: "김도현",
    scheduledAt: "2025-09-13T09:00:00",
    createdAt: "2025-09-03",
    excerpt: "가맹점주 대상 재고관리 실전 팁을 정리한 블로그.",
    body: ["폐기율을 줄이는 발주 주기 설정법을 소개합니다."],
    aiScore: 84,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-09-04T09:30:00", author: "임재현", summary: "현장 데이터 반영 후 승인" }],
    comments: [{ id: "cm11", author: "임재현", at: "2025-09-04T09:30:00", action: "approve", text: "가맹점 실제 데이터와 맞습니다." }],
  },
  {
    id: "ct17",
    title: "매장 이벤트 홍보 숏폼",
    type: "short",
    customerId: "cu6",
    status: "draft",
    channels: ["인스타그램"],
    keywords: ["매장이벤트", "숏폼"],
    assignee: "최민준",
    createdAt: "2025-09-07",
    excerpt: "9월 한정 매장 이벤트 홍보 숏폼 대본.",
    body: ["9월 한정! 두 잔 사면 한 잔 무료", "가까운 매장을 지금 확인해보세요"],
    aiScore: 76,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-07T10:40:00", author: "AI 자동 생성", summary: "이벤트 홍보 대본 초안" }],
    comments: [],
  },
  {
    id: "ct18",
    title: "정기 구독 서비스 이용 가이드",
    type: "blog",
    customerId: "cu8",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["구독서비스", "헬스케어"],
    thumbnail: IMG.closed,
    assignee: "정유진",
    publishedAt: "2025-08-15T09:00:00",
    createdAt: "2025-08-08",
    excerpt: "정기 구독 서비스 이용 방법을 안내하는 가이드 블로그.",
    body: ["H헬스 정기 구독 서비스 신청부터 이용까지의 과정을 안내합니다.", "의학적 효능 표현은 검수팀 확인을 거쳤습니다."],
    aiScore: 93,
    versions: [
      { id: "v1", label: "v1 초안", at: "2025-08-08T09:00:00", author: "AI 자동 생성", summary: "이용 가이드 초안" },
      { id: "v2", label: "v2 의료검수", at: "2025-08-11T14:00:00", author: "권나윤", summary: "의료광고법 검토 완료" },
    ],
    comments: [{ id: "cm12", author: "권나윤", at: "2025-08-11T14:00:00", action: "approve", text: "의료광고법 검토 완료했습니다. 발행 진행해주세요." }],
  },
  {
    id: "ct19",
    title: "환절기 건강관리 카드뉴스",
    type: "cardnews",
    customerId: "cu8",
    status: "pending",
    channels: ["네이버 블로그"],
    keywords: ["환절기건강", "면역관리"],
    thumbnail: IMG.wood,
    assignee: "정유진",
    createdAt: "2025-09-06",
    excerpt: "환절기 건강관리 수칙을 정리한 카드뉴스.",
    body: ["1장: 일교차 큰 요즘, 면역력 관리는 필수", "2장: 하루 물 섭취량 체크하기"],
    aiScore: 80,
    rejectReason: undefined,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-06T13:30:00", author: "AI 자동 생성", summary: "건강 수칙 초안, 의료 검수 대기" }],
    comments: [],
  },
  {
    id: "ct20",
    title: "체험단 모집 안내 카드뉴스",
    type: "cardnews",
    customerId: "cu10",
    status: "scheduled",
    channels: ["인스타그램"],
    keywords: ["체험단모집", "펫용품"],
    thumbnail: IMG.flatlay2,
    assignee: "정유진",
    scheduledAt: "2025-09-14T10:00:00",
    createdAt: "2025-09-05",
    excerpt: "신제품 체험단을 모집하는 카드뉴스.",
    body: ["1장: 우리 아이 첫 체험단을 모집합니다", "2장: 참여 방법 안내"],
    aiScore: 85,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-09-05T15:00:00", author: "홍재민", summary: "체험단 조건 확정 후 승인" }],
    comments: [{ id: "cm13", author: "홍재민", at: "2025-09-05T15:00:00", action: "approve", text: "모집 조건 정확합니다." }],
  },
  {
    id: "ct21",
    title: "반려동물 가을철 산책 안전 수칙",
    type: "blog",
    customerId: "cu10",
    status: "draft",
    channels: ["카카오채널"],
    keywords: ["산책안전", "반려동물"],
    assignee: "이하은",
    createdAt: "2025-09-07",
    excerpt: "가을철 산책 시 주의할 점을 정리한 블로그 초안.",
    body: ["기온이 낮아지는 가을, 산책 시간대 조정이 필요합니다."],
    aiScore: 78,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-07T17:10:00", author: "AI 자동 생성", summary: "산책 안전 초안" }],
    comments: [],
  },
  {
    id: "ct22",
    title: "1분기 성과 리포트 요약 블로그",
    type: "blog",
    customerId: "cu2",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["성과리포트"],
    thumbnail: IMG.imac,
    assignee: "김도현",
    publishedAt: "2025-04-10T09:00:00",
    createdAt: "2025-04-05",
    excerpt: "1분기 콘텐츠 성과를 요약한 리포트형 블로그.",
    body: ["1분기 총 18건의 콘텐츠가 발행되었고, 평균 도달률은 전분기 대비 12% 상승했습니다."],
    aiScore: 88,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-04-07T10:00:00", author: "한승우", summary: "리포트 수치 확인 후 승인" }],
    comments: [{ id: "cm14", author: "한승우", at: "2025-04-07T10:00:00", action: "approve", text: "수치 확인했습니다." }],
  },
  {
    id: "ct23",
    title: "여름 휴가철 배송 안내",
    type: "blog",
    customerId: "cu1",
    status: "published",
    channels: ["네이버 블로그"],
    keywords: ["여름휴가", "배송안내"],
    thumbnail: IMG.air,
    assignee: "이하은",
    publishedAt: "2025-07-20T09:00:00",
    createdAt: "2025-07-15",
    excerpt: "여름 휴가철 배송 일정 변경 안내 블로그.",
    body: ["7월 말부터 8월 초까지 물류센터 운영 일정이 변경됩니다."],
    aiScore: 87,
    versions: [{ id: "v1", label: "v1 승인본", at: "2025-07-16T10:00:00", author: "박서연", summary: "물류 일정 확인 후 승인" }],
    comments: [{ id: "cm15", author: "박서연", at: "2025-07-16T10:00:00", action: "approve", text: "물류팀 확인 완료했습니다." }],
  },
  {
    id: "ct24",
    title: "가맹 창업 비용 가이드 블로그",
    type: "blog",
    customerId: "cu6",
    status: "pending",
    channels: ["네이버 블로그"],
    keywords: ["가맹창업", "창업비용"],
    thumbnail: IMG.desk,
    assignee: "김도현",
    createdAt: "2025-09-08",
    excerpt: "가맹 창업을 고려하는 예비 점주를 위한 비용 가이드.",
    body: ["가맹비, 인테리어 비용, 초도 물품비를 항목별로 정리했습니다."],
    aiScore: 83,
    versions: [{ id: "v1", label: "v1 초안", at: "2025-09-08T08:50:00", author: "AI 자동 생성", summary: "비용 항목 초안" }],
    comments: [],
  },
];

/* ── 자동화 워크플로우 ── */
export const workflows: Workflow[] = [
  {
    id: "wf1",
    name: "블로그 자동 발행 파이프라인",
    description: "RSS로 업계 뉴스를 수집해 블로그 초안을 생성하고, 승인 후 네이버 블로그에 자동 발행합니다.",
    status: "active",
    trigger: "RSS 수집 (30분마다)",
    customerId: "cu1",
    steps: [
      { id: "s1", label: "업계 뉴스 RSS 수집", type: "collect", detail: "이커머스 트렌드 리포트 RSS | 키워드 3개" },
      { id: "s2", label: "블로그 초안 생성", type: "generate", detail: "정밀 생성 모델 | A테크 전용 프롬프트" },
      { id: "s3", label: "운영팀 승인", type: "approve", detail: "담당자 이하은 → 박서연 2단계 승인" },
      { id: "s4", label: "네이버 블로그 발행", type: "publish", detail: "승인 완료 시 즉시 발행" },
      { id: "s5", label: "슬랙 알림", type: "notify", detail: "#a-tech-content 채널로 발행 결과 전송" },
    ],
    successRate: 96,
    lastRunAt: "2025-09-08T09:00:00",
    runsToday: 4,
    history: [
      { id: "r1", at: "2025-09-08T09:00:00", status: "success", duration: "2분 14초", detail: "신규 뉴스 2건 수집, 초안 1건 생성" },
      { id: "r2", at: "2025-09-08T08:30:00", status: "success", duration: "1분 02초", detail: "신규 뉴스 없음, 생성 생략" },
      { id: "r3", at: "2025-09-07T18:00:00", status: "success", duration: "2분 40초", detail: "초안 1건 생성, 승인 대기 전환" },
      { id: "r4", at: "2025-09-07T09:30:00", status: "failed", duration: "0분 48초", detail: "RSS 응답 지연으로 타임아웃, 재시도 예약됨" },
    ],
  },
  {
    id: "wf2",
    name: "카드뉴스 주간 배치",
    description: "매주 월요일 오전, 지난주 등록된 신제품 정보를 기반으로 카드뉴스 초안을 일괄 생성합니다.",
    status: "active",
    trigger: "일정 예약 (매주 월 09:00)",
    steps: [
      { id: "s6", label: "신제품 등록 데이터 조회", type: "collect", detail: "고객사별 상품 DB 연동" },
      { id: "s7", label: "카드뉴스 6~8장 생성", type: "generate", detail: "이미지 생성 모델 + 정밀 생성 모델 조합" },
      { id: "s8", label: "담당 에디터 승인", type: "approve", detail: "고객사별 담당 에디터에게 배정" },
      { id: "s9", label: "예약 발행 등록", type: "publish", detail: "콘텐츠 캘린더에 예약 슬롯 자동 등록" },
    ],
    successRate: 91,
    lastRunAt: "2025-09-08T09:00:00",
    runsToday: 1,
    history: [
      { id: "r5", at: "2025-09-08T09:00:00", status: "success", duration: "6분 32초", detail: "6개 고객사, 총 9건 초안 생성" },
      { id: "r6", at: "2025-09-01T09:00:00", status: "success", duration: "5분 58초", detail: "5개 고객사, 총 7건 초안 생성" },
      { id: "r7", at: "2025-08-25T09:00:00", status: "success", duration: "6분 10초", detail: "6개 고객사, 총 8건 초안 생성" },
    ],
  },
  {
    id: "wf3",
    name: "숏폼 대본 자동 생성",
    description: "신제품이 등록되면 웹훅으로 트리거되어 15초 분량 숏폼 대본을 자동 생성합니다.",
    status: "paused",
    trigger: "API 웹훅 (상품 등록 이벤트)",
    steps: [
      { id: "s10", label: "상품 등록 이벤트 수신", type: "collect", detail: "고객사 상품 DB 웹훅" },
      { id: "s11", label: "숏폼 대본 생성", type: "generate", detail: "빠른 응답 모델 | 15초 분량 고정" },
      { id: "s12", label: "담당자 검토", type: "approve", detail: "생성 즉시 담당 에디터에게 알림" },
    ],
    successRate: 88,
    lastRunAt: "2025-08-30T14:22:00",
    runsToday: 0,
    history: [
      { id: "r8", at: "2025-08-30T14:22:00", status: "success", duration: "1분 20초", detail: "신제품 1건, 대본 초안 생성" },
      { id: "r9", at: "2025-08-27T11:05:00", status: "success", duration: "1분 33초", detail: "신제품 1건, 대본 초안 생성" },
    ],
  },
  {
    id: "wf4",
    name: "경쟁사 뉴스 모니터링 → 카드뉴스",
    description: "경쟁사 관련 뉴스를 수집해 대응 카드뉴스 초안을 자동 생성합니다.",
    status: "error",
    trigger: "RSS 수집 (1시간마다)",
    customerId: "cu2",
    steps: [
      { id: "s13", label: "산업재 뉴스 API 수집", type: "collect", detail: "경쟁사 키워드 4개 모니터링" },
      { id: "s14", label: "대응 카드뉴스 생성", type: "generate", detail: "정밀 생성 모델" },
      { id: "s15", label: "법무 검수 요청", type: "approve", detail: "B소재 전용 승인 라우팅" },
    ],
    successRate: 62,
    lastRunAt: "2025-09-08T07:00:00",
    runsToday: 3,
    history: [
      { id: "r10", at: "2025-09-08T07:00:00", status: "failed", duration: "0분 12초", detail: "산업재 뉴스 API 인증 만료 (401)" },
      { id: "r11", at: "2025-09-08T06:00:00", status: "failed", duration: "0분 11초", detail: "산업재 뉴스 API 인증 만료 (401)" },
      { id: "r12", at: "2025-09-08T05:00:00", status: "failed", duration: "0분 13초", detail: "산업재 뉴스 API 인증 만료 (401)" },
    ],
  },
  {
    id: "wf5",
    name: "고객 문의 요약 리포트",
    description: "매일 저녁, 고객사별 콘텐츠 승인/반려 현황을 요약해 운영팀에 전달합니다.",
    status: "active",
    trigger: "일정 예약 (매일 18:00)",
    steps: [
      { id: "s16", label: "당일 승인/반려 데이터 집계", type: "collect", detail: "고객사 전체 기준" },
      { id: "s17", label: "요약 리포트 생성", type: "generate", detail: "빠른 응답 모델" },
      { id: "s18", label: "운영팀 슬랙 알림", type: "notify", detail: "#content-ops 채널로 전송" },
    ],
    successRate: 99,
    lastRunAt: "2025-09-07T18:00:00",
    runsToday: 0,
    history: [
      { id: "r13", at: "2025-09-07T18:00:00", status: "success", duration: "0분 40초", detail: "승인 6건, 반려 1건 요약" },
      { id: "r14", at: "2025-09-06T18:00:00", status: "success", duration: "0분 38초", detail: "승인 5건, 반려 0건 요약" },
    ],
  },
  {
    id: "wf6",
    name: "SNS 발행 후 성과 리포트 자동 발송",
    description: "콘텐츠가 발행되면 24시간 뒤 성과 요약을 고객 담당자에게 자동 발송합니다.",
    status: "active",
    trigger: "이벤트 (발행 24시간 후)",
    steps: [
      { id: "s19", label: "발행 콘텐츠 성과 수집", type: "collect", detail: "채널별 도달/반응 지표" },
      { id: "s20", label: "리포트 요약 생성", type: "generate", detail: "빠른 응답 모델" },
      { id: "s21", label: "담당자 이메일 발송", type: "notify", detail: "고객사 매니저 앞 자동 발송" },
    ],
    successRate: 97,
    lastRunAt: "2025-09-07T09:30:00",
    runsToday: 2,
    history: [
      { id: "r15", at: "2025-09-07T09:30:00", status: "success", duration: "0분 55초", detail: "2건 리포트 발송" },
      { id: "r16", at: "2025-09-06T18:00:00", status: "success", duration: "0분 51초", detail: "1건 리포트 발송" },
    ],
  },
];

/* ── AI 프롬프트 관리 ── */
export const promptTemplates: PromptTemplate[] = [
  {
    id: "pt1",
    name: "블로그 - 정보성 기본 톤",
    contentType: "blog",
    model: "정밀 생성 모델 (고품질)",
    systemPrompt: "당신은 브랜드 블로그 에디터입니다. 주어진 주제와 키워드로 800~1200자 분량의 정보성 블로그를 작성하세요. 과장 표현과 확인되지 않은 수치는 사용하지 마세요.",
    tone: "신뢰감 있고 담백한 정보 전달형",
    temperature: 0.4,
    versions: [
      { id: "pv1", version: "v3", at: "2025-08-11", author: "박서연", changelog: "'너무 딱딱하다'는 고객 피드백 반영, 문장 길이 축소" },
      { id: "pv2", version: "v2", at: "2025-06-02", author: "김도현", changelog: "키워드 밀도 가이드 추가" },
      { id: "pv3", version: "v1", at: "2025-03-04", author: "박서연", changelog: "최초 작성" },
    ],
    updatedAt: "2025-08-11",
  },
  {
    id: "pt2",
    name: "카드뉴스 - 신제품 소개",
    contentType: "cardnews",
    model: "이미지 생성 모델",
    systemPrompt: "6~8장 분량의 카드뉴스를 구성하세요. 1장은 후킹 문구, 마지막 장은 CTA로 마무리합니다. 각 장 이미지 프롬프트도 함께 생성하세요.",
    tone: "간결하고 임팩트 있는 카피",
    temperature: 0.6,
    versions: [
      { id: "pv4", version: "v2", at: "2025-07-01", author: "이하은", changelog: "CTA 문구 템플릿 3종 추가" },
      { id: "pv5", version: "v1", at: "2025-03-10", author: "박서연", changelog: "최초 작성" },
    ],
    updatedAt: "2025-07-01",
  },
  {
    id: "pt3",
    name: "숏폼 - 캐주얼 브랜드보이스",
    contentType: "short",
    model: "빠른 응답 모델",
    systemPrompt: "15초 분량의 숏폼 대본을 작성하세요. 도입 3초 안에 시선을 끄는 문장으로 시작하고, 마지막은 행동 유도 문구로 마칩니다.",
    tone: "발랄하고 캐주얼",
    temperature: 0.75,
    versions: [
      { id: "pv6", version: "v1", at: "2025-04-20", author: "최민준", changelog: "최초 작성" },
    ],
    updatedAt: "2025-04-20",
  },
  {
    id: "pt4",
    name: "블로그 - SEO 최적화",
    contentType: "blog",
    model: "정밀 생성 모델 (고품질)",
    systemPrompt: "핵심 키워드를 제목과 첫 문단에 반드시 포함하고, 소제목(H2) 3개 이상으로 구조화하세요. 메타 설명 150자를 함께 생성하세요.",
    tone: "검색 노출을 고려한 구조형",
    temperature: 0.35,
    versions: [
      { id: "pv7", version: "v2", at: "2025-06-18", author: "김도현", changelog: "메타 설명 자동 생성 항목 추가" },
      { id: "pv8", version: "v1", at: "2025-03-20", author: "박서연", changelog: "최초 작성" },
    ],
    updatedAt: "2025-06-18",
  },
  {
    id: "pt5",
    name: "카드뉴스 - E뷰티 전용",
    customerId: "cu5",
    contentType: "cardnews",
    model: "이미지 생성 모델",
    systemPrompt: "Z세대 타깃, 발랄한 톤. 유행어는 팀 검수 목록에 있는 표현만 사용하세요. 컬러 코드는 반드시 정확히 표기하세요.",
    tone: "트렌디하고 발랄한 Z세대 톤",
    temperature: 0.7,
    versions: [
      { id: "pv9", version: "v1", at: "2025-04-05", author: "서다인", changelog: "E뷰티 전용 프롬프트 최초 작성" },
    ],
    updatedAt: "2025-04-05",
  },
  {
    id: "pt6",
    name: "숏폼 - F푸드 전용",
    customerId: "cu6",
    contentType: "short",
    model: "빠른 응답 모델",
    systemPrompt: "가맹점 관점의 실용 정보를 포함하고, 친근하고 유쾌한 어투를 유지하세요. 가격 언급 시 반드시 '매장별 상이' 문구를 포함하세요.",
    tone: "친근하고 유쾌한 가맹 브랜드 톤",
    temperature: 0.65,
    versions: [
      { id: "pv10", version: "v1", at: "2025-04-16", author: "임재현", changelog: "F푸드 전용 프롬프트 최초 작성" },
    ],
    updatedAt: "2025-04-16",
  },
  {
    id: "pt7",
    name: "블로그 - C페이 규제 검수형",
    customerId: "cu3",
    contentType: "blog",
    model: "정밀 생성 모델 (고품질)",
    systemPrompt: "모든 수치 표현에는 출처와 기준일을 명시하세요. 확정되지 않은 혜택이나 향후 계획은 서술하지 마세요.",
    tone: "신뢰형, 규제 산업 특화",
    temperature: 0.3,
    versions: [
      { id: "pv11", version: "v2", at: "2025-07-14", author: "윤소미", changelog: "출처 표기 필수화 규칙 강화" },
      { id: "pv12", version: "v1", at: "2025-03-25", author: "박서연", changelog: "최초 작성" },
    ],
    updatedAt: "2025-07-14",
  },
  {
    id: "pt8",
    name: "카드뉴스 - B소재 B2B 전용",
    customerId: "cu2",
    contentType: "cardnews",
    model: "이미지 생성 모델",
    systemPrompt: "B2B 담당자를 타깃으로 합니다. 감성적 표현보다 수치와 근거 중심으로 작성하고, 안전 관련 문구는 반드시 법무 검수 표시를 남기세요.",
    tone: "담백하고 근거 중심적",
    temperature: 0.35,
    versions: [
      { id: "pv13", version: "v1", at: "2025-03-18", author: "한승우", changelog: "최초 작성" },
    ],
    updatedAt: "2025-03-18",
  },
];

/* ── 데이터 수집 관리 ── */
export const dataSources: DataSource[] = [
  {
    id: "ds1",
    name: "이커머스 트렌드 리포트 RSS",
    type: "rss",
    url: "https://feeds.example-commerce-trend.kr/rss",
    category: "이커머스",
    keywords: ["라이브커머스", "당일배송", "리퍼브"],
    interval: "30분마다",
    status: "active",
    lastCollectedAt: "2025-09-08T09:00:00",
    itemsToday: 6,
    itemsTotal: 1842,
    history: [
      { id: "h1", at: "2025-09-08T09:00:00", itemsCollected: 2, status: "success" },
      { id: "h2", at: "2025-09-08T08:30:00", itemsCollected: 0, status: "success" },
      { id: "h3", at: "2025-09-08T08:00:00", itemsCollected: 1, status: "success" },
    ],
  },
  {
    id: "ds2",
    name: "산업재 뉴스 API",
    type: "api",
    url: "https://api.example-industry-news.kr/v2/articles",
    category: "제조 / 산업재",
    keywords: ["복합소재", "친환경인증", "경쟁사동향"],
    interval: "1시간마다",
    status: "error",
    lastCollectedAt: "2025-09-08T07:00:00",
    itemsToday: 0,
    itemsTotal: 926,
    history: [
      { id: "h4", at: "2025-09-08T07:00:00", itemsCollected: 0, status: "failed", note: "API 키 만료 (401)" },
      { id: "h5", at: "2025-09-08T06:00:00", itemsCollected: 0, status: "failed", note: "API 키 만료 (401)" },
      { id: "h6", at: "2025-09-08T05:00:00", itemsCollected: 0, status: "failed", note: "API 키 만료 (401)" },
    ],
  },
  {
    id: "ds3",
    name: "핀테크 규제 뉴스 RSS",
    type: "rss",
    url: "https://feeds.example-fintech-reg.kr/rss",
    category: "핀테크",
    keywords: ["금융규제", "전자금융", "간편결제"],
    interval: "1시간마다",
    status: "active",
    lastCollectedAt: "2025-09-08T09:00:00",
    itemsToday: 3,
    itemsTotal: 1204,
    history: [
      { id: "h7", at: "2025-09-08T09:00:00", itemsCollected: 1, status: "success" },
      { id: "h8", at: "2025-09-08T08:00:00", itemsCollected: 2, status: "success" },
    ],
  },
  {
    id: "ds4",
    name: "리빙 인테리어 매거진 RSS",
    type: "rss",
    url: "https://feeds.example-living-magazine.kr/rss",
    category: "리빙 / 인테리어",
    keywords: ["인테리어트렌드", "컬러트렌드"],
    interval: "3시간마다",
    status: "active",
    lastCollectedAt: "2025-09-08T06:00:00",
    itemsToday: 2,
    itemsTotal: 388,
    history: [{ id: "h9", at: "2025-09-08T06:00:00", itemsCollected: 2, status: "success" }],
  },
  {
    id: "ds5",
    name: "뷰티 트렌드 뉴스 API",
    type: "api",
    url: "https://api.example-beauty-trend.kr/v1/news",
    category: "뷰티 / 코스메틱",
    keywords: ["클린뷰티", "신상메이크업", "성분트렌드"],
    interval: "1시간마다",
    status: "active",
    lastCollectedAt: "2025-09-08T09:00:00",
    itemsToday: 5,
    itemsTotal: 1560,
    history: [
      { id: "h10", at: "2025-09-08T09:00:00", itemsCollected: 3, status: "success" },
      { id: "h11", at: "2025-09-08T08:00:00", itemsCollected: 2, status: "success" },
    ],
  },
  {
    id: "ds6",
    name: "F&B 프랜차이즈 뉴스 RSS",
    type: "rss",
    url: "https://feeds.example-fnb-franchise.kr/rss",
    category: "F&B 프랜차이즈",
    keywords: ["신메뉴", "가맹정책"],
    interval: "2시간마다",
    status: "paused",
    lastCollectedAt: "2025-09-05T09:00:00",
    itemsToday: 0,
    itemsTotal: 702,
    history: [{ id: "h12", at: "2025-09-05T09:00:00", itemsCollected: 1, status: "success" }],
  },
  {
    id: "ds7",
    name: "모빌리티 산업 뉴스 API",
    type: "api",
    url: "https://api.example-mobility-news.kr/v1/articles",
    category: "모빌리티",
    keywords: ["전기차", "공유모빌리티"],
    interval: "2시간마다",
    status: "paused",
    lastCollectedAt: "2025-08-25T09:00:00",
    itemsToday: 0,
    itemsTotal: 214,
    history: [{ id: "h13", at: "2025-08-25T09:00:00", itemsCollected: 0, status: "success", note: "G모빌리티 계약 일시중지로 수집 중단" }],
  },
  {
    id: "ds8",
    name: "헬스케어 저널 RSS",
    type: "rss",
    url: "https://feeds.example-health-journal.kr/rss",
    category: "헬스케어",
    keywords: ["면역관리", "건강기능식품"],
    interval: "3시간마다",
    status: "active",
    lastCollectedAt: "2025-09-08T06:00:00",
    itemsToday: 1,
    itemsTotal: 655,
    history: [{ id: "h14", at: "2025-09-08T06:00:00", itemsCollected: 1, status: "success" }],
  },
];

/* ── 활동 로그 (대시보드) ── */
export const activityLog: ActivityLogEntry[] = [
  { id: "a1", at: "2025-09-08T09:12:00", actor: "AI 자동 생성", action: "블로그 초안을 생성했습니다", target: "AI가 정리한 이번 주 이커머스 트렌드 3가지" },
  { id: "a2", at: "2025-09-08T08:50:00", actor: "김도현", action: "블로그를 승인 요청했습니다", target: "가맹 창업 비용 가이드 블로그" },
  { id: "a3", at: "2025-09-07T18:00:00", actor: "워크플로우", action: "고객 문의 요약 리포트를 발송했습니다", target: "승인 6건, 반려 1건" },
  { id: "a4", at: "2025-09-07T17:10:00", actor: "이하은", action: "블로그 초안을 저장했습니다", target: "반려동물 가을철 산책 안전 수칙" },
  { id: "a5", at: "2025-09-07T15:00:00", actor: "홍재민", action: "카드뉴스를 승인했습니다", target: "체험단 모집 안내 카드뉴스" },
  { id: "a6", at: "2025-09-07T09:30:00", actor: "워크플로우", action: "발행 성과 리포트를 발송했습니다", target: "2건 발송 완료" },
  { id: "a7", at: "2025-09-06T16:00:00", actor: "AI 자동 생성", action: "블로그 초안을 생성했습니다", target: "성분 인증 마크 안내 블로그" },
  { id: "a8", at: "2025-09-06T13:30:00", actor: "AI 자동 생성", action: "카드뉴스 초안을 생성했습니다", target: "환절기 건강관리 카드뉴스" },
  { id: "a9", at: "2025-09-05T15:00:00", actor: "정유진", action: "체험 고객 상담 메모를 남겼습니다", target: "K펫" },
  { id: "a10", at: "2025-09-04T16:30:00", actor: "박서연", action: "카드뉴스를 승인했습니다", target: "가을맞이 신제품 라인업 카드뉴스" },
  { id: "a11", at: "2025-09-02T09:50:00", actor: "한승우", action: "블로그를 반려했습니다", target: "친환경 소재 인증 획득 소식" },
  { id: "a12", at: "2025-09-01T09:00:00", actor: "워크플로우", action: "블로그를 자동 발행했습니다", target: "추석 연휴 배송 지연 안내와 스마트 주문 팁" },
];

/* ── 팀 계정 / 권한 ── */
export const teamUsers: TeamUser[] = [
  { id: "u1", name: "박서연", email: "seoyeon.park@marketflow.example", role: "슈퍼관리자", status: "active", lastActiveAt: "2025-09-08T09:20:00" },
  { id: "u2", name: "김도현", email: "dohyun.kim@marketflow.example", role: "운영관리자", status: "active", lastActiveAt: "2025-09-08T08:55:00" },
  { id: "u3", name: "강태우", email: "taewoo.kang@marketflow.example", role: "운영관리자", status: "active", lastActiveAt: "2025-09-07T19:10:00" },
  { id: "u4", name: "이하은", email: "haeun.lee@marketflow.example", role: "에디터", status: "active", lastActiveAt: "2025-09-07T17:10:00" },
  { id: "u5", name: "최민준", email: "minjun.choi@marketflow.example", role: "에디터", status: "active", lastActiveAt: "2025-09-07T10:40:00" },
  { id: "u6", name: "정유진", email: "yujin.jung@marketflow.example", role: "에디터", status: "active", lastActiveAt: "2025-09-05T15:00:00" },
  { id: "u7", name: "서다인", email: "dain.seo.guest@e-beauty.example", role: "뷰어", status: "invited", lastActiveAt: "2025-09-03T14:00:00" },
  { id: "u8", name: "한승우", email: "sw.han.guest@b-material.example", role: "뷰어", status: "disabled", lastActiveAt: "2025-07-20T11:00:00" },
];

/* ── SNS 채널 연동 ── */
export const channelIntegrations: ChannelIntegration[] = [
  { id: "ch1", platform: "네이버 블로그", accountName: "@marketflow-ops", connected: true, status: "정상", lastSyncAt: "2025-09-08T09:00:00", followers: 18420 },
  { id: "ch2", platform: "인스타그램", accountName: "@marketflow.official", connected: true, status: "정상", lastSyncAt: "2025-09-08T09:00:00", followers: 32110 },
  { id: "ch3", platform: "유튜브", accountName: "MarketFlow Studio", connected: true, status: "재인증 필요", lastSyncAt: "2025-09-05T11:00:00", followers: 9840 },
  { id: "ch4", platform: "카카오채널", accountName: "@marketflow", connected: true, status: "정상", lastSyncAt: "2025-09-08T08:30:00", followers: 14200 },
  { id: "ch5", platform: "페이스북", accountName: "MarketFlow Korea", connected: false, status: "연동 안 됨" },
];

/* ── API Key 관리 ── */
export const apiKeys: ApiKeyEntry[] = [
  { id: "ak1", service: "이미지 생성 API", keyMasked: "mf_img_••••••••3f2a", createdAt: "2025-03-04", lastUsedAt: "2025-09-08T09:00:00", status: "active" },
  { id: "ak2", service: "아바타 영상 생성 API", keyMasked: "mf_avatar_••••••••91cd", createdAt: "2025-04-02", lastUsedAt: "2025-08-30T14:22:00", status: "active" },
  { id: "ak3", service: "네이버 블로그 API", keyMasked: "mf_naver_••••••••7b10", createdAt: "2025-03-04", lastUsedAt: "2025-09-08T09:00:00", status: "active" },
  { id: "ak4", service: "인스타그램 그래프 API", keyMasked: "mf_ig_••••••••44e8", createdAt: "2025-03-04", lastUsedAt: "2025-09-08T09:00:00", status: "active" },
  { id: "ak5", service: "산업재 뉴스 API", keyMasked: "mf_news_••••••••c02f", createdAt: "2025-03-18", lastUsedAt: "2025-09-08T07:00:00", status: "revoked" },
];

/* ── 대시보드 KPI 차트 데이터 ── */
export const weeklyGeneratedContent: KpiPoint[] = [
  { label: "9/2", value: 14 },
  { label: "9/3", value: 18 },
  { label: "9/4", value: 21 },
  { label: "9/5", value: 16 },
  { label: "9/6", value: 19 },
  { label: "9/7", value: 12 },
  { label: "9/8", value: 9 },
];

export const channelPublishShare = [
  { label: "네이버 블로그", value: 42, caption: "42건" },
  { label: "인스타그램", value: 35, caption: "35건" },
  { label: "카카오채널", value: 14, caption: "14건" },
  { label: "유튜브", value: 9, caption: "9건" },
  { label: "페이스북", value: 3, caption: "3건" },
];
